alpha/apps/kaltura/lib/cache/kApiCache.php, api_v3/lib/KalturaResponseCacher.php
=> Reducing max_age in sendCachingHeaders if needed (based on minCacheTTL)

plugins/cue_points/base/lib/kCuePointManager.php
=> Fixed function arguments mixup

plugins/cue_points/base/lib/kCuePointManager.php
=> Gathering and passing copied cuepoint ids for post processing

generator/sources/java/README.txt, generator/sources/java/test.sh, generator/sources/java/testAPI/test.sh
updated README to reflect that
=> script to auto build and run units on Linux

alpha/apps/kaltura/lib/model/objectfilters/entryFilter.class.php, alpha/lib/model/index/entryIndex.php, api_v3/lib/KalturaEntryService.php, api_v3/lib/types/entry/KalturaBaseEntry.php, api_v3/lib/types/entry/filters/KalturaBaseEntryFilter.php, api_v3/lib/types/entry/filters/base/KalturaBaseEntryBaseFilter.php
=> Applied a matchand filter for entitledUsersEdit/Publish

api_v3/services/FlavorAssetService.php
@AviBueno  - please review and merge.
=> fix parameter hint

plugins/content_distribution/providers/unicorn/lib/UnicornDistributionEngine.php, plugins/content_distribution/providers/unicorn/lib/api/KalturaUnicornDistributionJobProviderData.php
=> Take notification URL from kConf cdn_api_host

generator/sources/android/DemoApplication/src/com/kaltura/services/UploadToken.java
=> android demo app upload bug fix

deployment/permissions/service.jobs.ini
Resolving Admin Console reconvert permission missing.
See https://kaltura.atlassian.net/browse/PLAT-2011
=> PLAT-2011 - Rectify duplicate permissionItem67

alpha/apps/kaltura/lib/rules/conditions/kOrCondition.php, alpha/lib/enums/accessControlConditionType.php, api_v3/lib/types/rules/conditions/KalturaOrCondition.php, release-notes.md, tests/standAloneClient/captionAssetHttpNotifications.xml
=> Caption added HTTP Notifications

alpha/apps/kaltura/lib/storage/kFileSyncUtils.class.php, plugins/content_distribution/services/ContentDistributionBatchService.php
=> Avoid resolving file-sync link for pull URL

plugins/content_distribution/providers/unicorn/lib/UnicornDistributionEngine.php, plugins/content_distribution/providers/unicorn/lib/api/KalturaUnicornDistributionJobProviderData.php, plugins/content_distribution/providers/unicorn/lib/model/kUnicornDistributionJobProviderData.php, plugins/content_distribution/providers/unicorn/services/UnicornService.php
=> No need to wait for notification if media didn't change

alpha/lib/model/entry.php, api_v3/services/CategoryEntryService.php
=> Allowing a co-publisher to delete a category entry

alpha/lib/model/entry.php
=> Skipping empty pusers in setEntitledPusersEdit/setEntitledPusersPublish

api_v3/lib/types/KalturaCategoryUser.php, api_v3/lib/types/batch/KalturaCopyJobData.php
@tan-tan-kanarek  - please review fix KMS-6016
=> Jupiter 10.5.0 cr 198603 group user

alpha/apps/kaltura/lib/storage/kStorageExporter.php
PLAT-2147#Moshe 1minute
@tan-tan-kanarek please review
=> Cosmetic change - remove a new line inside remark

alpha/apps/kaltura/lib/KDLWrap.php, alpha/lib/model/flavorParams.php, api_v3/lib/types/conversionProfile/KalturaFlavorParams.php, infra/cdl/kdl/KDLCommon.php, infra/cdl/kdl/KDLFlavor.php, infra/cdl/kdl/KDLMediaObjectData.php, infra/cdl/kdl/KDLOperatorFfmpeg0_10.php
IMX source cropping
Non Compliancy for SD sized sources with large bitrate
=> Jupiter 10.5.0 em 877 plat 2399 imx and sd

deployment/base/scripts/createQueryCacheTriggers.php, plugins/event_notification/lib/model/EventNotificationTemplate.php, plugins/event_notification/lib/model/EventNotificationTemplatePeer.php
=> add query cache rule for event notif template

alpha/apps/kaltura/modules/partnerservices2/actions/executeplaylistAction.class.php
affects the protocol used for building URLs in the response
=> add the protocol to the cache key

api_v3/services/UserService.php
=> revert default user type filtering

alpha/config/IndexSchema.xml, alpha/lib/model/index/kuserIndex.php, configurations/sphinx/kaltura.conf.template
=> add kuser.type field to sphinx index

alpha/apps/kaltura/lib/kManifestRenderers.php
also, removed duplicate Access-Control-Allow-Origin in live mpegdash
=> add Access-Control-Expose-Headers

tests/standAloneClient/captionAssetHttpNotifications.xml
=> Support change event on caption-asset

plugins/multi_centers/lib/kMultiCentersFlowManager.php
=> Changing filesync status to ERROR if it is not alrady deleted

plugins/multi_centers/lib/kMultiCentersFlowManager.php
=> Revert "Changing filesync status to ERROR if it is not alrady deleted"

plugins/multi_centers/lib/kMultiCentersFlowManager.php
=> Changing filesync status to ERROR if it is not alrady deleted/purged

api_v3/services/CategoryEntryService.php
need to detach the pager before calling doCount
=> categoryEntry.list bug fix

plugins/admin_console/kaltura_internal_tools/admin/KalturaInternalToolsSystemHelperAction.php
will not be interpreted. replaced with "\n".
=> this is displayed in a textbox and hence, '<br>' or any other HTML tags

generator/sources/java/testAPI/test.sh
- check if javac and jar are execs, if not exit with msg.
=> - exec bit on test.sh

alpha/apps/kaltura/lib/batch2/kFlowHelper.php
@sharonadar, please review this small change.
=> PLAT 2621 - Refactor the use of expiry const

alpha/apps/kaltura/lib/batch2/kFlowHelper.php, alpha/apps/kaltura/lib/batch2/kJobsManager.php, alpha/apps/kaltura/lib/batch2/model/kLiveReportExportJobData.php, api_v3/lib/types/liveReports/api/KalturaLiveReportExportParams.php
=> PLAT-2621 | Support placeholders in the applicationUrlTemplate (+rename param)

batch/batches/LiveReportExport/Engines/LiveReportEngine.php, batch/batches/LiveReportExport/Engines/LiveReportEntryTimeLiveQueryEngine.php, batch/batches/LiveReportExport/Engines/LiveReportLocationEngine.php
=> PLAT-2639 | Make sure DVR columns are shown only if entry supports DVR

alpha/lib/model/BulkUploadResultPeer.php
=> PLAT-2669: Removed duplicated function

generator/sources/php53/composer.json
@jessp01, I'm adding the composer.json file to php5.3.
=> added composer.json to php5.3 client library sources

api_v3/lib/types/liveReports/api/KalturaLiveReportOrderBy.php, api_v3/services/LiveReportsService.php
@sharonadar, please review.
We'll have to generate client libs afterwards.
=> PLAT-2616 | Fix sorting and set the sorting column as name

batch/batches/LiveReportExport/Engines/LiveReportEntryExactTimeEngine.php, batch/batches/LiveReportExport/Engines/LiveReportEntryQueryEngine.php, batch/batches/LiveReportExport/Engines/LiveReportLivePartnerExactTimeEngine.php, batch/batches/LiveReportExport/Engines/LiveReportPartnerQueryEngine.php, batch/batches/LiveReportExport/Engines/LiveReportQueryHelper.php, batch/batches/LiveReportExport/Exporters/LiveReportExporter.php, batch/batches/LiveReportExport/Exporters/PartnerTotalLiveExporter.php
=> PLAT-2654 | Add an option to sum a few field values to support DVR

admin_console/forms/PartnerConfigurationLimitSubForm.php
=> PLAT-2755: Ensuring limit element exists before accessing it.

generator/sources/java/testAPI/test.sh
classpath along with the video files.
=> now that we use an INI file for the API creds, needs to be copied to

configurations/generator.ini, generator/CSharpClientGenerator.php, generator/ObjCClientGenerator.php, generator/sources/cli/README, generator/sources/objc/DemoApplication/Shared/Client.m, generator/sources/objc/KalturaClient/KalturaClient/KalturaClientBase.h, generator/sources/objc/KalturaClient/KalturaClient/KalturaClientBase.m, generator/sources/objc/KalturaClient/KalturaClient/KalturaXmlParsers.m, generator/sources/objc/KalturaClientTester/KalturaClientTester/KalturaClientTester.m, generator/sources/python/KalturaClient/tests/test_functional.py, generator/tests/3_configureTestPartner.php, generator/tests/4_runTests.php, generator/tests/config.template.ini, generator/tests/utils.php
objc/csharp fix compilation with map type
hide pojo/bpmn for now from download page
fix python tests
fix test runner following change in test params convention
objc rename the existing KalturaClientConfiguration => KalturaConfiguration
=> client library fixes

alpha/apps/kaltura/lib/batch2/kFlowHelper.php
=> Keep original image file extension

alpha/apps/kaltura/lib/storage/kFileUtils.php, api_v3/lib/KalturaLiveEntryService.php, api_v3/services/LiveStreamService.php, configurations/local.template.ini, plugins/cue_points/base/services/LiveCuePointService.php
=> #PLAT-2762 make sure to perform live entry updates from the original dc

alpha/apps/kaltura/lib/batch2/kFlowHelper.php, alpha/apps/kaltura/lib/propel/php5/KalturaObjectBuilder.php, alpha/apps/kaltura/lib/propel/php5/KalturaPeerBuilder.php, alpha/lib/model/entryPeer.php, alpha/lib/model/om/Baseentry.php, alpha/lib/model/om/BaseentryPeer.php
@yossipapi Could you please review?
=> Jupiter 10.6.0 plat 2593

alpha/lib/model/FileSync.php, alpha/lib/model/asset.php
=> SUP-4081: Not prepending baseUrl if url already contains a protocol prefix

api_v3/services/BaseEntryService.php
=> QnD: Return hardcoded KalturaBaseEntryListResponse in baseentry->list

api_v3/services/BaseEntryService.php
=> Added a comment

alpha/apps/kaltura/lib/kAssetUtils.class.php, api_v3/lib/syndication/KalturaSyndicationFeedRenderer.php
=> Not prepending baseUrl if url already contains a protocol prefix

plugins/content_distribution/providers/youtube_api/lib/YoutubeApiDistributionEngine.php, plugins/content_distribution/providers/youtube_api/lib/api/KalturaYoutubeApiDistributionJobProviderData.php
=> Jupiter 10.9.0 plat 2849

api_v3/lib/types/entry/filters/KalturaPlayableEntryFilter.php
=> KalturaPlayableEntryFilter::prepareEntriesCriteriaFilter pager is

plugins/content_distribution/providers/youtube_api/lib/admin/YoutubeApiProfileConfiguration.php
=> Catch exception in form instantiation

VERSION.txt
=> Revert "Jupiter 10.10.0 update version"

alpha/apps/kaltura/lib/propel/php5/KalturaObjectBuilder.php, alpha/lib/model/om/Baseentry.php
=> Keep incCustomData in oldCustomData values, in a similar way we use for

api_v3/lib/KalturaLiveEntryService.php
Added copying of tags and categories to new Live to VOD entries. All the description, custom metadata and such are already being copied.
=> Jupiter 10.10.0 plat 2744

alpha/lib/model/entry.php, api_v3/lib/KalturaEntryService.php, plugins/cue_points/base/lib/kCuePointManager.php
to support copy cue points from recorded entry to clip / trim
=> copy cue points from source entry and not from root entry

generator/CSharpClientGenerator.php
=> fix c# generator

alpha/apps/kaltura/modules/extwidget/actions/playManifestAction.class.php
no reason to wait for serve flavor
=> block inactive partners in play manifest

api_v3/lib/KalturaJsonSerializer.php
=> Overcome null in first attribute

generator/CliClientGenerator.php, generator/sources/cli/kalcliAutoComplete.php
- dont autocomplete read only properties
- support implicit api parameters (ks, responseProfile, partnerId)
=> kalcli improvements

plugins/bulk_upload/xml/xml/ingestion.xsd
SUP-4595
@tan-tan-kanarek please review
=> Remove KS size limit from ingestion xml

alpha/lib/model/DeliveryProfileVod.php
temporarily write a log line in this case
=> disable origin fallback for large files

alpha/apps/kaltura/lib/storage/VodPackagerDeliveryUtils.php, alpha/lib/model/DeliveryProfileAkamaiAppleHttpDirect.php, alpha/lib/model/DeliveryProfileVod.php
- support https in vod packager hds/mss/dash
- fix tokenization in akamai hls direct (acl should include only the path not the full url)
=> delivery profile fixes

plugins/content/caption/search/lib/api/filters/advanced/KalturaEntryCaptionAssetSearchItem.php, plugins/content/caption/search/lib/model/filters/EntryCaptionAssetSearchFilter.php
Added KalturaEntryCaptionAssetSearchItem to support caption search in entry list services
=> Added KalturaEntryCaptionAssetSearchItem

api_v3/lib/types/resource/operations/KalturaConcatAttributes.php
=> Throw exception on a non-supported object

api_v3/lib/types/filters/KalturaGroupUserFilter.php
@tan-tan-kanarek  - could you please review?
=> PLAT-2940 fix call to undefined method

deployment/uiconf/KalturaClientBase.php, generator/Php4ClientGenerator.php, generator/Php5ClientGenerator.php, generator/PhpZendClientGenerator.php, generator/sources/php4/KalturaClientBase.php, generator/sources/php5/KalturaClientBase.php, generator/sources/php53/library/Kaltura/Client/Base.php, generator/sources/zend/Kaltura/Client/ClientBase.php
SUP-4358
add valid return value so that the ValidateObjectType will pass
Ran all tests of all clients through the testing scripts plus ran @jessp01 script as well 
Still waiting for the objc testing 
FYI @MosheMaorKaltura
=> SUP-4358 additional php fixes

api_v3/lib/KalturaJsonSerializer.php
=> Removing null values from the JSON without using regex

generator/sources/python/KalturaClient/tests/test_distribution.py
Thanks @flipmcf, I cherry picked your commits into this branch and merged
=> Jupiter 10.12.0 pyclient distrbution tests

generator/sources/java/src/com/kaltura/client/utils/ParseUtils.java
SUP4292
Expedn the part int to include values that have E notation
=> SUP4292 Validate int boundries

alpha/lib/model/Partner.php, api_v3/lib/KalturaResponseCacher.php
will enable the deprecation of the user secret
=> always allow the admin secret in session.start

generator/sources/java/src/com/kaltura/client/utils/ParseUtils.java
=> Revert "SUP4292 Validate int boundries"

alpha/apps/kaltura/lib/mySigninValidator.class.php, alpha/apps/kaltura/lib/request/kSessionBase.class.php, alpha/lib/model/UserLoginData.php
=> Jupiter 10.12.0 plat 2957

alpha/apps/kaltura/lib/myPlaylistUtils.class.php, alpha/lib/model/entryPeer.php
This commit had already been gone through 'compat check' that went OK and code review by @erankor .
Original commit was prepared by Avi Bueno,
=> Jupiter 10.12.0 plat 2829

plugins/content/external_media/lib/model/ExternalMediaEntry.php
=> In case ExternalMediaEntry make sure that externalSourceType is copied.

plugins/drm/lib/DrmLicenseUtils.php
=> Fix typo of acount_id=>account_id and change kCurrentContext::$partner_id => kCurrentContext::getCurrentPartnerId()

generator/Xml2As3ClientGenerator.php
add the minimum support for map to make KMC compile
=> Jupiter 10.13.0 fix as3 client

admin_console/forms/PartnerConfiguration.php, alpha/apps/kaltura/lib/myPartnerUtils.class.php, alpha/apps/kaltura/modules/extwidget/actions/embedIframeJsAction.class.php, alpha/lib/model/Partner.php, plugins/admin_console/system_partner/lib/api/KalturaSystemPartnerConfiguration.php
=> Jupiter 10.13.0 plat 2971

admin_console/web/tools/bigRedButton.php
=> Add current time clock and lasy sync point time display on big red button page.

plugins/metadata/lib/api/KalturaMetadataProfile.php, plugins/metadata/lib/api/filters/advanced/DynamicObjectSearchFilter.php, plugins/metadata/lib/api/filters/advanced/KalturaDynamicObjectSearchItem.php, plugins/metadata/lib/api/filters/advanced/MetadataSearchFilter.php, plugins/metadata/lib/kMetadataFlowManager.php, plugins/metadata/lib/kMetadataManager.php, plugins/metadata/lib/model/MetadataProfile.php
- Allow searching by specific field that is using a dynamic object
- Added option to disable automating re-indexing when a dynamic object is updated
- Fixed MetadataSearch filter behavior when searching with multiple words
=> Jupiter 10.13.0 Dynamic Objects Enhancements

alpha/apps/kaltura/lib/kUploadTokenMgr.php
=> Keep uploadToken fileName ext when fileData is tmp

admin_console/views/scripts/widget/list.phtml
=> Show HTML5 version when search uiconf in AC

alpha/lib/model/DeliveryProfileLiveAppleHttp.php
=> Jupiter 10.14.0 plat 3310

tests/standAloneClient/entryCustomMetadataChangedHttpNotification.xml
=> Jupiter 10.14.0 ps 2259

configurations/base.ini
Jupiter-10.14.0-update-base.ini#time 1m
=> Jupiter-10.14.0 Update base.ini versions

alpha/apps/kaltura/lib/myPlaylistUtils.class.php, plugins/sphinx_search/lib/SphinxEntryCriteria.php
in order to limit the expiration of the conditional cache
=> use kApiCache::getTime instead of time

configurations/base.ini
Jupiter-10.14.0-update-base.ini-2#time 0
=> Update liveanalytics_version v2.4

alpha/apps/kaltura/lib/monitor/KalturaMonitorClient.php, batch/batches/KBatchBase.class.php, batch/batches/KJobHandlerWorker.class.php
=> report the job partner id to the apimon

alpha/lib/model/KuserKgroup.php, alpha/lib/model/KuserKgroupPeer.php, alpha/lib/model/categoryKuser.php, alpha/lib/model/categoryKuserPeer.php, deployment/base/scripts/createQueryCacheTriggers.php
on kuser_kgroup and category_kuser
=> add query cache rules

api_v3/web/testme/js/kField.js
Prevent TypeError when removing an empty element
=> Prevent TypeError when removing an empty element

admin_console/controllers/PartnerController.php, admin_console/forms/PartnerFilter.php
=> Add Uiconf filter to search partner in AC

api_v3/lib/types/KalturaObject.php, api_v3/services/ThumbAssetService.php
SUP-4924
Added support for filter that is not KalturaThumbAssetFilterand not KalturaAssetFilter:
Cast it upward to KalturaAssetFilter and then cast it downward to KalturaThumbAssetFilterand
=> Fix thumbAsset->list filter backward compatibility

alpha/apps/kaltura/lib/renderers/kRendererDumpFile.php, alpha/apps/kaltura/lib/request/infraRequestUtils.class.php, alpha/apps/kaltura/lib/storage/kFileUtils.php, alpha/apps/kaltura/modules/extwidget/actions/thumbnailAction.class.php, alpha/lib/model/entry.php, alpha/web/index.php
reduce the cache time of thumbnail, use the HTTP If-Modified-Since header to avoid an increase in origin traffic
=> Jupiter 10.15.0 thumbnail if modified since

api_v3/lib/types/KalturaObject.php
=> Related-objects are read-only

batch/batches/Mailer/KAsyncMailer.class.php
the logs much bigger, but assuming we do, we need to use print_r().
=> Personally, not sure we want to print the email body as it just makes

alpha/lib/model/UserEntry.php, api_v3/lib/types/KalturaUserEntry.php
https://github.com/kaltura/server/pull/2758#discussion_r33554933
=> Fix for comments regarding pull request #2758

plugins/bulk_upload/xml/batch/BulkUploadEngineXml.php
Jupiter-10.15.0-PLAT3088-3#time 5m
=> Handle DUPLICATE_CATEGORY as string

plugins/content_distribution/providers/tvinci/lib/TvinciDistributionFeedEngine.php, plugins/content_distribution/providers/tvinci/lib/TvinciDistributionProvider.php, plugins/content_distribution/providers/tvinci/lib/admin/TvinciProfileConfiguration.php, plugins/content_distribution/providers/tvinci/lib/api/KalturaTvinciDistributionJobProviderData.php, plugins/content_distribution/providers/tvinci/lib/api/KalturaTvinciDistributionProfile.php, plugins/content_distribution/providers/tvinci/lib/feed/TvinciDistributionFeedHelper.php, plugins/content_distribution/providers/tvinci/lib/model/TvinciDistributionProfile.php, plugins/content_distribution/providers/tvinci/lib/xml/tvinci_default.xslt
=> MediaPrep comment out custom XSLT

batch/batches/Index/Engines/KIndexingKuserPermissionsEngine.php
Jupiter-10.15.0-PLAT-3334#time 2h
=> Fix wrong function call to kalturaUserService::indexAction instead of  kalturaUserService::index

plugins/multi_centers/batch/FileSyncImport/KAsyncFileSyncImport.class.php, plugins/multi_centers/services/FileSyncImportBatchService.php, release-notes.md
also, have source dc default to 1 - currentDc, to simplify worker config
=> update release notes

plugins/multi_centers/batch/FileSyncImport/KAsyncFileSyncImport.class.php
KBatchBase::$taskConfig->filter is KalturaBatchJobFilter, need to change
it to KalturaFileSyncFilter
=> file sync import bug fix

plugins/content_distribution/providers/tvinci/lib/TvinciDistributionFeedEngine.php, plugins/content_distribution/providers/tvinci/lib/xml/tvinci_envelope.xml
=> PLAT-3423 injest to ingest

alpha/apps/kaltura/lib/db/KalturaPDO.php
so that it can be parsed by the performance report
=> print the sql comment in KalturaPDO::exec

alpha/apps/kaltura/modules/extwidget/actions/serveFlavorAction.class.php
Needs to be merged to Jupiter-10.16.0
@erankor please approve.
=> fix for issue in serveFlavor were a valid flavor exists with a deleted entry

alpha/scripts/utils/fileSyncQueueStatus.php, plugins/multi_centers/batch/FileSyncImport/KAsyncFileSyncImport.class.php, plugins/multi_centers/services/FileSyncImportBatchService.php
- have the worker quit once an hour, in order to get config/code changes
- increase the sleep time when the worker has nothing to do
- hide log lines in fileSyncQueueStatus.php
=> file sync import touch ups

alpha/config/kConf.php
Jupiter-10.16.0-getMap-check-null#time 2h
=> Protect againts NULL pointer

infra/cache/kCouchbaseCacheWrapper.php
Jupiter-10.16.0-validate-CouchbaseCluster-exists#time 2h
=> Validate that class CouchbaseCluster exists.

plugins/content_distribution/providers/tvinci/lib/TvinciDistributionFeedEngine.php, plugins/content_distribution/providers/tvinci/lib/api/KalturaTvinciDistributionJobProviderData.php, plugins/content_distribution/providers/tvinci/lib/feed/TvinciDistributionFeedHelper.php, plugins/content_distribution/providers/tvinci/lib/xml/tvinci_default.xslt
=> Jupiter 10.14.0 xslt media prep

alpha/lib/model/syndicationFeed.php
Jupiter-10.16.0-PLAT-3470#time 5m
=> Remove syntax error in code

alpha/apps/kaltura/modules/system/templates/galleryPartialSuccess.php
Jupiter-10.16.0-fix-lint-error#Time 10sec
=> Fix lint error

plugins/cue_points/quiz/QuizPlugin.php
=> Modify return value of reports from quiz plugins to conform to the rest of the reports

plugins/webex/WebexPlugin.php
PHP Notice:  Undefined index: content-type in
/opt/kaltura/app/plugins/webex/WebexPlugin.php on line 24
=> Fixes: PHP Notice: Undefined index: content-type in  /opt/kaltura/app/plugins/webex/WebexPlugin.php on line 24

infra/general/KCurlWrapper.class.php, plugins/webex/WebexPlugin.php, vendor/webex/xml/WebexXmlClient.class.php
Jupiter-10.16.0-SUP-5363#time 1d
=> Handle case of more than one cookie in header.

api_v3/web/testme/index.php
=> Changing & to &amp;

infra/general/kString.class.php
in preparation for handling all serveFlavor's with fileName in nginx-vod
=> remove amp from the list of url allowed chars

plugins/content_distribution/providers/tvinci/lib/xml/tvinci_default.xslt
=> Reduce number of empty containers MediaPrep

api_v3/lib/types/conversionProfile/KalturaAsset.php
=> ThumbAsset list or get did not return value

alpha/apps/kaltura/lib/cache/kResponseProfileCacher.php
=> getRootObjects already recusively returns all roots

alpha/apps/kaltura/lib/reports/myReportsMgr.class.php, infra/plugins/interfaces/IKalturaReportProvider.php, plugins/cue_points/ad_cue_point/lib/api/filters/KalturaAdCuePointFilter.php, plugins/cue_points/annotation/lib/api/filters/KalturaAnnotationFilter.php, plugins/cue_points/code_cue_point/lib/api/filters/KalturaCodeCuePointFilter.php, plugins/cue_points/event_cue_point/lib/api/filters/KalturaEventCuePointFilter.php, plugins/cue_points/quiz/QuizPlugin.php, plugins/cue_points/quiz/lib/api/KalturaAnswerCuePoint.php, plugins/cue_points/quiz/lib/api/filters/KalturaAnswerCuePointFilter.php, plugins/cue_points/quiz/lib/api/filters/KalturaQuestionCuePointFilter.php, plugins/cue_points/quiz/lib/api/filters/base/KalturaAnswerCuePointBaseFilter.php, plugins/cue_points/quiz/lib/enums/QuizReportType.php, plugins/cue_points/thumb_cue_point/lib/api/filters/KalturaThumbCuePointFilter.php
Already discussed in "https://github.com/kaltura/server/pull/2903"
=> Jupiter 10.16.0 plat 3447

deployment/base/scripts/init_data/08.flavorParamsConversionProfile.ini
=> Incorrect configuration in flavorParamConversionProfile

plugins/event_notification/providers/http/lib/api/KalturaHttpNotificationObjectData.php
=> Encode content

api_v3/lib/types/delivery/KalturaDeliveryFactory.php, infra/general/KCurlWrapper.class.php
1. support setting custom headers in KCurlWrapper::getContent
2. support extending KalturaDeliveryProfile in plugins
=> changes for the watermark feature

api_v3/lib/KalturaEntryService.php, api_v3/services/BaseEntryService.php
=> Fix from code review

alpha/apps/kaltura/lib/request/infraRequestUtils.class.php, alpha/apps/kaltura/modules/kmc/actions/reportsAction.class.php, alpha/apps/kaltura/modules/partnerservices2/actions/startwidgetsessionAction.class.php
- change the priority of request parameters - path, query string, body
- lock widget session user id to 0
- remove ks generation from kmc.reports ps2 action
=> misc fixes

alpha/apps/kaltura/lib/request/infraRequestUtils.class.php, alpha/apps/kaltura/modules/extwidget/actions/playManifestAction.class.php
1. give parameters that appear ealier in the path a higher prio
2. use getRequestParams to parse playManifest parameters
=> parameter parsing changes

plugins/content_distribution/providers/tvinci/lib/api/KalturaTvinciDistributionJobProviderData.php
=> PLAT-3575 support ism instead of a4m

deployment/permissions/service.userentry.ini
=> Add permission for playback role to do userentry->add

plugins/event_notification/services/EventNotificationTemplateService.php
=> avoid use of unicode chars as it screws generators like Maven and is

alpha/apps/kaltura/lib/request/infraRequestUtils.class.php
to work around an issue with the java client / screen recorder
=> give FILES higher priority than POST

plugins/content_distribution/providers/tvinci/lib/api/KalturaTvinciDistributionJobProviderData.php
=> PLAT-3575 change mbr to ism

api_v3/web/testme/css/main.css, api_v3/web/testme/index.php, api_v3/web/testme/js/kPrettify.js, api_v3/web/testme/js/kTestMe.js, api_v3/web/testme/testme.result.php
=> Revert "PLAT-3078"

plugins/cue_points/quiz/lib/model/AnswerCuePoint.php
=> Add setting of customDataObj during pre-insert of answer cue points so all the data will actually be updated

alpha/apps/kaltura/lib/reports/myReportsMgr.class.php
=> Check weather result is OK in a better way

plugins/multi_centers/services/FileSyncImportBatchService.php
with the originalId since fromObject pulls it from there
=> need to update fileSync->custom_data

api_v3/lib/types/entry/KalturaDataEntry.php
=> fix for fatal, create dbObject instead of API object

plugins/content_distribution/providers/tvinci/lib/api/KalturaTvinciDistributionJobProviderData.php
=> PLAT-3575 HF

alpha/lib/model/LiveEntry.php
=> adding logs to understand the cause of infinite entries creation

deployment/updates/scripts/xml/updateCommentWasAddedToEntryEmailNotificationTemplate.xml
=> Script to update the 'comment was added' notification template

api_v3/lib/types/conversionProfile/filters/KalturaAssetFilter.php
otherwise we get a bad query - count on all flavors in the system
=> return empty set when the entry ids are empty

batch/batches/Notifier/KAsyncNotifier.class.php
Reserve update write to worker log
=> Remove update of notificationResult on the batch job itself

deployment/permissions/service.attachment.attachmentasset.ini, deployment/updates/scripts/add_permissions/2015_08_25_update_attachment_asset_permission.php
update and setContent (PLAT-3730)
=> Added permission for user session KS in attachmentAsset service for

plugins/cue_points/quiz/QuizPlugin.php
=> change throwing kCoreException instead of Exception

plugins/cue_points/quiz/QuizPlugin.php
=> Return the correct count for the report

alpha/lib/enums/AppTokenHashType.php, alpha/lib/model/AppToken.php, api_v3/lib/types/KalturaAppToken.php, api_v3/lib/types/enums/KalturaAppTokenHashType.php, api_v3/services/AppTokenService.php
=> Revert "Revert "Jupiter 10.17.0 plat 3477""

plugins/cue_points/quiz/QuizPlugin.php
=> Disregard anonymous users answers in reports

plugins/cue_points/quiz/QuizPlugin.php
=> Disregard answers for unsubmitted quizzes.

plugins/cue_points/quiz/QuizPlugin.php
=> switch order by functions for quiz reports

plugins/cue_points/quiz/QuizPlugin.php
=> Revert "Disregard answers for unsubmitted quizzes."

api_v3/config/testme.ini
remove JSON possibility testme
=> remove JSON possibility testme

plugins/content_distribution/providers/tvinci/TvinciDistributionPlugin.php, plugins/content_distribution/providers/tvinci/lib/admin/TvinciProfileConfiguration.php, plugins/content_distribution/providers/tvinci/lib/admin/XSLTFileValidator.php, plugins/content_distribution/providers/tvinci/lib/feed/TvinciDistributionFeedHelper.php
=> Media Prep 1.1 first fix

generator/sources/csharp/KalturaClientTester/KalturaClientTester.cs
=> Add test case for SUP 2038

plugins/cue_points/quiz/QuizPlugin.php
=> Revert "Disregard anonymous users answers in reports"

plugins/content_distribution/providers/tvinci/lib/admin/TvinciProfileConfiguration.php, plugins/content_distribution/providers/tvinci/lib/admin/XSLTFileValidator.php, plugins/content_distribution/providers/tvinci/lib/feed/TvinciDistributionFeedHelper.php
PLAT-3745
and additionally PLAT-3747
=> MediaPrep1.1 AdmisnConsole UI bug fix

plugins/cue_points/quiz/QuizPlugin.php
=> Return empty report (headers only) instead of exception when entry is

alpha/apps/kaltura/lib/request/infraRequestUtils.class.php
=> Add support in html

deployment/base/sql/01.kaltura_ce_tables.sql
=> Jupiter 10.19.0 scheduler status table id column to bigint

release-notes.md
=> Adding instruction to release notes for SUP-4380

deployment/base/scripts/init_content/03.EventNotificationTemplate.0.template.xml
=> Added attributes to comment email notification

release-notes.md
=> Revert "Jupiter 10.20.0 sup4380"

infra/plugins/KalturaParentContributedPlugin.php
HF-SUP-5904
Changed self:: to this-> in an abstract class
=> SUP-5904-HOTFIX

plugins/content_distribution/providers/tvinci/lib/xml/tvinci_default.xslt
TEN image ingest
JPG extension is needed
=> TEN imgae ingest

alpha/lib/model/UserEntryPeer.php, api_v3/services/UserEntryService.php
=> Allow access only to user's userEntries and return empty list when

alpha/apps/kaltura/lib/batch2/model/kAkamaiUniversalProvisionJobData.php, alpha/scripts/utils/setAkamaiUniversalLiveParamsForPartner.php
=> Add option to manually set hls/hds url for akamai universal live

batch/kaltura_batch.sh
Refactor batch init script to correctly cover start/restart/stop commands with correct status detection and pid/lockfile handling.
Updated with advice of @jessp01
=> Update Batch Manager init script

configurations/apache/kaltura.conf.template
f LB has X_FORWARDED_PROTO set to 'https', set HTTPS to 'on'
=> SSL offloading support

deployment/base/scripts/init_content/04.dropFolder.-4.template.xml
Partner -4 must be impersonated when fetching the default CP
=> Jupiter 10.20.0 kms tasks

plugins/content_distribution/providers/tvinci/lib/feed/TvinciDistributionFeedHelper.php
=> Revert "PLAT-3863"

plugins/content_distribution/providers/tvinci/lib/admin/TvinciProfileConfiguration.php, plugins/content_distribution/providers/tvinci/lib/api/KalturaTvinciDistributionProfile.php, plugins/content_distribution/providers/tvinci/lib/feed/TvinciDistributionFeedHelper.php, plugins/content_distribution/providers/tvinci/lib/model/TvinciDistributionProfile.php, plugins/content_distribution/providers/tvinci/lib/xml/tvinci_default.xslt
=> revert widevine MediaPrep1.1

api_v3/services/BulkUploadService.php, plugins/bulk_upload/csv/BulkUploadCsvPlugin.php
=> Revert "Jupiter 10.17.0 sup 3920"

plugins/content/caption/base/lib/errors/KalturaCaptionErrors.php, plugins/content/caption/base/services/CaptionAssetService.php
The entry does need vaidation since in case of a KS with caption
privilege the entry is not beeing validated as assumed by the comment in
the code
=> Fix PHP Fatal error in CaptionAssetService.php line 581

infra/cdl/kdl/KDLFlavor.php
add an option to set the scale as % of the source dims
=> KMS-8869-Jukin Video Watermark

generator/sources/cli/kalcli.php, generator/sources/cli/kalcliSwitches.php
support params output format - makes it easier to execute 'get', make some changes on result and then execute 'update'
=> Jupiter 10.21.0 kalcli enhancement

alpha/lib/model/LiveEntry.php, alpha/lib/model/MediaServer.php
=> support specific configuration host and port for hls manifest url

configurations/monit/monit.d/percona.template.rc
=> New template file for percona DB

configurations/monit/monit.d/percona.template.rc
=> Added template for Percona

configurations/db.template.ini
=> Added template for Sphinx_log

plugins/metadata/lib/model/om/BaseMetadataProfilePeer.php
=> Fix elseif case to check if partnerGroup array contains WILD_CHAR

infra/cdl/kdl/KDLFlavor.php
Add fade in/out to the burnt in watermarks
=> PLAT-3915-Fade-Watermark

plugins/transcoding/mp4box/lib/KOperationEngineMp4box.php
=> PLAT-3916-MP4Box

alpha/apps/kaltura/lib/renderers/kRendererPdfFile.php, infra/general/PdfGenerator.php, plugins/cue_points/quiz/lib/model/kQuizPdf.php, plugins/cue_points/quiz/services/QuizService.php
Jupiter-10.21.0-update-krenderer-output#time 0.5d
=> Remove the explicit call the the kPdfRenderer::output() method

configurations/monit/monit.d/percona.template.rc
=> Replaced the `hostname` command with @HOSTNAME@ token

deployment/base/scripts/couchbase/deploy.sh, deployment/base/scripts/couchbase/get.sh, deployment/base/scripts/couchbase/views.ddoc
=> Deploy couchbase using command line

generator/sources/php5/KalturaClientBase.php, generator/sources/php53/library/Kaltura/Client/Base.php, generator/sources/zend/Kaltura/Client/ClientBase.php
changes to support sync with the latest saas config
=> Jupiter 10.21.0  plat 3863

api_v3/lib/types/entry/KalturaBaseEntry.php
=> Add deprecated notation to baseEntry categories and categories_ids

plugins/event_notification/providers/email/lib/batch/recipients/KEMailNotificationUserRecipientEngine.php, plugins/event_notification/providers/email/lib/batch/recipients/KEmailNotificationCategoryRecipientEngine.php
=> Change pager size for notification email recipients to 500

configurations/plugins.template.ini
=> Transcript plugin should be enabled by default

admin_console/configs/lang/en.php
Add missing strings to KAC translations
=> Add missing strings to KAC translations

alpha/apps/kaltura/lib/batch2/bcdl/kBusinessPreConvertDL.php
To handle sources that have frame size that is larger then the all flavors
=> SUP-6220 - fix adjustToFramesize

alpha/apps/kaltura/lib/batch2/bcdl/kBusinessPreConvertDL.php
Set WM params through custom metadata fields
=> PLAT-3915-Customable-Watermarking

alpha/scripts/compatCheck.php
may appear in some syndication feeds
=> support xml namespaces in compat check

plugins/metadata/services/MetadataService.php
=> Add save of metadata in any case

plugins/sphinx_search/lib/kSphinxSearchManager.php
=> prevent overflow in sphinx date fields

alpha/apps/kaltura/lib/batch2/kJobsManager.php
=> Abort batch job only if it exists

api_v3/services/MediaService.php
SUP-6102 Default Metadata on web upload
Default Metadata on web upload
=> SUP-6102 Default Metadata on web upload

plugins/content_distribution/providers/tvinci/lib/admin/TvinciProfileConfiguration.php, plugins/content_distribution/providers/tvinci/lib/api/KalturaTvinciDistributionProfile.php, plugins/content_distribution/providers/tvinci/lib/feed/TvinciDistributionFeedHelper.php, plugins/content_distribution/providers/tvinci/lib/model/TvinciDistributionProfile.php, plugins/content_distribution/providers/tvinci/lib/xml/tvinci_default.xslt
PLAT-3863 insertion of the widevine tags to MediaPrep
insertion of the widevine tags to MediaPrep
=> PLAT-3863 insertion of the widevine tags to MediaPrep

tests/standAloneClient/scheduledTaskProfiles/30DayDeleteAfterScheduleEnd.xml
Delete entry 30 days after schedule end date
=> New scheduled task profile

plugins/content_distribution/providers/tvinci/lib/admin/TvinciProfileConfiguration.php, plugins/content_distribution/providers/tvinci/lib/admin/XSLTFileValidator.php
PLAT-4052 validate xslt file exists before
=> PLAT-4052 validate xslt file exists before

generator/sources/php5/KalturaClientBase.php
=> Use PHP format

api_v3/lib/types/conversionProfile/KalturaFlavorParams.php
=> Changing flavorRate variable from int to float

plugins/content_distribution/providers/tvinci/lib/feed/TvinciDistributionFeedHelper.php, plugins/content_distribution/providers/tvinci/lib/xml/tvinci_default.xslt
PLAT-4057 , PLAT-4061
changes to fix errors in the MediaPrep widevine changes
=> PLAT-4057 , PLAT-4061

alpha/apps/kaltura/lib/reports/myReportsMgr.class.php, infra/plugins/interfaces/IKalturaReportProvider.php, plugins/cue_points/quiz/QuizPlugin.php
=> Add suuport to pager in case of Quiz reports

alpha/apps/kaltura/lib/reports/myReportsMgr.class.php, infra/plugins/interfaces/IKalturaReportProvider.php, plugins/cue_points/quiz/QuizPlugin.php
=> Revert "Add suuport to pager in case of Quiz reports"

api_v3/config/testme.ini, api_v3/web/testme/css/main.css, api_v3/web/testme/index.php, api_v3/web/testme/js/kPrettify.js, api_v3/web/testme/js/kTestMe.js, api_v3/web/testme/testme.result.php
PLAT-3078 insert the ace editor to test me
=> PLAT-3078 insert the ace editor to test me

plugins/cue_points/quiz/lib/api/enums/KalturaQuizFileType.php, plugins/cue_points/quiz/services/QuizService.php
=> Add the missing file from the Kajam-11.1.0-PLAT-3975 branch

plugins/cue_points/quiz/lib/model/kQuizPdf.php, plugins/cue_points/quiz/services/QuizService.php
Add sort capability according to the quiz questions. Sorting is done alphabetically.
Kajam-11.1.0-PLAT-3952 # 1 day
=> Add comments in plugins/cue_points/quiz/services/QuizService.php

deployment/base/sql/01.kaltura_ce_tables.sql
=> Fix default type kuser, needed for KMS

alpha/apps/kaltura/modules/extwidget/templates/openGraphSuccess.php, alpha/apps/kaltura/modules/extwidget/templates/previewSuccess.php
to swfs ( SFW open graph is longer broadly supported )
=> #PLAT-3590 -- Add og:video:url, consolidate og:video links, remove links

api_v3/services/BaseEntryService.php
PLAT 3902 allow isShceduledNow when sview privilege
=> PLAT 3902 allow isShceduledNow when sview privilege

generator/sources/zend/Kaltura/Client/ClientBase.php
=> Send Kaltura objectType instead of class name

api_v3/services/BaseEntryService.php
count(objects) may be 0 even when totalCount is 1 due to paging
=> check count(objects) in addition to totalCount

plugins/cue_points/quiz/services/QuizService.php
=> Update path in getUrlAction according to TanTan remarks

deployment/base/sql/01.kaltura_ce_tables.sql
=> Changed the defaut value of 'type' in kuser to '0'

plugins/cue_points/quiz/lib/model/kQuiz.php, plugins/cue_points/quiz/services/QuizUserEntryService.php
=> Revert 21f713aeac8289d062ba0e94428b9c18bebec0d7

api_v3/services/BaseEntryService.php
=> Revert df0df9f1c9f18dceae227a2b296501610cdd4d6f

alpha/apps/kaltura/lib/KSecureEntryHelper.class.php
=> Revert dc520893dd0a2a77a73c6ed1020509c16c9df5b1

alpha/apps/kaltura/lib/KSecureEntryHelper.class.php, api_v3/services/BaseEntryService.php
HOT-FIX PLAT 3902 SVIEW privileges
=> HOT-FIX PLAT 3902 SVIEW privileges

plugins/content/caption/base/lib/captionManagers/srtCaptionsContentManager.php
also ignore spaces after the index in the regular expression
=> support SRTs encoded in UTF-16

alpha/apps/kaltura/lib/myEntryUtils.class.php, api_v3/lib/types/entry/KalturaBaseEntryCloneOptions.php, api_v3/services/BaseEntryService.php, plugins/cue_points/quiz/errors/KalturaQuizErrors.php, plugins/cue_points/quiz/lib/api/KalturaQuiz.php
Due to many indentation issue in the file, please review with ?w=1
=> Kajam 11.1.0 plat 4058 new

api_v3/lib/types/serverNode/base/KalturaServerNode.php, api_v3/lib/types/serverNode/deliveryServer/edgeServerNode/KalturaEdgeServerNode.php, plugins/media/wowza/lib/api/KalturaWowzaMediaServerNode.php, plugins/media/wowza/lib/model/WowzaMediaServerNode.php
=> When adding serverNode validate inser & update by type + remove default

api_v3/services/BaseEntryService.php
=> Entry clone action is enabled only for entries in READY state

alpha/apps/kaltura/lib/kEntitlementUtils.php, alpha/lib/interfaces/IOwnable.php, alpha/lib/model/entry.php, api_v3/lib/KalturaDispatcher.php, api_v3/lib/KalturaDocCommentParser.php, api_v3/services/BaseEntryService.php, api_v3/services/ThumbAssetService.php
Merging after code review by tantan and fix by Michal R.
=> Kajam 11.1.0 plat 4117

plugins/cue_points/quiz/services/QuizUserEntryService.php
=> Change logic of showGradeAfterSubmission

alpha/apps/kaltura/lib/reports/myReportsMgr.class.php, api_v3/lib/types/report/KalturaEndUserReportInputFilter.php
=> escape all user input param to avoid sql injection

alpha/lib/model/Partner.php
=> Changed the admin console from 3 to unlimited

alpha/lib/model/syndicationFeed.php, api_v3/lib/syndication/KalturaFeedRenderer.php, api_v3/lib/types/syndicationFeed/KalturaBaseSyndicationFeed.php
@assafb  Please review. If code review is ok, this pull request will be closed and a new one opened for Kajam-12.0.0
=> Kajam 11.0.0 plat 4028

alpha/lib/model/syndicationFeed.php, api_v3/lib/syndication/KalturaFeedRenderer.php, api_v3/lib/types/syndicationFeed/KalturaBaseSyndicationFeed.php
=> Revert "Kajam 11.0.0 plat 4028"

alpha/lib/data/live/kRecordedSegmentsInfo.php, api_v3/lib/KalturaLiveEntryService.php, plugins/cue_points/base/lib/kCuePointManager.php
Undo all the AMF stuff due to PLAT-4612
also return the duration on live entry to fix races between files & cue
points processing
=> revert for WEBC-631 & more

deployment/base/scripts/insertDefaults.php
with Basewidget::doSave(PropelPDO $con, $skipReload = false)
=> Declaration of Insertwidget::doSave(PropelPDO $con) should be compatible

configurations/cron/dwh.template
=> Fixed user in CRON

configurations/admin.template.ini
=> Add parameter "CaptureSpace - Full client" to client config

alpha/scripts/utils/unDeleteUIConf.php
=> Do not strict file_sync search for uiconf Data file

alpha/lib/data/live/kRecordedSegmentsInfo.php, api_v3/lib/KalturaLiveEntryService.php, plugins/cue_points/base/lib/kCuePointManager.php
Undo all the AMF stuff due to PLAT-4612
also return the duration on live entry to fix races between files & cue
points processing
=> revert for WEBC-631 & more for 11.3.0

alpha/apps/kaltura/modules/extwidget/actions/serveFlavorAction.class.php
=> Added in order to support nginx on ssl

plugins/cue_points/quiz/lib/api/KalturaAnswerCuePoint.php, plugins/cue_points/quiz/lib/model/kQuiz.php
Kajam-11.4.0-PLAT-4632 # 2 days
=> Update review comments

batch/batches/Convert/Engines/KConversionEngineFfmpeg.class.php
Fix the audio source mapping, to adjust for sepating vidoe and audio sources in order to support NGS (video only) piping.
Audio source mapping changed to 1 (original 0)
=> Fix the audio source mapping (NGS)

plugins/bulk_upload/drop_folder_xml/plugins/batch/Engine/KFeedDropFolderEngine.php
QA was not performed - revert change for PLAT-4663
=> Revert change for PLAT-4663

infra/storage/file_transfer_managers/sftpMgr.class.php
=> Fixing password with apostrophe when using sshpass

infra/storage/file_transfer_managers/sftpMgr.class.php
=> Revert "Fixing password with apostrophe when using sshpass"

alpha/apps/kaltura/lib/batch2/bcdl/kBusinessPreConvertDL.php
Optionally preserve original source when custom intermediate-source is used
=> PLAT-4862-keep-original-source

api_v3/web/testme/index.php, api_v3/web/testme/testme.result.php
=> Fix Ace Editor behavior in testme result

generator/sources/bpmn/processes/eventNotificationTemplate.dispatchBySystemName.bpmn
Results in script not executing
=> Missing language definition on script tag

alpha/lib/model/category.php
Kajam-11.6.0-PLAT-4922#time 1d
=> PLAT-4922 reduce memory usage at categoryUser->add

api_v3/lib/types/KalturaObject.php
=> Handle case where cached code file is not ready

infra/cdl/kdl/KDLFlavor.php
error:
Undefined property: KDLMediaDataSet::$_contentStreams
=> fixes:     /opt/kaltura/app/infra/cdl/kdl/KDLFlavor.php:523

api_v3/lib/KalturaErrors.php, api_v3/services/CategoryUserService.php, configurations/base.ini
=> Limit amount of users per category to 5k

alpha/apps/kaltura/modules/extservices/actions/googleoauth2Action.class.php
=> PLAT-4968-HOTFIX

alpha/apps/kaltura/modules/extservices/actions/googleoauth2Action.class.php
=> PLAT-4938-HOTFIX

api_v3/services/BulkUploadService.php
=> Fix delete bulk upload when job not in batch_job_sep

api_v3/lib/KalturaErrors.php, api_v3/services/CategoryUserService.php, configurations/base.ini
=> Hot fix that limit amount of users per category to 5K

infra/general/kHtmlPurifier.class.php
Cache.DefinitionImpl
Version added 2.0.0
TypeString (or null)
Default 'Serializer'
=> See http://htmlpurifier.org/live/configdoc/plain.html:

plugins/cue_points/base/CuePointMetadataPlugin.php
historycal cue point plugin enabled validation
=> Fix mistake in ')' location + remove validatio of plugin enabled due to

alpha/apps/kaltura/lib/storage/kFileSyncUtils.class.php
it will fail and cause PHP to emit a PHP Warning:  chmod(): Operation not permitted.
if the current uid is root, this is of course allowed.
=> do not attempt to change group or permissions in the event the proc' UID is not the same as the file owner

alpha/apps/kaltura/lib/myPlaylistUtils.class.php
=> Validate entry is not deleted in DB when executing a playlist

api_v3/lib/KalturaTypeReflectorCacher.php, api_v3/lib/types/KalturaObject.php
This code change will allow the following -- 
1. Cache files created by apache \ kaltura can be read by the other
2. If the dir will created by one user, the other will be able to add files also.
PLAT-4842#time 20h
=> Change cache files,dir permission since they are accessed from user apache and kaltura simulationously

api_v3/lib/types/KalturaObject.php
=> Break mkdir to mkdir+chmod function since it creates the dir with wrong permission

plugins/sphinx_search/scripts/kaltura_populate.sh
add the ability to start populate even in case maintenance file exists.
=> add forcestart to populate init script

alpha/apps/kaltura/lib/monitor/KalturaMonitorClient.php, alpha/apps/kaltura/lib/monitor/apimonServer.py
also support multiple aggregation fields in the apimon server
=> add sql length to apimon

deployment/updates/scripts/add_permissions/2015_11_12_captureSpace_update_service.php
PLAT-5003 #1h
@MosheMaorKaltura , @tan-tan-kanarek , kindly review.
=> Added CaptureSpace missing permission file

alpha/lib/model/flavorParams.php
CropIMX processing is set to be a default behavior.
=> PLAT-4982-CropIMX update

alpha/apps/kaltura/lib/access_control/model/kEntryContextDataResult.php, alpha/apps/kaltura/lib/kContextDataHelper.php, alpha/apps/kaltura/lib/myPlaylistUtils.class.php, alpha/apps/kaltura/lib/storage/VodPackagerDeliveryUtils.php, alpha/apps/kaltura/modules/extwidget/actions/playManifestAction.class.php, alpha/apps/kaltura/modules/extwidget/actions/serveFlavorAction.class.php, alpha/lib/data/kFilterPager.php, alpha/lib/model/DeliveryProfileVod.php, api_v3/lib/types/entry/KalturaEntryContextDataResult.php, api_v3/services/BaseEntryService.php
=> Kajam 11.7.0 stitched playlist

alpha/lib/model/kuserPeer.php
=> myEntryUtils::copyEntry failed due to bad calling of lock function

plugins/cue_points/base/lib/model/CuePointPeer.php, plugins/cue_points/quiz/lib/model/kQuizPdf.php
=> List the order of the question in PDF based on start_time

plugins/content_distribution/providers/facebook/lib/model/FacebookDistributionProfile.php
=> Remove user_videos from facebook required permissions

plugins/content_distribution/providers/facebook/lib/model/FacebookDistributionProfile.php
=> remove user_actions.video from facebook permissions

api_v3/lib/types/filters/KalturaUserEntryFilter.php, plugins/cue_points/quiz/lib/api/filters/KalturaQuizUserEntryFilter.php
=> Move anonymous handling upper layer to KalturaUserEntry

plugins/cue_points/quiz/QuizPlugin.php
=> Allow quiz plugin for all partners

deployment/updates/sql/2016_02_03_add_default_duration_to_drm_policies.sql, plugins/drm/lib/kDrmPartnerSetup.php, release-notes.md
=> add duration of 1 (counted in days) to default drm_policy

configurations/batch/batch.ini.template, plugins/content_distribution/providers/hulu/lib/HuluDistributionEngine.php
=> have the HULU distribution retry if failed for Aspera upload, up to an hour and a half

plugins/content/document/scripts/convert.php
Add file from /opt/kalura/bin/x64/convert.php to source control.
Please enter the commit message for your changes. Lines starting
=> Add batch execution source file to source control existed in /opt/kalura/bin/x64/convert.php`

plugins/content_distribution/providers/facebook/lib/model/FacebookDistributionProfile.php
=> Chaned 6 to 10 minutes in print validation

batch/kaltura_batch.sh
=> small fixes for script for migration

deployment/permissions/object.KalturaLiveStreamEntry.ini, release-notes.md
=> add two missing permissions to KalturaLiveStreamEntry.ini

plugins/content_distribution/providers/facebook/lib/api/filters/KalturaFacebookDistributionProfileFilter.php, plugins/content_distribution/providers/facebook/lib/api/filters/KalturaFacebookDistributionProviderFilter.php, plugins/content_distribution/providers/facebook/lib/api/filters/base/KalturaFacebookDistributionProfileBaseFilter.php, plugins/content_distribution/providers/facebook/lib/api/filters/base/KalturaFacebookDistributionProviderBaseFilter.php, plugins/content_distribution/providers/facebook/lib/api/filters/orderEnums/KalturaFacebookDistributionProfileOrderBy.php, plugins/content_distribution/providers/facebook/lib/api/filters/orderEnums/KalturaFacebookDistributionProviderOrderBy.php
Kaltura Facebook Distributor filters
=> Kaltura Facebook Distributor filters

api_v3/services/PartnerService.php
https://github.com/kaltura/server/pull/3531/files
=> similar fix as in partner->register():

plugins/bulk_upload/csv/batch/BulkUploadEngineCsv.php
=> Avoid processing empty csv lines in bulk upload

alpha/apps/kaltura/modules/extwidget/actions/serveFlavorAction.class.php
return the encryption key to nginx-vod which will decrypt/reencrypt if needed
=> add support for serving encrypted flavors

alpha/lib/model/DeliveryProfileVod.php, plugins/content_distribution/providers/comcast_mrss/lib/ComcastMrssFeed.php, plugins/content_distribution/providers/comcast_mrss/lib/admin/ComcastMrssProfileConfiguration.php, plugins/content_distribution/providers/comcast_mrss/lib/api/KalturaComcastMrssDistributionProfile.php, plugins/content_distribution/providers/comcast_mrss/lib/model/ComcastMrssDistributionProfile.php
=> Revert "Kajam 11.9.0 add thumbnail ext"

alpha/apps/kaltura/lib/batch2/kFlowHelper.php, api_v3/lib/KalturaEntryService.php
=> Revert "image ext preserved if legit"

alpha/apps/kaltura/modules/extwidget/actions/serveFlavorAction.class.php
for testing purposes, will only work with a single video or videos that were transcoded with the same params and --stitchable
=> add support for live cyclic playlists

plugins/cue_points/code_cue_point/lib/model/CodeCuePoint.php
so code cue point will be copied to VOD
=> add CodeCuePoint:: copyFromLiveToVodEntry

generator/sources/php53/library/Kaltura/Client/Base.php
=> php53 client exception error exposing

api_v3/lib/types/conversionProfile/KalturaThumbnailServeOptions.php, api_v3/services/ThumbAssetService.php
=> Add referrer param to KalturaThumbnailServeOptions

alpha/apps/kaltura/lib/batch2/model/kConvertJobData.php
=> set all flavors urgency to required when replacing an entry mode

configurations/generator.ini
=> modified testing client and added additional configurations

alpha/scripts/utils/moveConvertJobs.php
elements of countByDc should be ints not arrays
=> move jobs small fix

infra/cdl/kdl/KDLFlavor.php
Removed erroneous condition on Framesize compliance check
=> PLAT-5194-FrameSize-flavor-optimization-fix

api_v3/lib/KalturaFrontController.php
=> Fix fatal issue on malformed mulit-request

alpha/apps/kaltura/lib/batch2/kFlowHelper.php, api_v3/lib/KalturaEntryService.php
=> redo the fix that we already had

alpha/scripts/utils/moveConvertJobs.php
=> move convert jobs log change

plugins/cue_points/base/lib/model/CuePointPeer.php, plugins/cue_points/quiz/lib/api/filters/KalturaAnswerCuePointFilter.php
=> Revert "if we don't have a puserId (such as in widgetKS) we need to check for…"

api_v3/services/UserService.php
=> Revert "input validation when add a user"

alpha/apps/kaltura/lib/reports/content_contributions/content_contributions_count.sql, alpha/apps/kaltura/lib/reports/content_contributions/content_contributions_detail.sql, alpha/apps/kaltura/lib/reports/content_contributions/content_contributions_graph.sql, alpha/apps/kaltura/lib/reports/content_contributions/content_contributions_total.sql, alpha/apps/kaltura/lib/reports/myReportsMgr.class.php
=> support search by entry_id in content_contributions report

configurations/sphinx/kaltura.conf.template, plugins/content/caption/search/config/IndexSchema.xml, plugins/content/caption/search/lib/model/index/CaptionAssetItemIndex.php, plugins/content/caption/search/sphinx/CaptionSphinxPlugin.php
=> Remove usage of sphinx attribute str_caption_asset_id

alpha/scripts/utils/setPartnerAdditionalParameters.php
=> utility to add partner additional parameters for mailing list

plugins/cue_points/base/lib/model/CuePointPeer.php
=> Revert of https://github.com/kaltura/server/pull/3945/files

alpha/apps/kaltura/lib/batch2/kJobsManager.php, alpha/apps/kaltura/lib/batch2/model/kMoveCategoryEntriesJobData.php, alpha/apps/kaltura/lib/model/objectfilters/categoryEntryFilter.class.php, alpha/apps/kaltura/lib/model/objectfilters/categoryKuserFilter.class.php, alpha/lib/model/category.php, api_v3/lib/types/batch/KalturaMoveCategoryEntriesJobData.php, api_v3/services/CategoryService.php, batch/batches/MoveCategoryEntries/KAsyncMoveCategoryEntries.class.php
SUP-5851
@MosheMaorKaltura for review
=> fix category delete to be iterative and not recursive

alpha/lib/model/category.php
=> remove alerts when deleting categoryKusers

alpha/lib/model/category.php
=> fix delete categories

alpha/config/IndexSchema.xml, alpha/lib/model/entry.php, alpha/lib/model/index/entryIndex.php, plugins/sphinx_search/lib/SphinxEntryCriteria.php
=> Revert "index also md5 reference id to support long strings search"

generator/CSharpClientGenerator.php
=> Change csharp lib defalut bool value

alpha/apps/kaltura/modules/extwidget/actions/playManifestAction.class.php
=> for HLS requests add all flavors that have the tag "audio_only"

alpha/lib/model/EntryServerNode.php, alpha/lib/model/EntryServerNodePeer.php, alpha/lib/model/ServerNode.php, alpha/lib/model/ServerNodePeer.php, deployment/base/scripts/createQueryCacheTriggers.php
entryServerNode:entryId
serverNode:id
=> add query cache triggers

alpha/apps/kaltura/lib/monitor/apimonServer.py
to support current OTT json structure
=> allow passing floats as strings in the json

alpha/apps/kaltura/lib/events/kEventsManager.php
=> Wrap $event->consume with try and catch

api_v3/lib/types/conversionProfile/KalturaFlavorAssetUrlOptions.php, api_v3/services/FlavorAssetService.php
=> Kajam 11.12.0 sup7741

api_v3/lib/KalturaLiveEntryService.php
=> Revert "Kajam 11.11.0 sup 7792"

api_v3/services/UserEntryService.php, plugins/cue_points/quiz/QuizPlugin.php, plugins/cue_points/quiz/lib/api/KalturaQuizUserEntry.php
=> Validate entry exist and is a quiz when trying to add quizUserEntry

alpha/lib/model/category.php, api_v3/services/SessionService.php, batch/batches/MoveCategoryEntries/KAsyncMoveCategoryEntries.class.php
=> Kajam 11.12.0 sup 5851

alpha/lib/model/category.php
=> modify category method name

alpha/apps/kaltura/lib/kObjectCreatedHandler.php, alpha/lib/data/live/kLiveEntryRecordingOptions.php, alpha/lib/model/LiveEntry.php, api_v3/lib/KalturaLiveEntryService.php, api_v3/lib/types/entry/live/KalturaLiveEntryRecordingOptions.php
@tan-tan-kanarek  @assafb  Please review.
=> Kajam 11.13.0 tr 952

alpha/apps/kaltura/modules/extwidget/actions/playManifestAction.class.php
=> Fix playManifest to filter by paramsIds always

api_v3/lib/KalturaLiveEntryService.php
=> Handle case of simulatanous call to unregisterMediaServerAction

generator/NodeClientGenerator.php, generator/sources/node/KalturaClientBase.js
node client changes... please review and merge
=> node client modifications

alpha/lib/model/category.php, api_v3/services/SessionService.php, batch/batches/MoveCategoryEntries/KAsyncMoveCategoryEntries.class.php
SUP-5851
@tan-tan-kanarek  - finished modifying code after your comments. can you please review?
=> category deletion modification

plugins/like/lib/api/KalturaLike.php, plugins/like/lib/api/filters/base/KalturaLikeBaseFilter.php, plugins/like/lib/model/filters/LikeFilter.class.php
PALT-5534
@MosheMaorKaltura Please review and merge
=> extend likeService.listAction to have entryIdIn

plugins/like/lib/api/KalturaLike.php, plugins/like/lib/api/filters/base/KalturaLikeBaseFilter.php, plugins/like/lib/model/filters/LikeFilter.class.php
=> Revert "extend likeService.listAction to have entryIdIn"

generator/NodeClientGenerator.php, generator/sources/node/KalturaClientBase.js
=> Revert "node client modifications"

alpha/lib/model/category.php, api_v3/services/SessionService.php, batch/batches/MoveCategoryEntries/KAsyncMoveCategoryEntries.class.php
=> Revert "category deletion modification"

alpha/apps/kaltura/lib/KDLWrap.php, alpha/apps/kaltura/modules/system/actions/flavorParamsAction.class.php, alpha/apps/kaltura/modules/system/templates/flavorParamsSuccess.php, alpha/lib/model/flavorParams.php, alpha/lib/model/flavorParamsOutput.php, api_v3/lib/types/conversionProfile/KalturaFlavorParams.php, batch/batches/Convert/Engines/KConversionEngineFfmpeg.class.php, batch/batches/Convert/OperationEngines/KOperationEngineFfmpeg.php, infra/cdl/kdl/KDLCommon.php, infra/cdl/kdl/KDLFlavor.php, infra/cdl/kdl/KDLMediaObjectData.php, infra/cdl/kdl/KDLOperatorFfmpeg.php, infra/cdl/kdl/KDLOperatorFfmpeg0_10.php, infra/cdl/kdl/KDLOperatorFfmpeg2_1_3.php, infra/cdl/kdl/KDLOperatorFfmpeg2_2.php, plugins/transcoding/mp4box/lib/KOperationEngineMp4box.php, plugins/transcoding/watermark/WatermarkPlugin.php
add - subtitle burn-in support
chg - support multiple watermarks
add - adjust h264 levels
=> Kajam 11.14.0 kms 11327 plat 5350

alpha/lib/model/kuser.php
PLAT-5354
@MosheMaorKaltura please review.
=> trigger update user in db when changing only role

plugins/like/lib/api/KalturaLike.php, plugins/like/lib/api/filters/base/KalturaLikeBaseFilter.php, plugins/like/lib/model/filters/LikeFilter.class.php
=> Revert "Revert "extend likeService.listAction to have entryIdIn""

plugins/like/lib/api/KalturaLike.php, plugins/like/lib/api/filters/base/KalturaLikeBaseFilter.php, plugins/like/lib/model/filters/LikeFilter.class.php
=> Revert "Revert "Revert "extend likeService.listAction to have entryIdIn"""

api_v3/lib/KalturaEntryService.php
=> Reverted user id copy from template entry

deployment/updates/scripts/2016_04_05_migrate_tvinci_distribution_tags_to_be_dynamic.php, infra/content/kXml.class.php, plugins/content_distribution/providers/tvinci/lib/admin/TvinciProfileConfiguration.php, plugins/content_distribution/providers/tvinci/lib/admin/forms/TvinciTagSubForm.php, plugins/content_distribution/providers/tvinci/lib/admin/scripts/tvinci-distribution-tag-sub-form.phtml, plugins/content_distribution/providers/tvinci/lib/admin/scripts/tvinci-distribution-tags-sub-form.phtml, plugins/content_distribution/providers/tvinci/lib/api/KalturaTvinciDistributionProfile.php, plugins/content_distribution/providers/tvinci/lib/api/KalturaTvinciDistributionTag.php, plugins/content_distribution/providers/tvinci/lib/api/KalturaTvinciDistributionTagArray.php, plugins/content_distribution/providers/tvinci/lib/feed/TvinciDistributionFeedHelper.php, plugins/content_distribution/providers/tvinci/lib/model/TvinciDistributionProfile.php, plugins/content_distribution/providers/tvinci/lib/model/TvinciDistributionTag.php, plugins/content_distribution/providers/tvinci/lib/xml/tvinci_default.xslt, release-notes.md
This reverts commit 04906f2b311f12d7cf133e40b6f9228dd02cb905.
Conflicts:
release-notes.md
=> Revert "Revert "Kajam 11.12.0 plat 4645 new xslt""

generator/sources/node/tests/01.js, generator/sources/node/tests/02.js, generator/sources/node/tests/1.js, generator/sources/node/tests/config.js, generator/sources/node/tests/deadunitTests.js, generator/sources/node/tests/jess.js, generator/sources/node/tests/nested_reporter_test.unit.js, generator/sources/node/tests/npm-debug.log, generator/sources/node/tests/sync.js, generator/sources/node/tests/testme.good.js, generator/sources/node/tests/testme.js, generator/sources/node/tests/testme.js.old, generator/sources/node/tests/testme1.js, generator/sources/node/tests/testme2.js, generator/sources/node/tests/testme4.js
=> added node tests

plugins/metadata/lib/api/filters/advanced/MetadataSearchFilter.php
=> add textSelect metadata items to be searched for with Exact matches.

plugins/short_link/lib/api/KalturaShortLink.php
=> Change type of 'id' from int to string

plugins/drop_folder/admin/forms/ContentFileHandlerConfig.php
=> Add parameter contentMatchPolicy and slugRegex to fileHandlerConfig

generator/sources/node/README.txt, generator/sources/node/tests/config.js, generator/sources/python/KalturaClient/tests/test_uiconf.py
no-plat
commented specific python test temporarily until fix.
=> modified client testing

infra/cdl/kdl/KDLOperatorFfmpeg2_1_3.php
To support subs positioning & size
=> Updated subtitles burn-in

configurations/plugins.template.ini
=> Add needed plugins for scheduler to avoid generate.php failure

generator/sources/csharp/KalturaClientTester/KalturaClientTester.cs
=> don't stop and wait for readline when test ends csharp.

alpha/apps/kaltura/lib/events/events/kBatchJobStatusEvent.php, alpha/apps/kaltura/lib/events/interfaces/IKalturaBatchJobRelatedEvent.php, plugins/event_notification/providers/bpm/lib/IBusinessProcessCaseIdRelated.php, plugins/event_notification/providers/bpm/lib/model/BusinessProcessNotificationTemplate.php, plugins/event_notification/providers/bpm/lib/model/BusinessProcessSignalNotificationTemplate.php, plugins/integration/lib/events/kIntegrationJobClosedEvent.php, plugins/integration/plugins/bpm_event_notification/lib/kBpmEventNotificationIntegrationFlowManager.php, plugins/integration/plugins/bpm_event_notification/lib/model/kBpmEventNotificationIntegrationJobTriggerData.php
Discussed with @tan-tan-kanarek
=> Fix for BPM Signal Notifications

alpha/apps/kaltura/modules/kmc/templates/supportSuccess.php
@itaykinnrot @MosheMaorKaltura
=> #SUP-5613 #comment fix margin left value for checkbox input #time 1h

plugins/cue_points/quiz/QuizPlugin.php
=> Include anonymous answers results in quiz reports

plugins/drop_folder/admin/forms/XmlFileHandlerConfig.php
=> Add function populateFromObject to XmlFileHandlerConfig

plugins/like/lib/api/filters/KalturaLikeFilter.php
=> Add the entryId in to the criteria

api_v3/services/BatchService.php
=> checkIsDone should not throw exception if no flavors are found

deployment/updates/scripts/2016_04_05_migrate_tvinci_distribution_tags_to_be_dynamic.php
=> migrate so that mbr will beat out ism

plugins/cue_points/quiz/QuizPlugin.php
KMS-11651#time 5minutes
Validated on staging server
=> IVQ - make only report by question to include anonymous user

api_v3/lib/KalturaEntryService.php
=> Revert copy user id from template entry

alpha/lib/model/PartnerLoadPeer.php
=> in case of null partner we should return 0 and not crash.

alpha/lib/model/flavorAsset.php, api_v3/lib/types/conversionProfile/KalturaFlavorAsset.php
Kajam-11.14.0-PLAT5441 #time 3h
=> Added ability to set language on flavor asset object

alpha/apps/kaltura/modules/kmc/actions/supportAction.class.php
=> Encode post values when submit ticket

alpha/apps/kaltura/modules/kmc/actions/supportAction.class.php
=> Revert "Encode post values when submit ticket"

alpha/lib/model/flavorAsset.php, api_v3/lib/types/conversionProfile/KalturaFlavorAsset.php
=> Revert "Added ability to set language on flavor asset object"

plugins/content_distribution/providers/youtube_api/lib/YoutubeApiDistributionEngine.php
=> Add code to update privacy status and not just insert it

alpha/apps/kaltura/lib/KDLWrap.php
Automatically assign language to flavor asset
=> PLAT-5441 - flavor asset set language

generator/ErlangClientGenerator.php
/opt/kaltura/app/generator/ErlangClientGenerator.php on line 271
=> PHP Fatal error:  Cannot break/continue 1 level in

api_v3/lib/types/filters/base/KalturaAppTokenBaseFilter.php, api_v3/lib/types/filters/base/KalturaUserEntryBaseFilter.php, plugins/schedule/base/lib/api/filters/base/KalturaScheduleEventBaseFilter.php, plugins/schedule/base/lib/api/filters/base/KalturaScheduleEventResourceBaseFilter.php, plugins/schedule/base/lib/api/filters/base/KalturaScheduleResourceBaseFilter.php, plugins/short_link/lib/api/filters/base/KalturaShortLinkBaseFilter.php
=> added missing extends of KalturaRelatedFilter from generating filters

configurations/base.ini, infra/general/kHtmlPurifier.class.php
=> add exceptions needed for html purifier

alpha/lib/model/categoryKuser.php, alpha/lib/model/categoryKuserPeer.php, api_v3/services/UserService.php
=> Update categoryUser table when update User

release-notes.md
Added slating related release notes
=> Add Ad-stitching v2.0.0 release notes

plugins/schedule/base/lib/model/ScheduleEvent.php
=> added missing parentheses

alpha/apps/kaltura/lib/storage/kStorageExporter.php, alpha/lib/model/StorageProfile.php
=> Revert "Kajam 11.16.0 export thumbs plat 2325"

api_v3/services/ThumbAssetService.php, deployment/permissions/service.thumbasset.ini, release-notes.md
=> revert changes for exporting thumbs

generator/sources/cli/kalcli.php, generator/sources/cli/kalcliSwitches.php
dont read from stdin by default when the input is a tty.
x - disable stdin reading
X - force stdin reading
=> kalcli - change read stdin default

alpha/apps/kaltura/lib/batch2/bcdl/kBusinessPreConvertDL.php
=> PLAT-5524 fix isEncrypted Parameter

generator/TestmeGenerator.php
=> Exclude actions

alpha/lib/model/kuser.php, api_v3/services/UserService.php
=> move category_kuser update to kuser postUpdate

deployment/base/scripts/init_content/03.EventNotificationTemplate.0.template.xml, deployment/updates/scripts/xml/2016_05_31_updateEntryReadyTemplateForReplace.xml, release-notes.md
=> update entry ready mail notification

plugins/schedule/base/lib/kScheduleEventsConsumer.php
=> Added schedule events consumer

deployment/updates/scripts/xml/2016_05_31_updateEntryReadyTemplateForReplace.xml
=> update the email notification template update script

alpha/apps/kaltura/lib/reports/myReportsMgr.class.php
=> format time with hour part

plugins/schedule/base/lib/model/ScheduleEvent.php, plugins/schedule/base/lib/model/index/ScheduleEventIndex.php
=> templateEntryId index configuration modifications

alpha/lib/model/DeliveryProfile.php, alpha/lib/model/flavorAsset.php, infra/general/languageCodeManager.php
=> Multi language Add language manager and integrate deliveryProfile

api_v3/lib/KalturaEntryService.php
=> If no Kuser on entry Make sure that Kuser is always set from the KS.

alpha/apps/kaltura/lib/model/objectfilters/categoryKuserFilter.class.php, alpha/lib/model/category.php
=> add delete direct member only to filter in enable inherit

alpha/apps/kaltura/lib/KDLWrap.php, alpha/apps/kaltura/lib/batch2/bcdl/kBusinessPreConvertDL.php, alpha/lib/model/flavorParams.php, alpha/lib/model/flavorParamsConversionProfile.php, alpha/lib/model/flavorParamsOutput.php, alpha/lib/model/mediaInfo.php, api_v3/lib/types/conversionProfile/KalturaConversionProfileAssetParams.php, api_v3/lib/types/conversionProfile/KalturaFlavorParams.php, api_v3/lib/types/conversionProfile/KalturaMediaInfo.php, batch/batches/ExtractMedia/KAsyncExtractMedia.class.php, infra/cdl/kdl/KDLCommon.php, infra/cdl/kdl/KDLFlavor.php, infra/cdl/kdl/KDLMediaObjectData.php, infra/media/mediaInfoParser/KMediaFileComplexity.php
=> Kajam 11.17.0 plat 5640 content aware encoding

configurations/batch/batch.ini.template
params.localTempPath required to hold the complexity evaluation temp files
=> PLAT-5640-ContentAwareEncoding

alpha/lib/model/DeliveryProfile.php, alpha/lib/model/flavorAsset.php
=> if language not defined leave it as is

tests/standAloneClient/bpmNotificationsTemplates.xml
* Added "Transcript Asset Data Changed, Asset Status Equals"
* Transcript Asset Data Changed - Disable abortOnDelete and fixed wrong mainObjectCode
=> BPM Templates Update

alpha/apps/kaltura/lib/live/kBroadcastUrlManager.php
=> Restore adding the extra "/" to the brodcast url to match the old Wowza Servers

generator/config/generator.ini
=> Add KalturaVarConsolePartnerFilter to var_console

alpha/apps/kaltura/modules/extwidget/actions/playManifestAction.class.php, alpha/lib/model/assetParams.php
=> changed audio_only tag to alt_audio on playManifest

vendor/ZendFramework/library/Zend/Log/Formatter/Simple.php
=> fixed require command error - was pointing to wrong path

plugins/content/caption/base/lib/api/KalturaCaptionAsset.php, plugins/content/caption/base/lib/captionManagers/webVttCaptionsContentManager.php, plugins/content/caption/base/lib/kCaptionsContentManager.php, plugins/content/caption/base/lib/kWebVTTGenerator.php, plugins/content/caption/base/services/CaptionAssetService.php
=> Kajam 11.17.0 plat 5496

plugins/schedule/base/lib/iCal/kSchedulingICalEvent.php, plugins/schedule/bulk_upload/batch/BulkUploadEngineICal.php
=> added handling ical timezone without parentecies.

plugins/schedule/base/lib/model/ScheduleEvent.php
=> remove dupliaction of templateEntryId

plugins/integration/providers/cielo24/lib/kCielo24FlowManager.php, plugins/integration/providers/voicebase/lib/kVoicebaseFlowManager.php
- Raise kObjectDataChangedEvent when asset data is updated in Cielo24 and VoiceBase integration providers
Reviewed on https://github.com/kaltura/server/pull/4403
=> TR-1144 - Raise kObjectDataChangedEvent

infra/storage/file_transfer_managers/s3Mgr.class.php
=> Fix handling exception from S3->putObject

plugins/schedule/base/lib/iCal/kSchedulingICalComponent.php
found by BE automation phpUnit testing
PLAT-5519
=> fixed parsing iCal i case of Rule in event.

alpha/lib/model/DeliveryProfile.php
=> if language is undefined return language as-is

alpha/lib/model/entry.php
=> Don't copy displayInSearch from template entry

alpha/apps/kaltura/lib/monitor/apimonServer.py
=> catch json parsing errors in apimon server

plugins/schedule/base/lib/iCal/kSchedulingICal.php
=> fix filename type

alpha/apps/kaltura/modules/extwidget/actions/serveFlavorAction.class.php
to support packaging of captions/multi-audio in nginx-vod
=> serveFlavor - return the language + label in json

infra/general/timezones/lotusTimezones.php, infra/general/timezones/microsoftExchangeTimezones.php, infra/general/timezones/phpTimezones.php, infra/general/timezones/timezoneIdentifiers.php, infra/general/timezones/windowsTimezones.php
PLAT-5738
reviewed by @yossipapi
=> fix array declaration supported in php 5.3 and not in 5.6

alpha/apps/kaltura/lib/batch2/bcdl/kBusinessPreConvertDL.php
On frame size flavor matching, the next closest flavor might become redundant.
=> FIX-remove redundant on frame size matching

alpha/apps/kaltura/lib/monitor/apimonServer.py
also added reuse addr in order to allow fast start/stop
=> apimon - support saving the input to gzip files

alpha/apps/kaltura/lib/mySearchUtils.class.php
=> In case entry with parent ID set , set display_in_search to system

alpha/apps/kaltura/lib/myEntryUtils.class.php, alpha/apps/kaltura/lib/myFileConverter.class.php
=> fixed the thumbnail preview display direction when source is rotated

alpha/apps/kaltura/lib/myEntryUtils.class.php
=> rename static function to getRotate

infra/cdl/kdl/KDLAudioMultiStreaming.php, infra/cdl/kdl/KDLCommon.php, infra/cdl/kdl/KDLFlavor.php, infra/cdl/kdl/KDLOperatorFfmpeg2_1_3.php
- surround
- upgrade multi-lingual
=> Extend MultiStream support

alpha/apps/kaltura/lib/myEntryUtils.class.php, alpha/apps/kaltura/lib/myFileConverter.class.php
=> fixed Call to a member function getVideoRotation() on a non-object

deployment/base/scripts/init_data/03.UserRole.ini, deployment/updates/scripts/add_permissions/03.UserRole.ini
=> fixed typo

generator/config/generator.ini
=> Revert "add include o admin console client"

generator/config/generator.ini
=> Revert "Add KalturaSystemPartnerPackage to adminConsole"

plugins/content/transcript/TranscriptPlugin.php, plugins/content/transcript/lib/api/KalturaTranscriptAssetListResponse.php
=> Revert "Kajam 11.19.0 tr 1029"

deployment/updates/scripts/add_permissions/2016_07_5_add_capture_device_role_and_permissions.php
=> update permissions script for CAPTURE_DEVICE_ROLE

infra/cdl/kdl/KDLOperatorFfmpeg.php
new 'SplitCommandLineForVideoPiping' helper func
=> PLAT-4439-fix split for piping

infra/cdl/kdl/KDLAudioMultiStreaming.php
- additional auto-surround-to-stereo ⇒ DL/DR
- changed analizeSourceContentStreams
=> PLAT-4439-updates

infra/cdl/kdl/KDLFlavor.php
- clean up of obsolete multi-stream code
- auto-decrypt support
- new AR mode - anything that not 4:3, turn into 16:9
=> PLAT-4439-updates and auto-decrypt and new-ARmode

infra/media/mediaInfoParser/KMediaInfoMediaParser.php
Fix bug in old mediainfo with encrypted sources
=> Auto-decryption

alpha/apps/kaltura/modules/extwidget/actions/playManifestAction.class.php, alpha/lib/model/DeliveryProfile.php, alpha/lib/model/DeliveryProfileVodPackagerDash.php, alpha/lib/model/DeliveryProfileVodPackagerMss.php, api_v3/lib/types/delivery/KalturaDeliveryProfile.php
can be used to automatically add caption assets to the result
=> support supplementary assets in delivery profile

api_v3/lib/types/enums/KalturaLanguage.php, plugins/content_distribution/providers/cross_kaltura/lib/batch/CrossKalturaDistributionEngine.php
=> fixed k2k connector failed to distribute

infra/general/languageCodeManager.php
=> removed php warning

infra/general/languageCodeManager.php
=> Revert "removed php warning"

batch/batches/Provision/Engines/KProvisionEngineUniversalAkamai.php, infra/general/KCurlWrapper.class.php
=> change if return error code from akami server

alpha/apps/kaltura/lib/batch2/kFlowManager.php
=> add validation for fileSync

configurations/sphinx/kaltura.conf.template, plugins/cue_points/base/config/IndexSchema.xml, plugins/cue_points/base/lib/model/CuePoint.php, plugins/cue_points/base/lib/model/CuePointPeer.php, plugins/cue_points/base/lib/model/index/CuePointIndex.php
modified kaltura_cue_points table index to be string instead of int (type, is_public, kuser_id) so they can be text searchable. modified filter results in cuePoints to all user with a priviliage on a specific entry to retrieve other users private cuePoints connected to that entry.
PLAT-5742
=> Kajam 11.21.0 plat 5742

alpha/apps/kaltura/lib/myEntryUtils.class.php
=> fixed Thumbnail Preview Display Direction

plugins/cue_points/base/lib/model/CuePointPeer.php
=> recommented code that was supposed to be commented.

alpha/lib/model/entry.php
=> copy collaborators from template entry

infra/general/KCurlWrapper.class.php
=> check for return code from curl request

plugins/cue_points/base/lib/model/CuePoint.php, plugins/cue_points/base/lib/model/CuePointPeer.php
=> added is_public prefix for cuePoint indexing

plugins/schedule/base/lib/iCal/kSchedulingICalEvent.php
=> retrieve parents resources id's in case of a recurrences event retrieval

plugins/schedule/base/services/ScheduleEventService.php
=> fixed recurrences endDate calculations

plugins/cue_points/sphinx/lib/SphinxCuePointCriteria.php
=> Move is_public to use partner prefix for sphinx optimizatioon

plugins/schedule/base/lib/iCal/kSchedulingICalEvent.php
also fixed exporting only child resources id's when exists instead of combining with parent's resources id's
PLAT-5880
PLAT-5878
@noam-arad
=> get duration in Ical format when exporting ical.

plugins/cue_points/base/lib/api/filters/KalturaCuePointFilter.php, plugins/cue_points/sphinx/lib/SphinxCuePointCriteria.php
=> moving handling cuepoint filter typeIn and typeEqual to the sphinx applyingFilters part PLAT-5742

batch/batches/LiveToVOD/KAsyncLiveToVod.class.php
=> add field to copy in cue point

infra/media/thumbnailMaker/KImageMagickCropper.php
=> fixed thumbnail orientation - 270 video rotation case

alpha/apps/kaltura/lib/storage/urlTokenizers/kCloudFrontUrlTokenizer.php, alpha/apps/kaltura/lib/storage/urlTokenizers/kKsUrlTokenizer.php, alpha/apps/kaltura/lib/storage/urlTokenizers/kUrlTokenizer.php, api_v3/lib/types/delivery/KalturaUrlTokenizer.php, api_v3/lib/types/delivery/KalturaUrlTokenizerCloudFront.php
move the ip restriction flag to the base
=> support ip restriction in ks tokenizer

alpha/apps/kaltura/modules/extwidget/actions/playManifestAction.class.php
=> added altAudio flavors to manifest if protocol is mpeg-dash

plugins/content_distribution/providers/youtube_api/lib/YoutubeApiDistributionEngine.php
=> Catch Google_Service_Exception in YT api doSubmit

plugins/content_distribution/lib/kContentDistributionFlowManager.php
=> fixed remove entry from remote distribution

plugins/schedule/base/lib/api/KalturaScheduleEvent.php
=> edit validations for updating schedule events

alpha/apps/kaltura/modules/extwidget/actions/playManifestAction.class.php, alpha/lib/model/DeliveryProfileDynamicAttributes.php
=> handle the case where playManifest request has no flavors

plugins/schedule/base/lib/model/data/kScheduleEventRecurrence.php
=> fix bug when calculating endDate

alpha/apps/kaltura/modules/extwidget/actions/playManifestAction.class.php, alpha/lib/model/DeliveryProfileDynamicAttributes.php, alpha/lib/model/DeliveryProfileVod.php, alpha/lib/model/DeliveryProfileVodPackagerDash.php, alpha/lib/model/DeliveryProfileVodPackagerHds.php, alpha/lib/model/DeliveryProfileVodPackagerHls.php, alpha/lib/model/DeliveryProfileVodPackagerMss.php
=> support play-server in delivery profile

plugins/content_distribution/lib/kContentDistributionFlowManager.php
=> fixed entry with metadata not removed from remote distribution

api_v3/lib/KalturaEntryService.php
=> make accessControlId updatebale using user KS

plugins/schedule/base/lib/model/data/kScheduleEventRecurrence.php
=> fixed reccurences creation period length to be 2 years.

api_v3/lib/KalturaEntryService.php
Reverts kaltura/server#4662
Due to request by Mr. @shomronk
=> Revert "make accessControlId updatebale using user KS"

alpha/apps/kaltura/lib/kManifestRenderers.php, alpha/apps/kaltura/modules/extwidget/actions/playManifestAction.class.php, alpha/lib/model/DeliveryProfileDynamicAttributes.php, alpha/lib/model/DeliveryProfileVod.php, alpha/lib/model/DeliveryProfileVodPackagerDash.php, alpha/lib/model/DeliveryProfileVodPackagerHds.php, alpha/lib/model/DeliveryProfileVodPackagerHls.php, alpha/lib/model/DeliveryProfileVodPackagerMss.php
=> move playServer sessionId creation to renderer

api_v3/lib/syndication/SyndicationFeedRenderer.php
=> fix yahoo syndication play-media url

alpha/apps/kaltura/lib/batch2/bcdl/kBusinessConvertDL.php
=> update ad stitching transcoding command

plugins/cue_points/base/lib/model/CuePointPeer.php
=> fix adding duplicate pid prefix on cue_point_type in sphinx

plugins/schedule/base/lib/model/filters/ScheduleEventResourceFilter.class.php
=> fix filter event id or parent id

plugins/cue_points/base/lib/api/KalturaCuePoint.php
=> add check no RECORDED_LIVE in start time validation of cue point

alpha/apps/kaltura/lib/batch2/kFlowHelper.php, alpha/apps/kaltura/lib/batch2/model/kBulkUploadJobData.php, api_v3/lib/types/batch/KalturaBulkUploadJobData.php
SUP-7180
Please enter the commit message for your changes. Lines starting
=> fixed bulkUploadJobData emailRecipient field

plugins/schedule/base/lib/model/ScheduleEventPeer.php
PLAT-6130
Please review and merge
=> fix delete no only future events

api_v3/services/LiveReportsService.php
=> Use entryPeer::NAME in query of LiveEntry - report

plugins/schedule/base/SchedulePlugin.php, plugins/schedule/base/lib/api/KalturaScheduleEvent.php
reviewed already in pull request: https://github.com/kaltura/server/pull/4736
=> Lynx 12.2.0 plat 5485

api_v3/lib/KalturaErrors.php, plugins/schedule/base/lib/api/KalturaScheduleResource.php
reviewed on https://github.com/kaltura/server/pull/4725/files
=> Lynx 12.2.0 plat 5513

api_v3/lib/KalturaErrors.php, plugins/schedule/base/lib/api/KalturaScheduleEventResource.php
PLAT-5613
reviewed on https://github.com/kaltura/server/pull/4726/files
=> Validating that duplicate schedule event resources are not being created

plugins/schedule/base/lib/api/KalturaScheduleEvent.php
PLAT-6123
reviewed on https://github.com/kaltura/server/pull/4724
=> make sure that until and count are not both set when updating an event

plugins/schedule/base/lib/api/KalturaScheduleResource.php
=> make sure resource parent id is valid also on update

alpha/apps/kaltura/lib/kEntitlementUtils.php, alpha/lib/model/category.php, alpha/lib/model/entry.php, api_v3/lib/types/entry/KalturaBaseEntry.php, plugins/sphinx_search/lib/SphinxCategoryCriteria.php
@yossipapi 
Please Review and comment... 
We can do this together if you want.
=> Lynx 12.2.0 plat 5983 fix

api_v3/lib/KalturaErrors.php, plugins/schedule/base/lib/api/KalturaScheduleEventResource.php
=> validate resources and events exist when creating scheduleResourceEvent

infra/general/scheduling/DatesGenerator.php
=> removed log message

plugins/cue_points/base/lib/kCuePointManager.php, plugins/cue_points/base/lib/model/CuePointPeer.php
=> move function check cue point to cuePointPeer

alpha/apps/kaltura/lib/model/objectfilters/filters.class.php, plugins/schedule/base/lib/api/filters/base/KalturaScheduleEventBaseFilter.php, plugins/schedule/base/lib/model/filters/ScheduleEventFilter.class.php, plugins/schedule/base/lib/model/index/ScheduleEventIndex.php
=> add sort on summary field in schedule events

plugins/cue_points/base/lib/api/KalturaCuePoint.php
=> allow cue point with start time 0

configurations/sphinx/kaltura.conf.template, plugins/schedule/base/lib/model/ScheduleEvent.php
=> add the new sphinx attr to conf.template

alpha/apps/kaltura/modules/extwidget/actions/serveFlavorAction.class.php
enu & enb are not supported by the packager
=> serveFlavor - map enu & enb to eng

alpha/apps/kaltura/lib/myPartnerRegistration.class.php
Use stronger SHA1 algorithm for partner hash generation
=> Use stronger SHA1 algorithm

alpha/apps/kaltura/lib/myPartnerRegistration.class.php
=> Revert "Use stronger SHA1 algorithm"

plugins/content/caption/base/services/CaptionAssetService.php
=> change download file name when calling to setContent action

alpha/lib/model/Partner.php
=> change CountAdminUser from DB to sphinx

plugins/bulk_upload/xml/batch/BulkUploadEngineXml.php, plugins/bulk_upload/xml/xml/ingestion.xsd
=> add field in XML bulkupload to keep-Manual-Thumbnails

plugins/schedule/base/lib/api/KalturaScheduleEvent.php, plugins/schedule/base/lib/api/filters/orderEnums/KalturaScheduleEventOrderBy.php
anther fix related to PLAT-6164
=> add enum for summary sort

alpha/apps/kaltura/modules/extwidget/actions/playManifestAction.class.php
=> remove alt_audio tag from fallback tags

plugins/schedule/base/lib/iCal/kSchedulingICalEvent.php
=> make sure resource 0 will not be exported outside of BE

plugins/schedule/base/services/ScheduleEventResourceService.php, plugins/schedule/base/services/ScheduleEventService.php, plugins/schedule/base/services/ScheduleResourceService.php
=> change documentation for scheduling services

plugins/event_notification/providers/bpm/admin/BusinessProcessNotificationTemplateConfiguration.php
=> fix list on Business Processes

plugins/cue_points/base/lib/api/KalturaCuePoint.php
=> Allow startTime 0 whith triggerAt

plugins/integration/providers/voicebase/lib/kVoicebaseFlowManager.php
- Fixed wrong method call
- Added line break
=> TR-1663 - VoiceBase DFXP Transformation Fixes

alpha/apps/kaltura/lib/myEntryUtils.class.php
=> don't copy timethumbasset twice when copy entry

plugins/bulk_upload/xml/batch/BulkUploadEngineXml.php
=> TR-1673 - testing

alpha/apps/kaltura/lib/batch2/bcdl/kBusinessPreConvertDL.php, alpha/apps/kaltura/lib/batch2/kBatchManager.php, alpha/lib/model/entry.php, alpha/lib/model/flavorAsset.php, alpha/lib/model/kStreamContainer.php, api_v3/lib/types/KalturaStreamContainer.php, api_v3/lib/types/KalturaStreamContainerArray.php, api_v3/lib/types/conversionProfile/KalturaFlavorAsset.php, api_v3/lib/types/entry/KalturaMediaEntry.php, infra/cdl/kdl/KDLAudioMultiStreaming.php, infra/cdl/kdl/KDLCommon.php, infra/cdl/kdl/KDLFlavor.php, infra/cdl/kdl/KDLMediaDataSet.php, infra/cdl/kdl/KDLOperatorFfmpeg2_1_3.php, infra/media/mediaInfoParser/KMediaFileComplexity.php, plugins/bulk_upload/xml/batch/BulkUploadEngineXml.php, plugins/bulk_upload/xml/xml/ingestion.xsd
=> added streams section in bulk upload xml

alpha/apps/kaltura/lib/webservices/kSessionUtils.class.php
=> fix mixed int/string values in db query

plugins/integration/providers/voicebase/lib/kVoicebaseFlowManager.php
=> TR-1663 - Voicebase DFXP transformation

infra/general/scheduling/DatesGenerator.php, plugins/schedule/base/lib/api/KalturaScheduleEventRecurrence.php, plugins/schedule/base/lib/model/data/kScheduleEventRecurrence.php
=> fix dst time by changing the timezone when calculating recurrences dates

api_v3/lib/KalturaErrors.php, plugins/media/wowza/services/LiveConversionProfileService.php
=> Revert "Change live transcoding profile"

batch/batches/Convert/Engines/KConversionEngineFfmpeg.class.php
Fix WM aspect ratio for anamorphic sources
=> SUP-9607-FIX-WM-AspectRatio

alpha/apps/kaltura/lib/batch2/model/kConvertJobData.php
=> check intermediate source flow if no readiness found

alpha/apps/kaltura/lib/kManifestRenderers.php, alpha/lib/model/DeliveryProfile.php
=> added label support to manifest

infra/general/scheduling/DatesGenerator.php
=> first get canidate and then break loop

plugins/tag_search/sphinx/kTagFlowManager.php
=> Revert "tags will always have non-empty string in the privacy_context"

tests/standAloneClient/adCuePointHttpNotification.xml
=> add http notification on ad cue point

plugins/event_notification/providers/bpm/admin/EntryBusinessProcess.php, plugins/event_notification/providers/bpm/services/BusinessProcessCaseService.php
=> modified BusinessProcessCaseService list action to return latest case id

release-notes.md
=> add release notes

alpha/lib/model/entry.php
=> Copy partnerSortValue in case of entry close

configurations/local.template.ini
=> added directives for live analytics as well as for the new 'analytics'

alpha/apps/kaltura/lib/batch2/kBatchManager.php
=> Removed 'max_mbr_flavor_bitrate=8000' limitation

release-notes.md, tests/standAloneClient/adCuePointHttpNotification.xml
PLAT-6235
reviewed in https://github.com/kaltura/server/pull/4965
=> add play server notification

tests/standAloneClient/adCuePointHttpNotification.xml
=> change play server notifications to Ad cue point only

alpha/apps/kaltura/lib/kPlaybackContextDataHelper.php
=> handle case where no custom delivery profiles are defined

alpha/lib/model/Partner.php, alpha/lib/model/kuserPeer.php
=> Load getAdminLoginUsersNumber from sphinx
