alpha/lib/data/live/kLiveRecordingSegmentInfo.php
alpha/lib/model/LiveEntry.php
api_v3/lib/KalturaLiveEntryService.php
api_v3/lib/types/entry/KalturaLiveEntry.php
plugins/cue_points/base/lib/kCuePointManager.php
plugins/cue_points/base/lib/model/CuePoint.php
plugins/cue_points/thumb_cue_point/model/ThumbCuePoint.php

1. Added code to copy cuepoints from live to VOD within the barriers of the VOD duration.
2. Changed lastElapsedRecordingTime to lastElapsedLiveDuration and made lastElapsedRecordingTime deprecated.
3. Accumulating recorded entry duration in appendRecording via recordedLengthInMsec
4. Added kLiveRecordingSegmentInfo
5. Setting cuepoint status to HANDLED immediately if recording is disabled, otherwise, after copying cuepoints to VOD entry.
6. Copying only cuepoints with READY state (skipping already HANDLED cuepoints), which replaces the maxCopiedVodCuePointStartTime condition.

PLAT-2289 Live to VOD offset fix

---

configurations/monit/monit.template.rc

Decreasing the interval prevents major issues with service restarts and prevents monit from taking down the server simply by monitoring.

Decrease daemon interval

---

infra/KAutoloader.php

sometimes the apc gets messed up and returns objects / resources etc.

make sure the value returned from apc is a string

---

configurations/apache/conf.d/enabled.kaltura.conf.template
configurations/local.template.ini

- serveFlavor URLs should not be limited /p/[0-9]+/sp/[0-9]+
- internal_ip_range is required so that serveFlavor will support the pathOnly parameter

changes for nginx-vod-module integration with CE

---

infra/log/KalturaSerializableStream.php

sometimes php://output is used as the log file name

open only udg:// with fsockopen

---

configurations/generator.ini
generator/ObjCClientGenerator.php
generator/sources/cli/kalcli.php
generator/sources/cli/lib/KalturaCurlWrapper.php

objc - prefixing new/copy properties with _ is not enough, need to use a real letter
kalcli - return a non-zero code on error
generator.ini - marked some client libs as internal

Jupiter 10.4.0 client lib changes

---

api_v3/lib/types/filters/KalturaFilterPager.php
api_v3/services/FlavorAssetService.php
api_v3/services/ThumbAssetService.php
plugins/content/attachment/services/AttachmentAssetService.php
plugins/content/caption/base/services/CaptionAssetService.php

avoid calling doCount when the count can be determined according to the number of returned assets

optimize asset.list actions

---

alpha/apps/kaltura/lib/batch2/bcdl/kBusinessConvertDL.php
api_v3/lib/KalturaLiveEntryService.php
plugins/cue_points/base/lib/kCuePointManager.php

1. Ensuring all LIVE asset tags are copied to VOD,
2. Copying cuepoints from LIVE to VOD only when the mediaInfo was created for the VOD asset with the RECORDING_ANCHOR tag.
PLAT-2451 #time 2d

Copying cuepoints on RECORDING_ANCHOR VOD flavor only

---

alpha/apps/kaltura/modules/extwidget/actions/thumbnailAction.class.php

do not save the path to memcache if it contains _NOCACHE_, saving it to memcache can later cause index.php to return it with caching headers of 100 days

thumbnail action cache fix

---

deployment/updates/sql/2015_01_20_kuser_kgroup_table.sql

TYPE was removed somewhere in mysql v5.1
@erankor / @tan-tan-kanarek  - please review.
@AviBueno  - FYI

change 'type' to 'engine' to support old mysql version

---

api_v3/web/testme/ajax-get-type-subclasses.php

avoid holding all the type reflectors in an array

optimize the memory usage of ajax-get-type-subclasses

---

configurations/admin.template.ini
release-notes.md

Real-time dashboard permission in now based on the general live-stream permission

PLAT-2705 | Remove real-time report permission from Admin Console

---

alpha/apps/kaltura/lib/myPlaylistUtils.class.php
alpha/apps/kaltura/modules/partnerservices2/actions/executeplaylistAction.class.php
alpha/apps/kaltura/modules/partnerservices2/actions/executeplaylistfromcontentAction.class.php
alpha/apps/kaltura/modules/partnerservices2/actions/getplayliststatsfromcontentAction.class.php
api_v3/services/PlaylistService.php

to myPlaylistUtils::executeDynamicPlaylist() and preserving per-rule limits (unless the requested limit is higher).
Also, removed filter from PS2 executeplaylist* as it is not being used.
PLAT-1680

Fetching up to LIMIT results if a limit was supplied

---

alpha/apps/kaltura/lib/model/objectfilters/kuserFilter.class.php
api_v3/lib/types/filters/KalturaUserFilter.php

1. loginEnabledEqual should be translated to _gt_login_data_id instead of _gte_login_data_id. login_data_id is nullable in mysql but 0'd in sphinx.
2. when setting loginEnabledEqual in doFromObject, we should use the identical comparison operator (===), otherwise null is equal to 0.

fixed 2 bugs with KalturaUserFilter::loginEnabledEqual

---

alpha/scripts/compatCheck.php
deployment/uiconf/KalturaClientBase.php
generator/sources/php5/KalturaClientBase.php
generator/sources/php53/library/Kaltura/Client/Base.php
generator/sources/zend/Kaltura/Client/ClientBase.php

Used [CURLFile](http://php.net/manual/es/class.curlfile.php) instead "@filename" when posting files if PHP>=5.5.
Replaces #2005.

Used CURLFile instead "@filename" when posting files if PHP>=5.5

---

alpha/apps/kaltura/lib/myEntryUtils.class.php
alpha/lib/model/assetPeer.php

The root cause for SUP-4103 is that there are no thumbnails available andd we try to generate them on the fly, in order to generate them we try to get the flavor_asset with the highest bitrate to get the thumbnails from, in this case the customer has external storage configured and "delete after export" so that some of the flavor assets are connected to file syncs that are deleted. The fix is to see if to get the flavor asset with the highest bitrate and a file sync that is in status "ready". Such a flavor asset doesn't have to exist but this is still a better solution than the one we have in place.
@yuly-roberman please approve you have reviewed
Note: this is a new pull request to Jupiter-10.10, the previous one for Jupiter-10.9 was not relevant.

Jupiter 10.7.0 sup 4103

---

alpha/lib/model/DeliveryProfileAkamaiAppleHttpDirect.php
alpha/lib/model/DeliveryProfileVod.php

only relevant when the delivery profile url has a path

akamai hls direct fix for remote storage

---

plugins/drop_folder/batch/Engine/KDropFolderFileTransferEngine.php

…es from the folder (>30000) and then when we try to loop through them we create an identical array which uses up too much memory which causes a PHP Fatal and thus stops the watcher from completing it's job. In order to use less memory I added the use of references in the loop that way we don't create an identicatl array. Also if there are too many files I won't print it.

out of memory issue when trying to print all of the files to log

---

admin_console/configs/lang/sv.php
admin_console/configs/lang/sv_SE.php
var_console/configs/lang/sv.php
var_console/configs/lang/sv_SE.php

SUP-3451
Accept-Language header sent from page is set by Zend framework as not installed
Adding files to support Swedish in specific to redirect to english (as hebrew)

SUP-3451 Swedish language support required

---

plugins/metadata/lib/kMetadataManager.php

which, in PHP 5_5 and higher gives a fatal.

fix Call-time pass-by-reference has been removed

---

plugins/sphinx_search/lib/SphinxCategoryCriteria.php

SUP-4001
PartnerID was concatenated twice to the sphix search condition for the case of category _eq_display_in_search

SUP 4001 - sphinx category filter double partnerID

---

alpha/apps/kaltura/modules/extwidget/actions/playManifestAction.class.php

deleted, or just non-existing) the return value will be http status not
found (404) instead of the current 200.
The response header of (X-Kaltura-App) will be kept as usual.

Whenever the play-manifest requests for a non-existing entry (either

---

alpha/lib/model/flavorAsset.php
infra/general/kString.class.php

SUP-4491
Up until now we used to go over the file name and strip chars from a blacklist, but there are too many chars that can brake the url.
From now on we keep only chars that are in the whitelist and that we know they work.

Whitelist filename chars for flavorAsset-getUrl

---

plugins/cue_points/quiz/lib/api/KalturaAnswerCuePoint.php
plugins/cue_points/quiz/lib/api/KalturaQuestionCuePoint.php
plugins/cue_points/quiz/lib/api/KalturaQuizUserEntry.php
plugins/cue_points/quiz/lib/api/filters/base/KalturaAnswerCuePointBaseFilter.php
plugins/cue_points/quiz/lib/api/filters/base/KalturaQuestionCuePointBaseFilter.php
plugins/cue_points/quiz/lib/api/filters/base/KalturaQuizUserEntryBaseFilter.php
plugins/cue_points/quiz/lib/api/filters/orderEnums/KalturaAnswerCuePointOrderBy.php
plugins/cue_points/quiz/lib/api/filters/orderEnums/KalturaQuestionCuePointOrderBy.php
plugins/cue_points/quiz/lib/api/filters/orderEnums/KalturaQuizUserEntryOrderBy.php

Reverting some changes from "https://github.com/kaltura/server/pull/2696"
There is no need for order by on these and the client libraries are generated correctly and built fine.

Revert addition to "orderby" on Answer,Question cue points and QuizUserEntry

---

admin_console/web/js/assignDeliveryProfile.js

required in order to assign an mpegdash delivery profile to a partner

add an option of mpegdash in the admin console

---

alpha/lib/model/DeliveryProfileLiveAppleHttp.php

When checking whether content is live, ignore cases in which the
returned manifest is DVR.
#PLAT-3310 #time 0.5 day

DVR is not live

---

alpha/scripts/compatCheck.php

- use dash instead of underscore when sending headers (to support newer php/apache versions)
- use GET when issuing serve actions, since the range may not be respected in POST

compat check fixes

---

deployment/base/sql/01.kaltura_ce_tables.sql
deployment/base/sql/01.kaltura_sphinx_ce_tables.sql
deployment/base/sql/04.stored_procedures.sql

DB population parts to fail. Disable strict mode prior to deploying.
Also, set ROW_FORMAT=DYNAMIC; to avoid getting:
ERROR 1071 (42000): Specified key was too long; max key length is 767
bytes
See:
http://mechanics.flite.com/blog/2014/07/29/using-innodb-large-prefix-to-avoid-error-1071/
for more info on that.

MySQL 5.6 has strict mode enabled by default causing some of the

---

alpha/apps/kaltura/modules/extwidget/actions/serveMultiFileAction.class.php
plugins/multi_centers/batch/FileSyncImport/KAsyncFileSyncImport.class.php
plugins/multi_centers/lib/MultiCentersErrors.php
plugins/multi_centers/services/FileSyncImportBatchService.php

1. need to recreate the curl handle every cycle, since there is no way to undo the setting of CURLOPT_FILE
2. renew the file sync lock when performing resume, to support extremely large files
3. fix the comment of serveMultiFileAction

Jupiter 10.15.0 file sync import fixes2

---

alpha/apps/kaltura/lib/storage/kFileSyncUtils.class.php
alpha/apps/kaltura/modules/extwidget/actions/serveMultiFileAction.class.php

1. when a link becomes file, need to copy the originalDc and originalId in
case the file was pending
2. fixed the printing of file sync in a log line

file sync import fixes

---

api_v3/services/BatchService.php

the API response is dependent on file system status that may change

disable cache in checkFileExists

---

alpha/scripts/utils/fileSyncQueueStatus.php
plugins/multi_centers/batch/FileSyncImport/KAsyncFileSyncImport.class.php
plugins/multi_centers/services/FileSyncImportBatchService.php

- have the worker quit once an hour, in order to get config/code changes
- increase the sleep time when the worker has nothing to do
- hide log lines in fileSyncQueueStatus.php
- bug fix in the handling of createdAtLessThanOrEqual, lastId should be updated only when finding a file sync that is not old enough

file sync import touch ups

---

plugins/content_distribution/providers/tvinci/lib/model/TvinciDistributionField.php
plugins/content_distribution/providers/tvinci/lib/model/TvinciDistributionProfile.php

PLAT-3392
Distribution update is enabled for:
METADATA changes
CUSTOM_DATA changes (includes referenceID )
NAME
DESCRIPTION

PLAT-3392 support update on metada change

---

alpha/apps/kaltura/lib/storage/kFileSyncUtils.class.php
plugins/multi_centers/services/FileSyncImportBatchService.php

the initial original file sync is deleted and replaced by a link that turns into file, so the originalId be recalculated according to the file sync key

recalc the original id when a link becomes file

---

api_v3/lib/types/KalturaObject.php

prevent a crash in entry investigation page due to the deprecation of file sync jobs

fromObject: validate param is object

---

deployment/base/sql/01.kaltura_ce_tables.sql

Hostnames can be as long as 255 bytes (though most UNIX systems may limit them to 64:
see:
$ getconf HOST_NAME_MAX
Hostnames used in DNS can be as long as 253 bytes as a fully qualified
domain name (FQDN=host.example.com), in which case:
The first DNS label (removing . and anything after it from the hostname) can only be up to 63 bytes
The 253 byte limit applies to the entire FQDN, even if only the
first label is used for the Unix hostname
In short - we should enlarge to 255. 20 is hardly enough.

a hostname can consist of max of 255 chars.

---

configurations/cron/dwh.template

this adds a token for its location.

kettle.sh is no longer placed under $BASE_DIR/bin/pentaho/kitchen.sh,

---

alpha/apps/kaltura/lib/manifest/kManifestContributorConfig.php
alpha/apps/kaltura/modules/extwidget/actions/playManifestAction.class.php
plugins/content/caption/base/CaptionPlugin.php

WebVttCaptionsManifestEditor assumes M3U8 format and therefore should not be executed on any other format (e.g. redirect, json, media playlist, etc.)

need to add webvtt captions only to master m3u8

---

plugins/cue_points/quiz/QuizPlugin.php

As per @etameran 's request this parameter will be added only when the quiz is added.
When using the advanced filter KalturaQuizAdvancedFilter it will check weather dynamic_attributes.quiz_isQuiz=0 and when that parameter is missing that is true so the functionality stays the same.

Don't add isQuiz to dynamic attributes so it won't be indexed when not needed

---

configurations/apache/kaltura.ssl.conf.template

Directives AcceptMutex, LockFile, RewriteLock, SSLMutex,
SSLStaplingMutex, and WatchdogMutexPath have been replaced with a single
Mutex directive. You will need to evaluate any use of these removed
directives in your 2.2 configuration to determine if they can just be
deleted or will need to be replaced using Mutex.
http://httpd.apache.org/docs/current/mod/core.html#mutex

fixes https://github.com/kaltura/platform-install-packages/issues/436.

---

generator/sources/csharp/KalturaClient/KalturaClientBase.cs

SUP-2038
There was no handling of arrayNode of type item(array), as opposed to the PHP version of the client.
For example, the result of PlaylistService.Execute returns a list of items so the arrayNode["objectType"] is null and we get to the 'else' and return the result as string.

Add handling of arrayNode of type item(array) in DoMultiRequest

---

alpha/apps/kaltura/lib/storage/kDataCenterMgr.class.php
alpha/apps/kaltura/modules/extwidget/actions/serveMultiFileAction.class.php
alpha/apps/kaltura/modules/extwidget/actions/servefileAction.class.php

when an exception is thrown the server returns a symfony error page which
may end up in the content of the file sync

use dieError instead of throw in servefile

---

configurations/plugins.template.ini

2015-08-20 05:45:38 [KalturaPluginManager::isValid] ERR: exception
'Exception' with message 'Pending plugin name [integration] is not
available, plugin [VoicebasePlugin] could not be loaded.' in
/opt/kaltura/app/infra/log/KalturaLog.ph
when trying to generate clientlibs.

currently, one gets: 'Exception' with message 'Pending plugin name [integration] is not available, plugin [VoicebasePlugin] could not be loaded.'

---

configurations/plugins.template.ini

was overridden by https://github.com/kaltura/server/pull/3062.

redo https://github.com/kaltura/server/pull/3057 

---

alpha/apps/kaltura/lib/myFileConverter.class.php

'-noautorotate' to adjust to ffm2.7.2 that automatically normalizes rotated sources

PLAT-3935 thumb rotation

---

plugins/content_distribution/services/ContentDistributionBatchService.php

- Avoid updating the same entry more than once.
- Flush events to clear them from the memory and to make sure that
entry changes are saved to sphinx in case of crash.
- Clear memory, since every entry handled once, it's unlikely that the
same object will be needed twice.

Avoid crossing memory limit

---

alpha/apps/kaltura/lib/cache/kApiCache.php
api_v3/services/BaseEntryService.php

to prevent an attempt to play a non-ready entry from being cached for a long time, preventing playback even after it becomes ready

limit the anonymous cache of non ready entries

---

api_v3/lib/KalturaResponseCacher.php

in json the ks will not arrive as 1:ks=xxx, instead there will be an array for the each request and within it the ks

support json multirequest in apiv3 cache

---

plugins/content_distribution/lib/kContentDistributionFlowManager.php

the method can only return false/DOMNodeList, creating a situation where an update
from an empty value, or to an empty value is not recognized as an update to the metadata
by the distribution flow.

DOMXPath::query cannot return a null result

---

alpha/scripts/utils/permissions/addPermissionsAndItems.php

sample data looks like this:         
[object] => KalturaAdCuePoint
[parameter] => KalturaAdCuePoint
[action] => insert
[partnerId] => 0
[inherit] => 1
[param4] =>
[param5] =>
[tags] =>
[permissions] => cuePoint.MANAGE,
-1>PARTNER_-1_GROUP_*_PERMISSION, BASE_USER_SESSION_PERMISSION
There is no setinherit() function, so, check if the method $item,'set'.$key exists before trying to call it.

check if the method $item,'set'.$key exists before trying to call it

---

generator/sources/python/KalturaClient/tests/test_playlist.py

make sure the test category name is unique by adding timestamp.

since the CI runs this on multiple versions but on the same partner,

---

infra/media/mediaInfoParser/KAMFMediaInfoParser.php

it caused a problem on one of the QA servers running old Fedora version

don't redirect error to output on ffprobe command

---

batch/batches/Convert/Engines/KConversionEngineFfmpeg.class.php

Fix the audio source mapping, to adjust for sepating vidoe and audio sources in order to support NGS (video only) piping.
Audio source mapping changed to 1 (original 0)

Fix the audio source mapping (NGS)

---

alpha/lib/model/DeliveryProfile.php
alpha/lib/model/DeliveryProfileAkamaiHds.php
api_v3/lib/types/delivery/KalturaDeliveryProfile.php

- needed in order to add hdcore=x.x.x when playing without the player Akamai HD plugin
- the field was added on the base class to support using it in additional delivery profiles in the future

support added custom parameters on akamai hds urls

---

infra/cdl/kdl/KDLFlavor.php

In some cases the fixed frame-size flavors, failed to follow the target AR settings.

SUP-6867 - misbehavior on fixed frame-size falvors

---

alpha/lib/model/UserLoginData.php

I've modified this function to use a secure random byte source. mcrypt_create_iv() is used instead of random_bytes() so the change is compatible with PHP < 7.

Use secure random function to generate password reset tokens

---

alpha/apps/kaltura/lib/myContentStorage.class.php

increment version was only called for existing objects, but not for new objects

prevent collision in filesync versions between dcs

---

infra/storage/kFile.class.php

for example, AWS ELB returns that as 'transfer-encoding' and it causes problem when
requesting embedded player loader.

Case insensitive search for Transfer-Encoding HTTP header

---

configurations/monit/monit.d/batch.template.rc
configurations/monit/monit.d/httpd.template.rc
configurations/monit/monit.d/mariadb.template.rc
configurations/monit/monit.d/memcached.template.rc
configurations/monit/monit.d/mysqld.template.rc
configurations/monit/monit.d/nginx.template.rc
configurations/monit/monit.d/percona.template.rc
configurations/monit/monit.d/sphinx.populate.template.rc
configurations/monit/monit.d/sphinx.template.rc
configurations/monit/monit.d/wowza.template.rc

purposes.. the installation itself restarts these daemons quite a few
times for valid reasons.

if 5 restarts within 5 cycles then timeout is not good for our

---

generator/CSharpClientGenerator.php
generator/sources/csharp/KalturaClient/KalturaClientBase.cs
generator/sources/csharp/KalturaClient/KalturaFiles.cs
generator/sources/csharp/KalturaClient/KalturaParam.cs
generator/sources/csharp/KalturaClient/KalturaParams.cs
generator/sources/csharp/KalturaClient/KalturaServiceActionCall.cs
generator/sources/csharp/KalturaClientTester/KalturaClientTester.cs
generator/sources/csharp/KalturaClientTester/KalturaUploadThread.cs

Adding support for MemoryStream + example for threaded chunk upload.
Threaded chunk upload requires a small change in the backend service to allow writing a chunk after the current-end-of-file, thus this PR should not be merged before this BE change is implemented and merged.

Csharp client chunk upload enhancements

---

api_v3/lib/KalturaLiveEntryService.php

so we will be able to get it correctly later on (DC sync issue)

set version for first recorded asset of entry

---

alpha/apps/kaltura/lib/myInsertEntryHelper.class.php

but this way, at least things like:
https://github.com/kaltura/server/blob/Kajam-11.9.0/configurations/base.ini#L263
https://github.com/kaltura/server/blob/Kajam-11.9.0/configurations/base.ini#L268
https://github.com/kaltura/server/blob/Kajam-11.9.0/configurations/base.ini#L285
https://github.com/kaltura/server/blob/Kajam-11.9.0/configurations/base.ini#L244
will not suddenly become jpg.

To be honest, I'm not sure why we even care what the file ext is... 

---

alpha/apps/kaltura/lib/myEntryUtils.class.php

if the requested version is 100000 and it's not found.
this is in order to support clients who blindly create thumbnail urls with /version/100000

fall back to the current version of the thumbnail

---

api_v3/services/UserService.php

PLAT-4655
When adding a user we are not validating the input for insert and we then
insert the data to the object causing exceptions in the log
trying to insert a read only member.
Adding the input validation prior to the user object creation
will cause the add user to fail since we are
trying to set a read only member.
@MosheMaorKaltura please review it.

input validation when add a user

---

generator/sources/java/src/main/java/com/kaltura/client/KalturaClientBase.java

Fixes #3937: Malformed UTF-8 decoding in response data in non-utf8 platforms.

Java API: Malformed UTF-8 decoding in response data

---

api_v3/services/LiveStreamService.php

Patch for authenticate error while performing an immediate stop/start. Checkup for duplicate streams moved to 
media-server for the moment.
A permanent fix will follow.

Authenticate temporary fix for live

---

infra/log/KalturaLog.php

backtrace is only used to get the calling function name, no need for the args / objects

reduce logger memory usage

---

tests/standAloneClient/bpmNotificationsTemplates.xml

'mainObjectCode' is not needed, the internal integration job added by this BPM flow already uses entry object

Removed mainObjectCode from BPM Notification Template

---

alpha/lib/model/category.php

avoid counting the partner categories when the partner already has the feature DYNAMIC_FLAG_KMC_CHUNKED_CATEGORY_LOAD.

optimize category add

---

batch/batches/Convert/Engines/KConversionEngineFfmpeg.class.php

Limit 'old' h265/vp9 flow to engine 98 (experimental), in order to provide graceful switch for the users that currently run the 'old' flow.

PLAT-6650 New X265/HEVC support

---

alpha/lib/model/conversionProfile2.php

Define which tags represent flavors ‘grouping’ (aka ‘mbr’,’ism’).
‘Collection-tag’ causes activation of ‘optimization’ heuristics.
It can be used to define playback sets as well.

Collection’/’grouping/multi-flavor tagging support

---

api_v3/lib/types/conversionProfile/KalturaConversionProfile.php

Define which tags represent flavors ‘grouping’ (aka ‘mbr’,’ism’).
‘Collection-tag’ causes activation of ‘optimization’ heuristics.
It can be used to define playback sets as well.

‘Collection’/’grouping/multi-flavor tagging supp.

---

alpha/apps/kaltura/modules/extwidget/actions/serveFlavorAction.class.php

when one of the entries has no flavors, the durations array is unset, this makes php render it as an object in the json (e.g. {"0":64000,"1":30084,"3":50109} instead of [64000,30084,50109])

serve playlist bug fix

---

api_v3/lib/KalturaResponseCacher.php

Without it, https://developer.kaltura.com/console/#/session.start will
fail with "No 'Access-Control-Allow-Origin' header is present on the
requested resource. Origin 'https://developer.kaltura.com' is
therefore not allowed access"

set Access-Control-Allow-Origin header to '*' in handleSessionStart()

---

alpha/apps/kaltura/lib/cache/kApiCache.php

this->_responseMetadata should always be unserialized, need to serialize
it right before saving to memcache. In the previous implementation, after
storeCache it was serialized. In cases where a cache was extended (e.g.
from central cache to local cache) it doesn't go through storeCache and
therefore the unserialized array was saved without serialization.

api cache bug fix

---

batch/batches/Convert/Engines/KConversionEngineFfmpeg.class.php
infra/chunkedEncode/KChunkedEncodeSessionManager.php

Using it wll trigger a fatal error.

As of PHP 5.4.0, call-time pass-by-reference was removed

---

batch/batches/Convert/Engines/KConversionEngineFfmpeg.class.php

Otherwise,  using it will trigger a fatal error.

As of PHP 5.4.0, removed call-time pass-by-refer

---

alpha/apps/kaltura/lib/kManifestRenderers.php
plugins/content/caption/base/lib/kWebVTTGenerator.php

- don't return EXT-X-VERSION in master m3u8 (makes some devices fail playback)
- don't return X-TIMESTAMP-MAP when possible (can cause out-of-sync in roku)
- return the correct duration of the last webvtt segment

hls compatibility features

---

vendor/symfony/controller/sfRouting.class.php

In PHP 5.4 and above, the current code will fail with:
[Wed Jun 07 13:47:10.719555 2017] [:error] [pid 21226] [client
10.0.63.53:34243] PHP Warning:  preg_replace(): The /e modifier is no
longer supported, use preg_replace_callback instead in
/opt/kaltura/app/vendor/symfony/controller/sfRouting.class.php on line
460, referer: http://ce-ubuntu0.dev.kaltura.com/start/index.php

preg_replace(): The /e modifier is no longer supported

---

configurations/apache/conf.d/apps.conf.template

[Wed Jun 07 13:12:15.676303 2017] [authz_core:error] [pid 26155] [client
10.0.63.53:33634] AH01630: client denied by server configuration:
/opt/kaltura/app/kmc, referer:
http://ce-ubuntu0.dev.kaltura.com/index.php/kmc/kmc4
Since /opt/kaltura/app/kmc does not exist.

The /kmc alias is not only unnecessary but also triggers errors

---

alpha/apps/kaltura/lib/reports/myReportsMgr.class.php

- If mysqli_connect() failed, throw an exception, no point in returning $link
- If mysqli_select_db() failed, throw with a coherent message

Coherent exception message if the kalturadw DB cannot be reached

---

configurations/apache/conf.d/apps.conf.template

In Apache >= 2.4, this will result in a fatal error:
AH00526: Syntax error on line 41 of
/etc/apache2/sites-enabled/apps.conf:
Either all Options must start with + or -, or no Option may.
Also, you do not need ExecCGI for KEA [or anything else here for that
matter].

Broken Apache config

---

alpha/apps/kaltura/modules/extwidget/actions/serveFlavorAction.class.php

Addition to https://github.com/kaltura/server/pull/5863
Deleted flavors should return an error, without empty nginx-vod response. Otherwise, packager will try to call serveFlavor on second DC, which is not needed in this case.

SUPPS-1191 - Serve Flavor DC Redirect Fix

---

deployment/base/sql/01.kaltura_sphinx_ce_tables.sql

sphinx_log.type was was added to updates here deployment/updates/sql/2017_05_15_add_type_column_sphinx_log.sql on
2017_05_15 but was not added to the schema creation.
Currently this breaks the upload process, resulting in:
[BasePeer::doInsert] ERR: Exception: SQLSTATE[42S22]: Column not found:
1054 Unknown column 'TYPE' in 'field list' in
/opt/kaltura/app/infra/log/KalturaLog.php:83

sphinx_log.type is missing from the schema creation

---

alpha/apps/kaltura/lib/KDLWrap.php

Checking that cdlMediaInfo isnt null when trying to get streams

origin/Mercury-13.2.0-PLAT-7971 - Clip of entry not in ready state fails

---

plugins/bulk_upload/xml/batch/BulkUploadEngineXml.php

Declaration of BulkUploadEngineXml::updateObjectsResults() should be compatible with
KBulkUploadEngine::updateObjectsResults(array $requestResults, array
$bulkUploadResults)

PHP Strict Standards

---

alpha/apps/kaltura/modules/extservices/actions/googleoauth2Action.class.php

google_client sets the timezone to UTC, restoring it before calling
partner->save

googleoauth action fix save timezone

---

infra/general/PdfGenerator.php
vendor/fpdf/fpdf.php

Methods with the same name as their class will not be constructors in a future version of PHP

KMS15412: fix FPDF constructors for php7 support

---

alpha/apps/kaltura/lib/reports/kKavaReportsMgr.class.php

1. more accurate totalCount for small sets - add min threshold + compare row count to threshold (not page size * index)
2. improved time zone calculation - use a static list of non-round time zones + round everything else to nearest hour (dont use timezone_name_from_abbr at all)
3. use doSelectStmt instead of doSelect to reduce memory usage
4. truncate the page size to the limit instead of failing the request

kava compat check fixes

---

alpha/apps/kaltura/lib/reports/kKavaReportsMgr.class.php

- use the first dim instead of null for enriched dims, report type 12 has the entry name as first dimension, without entry id
- use the first dim when the dimensions arrays is exhausted - required for report type 6, which has object_id and domain_name as dimensions (both should get the domain name)

fix bugs introduced by custom reports changes

---

alpha/apps/kaltura/modules/extwidget/actions/embedPlaykitJsAction.class.php

Tidy up the kaltura player configuration:
- set a namespace under window object `window. __kalturaplayerdata`
- fix uiconf object to get a proper uiconf key and simplify object nesting from
```javascript
UIConf[1234] = {config: {...}}
```
to 
```javascript
UIConf[1234] = {...}
```
I think 13.8.0 is already on freeze, but opening this already to get review

fix playkit config namespace and setup

---

alpha/apps/kaltura/lib/reports/kKavaLiveReportsMgr.class.php

- support passing a limit (for csv)
- use granularity period for entry geo timeline (clip from may be different than clip to in case of csv)
- add type = LIVE to the query that orders by name - some events arrive with vod entryId, this filters them out

kava live fixes

---

api_v3/lib/types/liveReports/WSLiveReportsClient.class.php
api_v3/services/LiveReportsService.php
batch/batches/LiveReportExport/Engines/LiveReportLocationEngine.php

avoid using a pager
- increase request limit to 10k
- use smaller chunks (5 min)
- disable nu soap debug (to reduce mem usage)
- increase memory limit

live reports csv - support kava

---

deployment/base/scripts/init_data/07.DeliveryProfileAkamaiAppleHttpDirect.template.ini
deployment/base/scripts/init_data/07.DeliveryProfileAkamaiHttp.template.ini
deployment/base/scripts/init_data/07.DeliveryProfileLivePackagerDash.template.ini
deployment/base/scripts/init_data/07.DeliveryProfileLivePackagerHds.template.ini
deployment/base/scripts/init_data/07.DeliveryProfileLivePackagerHls.template.ini
deployment/base/scripts/init_data/07.DeliveryProfileLivePackagerMss.template.ini
deployment/base/scripts/init_data/07.DeliveryProfileVodPackagerDash.template.ini
deployment/base/scripts/init_data/07.DeliveryProfileVodPackagerHds.template.ini
deployment/base/scripts/init_data/07.DeliveryProfileVodPackagerHls.template.ini

It is overridden anyhow as the protocol is dynamically determined based
on what was passed to playManifest. So this is just confusing...

Remove protocol from DeliveryProfile url

---

api_v3/web/analyticsSyncServe.php

take only category entries with active status when calculating the categories of an entry (instead of <> deleted)

analtyics sync - category entry status

---

plugins/content/caption/search/lib/kCaptionSearchFlowManager.php

objectDeleted has to return true, otherwise the events manager considers the event as paused, and does not relay it to subsequent consumers

fix deletion of caption file syncs

---

alpha/apps/kaltura/modules/extwidget/actions/embedPlaykitJsAction.class.php

throw error if bundleConfig does not exist

---

alpha/apps/kaltura/lib/reports/kKavaReportsMgr.class.php

use the first metric instead of throwing an exception

kava - ignore bad getTable order by

---

alpha/apps/kaltura/lib/reports/kKavaReportsMgr.class.php

some user reports have self::METRIC_TOTAL_ENTRIES as first dimension, this value is not displayed in KMC which makes the table look bad

kava - use play as default order

---

alpha/scripts/utils/verifyObjectDeletion.php

runs periodically and ensures all the assets of a deleted entry are deleted + all file syncs of deleted assets are deleted.
this is required in order to simplify analytics storage calculation.

add delete verification script

---

alpha/apps/kaltura/lib/reports/kKavaLiveReportsMgr.class.php
alpha/scripts/utils/loadGeoCoordinates.php
api_v3/services/LiveReportsService.php

city+country is not unique enough in order to find geo coordinates.
there can be several cities with the same name in the same country.
need to use the region as well.

kava live - city coordinates fix (SUP-13330)

---

alpha/apps/kaltura/lib/kUploadTokenMgr.php

1. in case of chunked upload, a row is added per chunk
2. since the rows dont have entry_id they wont be shown in the admin console anyway.

remove upload track entry

---

alpha/apps/kaltura/lib/reports/kKavaReportsMgr.class.php

when the report is grouping by more than one dim (e.g. entryId + userId) the enriched dimension may have duplicate values. this can't happen for single dimension reports, so no need to perform array_unique for those

kava enrichment optimization

---

api_v3/services/ReportService.php

also fixed - when sending invalid partner id to partner usage/var usage reports, it returned the usage of all partners

temporarily revert kava contrib reports

---

alpha/lib/model/DeliveryProfile.php

When more than one KES is assigned as primary, you will always get only the first one. This allows to randomize the $deliveryNodes array and eventually get different KES.
In some cases, you want to have more than one KES assigned and you usually need to use the same playback domain for all of them and then create a DNS round robin for it. This change, although its not round robin, will allow some balancing between nodes.
Thanks,

Shuffle the $deliveryNodes array to randomize the assigned KES

---

alpha/apps/kaltura/modules/extwidget/actions/embedPlaykitJsAction.class.php

set `playerConfig` as empty object is it doesn't exist

fix PHP Strict Standards

---

api_v3/services/UiConfService.php

When no KS is passed, INVALID_UI_CONF_ID will be thrown.

uiconf->get() requires a KS

---

alpha/apps/kaltura/lib/myPartnerRegistration.class.php
alpha/apps/kaltura/lib/myPartnerUtils.class.php
alpha/apps/kaltura/lib/request/kSessionBase.class.php
alpha/apps/kaltura/modules/system/actions/helperAction.class.php
alpha/lib/model/UserLoginData.php
configurations/base.ini
infra/general/KCryptoWrapper.class.php
plugins/admin_console/kaltura_internal_tools/admin/KalturaInternalToolsSystemHelperAction.php
plugins/drm/providers/playready/admin/forms/scripts/play-ready-provider-configure-action.phtml
plugins/event_notification/providers/push/lib/model/registerNotificationPostProcessor.php

This is the server side follow up of https://github.com/kaltura/clients-generator/pull/278
Starting from PHP 7.1, the Mcrypt extension is deprecated.
There is a good underlying reason for that, to wit: libmcrypt's last update was back in 2007. This is bad for any piece of code but especially troubling for security sensitive ones.
The pulls above will ensure compatibility with KS strings generated using Mcrypt because we set the OPENSSL_ZERO_PADDING bit and do our own padding thus making it compatible with mcrypt's PKCS#5 padding, as opposed to OpenSSL's default which is PKCS#7.
More info about this can be found here:
http://thefsb.tumblr.com/post/110749271235/using-opensslendecrypt-in-php-instead-of
and in particular under the "Encoding, padding and OPENSSL_RAW_DATA vs. …

Use OpenSSL functions if mcrypt is not available

---

infra/cdl/kdl/KDLFlavor.php
infra/cdl/kdl/KDLMediaDataSet.php
infra/cdl/kdl/KDLProcessor.php

See http://php.net/manual/en/function.unset.php:
However, before PHP 7, this did not trigger a FATAL error, now it does:
> PHP Fatal error:  Cannot unset $this

It is not possible to unset $this inside an object method since PHP 5.

---

api_v3/lib/KalturaFrontController.php

when the request is sent using json, $_REQUEST does not return the request params, need to use $params instead

fix analytics log clientTag for json requests

---

infra/log/KalturaLog.php

1. simplifies parsing code
2. some fields that are not quoted can theoretically get commas

analytics log - strip commas from the values

---

alpha/lib/model/DeliveryProfilePeer.php

Fix issue - when access control profile specifies Delivery Profile which is not associated with the partner (even if it's a global profile, or belongs to the partner), Delivery Profile lookup will fail.

PSVAMB-2895

---

alpha/apps/kaltura/lib/kManifestRenderers.php
plugins/content/caption/base/CaptionPlugin.php

- use delivery profile hostname in case of VOD_PACKAGER_HLS or VOD_PACKAGER_HLS_MANIFEST and no remote storage
- replace delivery code after manifest contributors

PLAT-8827: change serveWebVTT to use delivery profile hostname

---

alpha/apps/kaltura/modules/kmc/actions/kmc4Action.class.php

e.g 
`kmc.vars.studioV3.playerVersionsMap` is
```
"{
"kaltura-ovp-player": "0.27.0",
"kaltura-tv-player": "0.27.0",
"playkit-ima": "0.6.0",
"playkit-youbora": "0.4.0",
"playkit-comscore": "1.0.1",
"playkit-google-analytics": "0.1.1",
"playkit-offline-manager":"1.0.2"
}"
```

add the player v3 versions map to studioV3 config

---

api_v3/lib/types/resource/KalturaStringResource.php
plugins/content/attachment/services/AttachmentAssetService.php

Fix issue - When an attachment asset's content is updated from a KalturaStringResource, the asset's file extension disappears.

PSVAMB-3216

---

alpha/apps/kaltura/lib/s3/S3.php
infra/general/KCurlWrapper.class.php
infra/general/S3.php

As documented here http://php.net/manual/en/function.curl-setopt.php:
1 used to mean check the existence of a common name in the SSL peer certificate.
2 will check the existence of a common name and also verify that it matches
the hostname provided. 0 will not check the names.
Support for value 1 was removed in cURL 7.28.1.
That means that all machines that have libcurl of version 7.28.1 or
higher will effectively behave as if this value was set to 2.
7.28.1 is very old and no current Linux distro version includes it.
Just by way of reference, RHEL/CentOS 7 has 7.29.0, Ubuntu 14.04 has
7.35.0 and Ubuntu 16.04 has 7.47.0.

CURLOPT_SSL_VERIFYHOST no longer accepts the value 1

---

alpha/apps/kaltura/modules/kmcng/actions/kmcngAction.class.php

Per @itaykinnrot request this PR remove studio v3 from kmcng beta version. It will be re-added for the GA version which include additional required data.

remove studio v3 from kmc beta

---

alpha/scripts/utils/verifyObjectDeletion.php

can hang if too many entries are deleted at the same time

verifyObjectDeletion - increase chunk size

---

alpha/apps/kaltura/lib/kAuthDataCache.php

Const Scalar Expressions only work from php 5.6

Naos-14.1.0-PLAT-8940-Facebook const fix

---

release-notes.md

I rewrite history so people who wants to install kmc-ng will be able to follow the instructions provided as part of the first kmcng deployment

add instructions to add kmc-ng to kaltura server

---

alpha/apps/kaltura/lib/reports/kKavaReportsMgr.class.php

1. cast the timezone offset to int - this prevents the selection of weird timezone (+14) in custom reports that don't have a timezone set (max(null, -14 * 60) evaluates to -14 * 60)
2. added additional validation on date id - fail dates like 20181301 (13 is invalid for month...)
3. when running 2 topN queries in getTable, leave all filters in the second topN - an entry can move between categories, removing the categories filter from the second topN can lead to wrong results.

kava fixes

---

api_v3/web/index.php

See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Max-Age.
This change should reduce the number of preflight `OPTIONS` requests to the server significantly, especially with a client-side application, e.g., KMC.

add Access-Control-Max-Age header to API calls

---

alpha/apps/kaltura/lib/reports/kKavaLiveReportsMgr.class.php
api_v3/services/LiveReportsService.php

return only the fields needed by the application, specifically peakAudience / peakDvrAudience require an additional query to calc, which can be skipped

kava live - optimization for KWP queries

---

api_v3/web/analyticsSyncServe.php

kava sync - increase group_concat_max_len

---

alpha/lib/data/live/kLiveStreamConfiguration.php

…void PHP Warning when calling count on it

PHP7: Make sure getStreamInfo will always return an array object to avoid PHP Warning when calling count on it

---

alpha/apps/kaltura/lib/myEntryUtils.class.php
alpha/apps/kaltura/lib/myPlaylistUtils.class.php
configurations/local.template.ini

PLAT-9262 handle thumb and volume mapped with encryption at rest

---

tests/standAloneClient/uniqueMediaspaceNotificationsTemplates.xml

Requirements are here: https://kaltura.atlassian.net/browse/PSVAMB-4593
Tech design doc is attached to the Jira ticket as well.
Implementation is to deploy new email notifications: similar to what KMS has now, but with additional conditions.
The first commit contains an exact copy of existing KMS notifications (I took the actual content from prod). So if you want to see only the changes to the old notification templates instead of full notification template contents, you can find them in the second commit.
Dev notes:
- Entry_Ready notification is being triggered out of partner context (from a batch job), so KalturaMatchMetadataCondition won't work there. That's why I used php code snippet to fetch the metadata in this event
- Comment_Was_Added_To_Entry notification trigger has been …

PSVAMB-4593 Email notifications per KMS

---

api_v3/services/ReportService.php

match the implementation of KalturaReportTable::fromReportTable, a dimension such as country/city may have commas that break the csv format

kava - strip commas from custom report values

---

batch/batches/Convert/KChunkedEncodeJobScheduler.class.php

uses 'taskConfig->params->chunkedEncodeMemcacheToken'  to differentiate between multiple KChunkedEncodeJobScheduler instances on the same server via separate 'chunked_encode_scheduler_TOKEN.pid' files

No-Plat-allows-several-chunk-schedulers-per-server

---

plugins/reach/admin/PartnerCatalogItemsCloneAction.php
plugins/reach/admin/ReachProfileCloneAction.php
plugins/reach/batch/kReachFlowManager.php
plugins/reach/lib/model/PartnerCatalogItemPeer.php

REACH-Cloning reach profile and partner catalog items

---

alpha/apps/kaltura/lib/kManifestRenderers.php

some apps are not base64-encoding the referrer, detect it by -
1. running base64_decode in strict mode
2. checking whether the result is valid utf8
when this happens, send the referrer as is on the beacon (without b64decode)

playManifest beacon non-base64 encoded referrers

---

configurations/batch/batch.ini.template

- Added KAsyncEntryVendorTasksCsv and KSyncReachCreditTaskRunner `enabledWorkers` directives [set to 0 by default]
- Adjusted value for KSyncReachCreditTaskRunner.sleepBetweenStopStart

REACH2 CHANGES

---

configurations/apache/conf.d/apps.conf.template

From now on, we will deploy html5lib onto /opt/kaltura/apps rather than to NFS for better performance.
This also fixes https://github.com/kaltura/server/pull/7343

Apache config changes

---

alpha/apps/kaltura/modules/extwidget/actions/serveFlavorAction.class.php

by default json_encode uses \u for non-ascii chars, this can result in invalid labels since the packager doesn't decode \u

serveFlavor use JSON_UNESCAPED_UNICODE

---

infra/cdl/kdl/KDLOperatorFfmpeg2_1_3.php

FFmpeg 4.0.2 failed on  audio channel filter desc, that worked for prev versions

SUP-16865-HF-to-support-FFM4-audio-syntax-change

---

infra/media/mediaInfoParser/KBaseMediaParser.php
infra/media/mediaInfoParser/KFFMpegMediaParser.php
infra/media/mediaInfoParser/KMediaInfoMediaParser.php

Do 'file_exist' check only for MediaInfo and FFMpeg with file path.
Avoid the check for FFmpeg with url

Naos 14.13.0 remote media data

---

plugins/search/providers/elastic_search/lib/elasticSearchUtils.php
plugins/search/providers/elastic_search/lib/model/items/ESearchEntryItem.php
plugins/search/providers/elastic_search/lib/model/items/ESearchItem.php
plugins/search/providers/elastic_search/lib/model/search/kESearchQueryManager.php

- query on boolean fields in elastic 6.x+ with values other then true/false is deprecated

eSearch - query boolean fields only with true/false

---

alpha/apps/kaltura/lib/reports/kKavaReportsMgr.class.php

do not assume the first dimension split has all headers - merge the headers of all splits

kava - table from keyed graphs fix

---

configurations/plugins.template.ini

install so no reason why it should be disabled by default.

Elasticsearch is included in CE/OP and deployed as part of the base..

---

plugins/event_notification/providers/email/lib/batch/recipients/KEMailNotificationGroupRecipientEngine.php

When running the `getGroupUserIds()` code with PHP 5.3, which is what's running on SaaS' batch servers, this code will NOT insert a comma [','] between the last two email addresses. In PHP 7, it will.
That means the last two email addrs will be concatenated like so:
`address@example.comaddress1@example.com`
rather than:
`address@example.com,address1@example.com`
This will result in a failure to notify the last two recipients as their addrs will be concatenated into one which will naturally be an invalid email addr.
The revised code will work equally well with both versions.

Incorrect concat() when running with PHP 5.3

---

plugins/event_notification/providers/email/lib/batch/recipients/KEMailNotificationGroupRecipientEngine.php

When running the `getGroupUserIds()` code with PHP 5.3, which is what's running on SaaS' batch servers, this code will NOT insert a comma [','] between the last two email addresses. In PHP 7, it will.
That means the last two email addrs will be concatenated like so:
`address@example.comaddress1@example.com`
rather than:
`address@example.com,address1@example.com`
This will result in a failure to notify the last two recipients as their addrs will be concatenated into one which will naturally be an invalid email addr.
The revised code will work equally well with both versions.

Incorrect concatenation when running with PHP 5.3

---

infra/media/mediaInfoParser/KFFMpegMediaParser.php

For audio-only MP3's/M4A's - prevent detecting of cover JPG/PNG as a video stream

SUP-18051-Audio-only-with-Cover-image

---

deployment/updates/scripts/2019_05_26_httpEntryVendorTaskDone.php
deployment/updates/scripts/xml/notifications/2019_05_26_httpEntryVendorTaskDone.template.xml
plugins/event_notification/providers/http/admin/scripts/js/kObjects.js
release-notes.md

- add "Entry Vendor Task Finished" HTTP notification (similar to the existing email notification: https://github.com/kaltura/server/blob/Orion-15.1.0/deployment/updates/scripts/xml/notifications/2018_02_22_entry_vendor_task_done.template.xml)
- add an option to choose entry vendor task as an option for HTTP notification

PSVAMB-7641 Entry Vendor Task Finished HTTP notification

---

alpha/apps/kaltura/modules/extwidget/templates/previewSuccess.php

Added a way to pass KS on the preview template.
Checked with QA servers:
`https://qa-apache-php7.dev.kaltura.com/index.php/extwidget/preview/partner_id/6502/uiconf_id/15222758/entry_id/0_4x8h8feu/embed/dynamic?flashvars[ks]=`

feat(FEC-9147): pass KS to server preview template

---

api_v3/lib/KalturaBaseUserService.php

Added null arguments when calling "parent::updateLoginDataImpl" from "AdminUserService->updatePasswordAction" as PHP7 will not tolerate call a function with less arguments then expected

SUP-17322: Added null arguments when calling 'parent::updateLoginDataImpl'

---

alpha/scripts/utils/configPartnerAuditTrail.php

@MosheMaorKaltura this is a fix for the default template script for audit trail configuration creation. The previous form of this script was impossible to execute due to autoload errors resulting from referencing API classes within alpha script context. Please review.

script fixed to prevent autoload issues

---

api_v3/services/PartnerService.php

At the moment, attempting to call this function when OTP was enabled on the partner will fail.

partner->getSecrets() should accept the optional $otp and pass it on to userLoginByEmail()

---

deployment/base/scripts/init_data/01.Partner.template.ini

- quotes aren't needed and there was only a closing '"' char, which caused a parsing error
- token was missing the ending '@' char.

Parse errors

---

plugins/bulk_upload/csv/batch/BulkUploadEngineCsv.php

Thus, on certain machines, if such trailing Unicode characters exist, a complete failure will occur as described in https://kaltura.atlassian.net/browse/PLAT-10100
This change fixes it. Verified on qa-apache-php7 where, before the
change, I was able to reproduce it.

PLAT-10100: The trim() function is not, by default, unicode safe.

---

deployment/base/scripts/createQueryCacheTriggers.php

make it easier to control the function that is used to set memcache values.

query cache triggers - add set func variable

---

deployment/base/scripts/init_data/06.FileSync.template.ini

Origin: https://github.com/kaltura/platform-install-packages/blob/Orion-15.10.0/RPM/SOURCES/entry_and_uiconf_templates.tar.gz

Update thumbnail locations and file sizes to fit origin.

---

plugins/bulk_upload/drop_folder_xml/plugins/providers/ap_feed/batch/KApFeedDropFolderEngine.php
plugins/bulk_upload/drop_folder_xml/plugins/providers/ap_feed/lib/api/KalturaApFeedDropFolder.php
plugins/bulk_upload/drop_folder_xml/plugins/providers/ap_feed/lib/model/ApFeedDropFolder.php

PSVAMB-6815

---

configurations/apache/conf.d/enabled.kaltura.conf.template
configurations/php/kaltura-fpm.template.ini

With FPM, `php_flag` cannot work so check whether the PHP 5 or PHP 7 modules are enabled (logical or is not supported with `ifModule` so you need two blocks) and only set it if so.

Support working with PHP FPM (the default PHP SAPI with RHEL/CentOS 8)

---

plugins/reach/lib/model/data/kVendorCredit.php

@MosheMaorKaltura  , @erankor  , @yossipapi  I've added the modifications Eran suggested and also tested it. It works the same way as before (without returning matrix, returning regular array)
dev@pa-front-stg1 ~$ genks 2368011 | kalcli -i reach_entryvendortask add entryVendorTask:objectType=KalturaEntryVendorTask entryVendorTask:entryId=1_f7jhkkyf entryVendorTask:catalogItemId=852 entryVendorTask:reachProfileId=1981
HTTP/1.1 200 OK
Date: Fri, 22 Nov 2019 16:50:55 GMT
X-Me: pa-front-stg1
X-Kaltura-Session: 690891171
Array
(
[0] =>
)

SUP-20245: fetch SUM(price) + price <> 0 to avoid reaching PHP memory_limit due to too many results + method improvements

---

api_v3/lib/types/partner/KalturaPartner.php

PLAT-10466 - handle invalid chars for partner describeYourself field

---

plugins/schedule/bulk_upload/batch/BulkUploadScheduleEventCsvEngine.php

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9164)

CSV Bulk Event Scheduling - Add option to specify resource by ID

---

alpha/apps/kaltura/lib/cache/kCacheManager.php
alpha/apps/kaltura/modules/extwidget/actions/embedPlaykitJsAction.class.php

* Get the `i18n` from the bundle builder (https://github.com/kaltura/playkit-js-bundle-builder/pull/8)
* push to the mem-cache 
* consider nested confvars (see https://github.com/kaltura/player-studio/pull/78) like:
```
{
"versions": {
"kaltura-ovp-player": "0.50.9",
"playkit-vr": "1.1.0"
},
"langs": ["fn", "he" ]
}
```
* filter the languages by this order:
- new comma separator url param (langs) 
- confvars.langs 
- 'en' by default.
* merge with the uiConf's translations and push to `__kalturaplayerdata`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9123)

feat(FEC-9465): Internationalization (i18n) - player localization

---

plugins/search/providers/elastic_search/lib/model/filters/ESearchEntryQueryFromFilter.php
plugins/search/providers/elastic_search/lib/model/filters/ESearchQueryFromFilter.php

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9195)

PLAT-10697:fixing categories fields search when converting KalturaMediaEntryFilter to esearch

---

plugins/search/providers/elastic_search/lib/model/filters/ESearchQueryFromAdvancedSearch.php

to the query eSearch adapter
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9197)

Orion-15.18.0-PLAT-10706-Add support for isQuiz filter

---

configurations/batch/batch.ini.template
plugins/content/document/DocumentPlugin.php
plugins/content/document/lib/operation_engines/KOperationEnginePdfCreator.php
plugins/content/document/lib/operation_engines/KOperationEnginePdfCreatorLinux.php
release-notes.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9194)

PLAT-10694: Add linux batch for doc conversion

---

alpha/apps/kaltura/lib/db/DbManager.php
release-notes.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9201)

PLAT-10713: Support sphinx sticky session during read operations as well

---

plugins/reach/lib/kReachManager.php

Reverts kaltura/server#9225
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9235)

Revert "REACH-727 - make sure only parent entry caption task is created"

---

alpha/apps/kaltura/lib/myEntryUtils.class.php

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9237)

N-Plat: when building curr thumb path use the original thumbName with out the uniqid

---

alpha/lib/model/AppToken.php
api_v3/lib/types/KalturaAppToken.php

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9254)

SUP-21037: update kuser_id column to match 'sessionUserId' = puser_id + generate user on the fly if not exist

---

api_v3/services/SessionService.php

The start widget session generates ks that doesn't work with playlist execute
Changing it to generate either ks with PRIVILEGE_DISABLE_ENTITLEMENT_FOR_ENTRY  or with PRIVILEGE_DISABLE_ENTITLEMENT_FOR_PLAYLIST but not both
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9311)

Propus-16.0.0-SUP-21515-start widget session

---

plugins/vendor/zoom/lib/model/kZoomEventHanlder.php

Hi @MosheMaorKaltura @ZurKaltura 
@MosheMaorKaltura should I test the code in the All-In-One?
I thought that before removing the events from:
plugins/vendor/zoom/lib/model/kZoomEventHanlder.php
plugins/vendor/zoom/lib/model/data/kZoomEvent.php
plugins/vendor/zoom/lib/model/enums/kEventType.php
Just stop processing the event - I know it makes an obsolete code, we can remove it after confirming we haven't ruined anything.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9353)

SUP-21801: stop processing old zoom event types

---

alpha/apps/kaltura/lib/kParentChildEntryUtils.php

The bug was introduced here:
https://kaltura.atlassian.net/browse/REACH2-727
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9366)

SUP-21560: fix captionAsset list where the entry's 'parentEntryId' is empty string

---

infra/chunkedEncode/KChunkedEncodeMemcacheWrap.php

To ease race condition over the locking of the fetch/read idx, when large number of srvs attempt to fetch the same job. 
This situation occurred in AWS env, with high connect/'walk around' times to DC memcache srv
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9368)

Fix FetchNextJob inter srvs race condition

---

alpha/lib/model/DeliveryProfileLive.php
alpha/lib/model/DeliveryProfileLiveAppleHttp.php
alpha/lib/model/DeliveryProfileLiveDash.php
alpha/lib/model/DeliveryProfileLiveHds.php
alpha/lib/model/DeliveryProfileLivePackagerDash.php
alpha/lib/model/DeliveryProfileLivePackagerHds.php
alpha/lib/model/DeliveryProfileLivePackagerHls.php
alpha/lib/model/DeliveryProfileLivePackagerMss.php
alpha/lib/model/MediaServerNode.php
plugins/media/live_cluster/lib/model/LiveClusterMediaServerNode.php

- add entry server node id to the m3u8 url in case of MediaServerNode of type LiveCluster.
- change getHttpUrl function in DeliveryProfileLive.php to receive entryServerNode instead of serverNode
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9380)

PLAT-10838: add entry server node id to the m3u8 url as sessionId

---

alpha/apps/kaltura/lib/kUploadTokenMgr.php

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9399)

Fix for cases where the uploaded chunk partially overrides content that was already concatenated to the output file

---

alpha/apps/kaltura/lib/request/kNetworkUtils.php
alpha/apps/kaltura/modules/extwidget/actions/serveFlavorAction.class.php
configurations/local.template.ini
release-notes.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9413)

PLAT-10806 authenticate uri

---

plugins/bulk_upload/csv/batch/BulkUploadVendorCatalogItemEngineCsv.php
plugins/reach/ReachPlugin.php
plugins/reach/admin/CatalogItemImportAction.php
plugins/reach/admin/forms/CatalogItemFilter.php
plugins/reach/admin/scripts/plugin/catalog-item-import-action.phtml
plugins/reach/admin/scripts/plugin/catalog-item-list-action.phtml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9424)

REACH2-857:Import catalog item csv from admin console

---

batch/batches/Storage/Periodic/KAsyncStoragePeriodicPurge.class.php
plugins/file_sync/services/FileSyncService.php
release-notes.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9437)

PLAT-10769: save the last updatedAt

---

alpha/apps/kaltura/modules/kmcng/actions/kmcngAction.class.php
release-notes.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9470)

PLAT-10934: Add V7 player UIConf to KMC wrapper

---

deployment/updates/scripts/2020_06_14_deploy_caption_asset_boolean_notification.php
deployment/updates/scripts/xml/2020_06_14_captionAssetBooleanEventNotification.template.xml
plugins/reach/lib/kReachManager.php
plugins/reach/lib/model/PartnerCatalogItemPeer.php
release-notes.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9486)

REACH2-849:adding automatic rule when caption asset is ready

---

alpha/apps/kaltura/lib/monitor/KalturaMonitorClient.php
alpha/apps/kaltura/lib/request/infraRequestUtils.class.php
alpha/apps/kaltura/lib/request/kIpAddressUtils.php

PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in /opt/kaltura/app/alpha/apps/kaltura/lib/request/infraRequestUtils.class.php on line 70
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /opt/kaltura/app/alpha/apps/kaltura/lib/request/kIpAddressUtils.php on line 198
PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in /opt/kaltura/app/alpha/apps/kaltura/lib/monitor/KalturaMonitorClient.php on line 402
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9496)

Fixes the below PHP errors

---

alpha/apps/kaltura/lib/media/myFlvHandler.class.php
alpha/apps/kaltura/lib/monitor/KalturaMonitorClient.php
alpha/apps/kaltura/lib/request/infraRequestUtils.class.php
alpha/apps/kaltura/lib/request/kIpAddressUtils.php
infra/cdl/kdl/KDLFlavor.php
infra/cdl/kdl/KDLOperatorBase.php
infra/media/mediaInfoParser/KFFMpegMediaParser.php
plugins/content_distribution/lib/kContentDistributionFlowManager.php
plugins/search/providers/elastic_search/lib/model/filters/ESearchEntryQueryFromFilter.php
vendor/ZendFramework/library/Zend/Form.php
vendor/ZendFramework/library/Zend/View/Helper/HeadLink.php
vendor/propel/util/BasePeer.php

PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in /opt/kaltura/app/alpha/apps/kaltura/lib/request/infraRequestUtils.class.php on line 70
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /opt/kaltura/app/alpha/apps/kaltura/lib/request/kIpAddressUtils.php on line 198
PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in /opt/kaltura/app/alpha/apps/kaltura/lib/monitor/KalturaMonitorClient.php on line 402
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /opt/kaltura/app/plugins/content_distribution/lib/kContentDistributionFlowManager.php on line 1685
PHP Warning:  "continue" targeting switch is equivalent to …

Fixes the below erros

---

alpha/lib/model/DeliveryProfileLive.php
alpha/lib/model/MediaServerNode.php
plugins/media/live_cluster/lib/model/LiveClusterMediaServerNode.php

add session type to playManifest url (only in case of LiveClusterMediaServerNode)
remove session_id (sid) from playManifest url

LIV-167: add session type to playManifest url

---

alpha/apps/kaltura/modules/extwidget/actions/embedPlaykitJsAction.class.php

Add playkit-kava and playkit-ott-analytics to kaltura-player >= 0.56.0 which doesn't exist these plugins anymore.
Related to https://github.com/kaltura/kaltura-player-js/pull/337

feat(FEC-10291): Kaltura Player - Migrate Analytics Plugins Injection from Kaltura Player to Server

---

alpha/apps/kaltura/modules/extwidget/actions/embedPlaykitJsAction.class.php

use `list()` to get the first element instead of `[0]` which unsupported in old PHP versions

fix: error on array access

---

api_v3/services/LiveStreamService.php

print adminTag live limits in validateMaxStreamsNotReached to logs (for debug)

LIV-197: print adminTag live limits to logs

---

alpha/apps/kaltura/modules/extwidget/actions/embedPlaykitJsAction.class.php

Return 404 in case of error to avoid CDN caching

fix: set 404 response in case of error

---

alpha/apps/kaltura/modules/extwidget/actions/servefileAction.class.php

otherwise empty files can be cached in the packager/cdn

servefile: return not found http status on err

---

infra/cache/kInfraMemcacheCacheWrapper.php

it seems that in some cases, removing references to the memcache object
is not enough

explicitly close the memcache conn

---

alpha/scripts/utils/ExportToDifferentStorage.php

sometimes the file sync is ready long before the flavor asset, and file syncs are being skipped. instead, exclude only deleted/error flavors.

export script - don't take only ready assets

---

alpha/apps/kaltura/modules/extwidget/actions/serveFlavorAction.class.php

based on path regex set in kConf

serveFlavor: support skipping packager cache

---

alpha/scripts/utils/ExportToDifferentStorage.php

kFileSyncUtils::resolve ignores links in bad status and returns the original file sync, moved to handle links directly instead of this function

export script: fix broken links

---

alpha/scripts/utils/ExportToDifferentStorage.php

when there was a file sync only in the target dc but not in the source dcs, the script incorrectly thought the target file sync is wrong and deleted it.
also moved the call to clone to inside the try/catch since it can throw in some cases.

export script bug fix

---

alpha/lib/model/FileSync.php

copyInto calls setStatus before setCustomData, setStatus loads the custom data by calling unsetOriginalId. since the custom data wasn't yet copied, m_custom_data is initialized to an empty object. setting it to null forces a reload of custom data on the next get/set.

export: make sure custom data fields are not lost

---

alpha/apps/kaltura/lib/cache/kQueryCache.php

from 5m to 1h, this will make the system more resilient to slave lags at the expense of more queries to master

query cache: increase query master thres

---

batch/batches/Convert/KAsyncConvert.class.php

Without this, since it's the batch daemon (running as the `kaltura` user) that creates the dir and the API (so basically the Apache user) that does the move and deletion operations, things will fail.

Super critical for conversion jobs

---

plugins/search/lib/model/SphinxLogPeer.php

simplify the query for mysql, to make sure it uses the dc,id index appropriately.

sphinx populate: issue a separate query per dc

---

deployment/base/sql/01.kaltura_sphinx_ce_tables.sql
deployment/updates/sql/2020_11_05_sphinx_log_dc_id_index.sql
plugins/search/lib/model/SphinxLogPeer.php
vendor/propel/util/BasePeer.php
vendor/propel/util/Criteria.php

when one dc is inactive, the queries for fetching its updates can become very heavy. it seems mysql doesn't use dc,id index in this case, even though it's better than id, so we are forcing it.

sphinx_log: add dc,id index and force it

---

alpha/apps/kaltura/lib/cache/kApiCache.php
alpha/apps/kaltura/lib/monitor/KalturaMonitorClient.php
alpha/apps/kaltura/modules/extwidget/actions/downloadAction.class.php
alpha/apps/kaltura/modules/extwidget/actions/rawAction.class.php
alpha/apps/kaltura/modules/extwidget/actions/serveFlavorAction.class.php
alpha/apps/kaltura/modules/extwidget/actions/serveIsmAction.class.php
alpha/apps/kaltura/modules/extwidget/actions/serveManifestAction.class.php
alpha/apps/kaltura/modules/extwidget/actions/serveMultiFileAction.class.php
alpha/apps/kaltura/modules/extwidget/actions/servefileAction.class.php
alpha/apps/kaltura/modules/extwidget/actions/thumbnailAction.class.php
alpha/apps/kaltura/modules/keditorservices/actions/flvclipperAction.class.php
alpha/web/index.php

- generate events for cached playManifest, serveFlavor and thumbnail
- remove unneeded initApiMonitor calls (initialized by ps2 bootstrap)

apimon: ps2 cleanup

---

alpha/apps/kaltura/lib/kSimuliveUtils.php
alpha/apps/kaltura/lib/myPlaylistUtils.class.php
alpha/apps/kaltura/modules/extwidget/actions/serveFlavorAction.class.php
alpha/lib/model/DeliveryProfile.php
alpha/lib/model/asset.php

get the entry's captionAssets and put it in the serveFlavor's json for the Simulive flow

PLAT-22530: support captions in Simulive

---

infra/monitor/KalturaMonitorClient.php

1. fallback to /p/ for playManifest without ks
2. allow prefixes before the /p/ for serveFlavor

apimon: improve partner id coverage

---

plugins/vendor/zoom/lib/model/processors/kZoomProcessor.php

PLAT-22584 - Zoom user is missing when trying to match cms_id

---

infra/chunkedEncode/KChunkedEncode.php

improperly set content video duration, caused in some marginal cased generation of empty last chunks
and failure of the whole CE session

FIX: empty last chunks

---

infra/chunkedEncode/KChunkedEncode.php

remove duration compliance, that forced CE sessions to have at least 3 chunks

Allow CE process short contents

---

infra/chunkedEncode/KChunkedEncode.php

remove duration compliance, that forced CE sessions to have at least 3 chunks

HF: Allow CE process short contents

---

infra/chunkedEncode/KChunkedEncodeSessionManager.php

at least 30s
otherwise very short contents (<15sec) might fall on timeout

HF:Set MinExection Timeout

---

alpha/lib/model/LiveEntryServerNode.php

change the default value of EntryServerNode:isPlayableUser to false to solve bug in "Explicit Live" feature

PLAT-22662: change EntryServerNode's 'isPlayableUser' default to false

---

alpha/lib/model/EntryServerNodePeer.php
alpha/lib/model/LiveEntry.php
alpha/lib/model/LiveEntryServerNode.php
api_v3/lib/types/EntryServerNode/live/KalturaLiveEntryServerNode.php

add the entry viewMode to the EntryServerNode object, needed for the "Explicit Live" feature implementation in LiveNG

PLAT-22661: add the entry viewMode to the EntryServerNode object

---

alpha/lib/model/LiveEntryServerNode.php

revert the EntryServerNode->isPlayableUser default value to false because of issues occurred on old live system

PLAT-22670: revert isPlayableUser default to true

---

alpha/scripts/utils/ExportToDifferentStorage.php

remove the call to setPartnerId, leave the partner that was set from the file sync key.

export script: cross pid link bug fix

---

.github/workflows/linter.yml

This will run a lint job that validated the following file formats:
https://github.com/github/super-linter#supported-linters
See sample job here: https://github.com/kaltura/developer-platform/runs/2113133647?check_suite_focus=true
And here are all the issue we have in this repo: https://github.com/kaltura/server/runs/2113347397?check_suite_focus=true
Naturally, the job is set up to only lint files that are included in each push and not all files in the repo, this was just for testing purposes (see https://github.com/kaltura/server/pull/10584/commits/ae5ce915428a0b3a0f263a039ff65b4e03da113d)
@gotlieb, @yossipapi, @erankor - FYI.

Code linter

---

alpha/lib/model/DeliveryProfileLive.php
alpha/lib/model/MediaServerNode.php
plugins/media/live_cluster/lib/model/LiveClusterMediaServerNode.php
plugins/media/wowza/lib/model/WowzaMediaServerNode.php

- in case of server node of "LiveClusterMediaServerNode" type (LiveNG) and explicitLive is on and "getServeVodFromLive" is true - we don't want the "type" to exist in url as it contradict with the new recording implementation
- in case of LiveNG - add '/tl/' to the url anyway - regardless of explicitLive (with '/tl/main' by default)

LIV-472: remove "type" from delivery profile url when serveVodFromLive

---

plugins/content/caption/base/lib/kCaptionsContentManager.php

@MosheMaorKaltura after reviewing, I believe this is OK
1. createNewCaptionFile is called
2. $unsupported_formats are being set (for scc and cap)
3. if caption is supported we call 'buildFile' at: plugins/content/caption/base/batch/CopyCaptions/KAsyncCopyCaptions.class.php:160
4. build file is abstract and implemented at the respective caption managers
5. **note** only srt and webVtt actually call "createCaptionsFile" which is where the fix for the line index is. Since dfxp does not have the same structure as srt and webvtt - I believe this is fine.
Happy to get your input
Thanks

SUP-18687: fix SRT line index when clipping the beginning of the entry

---

alpha/apps/kaltura/modules/extwidget/actions/serveFlavorAction.class.php

when there's an mpeg-ts timestamp wraparound, the player fails to sync
the captions to the video, and the captions stop. this change moves the
clipStartTime so that it will be far from the wraparound value (1<<33).
as long as the duration of the simulive video is less than 13.5h, no
wraparound will occur.

simulive mpeg-ts wraparound fix

---

plugins/media/live_cluster/lib/model/LiveClusterMediaServerNode.php

In case of entryId with 'tl' inside - the playManifest response mistakenly won't include the '/tl/' param
fix it by checking the 'tl' strpos **with slashes**

LIV-558: fix tl missing in case of entryId with 'tl'

---

alpha/scripts/kava/updateEntryPlaysViews.php

when binding to a prepared statement.

PSVAMB-24095: explicitly set entryId as string

---

plugins/reach/services/EntryVendorTaskService.php

Resubmission should not be possible for tasks while an active task exists in the queue.

PLAT-22921

---

plugins/schedule/base/lib/model/LiveStreamScheduleEvent.php

change the dynamicGetter in case of simuliveFlow (LiveStreamScheduleEvent) to return playable only if we're at least 18 seconds inside the event (and not immediately from the event start as today)

PLAT-22950: simulive - isLive true only when event is playable

---

alpha/apps/kaltura/lib/storage/kFileSyncUtils.class.php

Add sizeInBytes data to flavor asset when using shared and remote storage

SUP-27954-Add-SizeInBytes-To-Flavor-Asset:Add sizeInBytes to flavors when using share and remote storage

---

api_v3/lib/types/conversionProfile/KalturaAsset.php

Preventing extended the limitation of int variable in Java, when receiving big sizeInBytes variable in Json response for flavorAsset request in Java client.

SUP-27743-Java-Long-Integers-FlavorAsset-SizeInBytes:Change type of sizeInBytes from int to long

---

deployment/updates/scripts/2021_06_13_deploy_update_entry_was_added_to_channel_email_notification.php
deployment/updates/scripts/xml/2021_06_13_updateEntryWasAddedToChannelEmailNotification.template.xml

"Entry Was Added To Category" template is triggered by live entry and VOD entry. 
This update will prevent sending live entry notification and, therefore, prevent duplicate notification.

SUP-27690-Duplicate-Add-To-Channel-Notification:Prevent sending email notification for live entry

---

api_v3/lib/KalturaLiveEntryService.php

In case we send null value as the flavor param upload with the default conversion profile (unless we have default recording conversion profile)

LIV-529 : upload source when media info changed

---

api_v3/services/LiveStreamService.php

block liveStream:authenticate request of entry id of blocked partner (currently the partner validation is performed on the request partner - which is the live partner - and not on the entry's partner)

PLAT-23206: block liveStream:authenticate of blocked partner

---

api_v3/services/LiveStreamService.php
plugins/schedule/base/lib/model/LiveStreamScheduleEvent.php

on "dynamicGetter" of LiveStreamScheduleEvent - where we check if the simulive event is currently playable - check the case that the current time is actually equal to the "startTime" + 18 (change "<" to "<="). otherwise the response will be considered as "not live" and will be saved on cache until the end of the event with this incorrect response.
add log print to "getDetails" of the calculated broadcast status

PLAT-23257-HF: fix incorrect getDetails response

---

api_v3/services/LiveStreamService.php
plugins/schedule/base/lib/model/LiveStreamScheduleEvent.php

**This PR is to the main branch. The hot-fix already merged https://github.com/kaltura/server/pull/11183**
on "dynamicGetter" of LiveStreamScheduleEvent - where we check if the simulive event is currently playable - check the case that the current time is actually equal to the "startTime" + 18 (change "<" to "<="). otherwise the response will be considered as "not live" and will be saved on cache until the end of the event with this incorrect response.
add log print to "getDetails" of the calculated broadcast status

PLAT-23257: fix incorrect getDetails response

---

api_v3/lib/KalturaLiveEntryService.php

"old" live system sending the "mediaServerIndex" as string (https://github.com/kaltura/liveDVR/blob/3.0/lib/kaltura-client-lib/KalturaTypes.js#L2427). in the past, before refactor of LIV-780 (https://github.com/kaltura/server/pull/10948) we didn't compared the type.

LIV-780: fix False recording blocking

---

api_v3/lib/KalturaLiveEntryService.php

When comparing $mediaServerIndex and EntryServerNodeType::LIVE_PRIMARY should not be strongly typed.

PSVAMB-28297: Fix False recording blocking

---

alpha/apps/kaltura/lib/storage/kDataCenterMgr.class.php
alpha/lib/model/FileSync.php

@yossipapi only handled a single flow
There are 9 other places calling getDcById and some are not taking into consideration that it might return 'null'
We either fix all, or only specific flows (as this PR does)
Thanks

FOUN-288: Support decommissioning dc without deleting all file syncs that reside on it

---

plugins/reach/lib/kReachManager.php

support REACH automatic rules for External-Media type when updating duration after entry was added (KMS current flow)
* When KMS add External Media (YouTube) they first do externalMedia-->add and only then update with 'msDuration'

SUP-20297: support REACH automatic rules when updating External-Media type (KMS current flow)

---

infra/monitor/KalturaMonitorClient.php

- report the real action name when using defpartnerservices2base
- use the partner_id query param, if exists

apimon: improve ps2 tracking

---

infra/general/kExecWrapper.php
infra/monitor/KalturaMonitorClient.php

shell_exec / passthru do not return error, and are therefore not
monitored

apimon: add exec errors

---

infra/monitor/KalturaMonitorClient.php

this also fixes a bug where amqp errors were sent as ints, and therefore
not indexed

apimon: prefix rabbit/amqp errors

---

alpha/apps/kaltura/lib/cache/kPlayManifestCacher.php

this can happen when switching versions, just ignore the error and avoid
using the cache

kPlayManifestCacher: ignore missing files

---

alpha/apps/kaltura/lib/kSimuliveUtils.php
alpha/apps/kaltura/lib/scheduleEvent/ILiveStreamScheduleEvent.php
alpha/apps/kaltura/modules/extwidget/actions/playManifestAction.class.php
alpha/apps/kaltura/modules/extwidget/actions/serveFlavorAction.class.php
alpha/lib/model/LiveEntry.php
plugins/schedule/base/lib/api/KalturaLiveStreamScheduleEvent.php
plugins/schedule/base/lib/model/LiveStreamScheduleEvent.php

add "isContentInterruptible" field to LiveStreamScheduleEvent's custom data which define whether the "main" content (sourceEntry) of the simulive can be interrupted by a "real" live stream. by definition - preStart/postEnd content always interruptible.
in playManifest action - for simulive flow - if "real" live streaming right now and the event is interruptible now - serve as regular live and not as simulive.
change "getInternalLiveStatus" to public - as we need to call it from "kSimuliveUtils"
**from the serveFlavor perspective:**
-  if live interrupted - set endTime as null, which will cause addition of "expirationTime" to the json, will cause the requests to packager to get 404  and trigger new playManifest request by the player

LIV-846: simulive to live transition (and vice versa)

---

alpha/apps/kaltura/lib/cache/kApiCacheBase.php
alpha/apps/kaltura/modules/extwidget/actions/playManifestAction.class.php

in case of anonymous request - the playManifest response might be stuck in cache for up to 10 min (default cache time for playManifest responses)
this cache might break the simulive to live feature, as the player might get playManifest response that redirect it to vod packager instead of live (or the opposite), and break the playback transition.
The solution is that in case of anonymous playManifest request of **simulive flow only (!)**, we disabling the cache

LIV-894: fix simulive to live playManifest cache issue

---

alpha/apps/kaltura/lib/kSimuliveUtils.php
alpha/apps/kaltura/lib/scheduleEvent/ILiveStreamScheduleEvent.php
alpha/apps/kaltura/modules/extwidget/actions/playManifestAction.class.php
plugins/schedule/base/lib/model/LiveStreamScheduleEvent.php

Fixing the case of "real" live streaming while non-interruptible period. before this change - if PM request came after start streaming but before transition to interruptible period - it might stuck the playManifet response in cache with ttl finished after non-interruptible period finish - and cause playback transition failure:
The PR also contains simplification of https://github.com/kaltura/server/pull/11380
**The changes:**
added "getEventTransitionTimes" to LiveStreamScheduleEvent - which returning an array of transition times of playback (for example start of event playback / transition from main entry to post entry etc...)
added "getEventTransitionTimes" to ILiveStreamScheduleEvent interface
added "getClosestPlaybackTransitionTime" to kSiuliveUtils which getting an event and time and …

LIV-894-B: simulive to live - another caching issue

---

alpha/apps/kaltura/lib/kSimuliveUtils.php
alpha/apps/kaltura/modules/extwidget/actions/playManifestAction.class.php

in case of request arrives exactly on the end of the event - "getClosestPlaybackTransitionTime" return 0 and the conCacheExpirty will be set to "-1". instead of that - in such case we don't want to touch the cond cache time.

LIV-894: avoid setting condCacheExpiry of '-1'

---

alpha/apps/kaltura/lib/events/events/kObjectReadyForIndexEvent.php

set executionScope of INDEXING before indexing so simulive scheduleEvent's "getter" will return false and won't affect liveStatus of list action

SUP-31042: set executionScope of INDEXING before indexing (LIV-900)

---

plugins/schedule/base/lib/api/KalturaEntryScheduleEvent.php
plugins/schedule/base/lib/api/KalturaScheduleEvent.php

currently updating scheduleEvent to a time that overlap with it's linked events will fail due to "Another event is already scheduled during this time".
we need to filter out the linked events when checking for overlapping events to avoid this problem

VIRTC-18530: avoid consider linked events as overlap when updating

---

alpha/apps/kaltura/lib/kSimuliveUtils.php
alpha/apps/kaltura/modules/extwidget/actions/playManifestAction.class.php

in case of simulive with playlist source - override the servedType with MEDIA_CLIP to continue to the regular flow of simulive
in case of source of playlist type - create the json in accordance with all the playlist entries assets
**IMPORTANT:**
this PR will cause behavioral change for simulive. until now - if event total time was configured to be shorter than the sourceEntry - the source entry duration (only) in json was shorten to the event's total time. this PR changing it so if the event duration is shorter than the total time of all sources - the durations array will be transformed s.t the duration that causing the exceeding will be shorten to the remainder, and all the durations after will get the value of '1'.

LIV-917: simulive - add support for playlist source

---

alpha/apps/kaltura/lib/kSimuliveUtils.php
alpha/apps/kaltura/lib/myEntryUtils.class.php

chop the main content of simulive according to event main duration (excluding pre&post times), while preStart & postEnd entries content will always play the whole content
for example - content duraitons [1,10,1] and event durations of [1,5,1] => playback will be [1,5,1] (main content chopped from 10min to 5 min while pre&post playing their whole content)

LIV-932: simulive - chop the main content according to event duration

---

alpha/apps/kaltura/modules/extwidget/actions/playManifestAction.class.php

in case of playManifest request came with time / offset - we don't want to return a "real" live response even in case that "real" live interrupt (if got time / offset it doesn't make sense that interrupt occur as we can't predict)

No-Plat: cancel sim2live flow in case of playManifest request with time/offset

---

plugins/schedule/base/lib/api/KalturaLiveStreamScheduleEvent.php

currently the pre/post entry type must be 'MEDIA_CLIP', otherwise - simulive won't play as expected. added enforcement for these fields to API add/update actions

LIV-944: simulive - validate pre/post entry type supported

---

alpha/apps/kaltura/lib/kSimuliveUtils.php

partially revert of https://github.com/kaltura/server/pull/11525/files
for example - content durations [10,25,15] and event durations of [10,**20**,15] => playback will be [10,**25**,**10**] (main content won't be chopped, but only the post for this case)

LIV-932: simulive - consider the postEnd duration while chopping main playback

---

alpha/apps/kaltura/lib/cache/myObjectCache.class.php
alpha/apps/kaltura/lib/fastdb/fastdb.class.php
alpha/apps/kaltura/lib/myFileConverter.class.php

`__CLASS__` is supported across all PHP versions from as back as I can remember (and I've a very good memory), whereas `self::class`, with older PHP versions, would yield:
> PHP Parse error:  syntax error, unexpected T_CLASS, expecting T_STRING or T_VARIABLE or '$'
Both output the name of the class so..

Use __CLASS__ rather than `self::class`

---

alpha/apps/kaltura/lib/cache/kApiCache.php

when getting a ks with a valid signature that is invalid due to
session.end/iprestrict/urirestrict/expiration, use the partner id of the
ks for apimon reporting.

apimon: report the partner id on invalid ks error

---

plugins/search/providers/sphinx_search/scripts/populateFromLog.php

In the situation sphinx is not able to update a record, a NOTICE message is throw, even though it is an error so depending on loglevel, the message is not displayed and the issue is missed.

PSVAMB-37517: Change log message from notice to error level

---

infra/general/KDOMDocument.php

When updating metadata profile it gets stuck on status 3 (transforming)
The transformation batch job gets "Exception: Error: Empty file supplied as input..." because the file is a shared path.

SUP-31814  Change file_exists and filesize functions to the kfile for shared path.

---

deployment/bootstrap.php

> PHP Fatal error:  Uncaught Error: Class 'KalturaMultiLingualString' not found in /opt/kaltura/app/alpha/apps/kaltura/lib/multiLingualUtils.php:318 Stack trace:
thrown in /opt/kaltura/app/alpha/apps/kaltura/lib/multiLingualUtils.php on line 318
This will load the needed classes.

Following the introduction of `KalturaMultiLingualString`, deployment/base/scripts/insertDefaults.php fails

---

alpha/apps/kaltura/lib/live/kBroadcastUrlManager.php

Underscore in host can cause problem in dns-resolve.
For entry starting with '1_' - we just remove the prefix
For all other entries we just replace the underscore with '-'

LIV-1087: remove underscore from host in broadcast url

---

plugins/media/live_cluster/lib/model/LiveClusterMediaServerNode.php

Currently for all liveCluster server nodes the name, host-name and environment is the same.  We want to start use the environment as optional region - so moving the url to be build with the name field

LIV-1104: take env var from name

---

plugins/vendor/zoom/lib/model/kZoomEventHanlder.php

current behavior: transcripts from zoom events are being added when enableZoomTranscription is disabled.

SUP-37408 enableZoomTranscription is bool and not int.

---

deployment/base/sql/01.kaltura_ce_tables.sql

On New installs, avoid customers usage of low ids.

VCP-13172 reserve flavor_params low ids

---

api_v3/lib/KalturaLiveEntryService.php

When APPEND recording is used and we get 2 request in the same time (race) - the first should create the recording and the second need to use it. Note that the wrapper reset the recording entry ID after the should create func before the actual create.
We still have rare case if the 2 request will pass the should function, one will create the recording and only then the second will reset it - solving it will be by moving the lock but that has lot more affect so we rather avoid it

SUP-40499: Protect against duplicate recording VOD

---

infra/chunkedEncode/KChunkedEncodeSessionManager.php

Handling short chunk cases, caused by low source framerate, and inadequate source duration metadata.

Fix chunk validation logic

---

configurations/apache/conf.d/enabled.kaltura.conf.template

This change is necessary to skip PHP-FPM when running Apache with the PHP 8 module.

PLAT-24815: Support php8 in default apache conf

---

alpha/lib/model/DeliveryProfileLive.php
alpha/lib/model/MediaServerNode.php
plugins/media/live_cluster/lib/model/LiveClusterMediaServerNode.php

If the is a flavor with H265 put add to the URL container with fmp4 value that will tell the live to use fmp4 and not mpegts

LIV-1253: Force fmp4 in mix container

---

deployment/base/scripts/init_content/01.uiConf.99.template.xml

Currently the player is deployed without flashvars due to an issue with the deployment XML. I have adjusted the xml to match the param name according to API docs: https://developer.kaltura.com/api-docs/service/uiConf/action/add

Fix default v7 player in init_content

---

alpha/lib/enums/resetPassLinkType.php
alpha/lib/model/UserLoginDataPeer.php
configurations/local.template.ini
release-notes.md

before this PR - only "newrow.com" link was generated. this PR purpose is to add the option to choose between newrow.com domain (kme_nr) to kaltura.com domain (kme). the logic done outside Kaltura server (based on the URL the user used)

NR2-8250: add KME reset password link for Kaltura domain

---

alpha/apps/kaltura/modules/extwidget/actions/embedPlaykitJsAction.class.php

Using this feature, user can embed iframe request that can play external source in kaltura player such as youtube entries,
for example, add this to you query params - 
`&external_source={"progressive":[{"mimetype":"video/youtube","url":"aqz-KE-bpKQ"}]}`
(make sure you have youtube plugin enabled) and kaltura player will playit.
FYI - this ability exists in dynamic embed, now its added to iframe embed also

PLAT-24996: allow adding external source to kaltura player

---

alpha/apps/kaltura/modules/extwidget/actions/embedPlaykitJsAction.class.php

Example of how the dynamic embed code should look like if client wants to have multiple players on the same page.
` <div id="kaltura_player_379896348" style="width: 528px;height: 327px"></div>
<script type="text/javascript">
import("http://www.kaltura.local/p/102/embedPlaykitJs/uiconf_id/23448135?embed_factory=true").
then(({ kalturaPlayerFactory }) => {
try {
var kalturaPlayer = kalturaPlayerFactory.setup({
targetId: "kaltura_player_379896348",
provider: {
partnerId: 102,
uiConfId: 23448135
}
});
kalturaPlayer.loadMedia({entryId: '0_r37zt2c2'});
} catch (e) {
console.error(e.message)
}
});
</script>`

PLAT-25007: clustered dyamic embed

---

alpha/scripts/utils/updatePartnerEntries2Sphinx.php

This pull request fixes an issue where a PDOException was being thrown when encountering an unknown column in dynamic_attributes on kaltura_metadata. The code now catches the exception and provides appropriate error messages when updating the affected items.

ONPREM-1076 Fix PDOException for unknown column in sphinx

---

plugins/content/caption/base/CaptionPlugin.php

get entryServerNode with status MARKED_FOR_DELETION.

LIV-1295: fix live webvtt captions

---

infra/cdl/kdl/KDLOperatorFfmpeg6_0.php

Remove audio mapping code from video only contents

PLAT-25122-ffmpeg-audio-mapping-fix

---

alpha/apps/kaltura/lib/kManifestRenderers.php

We cannot use retrieveByPK since this code can be served from the cache layer. We added the type checker to be on the safe side.
The same behavior happens with VOD.

fix: shouldUseClosedCaptions func

---

alpha/scripts/kava/monitorPlaysViewsMemcache.php
alpha/scripts/kava/playsViewsCommon.php
alpha/scripts/kava/playsViewsElasticConsumer.php
alpha/scripts/kava/playsViewsMemcacheConsumer.php
alpha/scripts/kava/systemUtils.php

get elastic/memcache conf from env variables. 
add syncMemcache monitor.
add liveness prob php script

sync playsviews to memcache/elastic kava scripts

---

alpha/scripts/utils/mergeNewlyCreatedDuplicatedUsers.php

Improve log output by ensuring each log entry ends with a newline character to conform to prom text file format:
https://prometheus.io/docs/instrumenting/exposition_formats/#text-format-details

VCP-19323: Fix log output formatting in mergeNewlyCreatedDuplicatedUsers script

---

infra/storage/kEncryptFileUtils.php

/opt/kaltura/app/infra/storage/kEncryptFileUtils.php line 90 - Use of "self" in callables is deprecated

Fix deprecated notice

---

infra/cache/kApcWrapper.php

Correct the argument passed to the `apcu_fetch` function to ensure it properly returns the success status.

Fix apcu_fetch call in kApcWrapper

---

alpha/lib/model/UserLoginDataPeer.php

Fix the issue where password change fails if user is deleted from login PID but exists in another PID

SUP-44991: Password change fails if user is deleted from login PID
