kaltura/server

- configurations/base.ini
> Revert "update base.ini"

- alpha/apps/kaltura/lib/kPlaybackContextDataHelper.php
> sources priority order fix

- release-notes.md
- tests/standAloneClient/playServerFlavorHttpEventNotification.xml
> add play server flavor changed http notification

- tests/standAloneClient/playServerFlavorHttpEventNotification.xml
> added event condition - Entry type equal

- alpha/apps/kaltura/lib/model/objectfilters/KalturaCriteria.php
- infra/plugins/KalturaPluginManager.php
cache the the specific plugin that is needed, in:
- KalturaCriteria::Create
- KalturaPluginManager::loadObject
- KalturaPluginManager::getObjectClass
> avoid loading unneeded plugins

- api_v3/lib/syndication/ITunesFeedRenderer.php
> add explicit tag to channel in itunes syndication feed

- alpha/apps/kaltura/lib/storage/DeliveryProfileComparator.php
> sort delivery profiles as defined by the partner

- alpha/apps/kaltura/lib/kAccessControlMessage.php
- alpha/apps/kaltura/lib/kPlaybackContext.php
- alpha/apps/kaltura/lib/kPlaybackContextDataHelper.php
- alpha/apps/kaltura/lib/kPlaybackContextOptions.php
- alpha/apps/kaltura/lib/kPlaybackSource.php
- alpha/apps/kaltura/lib/myEntryUtils.class.php
- alpha/lib/enums/PlaybackProtocol.php
- api_v3/lib/types/KalturaAccessControlMessage.php
- api_v3/lib/types/KalturaAccessControlMessageArray.php
- api_v3/lib/types/KalturaPlaybackContext.php
- api_v3/lib/types/KalturaPlaybackSource.php
- api_v3/lib/types/entry/KalturaPlaybackContextOptions.php
- api_v3/services/BaseEntryService.php
- plugins/drm/DrmPlugin.php
- plugins/drm/lib/api/KalturaDrmPlaybackPluginData.php
- plugins/drm/lib/api/KalturaDrmPlaybackPluginDataArray.php
- plugins/drm/lib/model/kDrmPlaybackPluginData.php
- plugins/drm/providers/fairplay/FairplayPlugin.php
- plugins/drm/providers/fairplay/lib/api/KalturaFairPlayPlaybackPluginData.php
- plugins/drm/providers/fairplay/lib/model/kFairPlayPlaybackPluginData.php
- plugins/drm/providers/playready/PlayReadyPlugin.php
- plugins/drm/providers/widevine/WidevinePlugin.php
protocols and flavorIds to be comma separated string
remove priority parameter
remove storageId from manifest url and add deliveryProfileId to url
renaming of classes
fixes following code review
PLAT-6283
> Fixes after review:

- alpha/apps/kaltura/lib/batch2/bcdl/kBusinessPreConvertDL.php
> Added 'isset($sourceFlavorOutput)' check

- infra/storage/kFile.class.php
> change fread to fseek

- alpha/apps/kaltura/lib/storage/urlTokenizers/kKsUrlTokenizer.php
- alpha/apps/kaltura/lib/storage/urlTokenizers/kUrlTokenizer.php
- alpha/apps/kaltura/modules/extwidget/actions/playManifestAction.class.php
- api_v3/lib/types/delivery/KalturaDeliveryFactory.php
- api_v3/lib/types/delivery/KalturaUrlTokenizerKs.php
> enhance the ks tokenizer

- plugins/cue_points/annotation/lib/model/filters/AnnotationFilter.php
> Fix issue in annotation filter

- alpha/apps/kaltura/lib/cache/kApiCache.php
- alpha/apps/kaltura/lib/cache/kApiCacheBase.php
- alpha/apps/kaltura/lib/request/infraRequestUtils.class.php
- alpha/apps/kaltura/lib/request/requestParamsPreprocessor.php
- add the ability to enable cache locking
- add the ability to return stale conditional cache responses
- add the ability to manipulate the request params (requestParamsPreprocessor)
> cache features

- infra/general/KCurlWrapper.class.php
> add default definition of destFd as null

- infra/cdl/kdl/KDLFlavor.php
Handle watermarking for sources with invalid AR metadata
> SUP-9869 - Burned watermark aspect ratio

- infra/cdl/kdl/KDLFlavor.php
50==>25
59.94==>29.97
60==>30
...
> Improved High FrameRate truncating

- infra/cdl/kdl/KDLOperatorFfmpeg2_7_2.php
Added X265 specific processing
> PLAT-6650 New X265/HEVC support

- plugins/bulk_upload/csv/batch/BulkUploadUserEngineCsv.php
> check whether a group value is given for user in csv bulk upload

- alpha/lib/model/flavorParamsConversionProfile.php
Via flavorParamsConversionProfile::tag field
> flavorParams::tag override 

- api_v3/lib/types/conversionProfile/KalturaConversionProfileAssetParams.php
Via flavorParamsConversionProfile::tags field
> flavorParams::tags override

- alpha/apps/kaltura/lib/batch2/bcdl/kBusinessPreConvertDL.php
flavorParams::tag override via flavorParamsConversionProfile::tag field
‘Collection’/’grouping/multi-flavor tagging support
> flavorParams::tags and 'grouping' tags

- alpha/lib/model/DeliveryProfilePeer.php
> add delivery Id to playManifest

- plugins/admin_console/kaltura_internal_tools/admin/KalturaInternalToolsSystemHelperAction.php
> PHP notice in KalturaInternalToolsSystemHelperAction

- alpha/apps/kaltura/lib/kMrssManager.php
- alpha/lib/data/identifier/kCategoryIdentifier.php
- alpha/lib/data/identifier/kEntryIdentifier.php
- alpha/lib/data/identifier/kObjectIdentifier.php
> retrieving categories by fullName according to partnerId

- plugins/metadata/lib/kMetadataObjectCopiedHandler.php
> copy metadata when clone cuepoint

- plugins/schedule/base/services/ScheduleEventService.php
> get recurring conflicting events array and merging to one array

- api_v3/lib/types/entry/filters/advanced/KalturaCategoryEntryAdvancedFilter.php
> Change annotation of categoryEntryStatus to the correct type

- api_v3/lib/types/entry/filters/advanced/KalturaCategoryEntryAdvancedFilter.php
> Change type to string to allow multiple values.

- alpha/apps/kaltura/lib/myEntryUtils.class.php
- alpha/lib/model/assetParams.php
> optimize local thumb grabbing

- alpha/apps/kaltura/lib/kPlaybackContextDataHelper.php
- alpha/lib/model/DeliveryProfilePeer.php
> support manual live entry sources

- alpha/apps/kaltura/lib/kPlaybackContextDataHelper.php
> support live entry sources- added sources to live and vod entry

- alpha/apps/kaltura/lib/batch2/kJobsCacher.php
> sending clone criteria to getJobsFromDB

- batch/batches/CaptureThumb/KAsyncCaptureThumb.class.php
> fix thumbnail generation when offset in bigger then duration

- batch/batches/CaptureThumb/KAsyncCaptureThumb.class.php
> Revert "fix thumbnail generation when offset in bigger then duration"

- batch/batches/CaptureThumb/KAsyncCaptureThumb.class.php
> Revert "Revert "fix thumbnail generation when offset in bigger then duration""

- batch/batches/CaptureThumb/KAsyncCaptureThumb.class.php
> Revert "Revert "Revert "fix thumbnail generation when offset in bigger then duration"""

- infra/general/kString.class.php
> fix broken url for getDownloadUrl when file name contains %

- alpha/apps/kaltura/lib/cache/kCacheManager.php
- alpha/apps/kaltura/lib/kResourceReservation.php
- api_v3/lib/KalturaErrors.php
- configurations/base.ini
- infra/general/ResourceReservation.php
- plugins/schedule/base/services/ScheduleEventResourceService.php
- plugins/schedule/base/services/ScheduleEventService.php
> add reservation for resources

- alpha/apps/kaltura/lib/batch/myBatchPartnerUsage.class.php
> looping on partner with id instead of offset

- infra/cdl/kdl/KDLFlavor.php
It is not required for COPY audio flavors.
> Fix default multi-audio stream flow

- plugins/metadata/MetadataPlugin.php
- plugins/metadata/services/MetadataService.php
> no need to create new file_sync or increment version of metadata if actual data hasn't changed

- plugins/schedule/base/services/ScheduleEventService.php
> remove validation in getConflictsAction

- api_v3/lib/types/entry/KalturaLiveStreamEntry.php
> return stream URLs for Co-Editors

- alpha/apps/kaltura/lib/kObjectCopyHandler.php
> When creating an entry from a template copy also pending categories

- alpha/lib/model/entry.php
- api_v3/services/CategoryEntryService.php
> check if user can remove entry from category even when in a group

- infra/content/kXml.class.php
- plugins/content_distribution/providers/tvinci/lib/feed/TvinciDistributionFeedHelper.php
- plugins/metadata/lib/model/MetadataProfile.php
> in tvinici distrebutor adding all field to metadata objects

- alpha/apps/kaltura/lib/myEntryUtils.class.php
> append entry version to thumb filename in case of image entry

- batch/batches/KPeriodicWorker.class.php
- configurations/batch/batch.ini.template
- plugins/cue_points/base/batch/clearCuePonts/KAsyncClearCuePoints.class.php
> changing filter name on config file to advancedFilter

- alpha/lib/model/Partner.php
> check LOGIN_DATA_ID is not null in DB insted of sphinx

- alpha/apps/kaltura/lib/myPlaylistUtils.class.php
- alpha/apps/kaltura/lib/webservices/kSessionUtils.class.php
> allow to play redirect entry in playlist with ks access control

- alpha/scripts/utils/addPartnerToCielo24.php
- plugins/integration/providers/cielo24/Cielo24ClientHelper.php
- plugins/integration/providers/cielo24/Cielo24Options.php
- plugins/integration/providers/cielo24/Cielo24Plugin.php
- plugins/integration/providers/cielo24/lib/api/KalturaCielo24JobProviderData.php
- plugins/integration/providers/cielo24/lib/kCielo24FlowManager.php
- plugins/integration/providers/cielo24/lib/model/kCielo24JobProviderData.php
> Revert "Lynx 12.9.0 tr 1205"

- plugins/cue_points/base/CuePointPlugin.php
- plugins/cue_points/base/lib/model/CuePointPeer.php
- plugins/sphinx_search/lib/kSphinxSearchManager.php
> limit the number of cue point to insert to sphinx

- alpha/apps/kaltura/lib/webservices/kSessionUtils.class.php
> allow to play redirect entry with original entry ks

- alpha/web/index.php
> Enable cross domain requests

- alpha/apps/kaltura/lib/webservices/kSessionUtils.class.php
> fix undefined offset notice

- api_v3/lib/types/generic/KalturaBooleanValueArray.php
- api_v3/lib/types/generic/KalturaIntegerValueArray.php
KalturaBooleanValueArray -> KalturaBooleanValue
KalturaIntegerValueArray -> KalturaIntegerValue
> fix returned object from simple type arrays

- plugins/content_distribution/lib/kContentDistributionManager.php
> dont start unneeded import jobs

- infra/content/kXml.class.php
- plugins/content_distribution/providers/tvinci/lib/feed/TvinciDistributionFeedHelper.php
- plugins/metadata/lib/model/MetadataProfile.php
Reverts kaltura/server#5206
Reverting due to OTT support request
> Revert "in tvinici distrebutor adding all field to metadata objects"

- api_v3/lib/reflection/XmlClientGenerator.php
Reverts kaltura/server#5249
should be merged to Lynx-12.11.0
> Revert "fix client generation for typed array in action params"

- api_v3/lib/KalturaBaseService.php
> Lynx 12.11.0 limit serve caching headers

- alpha/apps/kaltura/modules/extwidget/actions/playManifestAction.class.php
- alpha/lib/model/DeliveryProfileDynamicAttributes.php
uses redirect renderer + fileName parameter (makes serveFlavor return Content-Disposition)
> support format/download in playManifest

- alpha/apps/kaltura/lib/KDLWrap.php
- alpha/apps/kaltura/lib/batch2/bcdl/kBusinessPreConvertDL.php
- alpha/apps/kaltura/lib/batch2/kJobsManager.php
- alpha/apps/kaltura/lib/batch2/model/kExtractMediaJobData.php
- alpha/lib/model/conversionProfile2.php
- alpha/lib/model/flavorParams.php
- alpha/lib/model/mediaInfo.php
- api_v3/lib/types/batch/KalturaExtractMediaJobData.php
- api_v3/lib/types/conversionProfile/KalturaConversionProfile.php
- api_v3/lib/types/conversionProfile/KalturaFlavorParams.php
- api_v3/lib/types/conversionProfile/KalturaMediaInfo.php
- batch/batches/ExtractMedia/KAsyncExtractMedia.class.php
- infra/cdl/kdl/KDLMediaDataSet.php
- infra/cdl/kdl/KDLMediaObjectData.php
- infra/cdl/kdl/KDLOperatorFfmpeg0_10.php
- infra/cdl/kdl/KDLOperatorFfmpeg1_1_1.php
- infra/media/mediaInfoParser/KFFMpegMediaParser.php
- Implement condition processing logic.
- ADD ability to switch the conv.prof according to source params and preset conditions.
- ADD detectGOP
- ADD maxGOP field
- ADD preserve source KeyFrames mode
> Lynx 12.11.0 plat 6786 conditional conv prof

- infra/storage/file_transfer_managers/s3Mgr.class.php
> retry s3 stroage export

- plugins/metadata/batch/Transform/KAsyncTransformMetadata.class.php
- plugins/metadata/services/MetadataBatchService.php
> removig call to undefine method

- api_v3/web/clientTest.php
> add htmlspecialchars

- alpha/apps/kaltura/modules/extwidget/templates/openGraphSuccess.php
- alpha/apps/kaltura/modules/extwidget/templates/previewSuccess.php
> call addslashes

- alpha/apps/kaltura/modules/kmc/actions/kmcEmbedAction.class.php
- alpha/apps/kaltura/modules/kmc/templates/kmcEmbedSuccess.php
> fix embed code

- alpha/apps/kaltura/modules/system/templates/loginSuccess.php
> add htmlspecialchars to $login

- infra/cdl/kdl/KDLFlavor.php
FIX WM aspect ratio for for fixed frame size flavors
> PLAT-7003-FIX-WM-aspect-ratio

- alpha/apps/kaltura/lib/request/kSessionBase.class.php
- alpha/apps/kaltura/lib/storage/urlTokenizers/kKsUrlTokenizer.php
- api_v3/lib/types/delivery/KalturaUrlTokenizerKs.php
can be used to enable drmlicenseaccess.getaccess
> ks tokenizer property for setting additional uris

- alpha/apps/kaltura/lib/myPartnerUtils.class.php
> check if https apiProtocol is set for request when setting protocol

- alpha/apps/kaltura/lib/batch2/kBatchManager.php
The conditional-conv-prof processing should be applied only for source assets
> PLAT-6899-Conditional-Profs-only-for-Sources

- plugins/content_distribution/lib/kContentDistributionFlowManager.php
> change distribution status if job is aborted

- configurations/base.ini
> add allowed file types for restricted mode

- configurations/base.ini
> add another allowed type for css

- plugins/content_distribution/providers/cross_kaltura/lib/batch/CrossKalturaDistributionEngine.php
> skip coping diplayInSearch on cross kaltura connector

- plugins/metadata/lib/model/MetadataProfile.php
> chane get metadata key to active only

- api_v3/lib/KalturaEntryService.php
> add a check that userId is a valid expression

- api_v3/lib/KalturaEntryService.php
> trim userId invalid chars insted of checking regex

- plugins/schedule/base/lib/model/ScheduleEvent.php
> Change ScheduleEvent::setOwnerId to public

- alpha/apps/kaltura/modules/extwidget/actions/playManifestAction.class.php
- alpha/lib/model/DeliveryProfileDynamicAttributes.php
- alpha/lib/model/DeliveryProfileVod.php
HOTFIX - PLAT-7142
Allow Session ID to be part of the player parameter
> HOTFIX - PLAT-7142 ad stitching player awareness patches

- alpha/lib/model/LiveEntry.php
- alpha/lib/model/entry.php
- api_v3/lib/types/entry/KalturaPlayableEntry.php
Should be merged to next branch
> set duration of live recording while recording is still being done

- alpha/lib/model/LiveEntry.php
- alpha/lib/model/entry.php
- api_v3/lib/types/entry/KalturaPlayableEntry.php
> Revert "set duration of live recording while recording is still being done"

- infra/media/mediaInfoParser/KMediaInfoMediaParser.php
Use ffprobe FPS if mediainfo val is bad
> PLAT-7120-FIX-Insane-FPS

- plugins/cue_points/thumb_cue_point/ThumbCuePointPlugin.php
PLAT-7217:add plugin interface && missing fields
> PLAT-7217:add plugin interface && missing fields

- alpha/apps/kaltura/modules/extwidget/actions/playManifestAction.class.php
- alpha/lib/model/DeliveryProfileDynamicAttributes.php
- alpha/lib/model/DeliveryProfileVod.php
PLAT-7142
Allow Session ID to be part of the player parameter
> PLAT-7142:ad stitching player awareness patches

- deployment/permissions/service.schedule.scheduleEvent.ini
- deployment/permissions/service.schedule.scheduleResource.ini
- deployment/updates/scripts/add_permissions/2017_04_05_add_schedule_and_schedule_resource_permissions_for_capture_device.php
- release-notes.md
> PLAT-7216: allow capture device permission to add/update/list scheduleEvent and scheduleResource

- plugins/capture_space/lib/api/KalturaCaptureSpaceHashAlgorithm.php
- plugins/capture_space/lib/kCaptureSpaceVersionManager.php
- plugins/capture_space/services/CaptureSpaceService.php
> PLAT-7238: add ability for hash algorithm in updateclients to be requested dynamically and cache the results of the hash

- plugins/capture_space/lib/api/KalturaCaptureSpaceHashAlgorithm.php
- plugins/capture_space/lib/kCaptureSpaceVersionManager.php
- plugins/capture_space/services/CaptureSpaceService.php
> Revert "PLAT-7238: add ability for hash algorithm in updateclients to be requested dynamically and cache the results of the hash"

- alpha/apps/kaltura/lib/kPlaybackContextDataHelper.php
> PLAT-7254 fix missing flavor params id for live entries

- alpha/lib/model/kuserPeer.php
> prevent creation of duplicate kuser when the puser is long

- plugins/sphinx_search/lib/SphinxCriteria.php
using these fields leads to less relevant results
> ignore entitlement fields in ranker

- plugins/schedule/base/services/ScheduleEventService.php
> PLAT-7301 support response profile in schedule events getConflicts

- alpha/apps/kaltura/lib/kContextDataHelper.php
- alpha/apps/kaltura/lib/kPlaybackContextDataHelper.php
- api_v3/services/BaseEntryService.php
> PLAT-7294 playback context handling recorded-live entries

- configurations/local.template.ini
infra/media/mediaInfoParser/KFFMpegMediaParser.php:32
else if (kConf::hasParam('bin_path_ffprobe')) {
> Add bin_path_ffprobe to local.template.ini

- plugins/content_distribution/providers/youtube_api/lib/YoutubeApiDistributionEngine.php
> PLAT-7256 - fix youtube distribution on update

- batch/batches/Convert/Engines/KConversionEngineFfmpeg.class.php
maxConcurrency taken from taskConfig::max
> PLAT-7365-set maxConcurrency

- plugins/schedule/base/lib/model/ScheduleEventPeer.php
> fix issue when getting conflicts to get only the active events

- alpha/lib/enums/XsltParameterName.php
- api_v3/lib/syndication/KalturaFeedRenderer.php
- api_v3/lib/types/syndicationFeed/xslt/opera_syndication.xslt
- api_v3/lib/types/syndicationFeed/xslt/roku_syndication.xslt
> PLAT-7022 PLAT-7344 - Roku and Opera syndication feed xslt modification

- infra/chunkedEncode/KChunkedEncodeSessionManager.php
An attempt to utilize unused slots/cores that are left due to division rounding
And improved printout
> Improved evaluateConcurrency func

- api_v3/lib/types/syndicationFeed/xslt/opera_syndication.xslt
> PLAT-7343 - update opera xslt

- alpha/apps/kaltura/modules/kmc/actions/supportAction.class.php
> PLAT-7288 support keep https

- plugins/poll/services/PollService.php
PLAT-7333 disable cache for service
> PLAT-7333 disable cache for service

- plugins/scheduled_task/lib/model/enums/ScheduledTaskAddOrRemoveType.php
- plugins/scheduled_task/lib/object_task_engine/KObjectTaskModifyCategoriesEngine.php
> add move to category option in modify category engine

- plugins/cue_points/base/services/CuePointService.php
> remove setting kuser when updating cue point

- plugins/scheduled_task/admin/MediaRepurposingSetStatusAction.php
- plugins/scheduled_task/admin/scripts/plugin/media-repurposing-list-action.phtml
> return the dry run batch job Id from the server

- configurations/base.ini
- deployment/permissions/service.poll.poll.ini
- plugins/poll/lib/PollActions.php
- plugins/poll/services/PollService.php
- release-notes.md
PLAT-7502 get vote implementation
> PLAT-7502 get vote implementation

- plugins/content_distribution/providers/youtube_api/lib/YoutubeApiDistributionEngine.php
> PLAT-7472 fix handling stripping html tags in youtube distribution

- configurations/base.ini
- plugins/drop_folder/batch/Engine/KDropFolderEngine.php
- plugins/drop_folder/lib/model/DropFolderFile.php
- plugins/drop_folder/services/DropFolderFileService.php
- plugins/webexDropFolderPlugin/batch/KWebexDropFolderEngine.php
> fix drop folder file copy and add log to webex engine

- alpha/lib/model/UserEntryPeer.php
- api_v3/lib/types/filters/KalturaUserEntryFilter.php
- api_v3/services/UserEntryService.php
- plugins/content/view_history/lib/api/filters/KalturaViewHistoryUserEntryFilter.php
- plugins/content/view_history/lib/model/filters/kViewHistoryUserEntryAdvancedFilter.php
> 1. Remove privacy context from userEntry calculations

- alpha/apps/kaltura/lib/kCurrentContext.class.php
- api_v3/services/ResponseProfileService.php
> Revert "Return Global parter only when specifically requested"

- admin_console/views/scripts/partner/list.phtml
Default assignment will be supported from ECMA2015 and onwards, which IE does not (yet) use
http://www.ecma-international.org/ecma-262/6.0/#sec-functiondeclarationinstantiation
This currently breaks the Admin Console functions in IE
> Default parameter assignment is not supported in IE

- infra/storage/file_transfer_managers/ftpMgr.class.php
- infra/storage/file_transfer_managers/localMgr.php
- infra/storage/file_transfer_managers/scpMgr.class.php
- infra/storage/file_transfer_managers/sftpMgr.class.php
- plugins/drop_folder/batch/DropFolderWatcher/KAsyncDropFolderWatcher.class.php
- plugins/drop_folder/batch/Engine/KDropFolderEngine.php
- plugins/drop_folder/batch/Engine/KDropFolderFileTransferEngine.php
> PLAT-7504 refactoring drop folder watcher for file transfer engine

- api_v3/lib/KalturaFrontController.php
…dd debug for catching other cases
> SUP-11372: Fail requests only of if previous request throw error + add debug for catching other cases

- plugins/scheduled_task/ScheduledTaskPlugin.php
- plugins/scheduled_task/batch/ScheduledTaskRunner/KScheduledTaskRunner.class.php
- plugins/scheduled_task/lib/MediaRepurposingHandler.php
- plugins/scheduled_task/lib/model/ScheduledTaskProfilePeer.php
> add reset of MR entry status when retention time changes

- infra/general/KDOMDocument.php
Reverts kaltura/server#5682
Merged to the wrong branch
> Revert "SUP-11306: handle ampersand chars in XML document"

- alpha/apps/kaltura/lib/kPlaybackContextDataHelper.php
- alpha/apps/kaltura/modules/extwidget/actions/playManifestAction.class.php
- api_v3/services/BaseEntryService.php
- plugins/drm/BaseDrmPlugin.php
- plugins/drm/DrmPlugin.php
- plugins/drm/providers/fairplay/FairplayPlugin.php
- plugins/drm/providers/playready/PlayReadyPlugin.php
- plugins/drm/providers/widevine/WidevinePlugin.php
…ms id when filtering the access control flavors limitation
@MosheMaorKaltura  
Do not merge until approve to merge from VIMB side
> PLAT-6734 getPlaybackContext fixes

- plugins/drop_folder/batch/Engine/KDropFolderEngine.php
> add order by to list

- plugins/search/providers/elastic_search/lib/api/types/KalturaESearchCaptionItem.php
- plugins/search/providers/elastic_search/lib/api/types/KalturaESearchCuePointItem.php
- plugins/search/providers/elastic_search/lib/api/types/KalturaESearchEntryItem.php
- plugins/search/providers/elastic_search/lib/api/types/KalturaESearchItem.php
- plugins/search/providers/elastic_search/lib/api/types/KalturaESearchMetadataItem.php
- plugins/search/providers/elastic_search/lib/model/ESearchCuePointItem.php
- plugins/search/providers/elastic_search/lib/model/ESearchEntryItem.php
- plugins/search/providers/elastic_search/lib/model/ESearchItem.php
- plugins/search/providers/elastic_search/lib/model/kESearchQueryManager.php
- plugins/search/providers/elastic_search/services/ESearchService.php
Small typos fixes and hierarchy placement
> Some refactoring

- deployment/updates/scripts/xml/2016_05_31_updateEntryReadyTemplateForReplace.xml
- deployment/updates/scripts/xml/2016_12_23_updateEntryReadyTemplateForLive.xml
- deployment/updates/scripts/xml/2017_06_20_AddMediaEntryReadyTemplate.xml
as RPM does not support that. @SERVICE_URL@ and @ADMIN_CONSOLE_PARTNER_ADMIN_SECRET@ tokens should be used instead.
> update scripts should never require interactive prompting

- alpha/apps/kaltura/lib/request/kSessionBase.class.php
- plugins/cue_points/base/services/CuePointService.php
> add bypass to user filter in the cue point service

- api_v3/web/analyticsSyncServe.php
serves updates to data required by the analytics enrichment
> add analytics sync script

- batch/batches/Import/KAsyncImport.class.php
- plugins/webex/WebexPlugin.php
> Lynx 12.20.0 sup 11418

- alpha/apps/kaltura/lib/model/entryWrapper.class.php
> add referenceId to the entry updateable fields list

- infra/cdl/kdl/KDLProcessor.php
> SUP-10803-arf-to-wmv inter-source files

- tests/monitoring/api_v3/common.php
https://github.com/kaltura/server/commit/73912965befa5b6d0aac6a746bde8565be96d81f
> following changes made here: https://github.com/kaltura/server/commit/73912965befa5b6d0aac6a746bde8565be96d81f

- api_v3/services/MediaService.php
> add check for type in media service

- batch/batches/Import/KAsyncImport.class.php
> check response code from curl request

- alpha/apps/kaltura/modules/extwidget/actions/thumbnailAction.class.php
> add serve thumbnail with thumbnail api with flavor_params_id parameter

- infra/cdl/kdl/KDLFlavor.php
New AR mode that attempts to preserve precisely the source AR. In order to avoid inter-asset visual shift phenomenon
> SUP-11599 - new AR mode

- alpha/apps/kaltura/modules/extwidget/actions/playManifestAction.class.php
> Mercury 13.0.0 ps 3201

- plugins/metadata/services/MetadataService.php
KMS-14633 - fix to index metaData on user after deleting a user . 
> KMS-14633 - modify metaData delete action.

- alpha/apps/kaltura/modules/extwidget/actions/serveFlavorAction.class.php
When entry was created on DC1 but not replicated to DC2, we should return empty JSON response. This will let ngnix vod module try and fetch it from DC1.
Example for empty JSON response:
```js
{"sequences":[{"clips":[{"type":"source","path":""}]}]}
```
> SUPPS-1191 - Serve Flavor DC Redirect Fix

- alpha/apps/kaltura/lib/model/objectfilters/UserEntryFilter.php
- alpha/lib/model/UserEntryPeer.php
- api_v3/lib/KalturaErrors.php
- api_v3/lib/types/KalturaUserEntry.php
- api_v3/lib/types/filters/KalturaUserEntryFilter.php
- api_v3/lib/types/filters/base/KalturaUserEntryBaseFilter.php
- api_v3/services/UserEntryService.php
> PLAT-7823 add params validation and partner filters to userEntry filter

- batch/batches/Import/KAsyncImport.class.php
> Revert "check response code from curl request"

- alpha/scripts/utils/apiGrep.py
when a log line matches the pattern prints all lines up to the next log line start. useful in order to grep a specific session / log lines that use print_r.
> add script for grepping api logs

- api_v3/services/LiveStreamService.php
> Revert "Update LiveStreamService.php"

- alpha/scripts/utils/apiGrep.py
use zcat | python instead of python's gzip module
> optimize grepping of gzip files

- alpha/apps/kaltura/lib/events/kEventsManager.php
can be useful in propel scripts
> add flag for disabling events

- alpha/scripts/utils/apiGrep.py
match any line, not only starting log lines
> apiGrep - add support for --match-any

- api_v3/lib/reflection/XmlClientGenerator.php
- plugins/drm/lib/api/enums/KalturaDrmSchemeName.php
> Revert "Mercury 13.0.0 client plugins"

- alpha/apps/kaltura/modules/extwidget/actions/serveFlavorAction.class.php
can be used to distribute serveFlavor paths between several mounts
> support path prefix replacement in serveFlavor

- plugins/metadata/lib/kMetadataManager.php
- plugins/search/providers/elastic_search/lib/kElasticSearchManager.php
> Mercury 13.1.0 elastic modifcations

- api_v3/web/analyticsSyncServe.php
required for calculating play time from quartile events
> analytics sync - add entry durations

- infra/chunkedEncode/KChunkedEncodeSessionManager.php
> Handle corrupted memcache Chunked Job object case

- plugins/drop_folder/admin/scripts/plugin/drop-folder-list-action.phtml
- plugins/drop_folder/batch/DropFolderWatcher/KAsyncDropFolderWatcher.class.php
- plugins/drop_folder/services/DropFolderService.php
origin/Mercury-13.2.0-PLAT-7909 fixing a bug in freeExclusiveDropFolder that re-enable disabled drop folders
> origin/Mercury-13.2.0-PLAT-7909 fixing a bug in freeExclusiveDropFolders

- api_v3/services/MediaService.php
- plugins/bulk_upload/xml/batch/BulkUploadEngineXml.php
> PLAT-7818 - Multi audio support for replacement entry

- alpha/apps/kaltura/lib/KDLWrap.php
@MosheMaorKaltura @anatolkaltura
> PLAT-7887 - support multi audio stream on entry trimming and clipping for KEA

- deployment/permissions/object.KalturaClipAttributes.ini
- deployment/updates/scripts/add_permissions/2017_08_24_add_kClip_Attribute_user_permission.php
> add permission for kclip attribute for base user

- alpha/lib/model/DeliveryProfileDynamicAttributes.php
…s before passing it to play-server
> No Plat: validate playerConfig is valid and meets Kaltura requirements before passing it to play-server

- alpha/lib/model/flavorAsset.php
> PLAT-7818 handling language and lable copy when replacing entry

- alpha/apps/kaltura/lib/batch2/kBatchManager.php
> PLAT-7953 - Audio upload fix to add the stream language correctly

- plugins/webex/WebexPlugin.php
> check if size from webex is 0 and retry the import job

- alpha/apps/kaltura/lib/kManifestRenderers.php
> fix analytics beacon error

- plugins/schedule/base/lib/api/KalturaScheduleEvent.php
- plugins/schedule/base/lib/iCal/kSchedulingICalEvent.php
> PLAT-7969 - fix ical bulk ingestion to handle [duration] field input

- plugins/schedule/base/lib/iCal/kSchedulingICalEvent.php
> Revert "PLAT-7969 - Update kSchedulingICalEvent.php"

- plugins/schedule/base/lib/iCal/kSchedulingICalEvent.php
> Revert "PLAT-7969- Update kSchedulingICalEvent.php"

- infra/general/languageCodeManager.php
- plugins/bulk_upload/xml/batch/BulkUploadEngineXml.php
- plugins/bulk_upload/xml/xml/ingestion.xsd
> Mercury 13.2.0 plat 7943

- plugins/schedule/base/lib/iCal/kSchedulingICalEvent.php
fix if condition to handle right duration format
> PLAT-7969 Update kSchedulingICalEvent.php

- alpha/apps/kaltura/lib/kManifestRenderers.php
in order to support playbackType=offline
> playManifest - allow overriding of playbackType

- alpha/apps/kaltura/lib/batch2/bcdl/kBusinessPreConvertDL.php
Forces the temp replacement assets to use enc-keys of the original assets
> PLAT-8023-FIX-Mismatch on enc-at-rest replacement

- alpha/apps/kaltura/lib/kManifestRenderers.php
1. remove kdp/html5/kwidget prefixes
2. strip cache_st
3. ignore everything after __ (can contain commit sha)
> playManifest beacon - improve clientTag parsing

- alpha/apps/kaltura/lib/batch2/kFlowManager.php
these jobs are deprecated and no longer being created
> remove code for aborting file sync import jobs

- plugins/beacon/lib/model/kBeaconCacheLayerActions.php
> Revert "No Plat: Take impersonated partnerId if one provided"

- alpha/apps/kaltura/lib/media/myFlvStreamer.class.php
- alpha/apps/kaltura/modules/keditorservices/actions/flvproviderAction.class.php
- alpha/apps/kaltura/modules/keditorservices/actions/getAllEntriesAction.class.php
- alpha/apps/kaltura/modules/partnerservices2/actions/getallentriesAction.class.php
- api_v3/services/MixingService.php
Need to check if the Data on entry (receiving from getDataPath()) also need to be encrypt
> PLAT-7961:Adopt the myFlvStreamer to FileSyncKey

- infra/storage/file_transfer_managers/sftpMgr.class.php
- plugins/content_distribution/providers/freewheel/lib/FreewheelDistributionEngine.php
- plugins/content_distribution/providers/freewheel_generic/lib/FreewheelGenericDistributionEngine.php
PHP bug details can be seen here: https://bugs.php.net/bug.php?id=73597
> PLAT-7906: Add php7 support for accessing sftp urls

- infra/general/FacebookGraphSdkUtils.php
- vendor/facebook-sdk-php-v5-customized/Facebook.php
Changing so we will use the 2.5 endpoint instead of the 2.4
> kaltura/Mercury-13.4.0-plat-8049 Changing the graph version to 2.5

- alpha/apps/kaltura/lib/KExternalErrors.class.php
- alpha/apps/kaltura/modules/extwidget/actions/embedPlaykitJsAction.class.php
Added fixes to support new syntax of client lib and fix iframe embed
> fix playkit embed

- alpha/apps/kaltura/lib/myEntryUtils.class.php
- alpha/lib/enums/BaseEntryCloneOptions.php
- api_v3/lib/types/resource/KalturaEntryResource.php
- api_v3/lib/types/resource/KalturaOperationResource.php
- api_v3/lib/types/resource/KalturaResource.php
- api_v3/services/BaseEntryService.php
- api_v3/services/MediaService.php
- plugins/metadata/lib/kMetadataObjectCopiedHandler.php
> PLAT-8083 allow including/excluding cloning metaData and flavors objects

- alpha/apps/kaltura/lib/webservices/APIErrors.class.php
- api_v3/services/MediaService.php
if flavorId is specified we will try to generate the volume map for it,
else we will try to retrieve the lowest bitrate flavor
> PLAT-7886: add optional param of flavorId to getVolumeMap action

- infra/general/FacebookGraphSdkUtils.php
- plugins/content_distribution/providers/facebook/lib/FacebookDistributionEngine.php
Ignoring place when we do create and update.
change the way we handle tags to support tagging pepole
> Plat 8089- facebook place is deprecated and updating tags

- plugins/search/providers/elastic_search/lib/kElasticSearchManager.php
> Revert "PLAT-8053: fix array to string conversion notice"

- alpha/lib/model/entry.php
- plugins/search/providers/elastic_search/config/mapping/entry_mapping.json
- plugins/search/providers/elastic_search/lib/model/enum/ESearchEntryFieldName.php
- plugins/search/providers/elastic_search/lib/model/enum/ESearchEntryOrderByFieldName.php
> Handle sorting by likes(votes), views, and entry name ASC and DSC

- plugins/content/caption/base/lib/captionManagers/srtCaptionsContentManager.php
- plugins/content/caption/base/lib/captionManagers/webVttCaptionsContentManager.php
- plugins/content/caption/base/lib/kCaptionsContentManager.php
- plugins/content/caption/base/lib/kWebVTTGenerator.php
> Revert "SUP-12232: replace \n with \r\n for webvtt ios11 support"

- alpha/apps/kaltura/lib/myEntryUtils.class.php
> KMS-15676 - clone quiz data in baseEntry->clone

- api_v3/web/analyticsSyncServe.php
add new request type for synching live entry ids
> analytics sync - add live entries

- infra/general/FacebookGraphSdkUtils.php
Origin/Mercury-13.6.0-PLAT-8144 Fixing Facebook update with tags already exists
> Origin/Mercury-13.6.0-PLAT-8144 Fixing Facebook update with tags

- alpha/apps/kaltura/modules/extservices/actions/googleoauth2Action.class.php
- plugins/content_distribution/providers/youtube/lib/YouTubeDistributionGoogleClientHelper.php
- plugins/content_distribution/providers/youtube_api/lib/YoutubeApiDistributionEngine.php
Fixing authenticate with new Youtube SDK
Reverting the youtube SDK update on our SFTP Youtube connector
> origin/mercury-13.5.0-PLAT-8171 fixing youtube SDK version update

- alpha/apps/kaltura/modules/extservices/actions/googleoauth2Action.class.php
- plugins/content_distribution/providers/youtube/lib/YouTubeDistributionGoogleClientHelper.php
- plugins/content_distribution/providers/youtube_api/lib/YoutubeApiDistributionEngine.php
We got Apache error when tried to authorize the google distribution
> Origin/mercury 13.6.0 plat 8171 fixing google distribution authenticate

- alpha/apps/kaltura/lib/reports/kKavaReportsMgr.class.php
addEndUserReportsDruidFilters depends on $partner_id
> kava bug fix

- alpha/apps/kaltura/lib/batch2/model/kConvertJobData.php
Mainly for the sake of dependent enc-at-rest jobs
> Raise urgency/priority of copy jobs

- infra/chunkedEncode/KChunkedEncode.php
Seems like it can do x265 too ...
> ChunkedEncode support for x265

- alpha/apps/kaltura/modules/extwidget/actions/embedPlaykitJsAction.class.php
last modified date should be latest date among uiConf updatedAt and bundleCreationDate
> PlaykitJX fix last modified date

- plugins/search/providers/elastic_search/lib/api/errors/KalturaESearchErrors.php
- plugins/search/providers/elastic_search/lib/api/types/KalturaESearchParams.php
- plugins/search/providers/elastic_search/lib/exceptions/kESearchException.php
- plugins/search/providers/elastic_search/lib/model/kESearchQueryParser.php
- plugins/search/providers/elastic_search/services/ESearchService.php
> PLAT-8134 - create ESearch Query (As string) Parser

- plugins/search/providers/elastic_search/lib/api/types/KalturaESearchObject.php
- plugins/search/providers/elastic_search/lib/api/types/KalturaESearchQuery.php
- plugins/search/providers/elastic_search/services/ESearchService.php
> PLAT-8134 "remove irrelevant code"

- alpha/apps/kaltura/lib/reports/kKavaBase.php
- alpha/apps/kaltura/lib/reports/kKavaReportsMgr.class.php
return region (not city) and perform strtoupper on the values
> align map overlap drill down with the old system

- VERSION.txt
> Revert "Updated version"

- plugins/integration/providers/voicebase/VoicebaseClientHelper.php
- plugins/integration/providers/voicebase/lib/KVoicebaseIntegrationEngine.class.php
> Revert "Mercury 13.2.0 tr 1682"

- alpha/lib/enums/BatchJobAppErrors.php
- plugins/scheduled_task/batch/ScheduledTaskRunner/KScheduledTaskRunner.class.php
- plugins/scheduled_task/lib/object_task_engine/KObjectTaskMailNotificationEngine.php
Adding media name to the notification email in media repurposing
> origin/Mercury-13.7.0-PLAT-8205 Add media name in notification email

- alpha/apps/kaltura/lib/reports/kKavaReportsMgr.class.php
> kava - avoid topN on non-linear metric

- admin_console/forms/PartnerConfiguration.php
Add item element to group to control columns alignment.
@NadavHarnik
> KMS-14857 - eSearch Language control

- api_v3/lib/KalturaDispatcher.php
- api_v3/lib/KalturaErrors.php
each rule contains a set of conditions, e.g. action=add, and keys, e.g. entryId, a counter is maintained per action+partner+key
> support api rate limiting

- plugins/scheduled_task/admin/forms/ConfigureSubForm.php
- plugins/scheduled_task/admin/forms/MediaRepurposingTaskDataSubForm.php
- plugins/scheduled_task/lib/api/types/object_tasks/KalturaMailNotificationObjectTask.php
- plugins/scheduled_task/lib/object_task_engine/KObjectTaskMailNotificationEngine.php
Origin/mercury 13.7.0 plat 8204 adding footer to email notification
> Origin/mercury 13.7.0 plat 8204

- alpha/apps/kaltura/modules/extwidget/actions/embedPlaykitJsAction.class.php
Add env config to be passed to player embed code(service and API urls and stat services URLs)
> Mercury 13.7.0 playKitJs

- alpha/apps/kaltura/modules/extwidget/actions/serveFlavorAction.class.php
> PLAT-8097 add new logic to matching flavors on playlist

- plugins/content/caption/search/CaptionSearchPlugin.php
- plugins/search/providers/elastic_search/config/mapping/category_mapping.json
- plugins/search/providers/elastic_search/config/mapping/entry_mapping.json
- plugins/search/providers/elastic_search/lib/elasticSearchUtils.php
- plugins/search/providers/elastic_search/lib/model/ESearchQueryAttributes.php
- plugins/search/providers/elastic_search/lib/model/items/ESearchCaptionItem.php
- plugins/search/providers/elastic_search/lib/model/items/ESearchCategoryItem.php
- plugins/search/providers/elastic_search/lib/model/items/ESearchCuePointItem.php
- plugins/search/providers/elastic_search/lib/model/items/ESearchEntryItem.php
- plugins/search/providers/elastic_search/lib/model/items/ESearchItem.php
- plugins/search/providers/elastic_search/lib/model/items/ESearchMetadataItem.php
- plugins/search/providers/elastic_search/lib/model/items/ESearchOperator.php
- plugins/search/providers/elastic_search/lib/model/items/ESearchUnifiedItem.php
- plugins/search/providers/elastic_search/lib/model/items/ESearchUserItem.php
- plugins/search/providers/elastic_search/lib/model/kESearchQueryManager.php
- plugins/search/providers/elastic_search/lib/search/kBaseSearch.php
add language support to name and description in partial search + optimize partial query for captions
> KMS-14857: add language support to name and description in partial search

- infra/chunkedEncode/KChunkedEncodeUtils.php
3min chunks for frameSize<=360 ( >480p ⇒ 1min, >360p ⇒ 2min, <=360p ⇒ 3min)
Check for log file existence
> Chunked Encoding - fixes and updates

- infra/chunkedEncode/KChunkedEncodeSessionManager.php
Improved ‘job-skip’ detection and job retry logic
Fixed job retry on FetchJob failure
Concurrency statistics
> Chunked Encoding - Improved ‘job-skip’ detection

- infra/chunkedEncode/KChunkedEncodeMemcacheWrap.php
FetchJob - 10 internal retries
FetchNextJob - 
- More strict handling of ‘unavailable’ jobs
- No local ‘readIndex’ increment
- No ‘readIndexTmp’
- Better/more general ‘semaphoreToken
‘setReadIndex’ with internal retries
> Chunked Encoding - improved FetchNextJob

- plugins/search/providers/elastic_search/lib/model/items/ESearchCaptionItem.php
- plugins/search/providers/elastic_search/lib/model/items/ESearchCuePointItem.php
- plugins/search/providers/elastic_search/lib/model/items/ESearchEntryItem.php
- plugins/search/providers/elastic_search/lib/model/items/ESearchItem.php
- plugins/search/providers/elastic_search/lib/model/kESearchQueryManager.php
Adding score boost factor for some search fields
> Origin/mercury 13.7.0 kms 14832 esearch score based on field

- deployment/base/scripts/init_data/03.UserRole.ini
- release-notes.md
> NO-PLAT: add live_entry_update permission to webcast

- alpha/lib/model/DeliveryProfileVodPackagerDash.php
> Revert "Mercury 13.7.0 plat 8281"

- infra/chunkedEncode/KBaseChunkedEncodeSessionManager.php
Added log for audio stream
On chunk failure, partially dump the conversion log into the main log
> Improved logging

- infra/chunkedEncode/KChunkedEncode.php
- Fix: Video only sources
- Fix: Misbehavior with some types of very long sources
- Add: Logging improvement
- Add: Enc-at-rest
> Several fixes and additions

- release-notes.md
> Mercury-13.8.0-PLAT-8090 Adding eSearch highlight

- plugins/search/providers/elastic_search/lib/model/items/ESearchMetadataItem.php
> Mercury-13.8.0-PLAT-8305 eSearch failing on medtadata prefix query

- alpha/apps/kaltura/lib/reports/kDruidBase.php
- alpha/apps/kaltura/lib/reports/kKavaReportsMgr.class.php
- alpha/apps/kaltura/lib/reports/myReportsMgr.class.php
- api_v3/services/ReportService.php
- use listFiltered when doing topN on a multi value dimension
- support report on multiple dimensions (e.g. entryId + userId)
- support enrichment of multiple fields (entry name + user id)
- add categoriesIds & countries filter
- add additional enrichment functions (quoted entry name, entry name + user id)
- disable entitlement when translating filter category name
> kava - core enhancements to support custom reports

- alpha/apps/kaltura/lib/myEntryUtils.class.php
> Revert "PLAT-8273: fix Code review comments for croping in the packager"

- alpha/apps/kaltura/lib/myEntryUtils.class.php
> Revert "Revert "PLAT-8273: fix Code review comments for croping in the packager""

- alpha/apps/kaltura/lib/model/objectfilters/appTokenFilter.class.php
- api_v3/lib/types/filters/base/KalturaAppTokenBaseFilter.php
- api_v3/services/AppTokenService.php
> PLAT-8349 - app token list filter fix

- alpha/apps/kaltura/lib/batch2/bcdl/kBusinessPreConvertDL.php
- batch/batches/CaptureThumb/KAsyncCaptureThumb.class.php
- batch/batches/PostConvert/KAsyncPostConvert.class.php
- infra/media/thumbnailMaker/KBaseThumbnailMaker.php
- infra/media/thumbnailMaker/KFFMpegThumbnailMaker.php
Merge Mercury 13.6.0 sup 11979 thumbs deinterlace into Mercury 13.9.0 sup 11979 thumbs deinterlace
> Mercury 13.6.0 sup 11979 thumbs deinterlace

- alpha/lib/model/DeliveryProfileLive.php
- alpha/lib/model/LiveEntry.php
> Revert "Mercury 13.8.0 plat 8313"

- infra/cdl/kdl/KDLMediaDataSet.php
prevent duplicate codec/format names
> Fix conditional-conv-prof crashes 3

- alpha/lib/model/DeliveryProfileLive.php
- alpha/lib/model/LiveEntry.php
> Revert "Revert "Mercury 13.8.0 plat 8313""

- alpha/apps/kaltura/lib/reports/kKavaLiveReportsMgr.class.php
> kava live - return the buffer time in min

- plugins/search/providers/elastic_search/config/mapping/entry_mapping.json
- plugins/search/providers/elastic_search/lib/api/errors/KalturaESearchErrors.php
- plugins/search/providers/elastic_search/lib/api/types/order/items/KalturaESearchMetadataOrderByItem.php
- plugins/search/providers/elastic_search/lib/exceptions/kESearchException.php
- plugins/search/providers/elastic_search/lib/model/enum/ESearchMetadataFieldName.php
- plugins/search/providers/elastic_search/lib/model/enum/ESearchMetadataOrderByFieldName.php
- plugins/search/providers/elastic_search/lib/model/items/ESearchCaptionItem.php
- plugins/search/providers/elastic_search/lib/model/items/ESearchCuePointItem.php
- plugins/search/providers/elastic_search/lib/model/items/ESearchMetadataItem.php
- plugins/search/providers/elastic_search/lib/model/order/items/ESearchMetadataOrderByItem.php
- plugins/search/providers/elastic_search/lib/model/order/items/ESearchOrderByItem.php
- plugins/search/providers/elastic_search/lib/model/search/kBaseSearch.php
- plugins/search/providers/elastic_search/services/ESearchService.php
- also refactor to use const field names in ESearchCaptionItem, ESearchCuePointItem, ESearchMetadataItem
> PLAT-8314: add ability to sort search results by a custom metadata field

- plugins/integration/providers/voicebase/VoicebaseClientHelper.php
- plugins/integration/providers/voicebase/lib/KVoicebaseIntegrationEngine.class.php
> Revert "merge TR-1682"

- plugins/search/providers/elastic_search/lib/model/items/ESearchMetadataItem.php
> Mercury 13.9.0 elastic integration x path handling

- api_v3/lib/KalturaDispatcher.php
- add ability to limit by partner id (_partnerId=xxx)
- make _key optional
> api rate limit enhancements

- alpha/apps/kaltura/modules/extwidget/actions/serveFlavorAction.class.php
> Revert of PLAT-8354: caption for  SUP-13040 - HOTFIX

- batch/batches/Import/KAsyncImport.class.php
- infra/general/KCurlWrapper.class.php
> Revert "Mercury 13.8.0 plat 8307"

- plugins/search/providers/elastic_search/lib/model/items/ESearchMetadataItem.php
- plugins/search/providers/elastic_search/lib/model/items/ESearchNestedObjectItem.php
- plugins/search/providers/elastic_search/lib/model/kESearchCoreAdapter.php
> handle xpath delimiter

- api_v3/lib/KalturaJsonSerializer.php
> fix json serializer

- alpha/apps/kaltura/lib/model/objectfilters/entryFilter.class.php
- alpha/lib/model/entry.php
- api_v3/lib/types/entry/filters/KalturaMediaEntryFilter.php
- plugins/search/providers/sphinx_search/lib/SphinxEntryCriteria.php
> Revert "PLAT-8296: remove sequence filter"

- alpha/apps/kaltura/lib/model/objectfilters/entryFilter.class.php
- alpha/apps/kaltura/lib/myEntryUtils.class.php
- alpha/apps/kaltura/modules/extwidget/actions/serveFlavorAction.class.php
- alpha/lib/model/entry.php
- api_v3/lib/types/entry/KalturaMediaEntry.php
- api_v3/lib/types/entry/filters/KalturaMediaEntryFilter.php
- configurations/admin.template.ini
- plugins/content_distribution/providers/doubleclick/lib/DoubleClickFeed.php
- plugins/content_distribution/providers/doubleclick/services/DoubleClickService.php
- plugins/search/providers/sphinx_search/lib/SphinxEntryCriteria.php
> Revert "PLAT-8361: update the timing on DFP syndication feed according to bump..."

- alpha/apps/kaltura/lib/myPartnerUtils.class.php
> Revert "PLAT-8311: set partner group to null when adding to criteria on entry…"

- api_v3/services/BaseEntryService.php
> Revert "SUP-12639: throw api error on replacement when source flavor not found"

- alpha/apps/kaltura/lib/reports/kKavaReportsMgr.class.php
instead of subtracting the offset in timestampToDateId / MonthId, format
the date in the requested time zone.
unfortunately:
1. we can't use an offset to specify the timezone (doesn't work in php 5.3)
2. timezone_name_from_abbr fails on most offsets
3. timezone_abbreviations_list provides weird results - multiple offsets
for a given timezone
so we use a static mapping table. the chosen timezones exist both in php
and in joda, but we still use Etc/GMT relative timezones, since druid
sometimes fails with 'real' timezones.
> kava timezone fixes

- plugins/scheduled_task/lib/object_task_engine/KObjectTaskMailNotificationEngine.php
Merge the hot fix from 13.10.0 to 13.11.0
> Mercury-13.11.0-PLAT-8442 MR email bug

- alpha/apps/kaltura/lib/kPlaybackContextDataHelper.php
> PLAT-8343 support hevc (h265) flavors in getPlaybackContext

- alpha/lib/model/entry.php
- plugins/search/providers/elastic_search/config/mapping/entry_mapping.json
- plugins/search/providers/elastic_search/lib/api/enum/KalturaESearchEntryFieldName.php
- plugins/search/providers/elastic_search/lib/api/types/items/entry/KalturaESearchEntryItem.php
- plugins/search/providers/elastic_search/lib/model/enum/ESearchEntryFieldName.php
- plugins/search/providers/elastic_search/lib/model/items/ESearchEntryItem.php
Mercury-13.11.0-PLAT-8154 Adding user names to eSearch index
> Mercury-13.11.0-PLAT-8154 Adding user names to eSearch index

- admin_console/configs/lang/en.php
- admin_console/web/css/global.css
- plugins/reach/ReachPlugin.php
- plugins/reach/admin/CatalogItemConfigureAction.php
- plugins/reach/admin/CatalogItemListAction.php
- plugins/reach/admin/CatalogItemSetStatusAction.php
- plugins/reach/admin/VendorProfileConfigureAction.php
- plugins/reach/admin/VendorProfileListAction.php
- plugins/reach/admin/VendorProfileSetStatusAction.php
- plugins/reach/admin/forms/CreateVendorProfile.php
- plugins/reach/admin/forms/RulesSubForm.php
- plugins/reach/admin/forms/VendorProfileConfigure.php
- plugins/reach/admin/forms/VendorProfileFilter.php
- plugins/reach/admin/scripts/plugin/catalog-item-list-action.phtml
- plugins/reach/admin/scripts/plugin/vendor-profile-configure-action.phtml
- plugins/reach/admin/scripts/plugin/vendor-profile-list-action.phtml
- plugins/reach/admin/scripts/rule-sub-form.phtml
- plugins/reach/admin/scripts/rules-sub-form.phtml
- plugins/reach/lib/api/arrays/KalturaVendorCatalogItemListResponse.php
- plugins/reach/lib/api/arrays/KalturaVendorProfielAdminRuleArray.php
- plugins/reach/lib/api/data/KalturaVendorProfileRuleCategoryEntryAdded.php
- plugins/reach/lib/api/data/KalturaVendorProfileRuleEntryAdded.php
- plugins/reach/lib/api/data/KalturaVendorProfileRuleOption.php
- plugins/reach/lib/api/data/VendorProfile/KalturaVendorProfile.php
- plugins/reach/lib/api/data/VendorProfile/KalturaVendorProfileAdminRule.php
- plugins/reach/lib/model/VendorProfile/kVendorProfileAdminRule.php
- plugins/reach/lib/model/enums/VendorProfileRuleOption.php
- plugins/reach/lib/model/enums/VendorProfileType.php
> Reach Vendor Profile Admin Console initial draft

- admin_console/configs/lang/en.php
- plugins/reach/admin/CatalogItemConfigureAction.php
- plugins/reach/admin/VendorProfileConfigureAction.php
- plugins/reach/admin/scripts/plugin/vendor-profile-list-action.phtml
> Mercury 13.9.0 reach vendro profile fix catalog item clone

- alpha/scripts/dwh/updateEntryPlaysViews.php
change array style after code review
> KMS-16500: update plays and views in elastic

- plugins/search/providers/elastic_search/lib/model/ESearchHighlightHelper.php
> Mercury-13.12.0-PLAT-8488 Duplicate result from eSearch Highlight

- alpha/apps/kaltura/lib/kPlaybackContextDataHelper.php
added to handle the case where ids equals to {}
> PLAT-8493: check if delivery profile ids var is empty instead of is null

- plugins/scheduled_task/batch/ScheduledTaskRunner/KScheduledTaskRunner.class.php
- plugins/scheduled_task/lib/object_task_engine/KObjectTaskConvertEntryFlavorsEngine.php
- plugins/scheduled_task/lib/object_task_engine/KObjectTaskDeleteEntryFlavorsEngine.php
- plugins/scheduled_task/lib/object_task_engine/KObjectTaskDeleteLocalContentEngine.php
- plugins/scheduled_task/lib/object_task_engine/KObjectTaskModifyCategoriesEngine.php
- plugins/scheduled_task/lib/object_task_engine/KObjectTaskModifyEntryEngine.php
- plugins/scheduled_task/lib/object_task_engine/KObjectTaskStorageExportEngine.php
- plugins/scheduled_task/plugins/content_distribution/lib/object_task_engine/KObjectTaskDistributeEngine.php
- plugins/scheduled_task/plugins/event_notification/lib/object_task_engine/KObjectTaskDispatchEventNotificationEngine.php
- plugins/scheduled_task/plugins/metadata/lib/object_task_engine/KObjectTaskExecuteMetadataXsltEngine.php
Adding a try catch for get user when getting the email
Removing impressionist and unimpersonate partner from each engine and only do it from a central location
> Mercury-13.12.0-PLAT-8503 - media re purposing failures

- plugins/integration/providers/voicebase/lib/kVoicebaseFlowManager.php
> Revert "TR-2059"

- plugins/cue_points/quiz/lib/api/KalturaQuestionCuePoint.php
- plugins/cue_points/quiz/lib/api/enums/KalturaQuestionType.php
- plugins/cue_points/quiz/lib/model/QuestionCuePoint.php
- plugins/cue_points/quiz/lib/model/enums/QuestionType.php
Plat 8456 - Add Question Type enum to Question Cue Point
> Plat-8456: Add new field(question type) to the Question cue point element

- alpha/apps/kaltura/lib/reports/kKavaReportsMgr.class.php
- support multiple enrichment functions
- support passing a context param to the enrichment function
> kava enrichment enhancements for custom reports

- alpha/apps/kaltura/lib/myDbHelper.class.php
avoid connecting to both slaves in a single session
> db slave stickiness

- plugins/search/providers/elastic_search/lib/model/items/ESearchBaseOperator.php
- plugins/search/providers/elastic_search/lib/model/items/ESearchCategoryItem.php
- plugins/search/providers/elastic_search/lib/model/items/ESearchEntryItem.php
- plugins/search/providers/elastic_search/lib/model/items/ESearchItem.php
- plugins/search/providers/elastic_search/lib/model/items/ESearchUserItem.php
- plugins/search/providers/elastic_search/lib/model/search/ESearchEntryQueryFilterAttributes.php
- plugins/search/providers/elastic_search/lib/model/search/kESearchQueryManager.php
- plugins/search/providers/elastic_search/lib/model/search/queries/kESearchBaseFieldQuery.php
- plugins/search/providers/elastic_search/lib/model/search/queries/kESearchBaseQuery.php
if the operator is AND and the field has no boost factor we can move it to filter context to skip score calculation and reduce query time
> PLAT-8165: optimize elastic queries

- alpha/apps/kaltura/modules/extwidget/actions/embedPlaykitJsAction.class.php
> Change return after 304 to KExternalErrors::dieGracefully();

- alpha/apps/kaltura/lib/reports/kDruidBase.php
- alpha/apps/kaltura/lib/reports/kKavaBase.php
- alpha/apps/kaltura/lib/reports/kKavaLiveReportsMgr.class.php
- alpha/apps/kaltura/lib/reports/kKavaReportsMgr.class.php
- api_v3/services/ReportService.php
also refactored parts of the code + fixed style issues -
- use functions from kDruidBase to build queries
- sort report params - dims, metrics etc.
- remove the need for $simple_metrics
- use single quote where possible
> kava - add top contributors report

- deployment/base/sql/01.kaltura_ce_tables.sql
Following https://github.com/kaltura/server/pull/6754/files
> Drop unused indexes

- infra/chunkedEncode/KChunkedEncode.php
Requires patched ffmpeg 3.2 patch 5
Otherwise the code will fail
> PLAT-8620 - HF - fix CE vs uDrm mismatch

- plugins/reach/services/EntryVendorTaskService.php
> add entry vendor task abort reason

- alpha/scripts/utils/addPartnerToCielo24.php
- plugins/integration/providers/cielo24/Cielo24ClientHelper.php
- plugins/integration/providers/cielo24/Cielo24Options.php
- plugins/integration/providers/cielo24/lib/KCielo24IntegrationEngine.class.php
- plugins/integration/providers/cielo24/lib/api/KalturaCielo24Errors.php
- plugins/integration/providers/cielo24/lib/api/KalturaCielo24JobProviderData.php
- plugins/integration/providers/cielo24/lib/model/kCielo24JobProviderData.php
> Revert "Mercury 13.14.0 tr 2095"

- plugins/metadata/lib/kMetadataManager.php
- plugins/search/providers/elastic_search/lib/kElasticSearchManager.php
fix the case where long metadata fields where not indexed
> KMS-17045: fix metadata field max length

- plugins/reach/admin/forms/CatalogItemConfigure.php
- plugins/reach/admin/forms/DictionariesSubForm.php
- plugins/reach/admin/forms/RulesSubForm.php
- plugins/reach/admin/forms/VendorProfileConfigure.php
- plugins/reach/admin/forms/VendorProfileFilter.php
- plugins/reach/admin/scripts/dictionaries-sub-form.phtml
- plugins/reach/admin/scripts/dictionary-sub-form.phtml
- plugins/reach/admin/scripts/plugin/vendor-profile-configure-action.phtml
- plugins/reach/admin/scripts/plugin/vendor-profile-list-action.phtml
- plugins/reach/admin/scripts/rules-sub-form.phtml
- plugins/reach/errors/KalturaReachErrors.php
- plugins/reach/lib/api/arrays/KalturaDictionaryArray.php
- plugins/reach/lib/api/data/KalturaDictionary.php
- plugins/reach/lib/api/data/VendorProfile/KalturaVendorProfile.php
- plugins/reach/lib/api/data/entryVendorTaks/KalturaEntryVendorTask.php
- plugins/reach/lib/kReachManager.php
- plugins/reach/lib/model/EntryVendorTask.php
- plugins/reach/lib/model/VendorProfile.php
- plugins/reach/lib/model/filters/EntryVendorTaskFilter.php
- plugins/reach/lib/model/kDictionary.php
> Reach vendor profile Glassory (Dictionary) support

- configurations/base.ini
Version including fix for PLAT-8646
> LiveDashboard version update

- alpha/apps/kaltura/lib/myPlaylistUtils.class.php
- alpha/apps/kaltura/lib/request/kSessionBase.class.php
- alpha/lib/model/asset.php
- deployment/permissions/service.caption.captionasset.ini
- plugins/content/caption/base/CaptionPlugin.php
- plugins/content/caption/base/lib/api/enums/KalturaCaptionAssetStatus.php
- plugins/content/caption/base/services/CaptionAssetService.php
- plugins/content/caption/search/lib/kCaptionSearchFlowManager.php
- plugins/reach/lib/api/data/entryVendorTaks/KalturaEntryVendorTask.php
- plugins/reach/lib/kReachUtils.php
> captions handling before playing

- plugins/reach/errors/KalturaReachErrors.php
- plugins/reach/services/EntryVendorTaskService.php
> entry vendor task abort

- tests/standAloneClient/entryCreatedFireBaseHttpNotification.xml
Adding a new template for sending a notification to google Firebase when adding an entry to a category
> Mercury-13.15.0-PLAT-8645-CategoryEntry-Added-Firebase template

- tests/standAloneClient/entryAddedToCategoryFireBaseHttpNotification.xml
Adding partner id to the json data
> Mercury-13.15.0-PLAT-8645 entry add to category fire base template

- configurations/batch/batch.ini.template
under [KAsyncExtractMedia : JobHandlerWorker]
Read in batch/batches/ExtractMedia/KAsyncExtractMedia.class.php:
calculateMediaFileComplexity()
> Added missing params.ffmpegCmd directive

- alpha/apps/kaltura/lib/reports/kDruidBase.php
can be significant for reports that require multiple queries.
also - enabled gzip compression of the response
> kava - druid connection keep alive

- alpha/scripts/utils/apiGrep.py
need to forward the param when spawning a child process
> api grep - fix ignore case

- plugins/cue_points/quiz/lib/api/KalturaQuestionCuePoint.php
- plugins/cue_points/quiz/lib/model/QuestionCuePoint.php
- plugins/cue_points/quiz/lib/model/QuizUserEntry.php
> PLAT-8695 allow excluding questions from score

- deployment/permissions/service.reach.reachProfile.ini
- deployment/permissions/service.reach.vendorCatalogItem.ini
- deployment/updates/scripts/add_permissions/2017_11_20_add_reach_permissions.php
- deployment/updates/scripts/add_permissions/2017_11_20_add_reach_vendor_role_and_permissions.php
> permissions

- plugins/search/providers/elastic_search/lib/api/enum/KalturaESearchCategoryOrderByFieldName.php
- plugins/search/providers/elastic_search/lib/api/types/order/items/KalturaESearchCategoryOrderByItem.php
- plugins/search/providers/elastic_search/lib/model/enum/ESearchCategoryOrderByFieldName.php
add order by category name, members count, entries count
> PLAT-8705: add order by fields to category search

- deployment/permissions/partner.-2.ini
- deployment/permissions/service.reach.reachProfile.ini
- plugins/reach/lib/model/ReachProfile.php
- plugins/reach/services/ReachProfileService.php
> reset credit

- plugins/content_distribution/providers/youtube_api/lib/YoutubeApiDistributionEngine.php
Mercury-13.16.0-SUP-13294 Youtube Video transcoding on youtube has timed out
> Mercury-13.16.0-supp-13294 adding log to processed Timeout

- plugins/scheduled_task/batch/ScheduledTaskBatchHelper.php
- plugins/scheduled_task/batch/ScheduledTaskDryRunner/KScheduledTaskDryRunner.class.php
> Mercury-13.16.0-PLAT-8691 - Media re purposing dry run refactor

- plugins/scheduled_task/batch/ScheduledTaskDryRunner/KScheduledTaskDryRunner.class.php
fixing duplicates in MR dry run
> Mercury-13.16.0-PLAT-8691- MR dry run refactor

- release-notes.md
Updating process timeout release notes
> Mercury-13.16.0-sup-13294 - youtube api distribution

- alpha/apps/kaltura/lib/reports/kKavaBase.php
- alpha/apps/kaltura/lib/reports/kKavaReportsMgr.class.php
- api_v3/services/ReportService.php
supported only for user_usage/specific_user_usage reports.
also - updated entry lifecycle event types
> kava - add getBaseTotal action

- api_v3/services/PlaylistService.php
- api_v3/services/SearchService.php
@NadavHarnik 
the fix was done since we are splitting sphinx and the actions will not be handled anymore (since they have partner_in (0,partner_id)
> PLAT-8472 - deprecate actions

- plugins/content_distribution/batch/Distribute/engines/DistributionEngine.php
- plugins/content_distribution/providers/example/lib/ExampleDistributionEngine.php
- plugins/content_distribution/providers/facebook/lib/FacebookDistributionEngine.php
- plugins/content_distribution/providers/ftp/lib/FtpDistributionEngine.php
- plugins/content_distribution/providers/unicorn/lib/UnicornDistributionEngine.php
> distribution fix to work with encrypted files

- alpha/lib/model/LiveEntry.php
- alpha/lib/model/LiveStreamEntry.php
Fixing how we retrieve apple http live stream configuration
> Mercury-13.17.0-SUP-13039 Playing apple http with non kaltura live

- api_v3/services/UserService.php
Also added @throws annotations
> exportToCsvAction: KalturaUserFilter $filter can be null

- alpha/apps/kaltura/lib/reports/kKavaReportsMgr.class.php
- add storage aggregated monthly to getTotal on partner/var usage
- add peak storage report (used by varconsole.getPartnerUsage)
> kava - usage reports touch ups

- deployment/permissions/service.fileasset.ini
- deployment/updates/scripts/add_permissions/2018_04_03_update_file_asset_permission.php
> PLAT-8708 add permissions to fileAsset service

- plugins/search/providers/sphinx_search/lib/kSphinxSearchManager.php
> PLAT-8735 skip sphinx for specific partners for specific actions.

- plugins/reach/errors/KalturaReachErrors.php
- plugins/reach/lib/kReachUtils.php
- plugins/reach/lib/model/kTimeRangeVendorCredit.php
- plugins/reach/lib/model/kVendorCredit.php
- plugins/reach/services/EntryVendorTaskService.php
> PLAT-8766 - valid credit dates before adding entry vendor task

- api_v3/lib/KalturaEntryService.php
- api_v3/services/BaseEntryService.php
- api_v3/services/PlaylistService.php
> PLAT-8311 revert

- plugins/reach/admin/ReachProfileConfigureAction.php
- plugins/reach/admin/forms/ReachProfileConfigure.php
- plugins/reach/admin/scripts/plugin/reach-profile-list-action.phtml
- plugins/reach/errors/KalturaReachErrors.php
- plugins/reach/lib/api/data/KalturaBaseVendorCredit.php
- plugins/reach/lib/api/data/KalturaReoccurringVendorCredit.php
- plugins/reach/lib/api/data/KalturaTimeRangeVendorCredit.php
- plugins/reach/lib/api/data/KalturaUnlimitedVendorCredit.php
- plugins/reach/lib/api/data/ReachProfile/KalturaReachProfile.php
- plugins/reach/lib/model/kTimeRangeVendorCredit.php
- plugins/reach/services/ReachProfileService.php
> PLAT-8765 - credit fixes

- alpha/apps/kaltura/lib/reports/kKavaBase.php
- alpha/apps/kaltura/lib/reports/kKavaReportsMgr.class.php
- plugins/var_console/services/VarConsoleService.php
- add vpaas report to kava
- support kava in varConsole.getPartnerUsage
> Mercury 13.18.0 kava vpaas report

- alpha/apps/kaltura/lib/clipconcat/kClipManager.php
fix email issue in post convert
> Mercury 13.15.0 plat 8651 chop and slice

- alpha/apps/kaltura/lib/myPartnerUtils.class.php
- alpha/apps/kaltura/lib/reports/kKavaReportsMgr.class.php
- alpha/apps/kaltura/modules/system/actions/partnerBillingAction.class.php
- alpha/apps/kaltura/modules/system/actions/viewPartnerTypesAction.class.php
- alpha/apps/kaltura/modules/system/actions/viewPartnersAAction.class.php
- api_v3/services/ReportService.php
- plugins/admin_console/system_partner/services/SystemPartnerService.php
- plugins/var_console/services/VarConsoleService.php
have kava route the request to myReportsMgr if it doesn't support the report.
also added partner_bandwidth_usage report
> replace myReportsMgr calls with kava

- alpha/lib/model/DeliveryProfileAkamaiHttp.php
In case file ext is empty try retrieve format from container format element
fix for +1.8 GB files, akamai delivery profile
> SUP-13945, get file extension from container format element

- plugins/webexDropFolderPlugin/batch/KWebexDropFolderEngine.php
Fixing a bug where handling the result as XML list response instead of array
> Mercury-13.18.0-PLAT-8809 fixing bug with recording

- alpha/lib/model/categoryKuser.php
- plugins/search/providers/elastic_search/lib/api/enum/KalturaESearchCategoryFieldName.php
- plugins/search/providers/elastic_search/lib/api/enum/KalturaESearchCategoryUserFieldName.php
- plugins/search/providers/elastic_search/lib/api/types/items/category/KalturaESearchCategoryItem.php
- plugins/search/providers/elastic_search/lib/api/types/items/category/KalturaESearchCategoryUserItem.php
- plugins/search/providers/elastic_search/lib/elasticSearchUtils.php
- plugins/search/providers/elastic_search/lib/entitlement/contributors/entry/kElasticUserCategoryEntryEntitlementDecorator.php
- plugins/search/providers/elastic_search/lib/model/enum/ESearchCategoryUserFieldName.php
- plugins/search/providers/elastic_search/lib/model/items/ESearchCategoryItem.php
- plugins/search/providers/elastic_search/lib/model/items/ESearchCategoryUserItem.php
search category by userId and permission level/permission name
> PLAT-8785: add categoryUserItem to categorySearch

- release-notes.md
> Mercury-13.18.0-PLAT-8732 - Make new testing webex account to work

- plugins/reach/admin/PartnerCatalogItemConfigureAction.php
- plugins/reach/admin/scripts/plugin/catalog-item-list-action.phtml
- plugins/reach/admin/scripts/plugin/partner-catalog-item-configure-action.phtml
- plugins/reach/admin/scripts/plugin/partner-catalog-item-list-action.phtml
> Admin Console fixes - remove warnings in logs

- plugins/reach/errors/KalturaReachErrors.php
- plugins/reach/services/EntryVendorTaskService.php
> Mercury 13.9.0 reach plat 8810

- plugins/content_distribution/providers/ftp/lib/FtpDistributionEngine.php
> SUP-14139 FtpDistributionEngine-fix

- plugins/reach/lib/kReachManager.php
> Fix duplicate save when adding entryVendorTask via add action

- plugins/content_distribution/providers/ftp/lib/FtpDistributionEngine.php
> PLAT-8828 - ftp fix

- configurations/base.ini
> SUP-13826 : add ogg audio file extension to supported types

- alpha/scripts/utils/createDropFolderFilesFromWebex.php
- alpha/scripts/utils/deleteWebexFiles.php
- alpha/scripts/utils/listWebexFiles.php
- infra/general/KCurlWrapper.class.php
- infra/general/webexWrapper.php
- plugins/drop_folder/batch/Engine/KDropFolderEngine.php
- plugins/webex/WebexPlugin.php
- plugins/webexDropFolderPlugin/batch/KWebexDropFolderEngine.php
- plugins/webexDropFolderPlugin/lib/model/data/kWebexHandleFilesResult.php
- vendor/webex/xml/WebexXmlClient.class.php
Adding a script to add dropFolder files from webex
Fixing bugs in the webex drop folder engine
> Mercury 13.18.0 sup 14047 webex drop folder transfer rate

- alpha/scripts/utils/createDropFolderFilesFromWebex.php
- plugins/webexDropFolderPlugin/batch/KWebexDropFolderEngine.php
- plugins/webexDropFolderPlugin/lib/model/data/kWebexHandleFilesResult.php
improving the createDropFolderFilesFromWebex script
> Mercury-13.19.0-sup-14047 webex script

- alpha/scripts/utils/createDropFolderFilesFromWebex.php
> Mercury-13.19.0-sup-14047 fix

- admin_console/forms/Delivery/UrlTokenizerAkamaiSecureHd.php
- alpha/apps/kaltura/lib/storage/urlTokenizers/kAkamaiSecureHDUrlTokenizer.php
- alpha/apps/kaltura/lib/storage/urlTokenizers/kCloudFrontUrlTokenizer.php
- alpha/apps/kaltura/lib/storage/urlTokenizers/kUrlTokenizer.php
Ad option for ip tokenization to the Akamai Tokenizer
> PSVAMB-3002

- plugins/drm/providers/widevine/batch/Convert/OperationEngines/KWidevineOperationEngine.php
@david-winder-kaltura 
@noam-arad 
since we have few failures per month in avg we can retry on all failures.
> SUP-14151 - fix retry on widevine packager failure

- alpha/lib/model/syndicationFeed.php
- api_v3/lib/types/syndicationFeed/KalturaITunesSyndicationFeed.php
> PLAT-8543 - itunes syndication feed

- alpha/scripts/utils/createDropFolderFilesFromWebex.php
- alpha/scripts/utils/deleteWebexFiles.php
- alpha/scripts/utils/listWebexFiles.php
- infra/general/webexWrapper.php
- plugins/webexDropFolderPlugin/batch/KWebexDropFolderEngine.php
Changing our delete from recycle bin logic to search the entry by name instead of create date as the create date is changing when the record get deleted
> Mercury-13.19.0-SUP-14278 Deleting files in Webex recycle bin

- alpha/lib/data/resource/kUrlResource.php
current doc created confusion with users, updating to be clearer.
> updated the docs about forceAsyncDownload

- alpha/apps/kaltura/modules/kmcng/actions/kmcngAction.class.php
> PLAT-8844 kmcng fix

- api_v3/web/analyticsSyncServe.php
- kuser id
- source type
- media type
also, replace the existing duration + isLive sync with a single sync for all entry fields
> analytics sync - add additional entry fields

- api_v3/lib/types/resource/KalturaAssetResource.php
- plugins/content/caption/base/services/CaptionAssetService.php
> PLAT-8880 increment entry version on caption update

- tests/standAloneClient/partnerAddedMediaSpaceHttpNotification.xml
Add 10 minutes tolerance and fix no partner ID in md5 signature
> PLAT 7514  add 10 minutes tolerance and fix no partner ID in md5 sig

- alpha/apps/kaltura/lib/kManifestRenderers.php
Replace delivery code in redirect headers of manifest
> Replace {deliveryCode}

- deployment/updates/scripts/2018_01_29_deploy_reach_notifications.php
- deployment/updates/scripts/2018_01_29_deploy_reach_vendor_related_response_profiles.php
- plugins/reach/admin/PartnerCatalogItemConfigureAction.php
> Reach plugin verification on template deployment

- plugins/scheduled_task/batch/ScheduledTaskRunner/KScheduledTaskRunner.class.php
- plugins/scheduled_task/lib/processors/KMediaRepurposingProcessor.php
Moving static field that wasn't moved in the merge
> Mercury-13.20.0-PLAT-8958-mergeFix

- plugins/content_distribution/providers/youtube/lib/feed/YouTubeDistributionCsvFeedHelper.php
> PLAT-8583 handle caption language

- infra/chunkedEncode/KChunkedEncode.php
prevent unintentional language setting in CE flow for aud/vid assets
otherwise the player fails to handle properly multi lingual use cases
> SUP-14595-prevent unintentional lang setting in CE

- infra/storage/kFileBase.php
- plugins/content_distribution/providers/youtube/lib/YouTubeDistributionRightsFeedEngine.php
- plugins/content_distribution/providers/youtube/lib/status_parser/YouTubeDistributionCsvParser.php
> Naos 14.0.0 plat 8583

- alpha/scripts/utils/getWorkersStatus.php
Plat-8829-Fix Production Issues with Corrupted INI files  and outputBuffer for multiple files
> Plat-8829-Fix Production Issues with Corrupted Ini files  and OB

- alpha/apps/kaltura/lib/reports/kKavaReportsMgr.class.php
- plugins/metadata/lib/kMetadataKavaUtils.php
- the category ids + names of the entry
- custom metadata fields
> kava - add more custom reports enrichment funcs

- alpha/apps/kaltura/lib/reports/kKavaReportsMgr.class.php
1. use FETCH_NUM in genericQueryEnrich instead of FETCH_ASSOC - enables selecting expressions (e.g. LENGTH_IN_MSECS/1000)
2. changed the default enrichment input to be the first output field - this will make setting 'input' often unneeded
> kava - enrichment improvements

- plugins/search/providers/elastic_search/config/mapping/category_mapping.json
- plugins/search/providers/elastic_search/config/mapping/entry_mapping.json
- plugins/search/providers/elastic_search/config/mapping/kuser_mapping.json
adding different log levels for easier grepping
> PLAT-8761: eSearch - add slow log to mapping

- alpha/apps/kaltura/lib/clipconcat/kClipManager.php
fade in \out for single clip effects
> Commit fade in \out for single clip

- alpha/apps/kaltura/lib/reports/kKavaReportsMgr.class.php
> kava - add D modifier to regex

- alpha/config/kConf.php
- infra/general/KCurlWrapper.class.php
- plugins/event_notification/providers/http/lib/KDispatchHttpNotificationEngine.class.php
> PLAT-8976 - Identifying internal urls on curl calls

- alpha/lib/model/entry.php
> SUP-14641 modify thumb url to have the correct version

- alpha/apps/kaltura/modules/extwidget/actions/playManifestAction.class.php
When the format is url/download
> Naos-14.1.0-PLAT-9002 handling specific playManifest delivery profile with remote storage 

- alpha/lib/model/UserLoginDataPeer.php
skip the update if the login data was updated in the last 5 seconds
> limit the number of last_login_pid updates

- alpha/apps/kaltura/lib/reports/kDruidBase.php
gets printed to the request log on the broker
> kava - add comment on druid queries

- alpha/apps/kaltura/lib/reports/kKavaReportsMgr.class.php
1. added metrics - play time/buffer time from view events
2. support passing from_date/to_date instead of from_day/to_day
> kava - custom reports supportive features

- plugins/scheduled_task/batch/ScheduledTaskRunner/KScheduledTaskRunner.class.php
- plugins/scheduled_task/lib/model/filter/ScheduledTaskProfileFilter.php
> PLAT-9064 - filter scheduledTasks that were not handled the current day

- plugins/reach/admin/forms/CatalogItemPricing.php
- plugins/reach/lib/kReachUtils.php
- plugins/reach/lib/model/ReachProfile.php
- plugins/reach/lib/model/data/kVendorCredit.php
- plugins/reach/services/ReachProfileService.php
> Mercury 13.20 reach credit sync fix

- plugins/reach/admin/forms/CatalogItemPricing.php
- plugins/reach/lib/kReachUtils.php
- plugins/reach/lib/model/ReachProfile.php
- plugins/reach/lib/model/data/kVendorCredit.php
- plugins/reach/services/ReachProfileService.php
> Revert "Mercury 13.20 reach credit sync fix"

- alpha/apps/kaltura/modules/kmc/templates/kmc4Success.php
- alpha/web/lib/css/kmc5.css
- alpha/web/lib/js/kmc5.js
Note the there are changes in whitespaces probably since out IDE environments has different style rules and this project is missing [editorconfig](https://editorconfig.org/) convention of something similar.  please review without whitespaces.
**Please just approve without merging**
> KMCNG-1941 add link to the html based kmc from the flash based kmc

- plugins/scheduled_task/batch/ScheduledTaskRunner/KScheduledTaskRunner.class.php
- plugins/scheduled_task/lib/api/types/KalturaScheduledTaskProfile.php
- plugins/scheduled_task/lib/api/types/filters/base/KalturaScheduledTaskProfileBaseFilter.php
- plugins/scheduled_task/lib/model/filter/ScheduledTaskProfileFilter.php
> Naos 14.2.0 plat 9064

- plugins/reach/lib/model/data/kReoccurringVendorCredit.php
- plugins/reach/lib/model/data/kTimeRangeVendorCredit.php
- plugins/reach/lib/model/data/kVendorCredit.php
> Naos 14.2.0 reach credit dates fix

- alpha/apps/kaltura/lib/reports/kKavaReportsMgr.class.php
- force use of slave database
- strip new lines from quoted values (prevent breaking the csv)
- support adding the descendants of input entry id (e.g. get live and query both live & recording)
- query enrichment -
o custom criteria with values derived from input params
o support group by
o support selection of functions (e.g. group_concat)
> kava custom reports enhancements

- plugins/scheduled_task/admin/ScheduleTaskUtils.php
> PLAT-9101 MR dry run list to all types extending from baseEntry

- api_v3/lib/types/filters/ValidateAccessResponseProfile.php
Change trim location to first method
> Commit trim clazz to avoid incorrect line endings(Windows)

- api_v3/services/PartnerService.php
- var_console/controllers/PartnerController.php
- var_console/views/scripts/partner/list.phtml
+Bug fix on partner get for adminuserid
+Bug fix for generateAdminKs for var console
> Naos-14.3.0-PLAT-9068 Adding access to new KMCNG for MA dashboard

- plugins/reach/lib/model/data/kUnlimitedVendorCredit.php
> PLAT-9096 - reach unlimited vendor credit date handling

- alpha/apps/kaltura/lib/media/kThumbnailDescriptor.class.php
> NO-PLAT fix ThumbnailDescriptor not to divide by zero.

- deployment/base/sql/01.kaltura_ce_tables.sql
https://kaltura.atlassian.net/browse/PLAT-9149
> Adjust auto inc for `dynamic_enums` and `partner` tables

- plugins/cue_points/quiz/QuizPlugin.php
> quiz- avoid UserEntryPeer::retrieveByPK per answer

- alpha/apps/kaltura/lib/webservices/APIErrors.class.php
- api_v3/services/ThumbAssetService.php
> fix addFromUrl to throw expecption in case that url result is empty

- alpha/apps/kaltura/lib/webservices/APIErrors.class.php
- api_v3/services/ThumbAssetService.php
> change url exception code

- alpha/apps/kaltura/lib/myEntryUtils.class.php
- api_v3/lib/KalturaEntryService.php
> NO-PLAT - fix file_get_contents

- infra/general/KCurlWrapper.class.php
> PLAT-9003 identify internal url calls through KCurlWrrapper

- alpha/apps/kaltura/lib/db/DbManager.php
> PLAT-8904 - choose sphinx by best lag algorithm

- plugins/reach/lib/model/data/kReoccurringVendorCredit.php
> PLAT-9227 - Reach credit dates calculation fix

- alpha/apps/kaltura/lib/request/kSessionBase.class.php
- alpha/apps/kaltura/modules/kmc/actions/extloginAction.class.php
- alpha/lib/model/kuserPeer.php
- api_v3/lib/KalturaBaseUserService.php
- api_v3/services/PartnerService.php
- var_console/controllers/PartnerController.php
listPartnersForUserAction doesn't work with ks with a master partner id different then its partner id
> Naos-14.6.0-SUP-15117 Change account from multi user management console

- alpha/apps/kaltura/modules/extwidget/actions/embedPlaykitJsAction.class.php
- infra/general/KCurlWrapper.class.php
> Naos 14.6.0 plat 9003

- infra/general/KCurlWrapper.class.php
Merging the code from 14.6.0 to 14.5.0
> Naos-14.5.0-SUP-15611 Handling HTTP response without code description

- alpha/apps/kaltura/lib/batch2/bcdl/kBusinessPreConvertDL.php
- alpha/apps/kaltura/lib/batch2/kFlowHelper.php
- alpha/apps/kaltura/lib/batch2/kJobsManager.php
- alpha/apps/kaltura/lib/batch2/model/kCaptureThumbJobData.php
- alpha/apps/kaltura/lib/batch2/model/kClipConcatJobData.php
- alpha/apps/kaltura/lib/batch2/model/kPostConvertJobData.php
- alpha/apps/kaltura/lib/clipconcat/kClipManager.php
- api_v3/lib/KalturaEntryService.php
- api_v3/lib/types/batch/KalturaCaptureThumbJobData.php
- api_v3/lib/types/batch/KalturaClipConcatJobData.php
- api_v3/lib/types/batch/KalturaPostConvertJobData.php
- batch/batches/CaptureThumb/KAsyncCaptureThumb.class.php
- batch/batches/PostConvert/KAsyncPostConvert.class.php
- infra/media/thumbnailMaker/KFFMpegThumbnailMaker.php
> PLAT-9255 + PLAT-6772 handle enc_at_rest flavor conversion and thumb generation.

- alpha/apps/kaltura/lib/KSecureEntryHelper.class.php
- alpha/apps/kaltura/modules/extwidget/actions/thumbnailAction.class.php
- alpha/lib/model/accessControl.php
> Revert "PLAT-9256: make sure thumbnail actions are cached for KES rules"

- alpha/apps/kaltura/lib/db/DbManager.php
> NO-PLAT logging sphinx weights and which sphinx was chosen.

- api_v3/lib/types/resource/KalturaEntryResource.php
- api_v3/lib/types/resource/KalturaOperationResource.php
- api_v3/lib/types/resource/KalturaResource.php
- api_v3/services/MediaService.php
> Revert "Add check for local file exist in media add and update content action"

- alpha/config/cache/kApcConf.php
- alpha/config/cache/kBaseConfCache.php
- alpha/config/cache/kBaseMemcacheConf.php
- alpha/config/cache/kCacheConfFactory.php
- alpha/config/cache/kFileSystemConf.php
- alpha/config/cache/kKeyCacheInterface.php
- alpha/config/cache/kLocalMemCacheConf.php
- alpha/config/cache/kMapCacheInterface.php
- alpha/config/cache/kRemoteMemCacheConf.php
- alpha/config/cache/kSessionConf.php
- alpha/config/kConf.php
- alpha/config/kConfCacheManager.php
- alpha/scripts/utils/insertConfigMapToDb.php
- alpha/scripts/utils/syncDbConfigMapsToCache.php
- alpha/scripts/utils/traceConfigValues.php
- configurations/kLocalMemCacheConf.template.ini
- configurations/kRemoteMemCacheConf.template.ini
- deployment/updates/sql/2018_08_19_create_config_maps_table.sql
- infra/cache/kBaseCacheWrapper.php
- infra/kEnvironment.php
- infra/log/KalturaLog.php
> Revert "Revert "Naos 14.5.0 plat 8932""

- alpha/apps/kaltura/lib/batch2/model/kBulkUploadJobData.php
- api_v3/services/BulkUploadService.php
- batch/batches/BulkUpload/KAsyncBulkUpload.class.php
- batch/batches/KBatchBase.class.php
> Naos-14.7.0-PLAT-9183-privileges in kBulkUploadJob 

- alpha/apps/kaltura/lib/reports/kKavaReportsMgr.class.php
> kava - respect pager in graph tables

- infra/kEnvironment.php
> Revert "PLAT-9331:fix merging of associative array configuration files with k…"

- plugins/drm/admin/forms/AdminApiConfigure.php
> PLAT-9309 support fps parameter persistance_duration

- plugins/bulk_upload/csv/batch/BulkUploadEngineCsv.php
> Naos-14.8.0-SUP-15174 handle BOM in csv bulk upload

- api_v3/lib/syndication/SyndicationFeedRenderer.php
Check if the uiconf includes kalturaPlayerJs - if so mark the uiconf as playkit and use the embedPlaykitJS service
> Support playkit(v3) player with syndication feeds

- batch/batches/BulkUpload/KAsyncBulkUpload.class.php
- plugins/bulk_upload/drop_folder_xml/DropFolderXmlBulkUploadPlugin.php
- plugins/bulk_upload/drop_folder_xml/lib/DropFolderXmlBulkUploadEngine.php
- plugins/bulk_upload/drop_folder_xml/lib/api/KalturaDropFolderXmlBulkUploadJobData.php
- plugins/bulk_upload/drop_folder_xml/lib/kDropFolderXmlEventsConsumer.php
- plugins/bulk_upload/drop_folder_xml/lib/kDropFolderXmlFileHandler.php
- plugins/bulk_upload/drop_folder_xml/lib/model/kDropFolderBulkUploadXmlJobData.php
The xml dropfolder bulk upload fails when there are more then the max records each run (default 100)
> Naos-14.7.0-SUP-15218 DropFolder bulk upload fails on retries

- alpha/apps/kaltura/lib/myEntryUtils.class.php
- alpha/apps/kaltura/lib/myFileConverter.class.php
> PLAT-9381 - handle encrypted thumbs serving

- api_v3/lib/syndication/SyndicationFeedRenderer.php
> Revert "Support playkit(v3) player with syndication feeds"

- alpha/apps/kaltura/lib/kMrssManager.php
> NO-PLAT - fix warning in kMrssManager

- batch/batches/Import/KAsyncImport.class.php
- infra/general/KCurlWrapper.class.php
- plugins/bulk_upload/xml/batch/BulkUploadEngineXml.php
- plugins/event_notification/providers/http/lib/KDispatchHttpNotificationEngine.class.php
- plugins/vendor/lib/model/zoom/ZoomWrapper.php
> PLAT-9003 -block internal urls that are not whitelisted

- alpha/apps/kaltura/modules/extwidget/actions/playManifestAction.class.php
- alpha/lib/model/flavorAsset.php
> PLAT-9241 - optimizing flavors on playmanifest

- README.md
@MosheMaorKaltura please review & merge.
> updated the contribution guidelines link to latest

- alpha/apps/kaltura/lib/reports/kKavaReportsMgr.class.php
- user usage (17) - add total metrics to graphs
- specific user usage (18) - add total metrics to graphs & table
also -
- support peak/average/latest metrics for all:
* storage
* entry count
* entry duration
* users
- acculate func - support multiple base values. required in order to create graphs of both entry count and duration
- add baseToEnd aggregation functions
- support setting a default column map for all action types (table, graph, total)
> kava - align user usage metrics

- alpha/apps/kaltura/lib/kMrssManager.php
> PLAT-9420 fix kMrssManager warning

- plugins/bulk_upload/xml/batch/BulkUploadEngineXml.php
> Revert "TR-2167"

- alpha/apps/kaltura/lib/reports/kKavaBase.php
- alpha/apps/kaltura/lib/reports/kKavaReportsMgr.class.php
generic features:
- add serverNodeIds filter
- player-events-realtime metrics - add avg_view_bitrate, support view_buffer_time
- add minute granularity
custom reports features:
- add report_optional_params
- support getting a limit param
- support a totals-only custom report (without dim & graph metrics)
- support filter.type
> kava - ecdn reports supportive features

- alpha/apps/kaltura/lib/clipconcat/kClipManager.php
> Naos 14.9.0 plat 9441

- alpha/apps/kaltura/lib/myEntryUtils.class.php
> PLAT-9381 - build thumb url for playlists

- alpha/apps/kaltura/lib/KDLWrap.php
- infra/cdl/kdl/KDLFlavor.php
- infra/cdl/kdl/KDLOperatorFfmpeg2_7_2.php
Enable 2 encryption modes via flavorParams::IsEncrypted field
1:encrypt contents >10sec (equivalent to original 'true')
2:encrypt all
> Naos 14.9.0 plat 9429 EaR

- configurations/admin.template.ini
- fix missing search Acl and change default dropfolder settings
> Update admin.ini for missing settings

- alpha/apps/kaltura/lib/batch2/kFlowHelper.php
- alpha/apps/kaltura/lib/clipconcat/kClipManager.php
- api_v3/lib/KalturaEntryService.php
- plugins/content/document/services/DocumentsService.php
> SUP-15957 handle source flavor fileExt on clipping and trimming

- infra/general/KCryptoWrapper.class.php
determine the aes method according to the key size, as mcrypt does
> crypto wrapper/openssl support additional methods

- alpha/lib/model/entry.php
> SUP-16219 - copy startDate and endDate from template entry

- admin_console/web/css/global.css
- plugins/reach/ReachPlugin.php
- plugins/reach/admin/PartnerCatalogItemListAction.php
- plugins/reach/admin/PartnerCatalogItemsCloneAction.php
- plugins/reach/admin/ReachProfileCloneAction.php
- plugins/reach/admin/ReachProfileListAction.php
- plugins/reach/admin/forms/ClonePartnerCatalogItems.php
- plugins/reach/admin/forms/CloneReachProfile.php
- plugins/reach/admin/scripts/plugin/partner-catalog-item-list-action.phtml
- plugins/reach/admin/scripts/plugin/reach-profile-list-action.phtml
> REACH-Cloning reach profile and partner catalog items

- infra/media/mediaInfoParser/KMediaInfoMediaParser.php
Handle duplicate duration fields in the media-info data
> PLAT-9505-WebM-failures

- plugins/beacon/config/mapping/beacon_scheduled_resource_index.json
- plugins/beacon/lib/model/items/kBeaconScheduledResourceItem.php
- plugins/search/providers/elastic_search/lib/elasticSearchUtils.php
- release-notes.md
Also contain minor fixes and release notes
> Naos-14.10.0-PLAT-9396 Beacon searchScheduledResource mapping

- plugins/integration/providers/cielo24/Cielo24ClientHelper.php
- plugins/integration/providers/cielo24/lib/kCielo24FlowManager.php
Add error handling to Cielo24 client helper
> PSVAMB-4523

- plugins/multi_centers/services/FileSyncImportBatchService.php
avoid scanning a large range of ids in case one dc is not creating file syncs for a long time.
> optimize file sync queries

- alpha/apps/kaltura/lib/reports/kKavaReportsMgr.class.php
- alpha/apps/kaltura/lib/reports/myReportsMgr.class.php
- kava should fallback to myReportsMgr for any unknown report type
- in myReportsMgr, avoid connecting to mysql for plugin reports
> fix quiz reports

- alpha/apps/kaltura/lib/reports/kKavaReportsMgr.class.php
also fix TOP_SYNDICATION drilldown dimension map
> kava - fix graph transform metrics

- alpha/apps/kaltura/lib/reports/kKavaReportsMgr.class.php
use 'delta' instead of count for all entry count metrics.
add a filter of physicalAdd/status to the entry counts in the admin console report.
> fix admin console report def

- alpha/apps/kaltura/lib/model/objectfilters/categoryFilter.class.php
> Fix fatal error when retrieving catgeories for fullIds indexing

- infra/chunkedEncode/KBaseChunkedEncodeSessionManager.php
In low/no motion videos, codec tend to stop the encoding before the chunk end.
In such cases, exit with error.
> No-Plat: handle too short chunk files

- alpha/lib/model/BulkUploadResultPeer.php
- api_v3/services/BatchService.php
- deployment/permissions/service.bulkupload.bulk.ini
- plugins/bulk_upload/filter/BulkUploadFilterPlugin.php
- plugins/bulk_upload/filter/batch/BulkUploadCategoryEntryEngineFilter.php
- plugins/bulk_upload/filter/batch/BulkUploadEngineFilter.php
- plugins/bulk_upload/filter/batch/BulkUploadMediaEntryEngineFilter.php
- plugins/bulk_upload/filter/lib/BulkUploadJobObjectType.php
- plugins/bulk_upload/filter/lib/api/KalturaBulkUploadResultJob.php
- plugins/bulk_upload/filter/lib/model/BulkUploadResultJob.php
- plugins/bulk_upload/xml/batch/BulkUploadEngineXml.php
- plugins/bulk_upload/xml/xml/ingestion.xsd
New feature - add feature allowing bulk updates through the regular XML on multiple entries retrieved according to a filter.
Includes addition to update (and also true update - not override) co-editors and co-publishers of entries via bulk upload XML.
Includes bugfix for issue where XML update to an entry resets the entry owner.
> PSVAMB-5604

- plugins/schedule/base/lib/api/filters/KalturaScheduleEventResourceFilter.php
> NO-PLAT fixed wrong array_filter syntax

- configurations/kRemoteMemCacheConf.template.ini
> NO-PLAT configuration fix for deprecated comment

- alpha/lib/model/kuser.php
Changing it to return only partners where the user is the admin
> Naos-14.13.0-PLAT-9614 Changing listPartnersForUserAction

- alpha/apps/kaltura/lib/reports/kKavaReportsMgr.class.php
this function can be used to print a core report in ini format, can be helpful when there's a need to create a custom report similar to a core report.
> kava - custom reports helper function

- admin_console/views/scripts/index/kelloggs.phtml
need to pass the url hash to the iframe
> kelloggs - support copy url

- api_v3/lib/KalturaResponseCacher.php
Adding getPlaybackContext to the extract referrer parameters cases
> Naos-14.13.0-SUP-16810-getPlaybackContext-caching

- plugins/cue_points/base/batch/copyCuePoints/Engine/KMultiClipCopyCuePointEngine.php
> PLAT-9629 - avoid copying Answer cuepoints to trimmed clipped entries

- plugins/schedule/bulk_upload/lib/api/KalturaBulkUploadICalJobData.php
- plugins/schedule/bulk_upload/services/ScheduleBulkService.php
> Naos 14.14.0 schedule event bulk upload

- plugins/schedule/base/lib/api/filters/KalturaScheduleResourceFilter.php
fixing bug found in compatibility check
> Naos-14.14.0-PLAT-9653

- alpha/lib/model/LiveEntryServerNode.php
Not calling "unsetMediaServer" so no recording per-session available.
> Revert SUP-17048

- alpha/lib/model/LiveEntryServerNode.php
Without the second half of the original fix
> Return primary fix

- api_v3/lib/types/batch/KalturaClipConcatJobData.php
> PLAT-9699 fix ClipConcatJobData parsing

- release-notes.md
> Revert "PLAT-9656:adding release notes"

- deployment/base/sql/01.kaltura_ce_tables.sql
…4 but never added to the DB deployment file
> Was introduced by this commit b5d587e1eeb6e10fe972acf28c4cbb7471a03074

- api_v3/services/GroupUserService.php
- release-notes.md
> Naos-14.16.0-PLAT-8580-Group user Add release-notes 

- api_v3/web/xsdDoc/index.php
- api_v3/web/xsdDoc/schema_info.php
> PLAT-9651 - handle xsdDoc page generation when type is invalid

- alpha/apps/kaltura/lib/reports/kKavaReportsMgr.class.php
in vpaas multi report, in case an account was created within the period it won't have a base value.
> kava - aggregate entry graphs when no base value

- plugins/scheduled_task/admin/MediaRepurposingUtils.php
changing N/A fields to be considered as null in media repurposing
> Naos-14.16.0-PLAT-9740 media repurposing 

- plugins/scheduled_task/admin/MediaRepurposingUtils.php
> PLAT-9740 - fix unset const

- configurations/plugins.template.ini
> PLAT-9742 -  add Group plugin to plugins.template.ini

- alpha/scripts/utils/checkYoutubeVideoStatus.php
- plugins/content_distribution/providers/youtube_api/lib/YoutubeApiDistributionEngine.php
no status when video rejected because of video length
the repose we get is empty list response like
{"code":200,"headers":{"expires":"Wed, 06 Mar 2019 10:03:45 GMT","date":"Wed, 06 Mar 2019 10:03:45 GMT","cache-control":"private, max-age=0, must-revalidate, no-transform","etag":"\"XpPGQXPnxQJhLgs6enD_n8JR4Qk/VCkLmxHGfd8bJ1zwkMnGdwrmJZs\"","vary":"Origin\nX-Origin","content-type":"application/json; charset=UTF-8","content-encoding":"gzip","x-content-type-options":"nosniff","x-frame-options":"SAMEORIGIN","x-xss-protection":"1; mode=block","server":"GSE","alt-svc":"quic=\":443\"; ma=2592000; v=\"46,44,43,39\"","transfer-encoding":"chunked"},"body":{"kind":"youtube#videoListResponse","etag":"\"XpPGQXPnxQJhLgs6enD_n8JR4Qk/VCkLmxHGfd8bJ1zwkMnGdwrmJZs\"","pageInfo":{"totalResults":0,"resultsPerPa …
> Naos.14.17.0-PLAT-9663 - youtubeApi 

- release-notes.md
> Naos-14.17.0-PLAT-9758 

- plugins/conf_maps/admin/ConfigurationMapListAction.php
- plugins/conf_maps/admin/scripts/plugin/configuration-map-list-action.phtml
> NO-PLAT - fix confmaps admin console page on service forbidden

- configurations/batch/batch.ini.template
add enabledWorker directive to the batch template
> Code Review

- alpha/apps/kaltura/lib/clipconcat/kClipManager.php
> PLAT-9771 - avoid concat on single operation attribute

- plugins/event_notification/providers/email/lib/batch/recipients/KEMailNotificationGroupRecipientEngine.php
> Revert "Incorrect concat() when running with PHP 5.3"

- plugins/cue_points/annotation/lib/model/Annotation.php
- plugins/cue_points/base/lib/model/om/BaseCuePoint.php
> SUP-17627 prevent email notification for temp entry annotation creation

- plugins/cue_points/base/batch/copyCuePoints/Engine/KCopyCuePointEngine.php
> Naos-14.18.0-SUP-17626

- plugins/cue_points/base/batch/copyCuePoints/Engine/KCopyCuePointEngine.php
> Revert "Naos-14.18.0-SUP-17626"

- deployment/base/scripts/init_data/03.UserRole.ini
- deployment/permissions/service.partner.ini
- deployment/updates/scripts/add_permissions/2019_04_10_update_capture_permission.php
and for the listFeatureStatus action
> adding STUDIO_BASE permission for capture role

- plugins/multi_centers/services/FileSyncImportBatchService.php
also reduced the range of scanned ids
> use slave in file sync import queries

- plugins/cue_points/sphinx/lib/SphinxCuePointCriteria.php
- plugins/search/providers/sphinx_search/lib/SphinxCriteria.php
> Revert "PLAT-9823 - user sphinx query when filter contains field type"

- plugins/cue_points/quiz/services/QuizUserEntryService.php
- plugins/cue_points/sphinx/lib/SphinxCuePointCriteria.php
> PLAT-9836: Make sure to set current context partner id even in cases where filter is not set

- plugins/cue_points/quiz/QuizPlugin.php
> PLAT-9867: Fix quiz plugin schema contribution to avoid API error when trying to bulk upload cue points

- alpha/apps/kaltura/modules/extwidget/actions/embedPlaykitJsAction.class.php
pass KS to the auto generated code for auto and iframe embeds
> Pass KS to embedPlaykitAction auto and iframe embeds

- plugins/beacon/scripts/BeaconsIndexesRotation.php
- plugins/search/providers/elastic_search/client/elasticClient.php
- plugins/search/providers/elastic_search/scripts/aliases/ElasticIndexRotationWorker.php
> Naos-14.18.0-PLAT-9794-adding option to remove unused indices

- configurations/admin.template.ini
> Sip feature enablement name modification

- plugins/sip/lib/model/providers/pexip/kPexipHandler.php
> Orion-15.0.0-sipIntegration

- alpha/apps/kaltura/lib/rules/conditions/kAuthenticatedCondition.php
> Orion 15.1.0 plat 9847

- plugins/sip/lib/model/providers/pexip/kPexipUtils.php
- plugins/sip/services/PexipService.php
> Orion-15.1.0-SipIntegration

- plugins/schedule/bulk_upload/batch/BulkUploadScheduleEventCsvEngine.php
- plugins/schedule/bulk_upload/lib/api/KalturaBulkUploadResultScheduleEvent.php
> PSVAMB-7338

- deployment/updates/scripts/add_permissions/2019_06_16_update_sip_permissions.php
- deployment/updates/scripts/ini_files/2019_06_16_sip_update_permissions.ini
> PLAT-9921 update sip permission to allow admin only usage.

- deployment/updates/create_version_mng_table.sql
- deployment/updates/fix_version_management.sql
- deployment/updates/update.php
In continuation to https://github.com/kaltura/server/pull/8515#issuecomment-499126795
> Fix schema update flow

- alpha/lib/model/entryPeer.php
> SUP-17775 - Player does not display all caption files in the CC button

- infra/chunkedEncode/KChunkedEncode.php
> HF-forced-KF-were-not-generated

- deployment/updates/sql/2019_07_05_add_sphinx_index_column_sphinx_log.sql
- deployment/updates/sql/2019_07_05_add_type_column_sphinx_log.sql
Same problem as with https://github.com/kaltura/server/pull/8515/commits/3718727ce18bfb519fa9cb0b103d3da5d1dc1a3a
> Fix upgrade sql alters

- alpha/lib/model/entry.php
- alpha/scripts/utils/setEntryCreationDate.php
@MosheMaorKaltura  merging to newest branch following your code review on PR #8524
> Orion 15.1.0 creation date update script

- alpha/lib/model/entryPeer.php
Handle cases when single element key isn't 0
> Orion-15.6.0-PLAT-10072-filterEntriesByPartnerOrKalturaNetwork

- alpha/lib/model/entryPeer.php
When we receive an empty entry
> Orion 15.6.0 plat 10072 fixing filterEntriesByPartnerOrKalturaNetwork

- plugins/content/caption/base/CaptionPlugin.php
- plugins/content/caption/base/services/CaptionAssetService.php
> PLAT-10095 - saving captions extension when upload caption via url

- infra/general/scheduling/DatesGenerator.php
> Revert "KMS-19596: when recurring by day for X weeks check first occurrence in…"

- alpha/apps/kaltura/lib/model/objectfilters/ServerNodeFilter.php
> Revert "PLAT-9908: add implementaiton for nameEqual in ServerNodeFilter"

- plugins/reach/admin/forms/DictionariesSubForm.php
- plugins/reach/admin/scripts/dictionaries-sub-form.phtml
- plugins/reach/admin/scripts/plugin/reach-profile-list-action.phtml
> REACH2-699 -  Reach Admin console fix for dictionary display

- alpha/apps/kaltura/lib/batch2/kJobsManager.php
- batch/batches/PostConvert/KAsyncPostConvert.class.php
- infra/media/mediaInfoParser/KBaseMediaParser.php
- infra/media/mediaInfoParser/KFFMpegMediaParser.php
- infra/media/mediaInfoParser/KMediaInfoMediaParser.php
Support media data extraction from encrypted assets
> Orion 15.8.0 sup 19263 messed wid hgt on ea r

- alpha/apps/kaltura/lib/model/objectfilters/KalturaCriteria.php
- alpha/lib/enums/SearchIndexFieldEscapeType.php
- plugins/search/providers/sphinx_search/lib/SphinxCriteria.php
- plugins/search/providers/sphinx_search/lib/SphinxUtils.php
> Handle backslashes when filter is Equal or In

- configurations/sphinx/kaltura.conf.template
- plugins/cue_points/base/config/IndexSchema.xml
- plugins/cue_points/base/lib/model/CuePointPeer.php
- plugins/cue_points/base/lib/model/index/CuePointIndex.php
- plugins/cue_points/sphinx/CuePointSphinxPlugin.php
> PLAT-10199 remove str_entry_id from sphnix kaltura_cue_point table

- alpha/apps/kaltura/lib/model/objectfilters/entryFilter.class.php
- alpha/apps/kaltura/lib/myPlaylistUtils.class.php
- alpha/lib/enums/entryModerationStatus.php
- alpha/scripts/utils/MRApiFilterVsElasticCheck.php
- api_v3/lib/types/entry/KalturaPlayableEntry.php
- api_v3/lib/types/entry/filters/base/KalturaPlayableEntryBaseFilter.php
- api_v3/lib/types/enums/KalturaEntryModerationStatus.php
- api_v3/services/PlaylistService.php
- plugins/scheduled_task/lib/object_filter_engine/KObjectFilterBaseEntryEngine.php
- plugins/search/providers/elastic_search/lib/model/enum/ESearchEntryFieldName.php
- plugins/search/providers/elastic_search/lib/model/enum/ESearchEntryFilterFields.php
- plugins/search/providers/elastic_search/lib/model/filters/ESearchCaptionQueryFromFilter.php
- plugins/search/providers/elastic_search/lib/model/filters/ESearchEntryQueryFromFilter.php
- plugins/search/providers/elastic_search/lib/model/filters/ESearchQueryFromAdvancedSearch.php
- plugins/search/providers/elastic_search/lib/model/filters/ESearchQueryFromFilter.php
- plugins/search/providers/elastic_search/lib/model/items/ESearchEntryItem.php
Media repurposing filter on elastic
Adding media filter last played at lower equal or null
> Orion 15.7.0 plat 9903

- alpha/apps/kaltura/lib/kEntitlementUtils.php
> PLAT-10222 - add session level caching to entry entiltlements check

- alpha/config/schema.xml
- alpha/data/sql/schema.sql
- alpha/lib/model/map/SsoTableMap.php
- deployment/base/scripts/init_data/01.Partner.template.ini
- deployment/base/sql/01.kaltura_ce_tables.sql
- deployment/permissions/partner.-8.ini
- deployment/permissions/service.sso.sso.ini
- deployment/updates/scripts/add_permissions/2019_11_10_kmc_sso_server_add_partner.php
- deployment/updates/sql/2019_11_10_alter_sso_add_redirect_url_column.sql
- deployment/updates/sql/2019_11_10_alter_sso_index.sql
- plugins/sso/admin/forms/SsoProfileConfigure.php
- plugins/sso/admin/scripts/plugin/sso-profile-list-action.phtml
- plugins/sso/base/lib/model/Sso.php
- plugins/sso/base/lib/model/SsoPeer.php
- plugins/sso/base/lib/model/om/BaseSso.php
- plugins/sso/base/lib/model/om/BaseSsoPeer.php
- plugins/sso/lib/api/KalturaSso.php
- plugins/sso/lib/api/filters/base/KalturaSsoBaseFilter.php
- plugins/sso/lib/model/filter/SsoFilter.php
- release-notes.md
PLAT-10250: be able to save SSO data to SSO profile in admin console as well.
PLAT-10251: search sso profile by redirect url.
PLAT-10252: adding dedicated partner for kmc sso server with permission to perform sso list
> PLAT-10251: sso- redirect url, data, new dedicated partner

- alpha/apps/kaltura/lib/batch2/bcdl/kBusinessPostConvertDL.php
> Revert "PLAT-10259: copy flavors only if replacement already started"

- plugins/bulk_upload/drop_folder_xml/plugins/providers/ap_feed/ApFeedDropFolderPlugin.php
Add feed drop folder dependency
> PSVAMB-6815

- api_v3/lib/types/filters/KalturaBaseUserFilter.php
- api_v3/lib/types/filters/base/KalturaBaseUserBaseFilter.php
- api_v3/lib/types/filters/base/KalturaUserBaseFilter.php
- api_v3/lib/types/filters/orderEnums/KalturaBaseUserOrderBy.php
- api_v3/lib/types/filters/orderEnums/KalturaUserOrderBy.php
> Revert "Revert "PSVAMB-8780 -> All the userFilter files were generated/updated after …""

- plugins/bulk_upload/drop_folder_xml/plugins/providers/ap_feed/ApFeedDropFolderPlugin.php
> Revert "PSVAMB-6815"

- batch/batches/KBatchBase.class.php
> Orion-15.11.0-HF-PLAT-10305 Fixing directory permissions changes

- plugins/cue_points/quiz/QuizPlugin.php
> PLAT-10256

- infra/general/iniUtils.php
> Revert "PLAT-10245"

- plugins/thumbnail/lib/model/enum/kCropGravityPoint.php
- plugins/thumbnail/lib/model/imagickAction/kCropAction.php
Changing how we treat gravity point in crop action and making it support more values
> Orion-15.12.0-PLAT-10345 thumbnail crop gravity point fix

- plugins/thumbnail/lib/api/errors/KalturaThumbnailErrors.php
- plugins/thumbnail/lib/model/enum/kThumbnailParameterName.php
- plugins/thumbnail/lib/model/imagickAction/kImageOutputAction.php
- plugins/thumbnail/lib/model/thumbStorage/kThumbStorageBase.php
Fixing according to QA feedback
> Orion-15.12.0-PLAT-10348 Thumbnail output action

- batch/scheduler/KGenericScheduler.class.php
> PLAT-10246

- plugins/cue_points/annotation/services/AnnotationService.php
> PLAT-10108- Allow comments For All

- batch/batches/KBatchBase.class.php
> Orion-15.12.0 - BatchBase Fix

- plugins/reach/services/EntryVendorTaskService.php
> PLAT-10366:fixing event notifications not being triggered when vendors doing entryVendorTask updateJob

- plugins/conf_maps/admin/forms/ConfigurationMapConfigure.php
- plugins/conf_maps/lib/api/KalturaConfMaps.php
- plugins/conf_maps/lib/api/filters/KalturaConfMapsFilter.php
> Show configuration map creator on admin console

- plugins/reach/lib/api/data/KalturaBaseVendorCredit.php
- plugins/reach/lib/api/data/KalturaTimeRangeVendorCredit.php
- plugins/reach/lib/api/data/ReachProfile/KalturaReachProfile.php
> PLAT-10376 - reach credit validation on update

- batch/batches/KBatchBase.class.php
- batch/scheduler/KGenericScheduler.class.php
> PLAT-10377 - batch load crash fix

- plugins/reach/lib/model/ReachProfile.php
> REACH2-730

- batch/batches/ReportExport/engines/kReportExportEngine.php
- batch/scheduler/KGenericScheduler.class.php
- batch/scheduler/KSchedulerConfig.class.php
> PLAT-10382 - batch load crash fix

- plugins/reach/lib/model/ReachProfile.php
- plugins/reach/services/ReachProfileService.php
> REACH-730/731 calculate usage percentage when updating credit

- alpha/lib/model/UserLoginDataPeer.php
> Revert "SUP-20258: fix 'invalid user' msg when setting initial pwd for KMC admins"

- alpha/apps/kaltura/lib/batch2/bcdl/kBusinessPostConvertDL.php
@inbal-ben-david 
@david-winder-kaltura
> SUP-20500 handle temp recorded entry flavors when updating entry status

- api_v3/services/LiveStreamService.php
> Revert "Fix array definition backward compatibility bug"

- plugins/reach/lib/api/data/KalturaTimeRangeVendorCredit.php
> Revert "REACH-730"

- plugins/reach/lib/model/ReachProfile.php
- plugins/reach/services/ReachProfileService.php
> Revert "REACH-730/731 calculate usage percentage when updating credit"

- plugins/reach/lib/api/data/KalturaBaseVendorCredit.php
- plugins/reach/lib/api/data/KalturaTimeRangeVendorCredit.php
- plugins/reach/lib/api/data/ReachProfile/KalturaReachProfile.php
> Revert "PLAT-10376 - reach credit validation on update"

- alpha/apps/kaltura/lib/model/objectfilters/KalturaCriteria.php
- alpha/config/IndexSchema.xml
- alpha/lib/enums/SearchIndexFieldEscapeType.php
- alpha/lib/model/category.php
- alpha/lib/model/index/categoryIndex.php
- deployment/base/scripts/index/IndexObjectsGenerator.php
- plugins/search/providers/sphinx_search/lib/SphinxCriteria.php
- release-notes.md
> PLAT-10269-escapeCategoryMd5: Implement index sharding on category + escape category md5 values to avoid unneeded matches

- plugins/content/document/scripts/convert.php
> SUP-20312 - fix document conversion.

- plugins/search/providers/elastic_search/lib/api/enum/KalturaESearchEntryFieldName.php
- plugins/search/providers/elastic_search/lib/api/types/items/entry/KalturaESearchEntryItem.php
- plugins/search/providers/elastic_search/lib/model/enum/ESearchEntryFieldName.php
- plugins/search/providers/elastic_search/lib/model/enum/ESearchEntryFilterFields.php
- plugins/search/providers/elastic_search/lib/model/filters/ESearchEntryQueryFromFilter.php
- plugins/search/providers/elastic_search/lib/model/items/ESearchEntryItem.php
> Revert "enable range searches for entry::votes property"

- alpha/data/sql/schema.sql
- deployment/base/sql/01.kaltura_ce_tables.sql
- deployment/updates/sql/2019_12_26_alter_config_maps_table.sql
> ConfMap table fix modify content column size

- alpha/config/cache/kFileSystemConf.php
- alpha/config/cache/kRemoteMemCacheConf.php
- alpha/scripts/utils/insertConfigMapToDb.php
- alpha/scripts/utils/syncDbConfigMapsToCache.php
- plugins/conf_maps/lib/api/KalturaConfMaps.php
- plugins/conf_maps/lib/api/filters/KalturaConfMapsFilter.php
- plugins/conf_maps/services/ConfMapsService.php
> Making sure confMaps hosts will be handled as lowerCase only.

- alpha/config/kConf.php
- alpha/config/kConfCacheManager.php
- batch/scheduler/KSchedulerConfig.class.php
> ignore local & remote cache when loading local batch configuration

- plugins/search/providers/sphinx_search/lib/SphinxCriteria.php
> PLAT-10223 - removing  sphinx optimizations when not relevant

- plugins/search/providers/elastic_search/lib/kElasticSearchManager.php
- plugins/search/providers/sphinx_search/lib/kSphinxSearchManager.php
> when skipping sphinx due to sql size limitation log the sql size

- alpha/apps/kaltura/lib/batch2/bcdl/kReplacementHelper.php
> shouldSyncFlavorInfo fix

- admin_console/controllers/UserController.php
- vendor/ZendFramework/library/Zend/Session.php
> PLAT-10188 - admin console sso fix

- plugins/vendor/zoom/lib/model/data/kZoomEvent.php
- plugins/vendor/zoom/lib/model/kZoomEngine.php
Changing description UUID to be in a newline
> Orion-15.15.0-PLAT-10556 Fixing typo in new transcription event name

- plugins/reach/admin/forms/ReachProfileCredit.php
> REACH2-761 display 0 in reach profile credit edit page

- plugins/reach/admin/forms/ReachProfileUnlimitedCredit.php
- plugins/reach/lib/api/data/KalturaUnlimitedVendorCredit.php
- plugins/reach/lib/model/data/kUnlimitedVendorCredit.php
> REACH2-769 remove toDate and addOn from unlimited credit.

- alpha/apps/kaltura/lib/live/kBroadcastUrlManager.php
- alpha/lib/model/LiveStreamEntry.php
- api_v3/lib/types/entry/KalturaLiveStreamEntry.php
- configurations/sip.template.ini
- deployment/permissions/object.KalturaLiveStreamEntry.ini
- deployment/updates/scripts/add_permissions/2020_01_19_add_rtmps_permissions_KalturaLiveEntry.php
- plugins/sip/lib/model/providers/pexip/kPexipHandler.php
- plugins/sip/lib/model/providers/pexip/kPexipUtils.php
- release-notes.md
@noam-arad 
@david-winder-kaltura
> PLAT-10575 create SIP ADPs with RTMPS stream urls

- plugins/search/providers/elastic_search/lib/kElasticSearchManager.php
- plugins/search/providers/sphinx_search/lib/kSphinxSearchManager.php
> Orion 15.16.0 sup 19976

- deployment/updates/scripts/add_permissions/2020_02_03_add_reach_catalog_item_kmc_permissions.php
- deployment/updates/scripts/ini_files/2020_02_04_object_reach_catalogitem_update_permissions.ini
- release-notes.md
> Orion 15.17.0 reach2 779

- plugins/search/providers/elastic_search/lib/model/filters/ESearchQueryFromFilter.php
allow filter with only advance search to run vs ESearch
> Orion-15.17.0-PLAT-10642 

- alpha/apps/kaltura/lib/batch2/model/kConvertJobData.php
- alpha/apps/kaltura/lib/clipconcat/kClipManager.php
- alpha/lib/enums/BatchJobUrgencyType.php
> PLAT-10626 - ClipConcat convert jobs should run with high priority

- plugins/content/caption/base/lib/kCaptionsContentManager.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9179)
> PLAT-10646 : Indexing of caption incomplete if there is an empty line

- configurations/plugins.template.ini
- plugins/media/live_cluster/lib/LiveClusterMediaServerNodeType.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9180)
> Add implements and to template

- infra/general/languageCodeManager.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9175)
> New method to be used by saas-specific distribution connector.
