kaltura/server

alpha/apps/kaltura/lib/reports/kKavaBase.php, alpha/apps/kaltura/lib/reports/kKavaReports.php, alpha/apps/kaltura/lib/reports/kKavaReportsMgr.class.php, api_v3/services/ReportService.php, plugins/content/registration/lib/kRegistrationKavaUtils.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9126)
=> KMS-19964 registration module report

api_v3/services/ReportService.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9183)
=> AN-1230: limit report csv file name size

plugins/reach/admin/forms/ReachProfileConfigure.php, plugins/reach/admin/scripts/dictionaries-sub-form.phtml, plugins/reach/lib/api/data/ReachProfile/KalturaReachProfile.php
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9189)
=> increase dictionary max chars to 4000

plugins/conf_maps/admin/scripts/plugin/configuration-map-list-action.phtml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9190)
=> make admin console window re-sizeable

plugins/content/registration/lib/kRegistrationKavaUtils.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9191)
=> add table name prefix to where clause

plugins/content/external_media/lib/api/filters/KalturaExternalMediaEntryFilter.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9193)
=> Orion-15.18.0-PLAT-10641-fixing KalturaExternalMediaEntryFilter

plugins/content/caption/base/batch/ConvertCaptions/KAsyncConvertCaptionAsset.class.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9185)
=> SUP-20389:convert scc caption time stamps

plugins/conference/lib/model/ConferenceServerNode.php, plugins/conference/services/ConferenceService.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9196)
=> Orion 15.18.0 webc 1836

alpha/apps/kaltura/lib/batch2/kBatchManager.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9198)
=> Orion 15.17.0 fix long err des

api_v3/web/analyticsSyncServe.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/8332)
=> new entry source types for KMS GO

alpha/lib/enums/durationType.php, alpha/lib/model/entry.php, alpha/lib/model/entryPeer.php, api_v3/lib/types/enums/KalturaDurationType.php, plugins/search/providers/elastic_search/lib/model/enum/ESearchEntryFilterFields.php, plugins/search/providers/elastic_search/lib/model/filters/ESearchEntryQueryFromFilter.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9200)
=> Orion-15.18.0-PLAT-10708 duration type support for query esearch adpater

alpha/apps/kaltura/lib/myPlaylistUtils.class.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9202)
=> SUP-21097:use total result in case pager is not being sent

plugins/search/providers/elastic_search/lib/model/filters/ESearchQueryFromAdvancedSearch.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9203)
=> Orion-15.18.0-PLAT-10714-support for kmc filtering by custom data to esearch adapter

release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9204)
=> PLAT-10694: Add linux batch for doc conversion

plugins/search/providers/elastic_search/lib/model/filters/ESearchQueryFromAdvancedSearch.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9205)
=> Orion-15.18.0-PLAT-10718 - fixing internal server error when filtering by custom data

plugins/content/external_media/ExternalMediaPlugin.php, plugins/search/providers/elastic_search/lib/model/enum/ESearchEntryFilterFields.php, plugins/search/providers/elastic_search/lib/model/filters/ESearchEntryQueryFromFilter.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9207)
=> Orion-15.18.0-PLAT-10720-external video type eSearch adapter support

alpha/apps/kaltura/lib/reports/kKavaBase.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9209)
=> new entry source type for kms go

alpha/apps/kaltura/lib/myEntryUtils.class.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9213)
=> PLAT-10725: Support switching temp thumbnail dir to allow storage cleanup

alpha/apps/kaltura/lib/model/objectfilters/EntryServerNodeFilter.class.php, api_v3/lib/types/EntryServerNode/base/KalturaEntryServerNode.php, api_v3/lib/types/EntryServerNode/base/filters/base/KalturaEntryServerNodeBaseFilter.php, batch/batches/ValidateLiveMediaServers/KAsyncValidateLiveMediaServers.class.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9208)
=> PLAT-10610: adding exclude server by type in conf

alpha/apps/kaltura/lib/batch2/kFlowHelper.php, batch/batches/Archive/KAsyncLiveEntryArchive.class.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9217)
=> PLAT-10732: fix a fatal error in auto archive

plugins/search/providers/elastic_search/ElasticSearchPlugin.php, plugins/search/providers/elastic_search/lib/model/search/kESearchQueryManager.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9219)
=> PLAT-10733:Use reduce results (optimised mode) as default

plugins/vendor/zoom/lib/model/kZoomClient.php, plugins/vendor/zoom/lib/model/kZoomEngine.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9218)
=> Orion-15.18.0-PLAT-10128-HF zoom failing to download webinars

alpha/apps/kaltura/lib/myEntryUtils.class.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9222)
=> PLAT-10725: Support defining multiple old thumb dirs

alpha/apps/kaltura/lib/myEntryUtils.class.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9223)
=> PLAT-10725: If move failed serve file from old thumb path

plugins/reach/lib/kReachManager.php
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9225)
=> REACH-727 - make sure only parent entry caption task is created

plugins/vendor/zoom/lib/model/kZoomClient.php, plugins/vendor/zoom/lib/model/kZoomEngine.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9227)
=> Orion 15.18.0-plat-10128-hotfix

plugins/vendor/zoom/lib/model/kZoomEngine.php
Without engine after Eran K comments
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9228)
=> Orion 15.18.0 plat 10128 hotfix

release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9229)
=> PLAT-10358: Live NG plugin - release note

deployment/permissions/service.eventnotification.eventnotificationtemplate.ini, deployment/updates/scripts/add_permissions/2020_03_09_monitoring_proxy_list_templates.php, release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9236)
=> PLAT-10625: allow listTemplates for ecdn monitoring proxy

deployment/updates/scripts/add_permissions/2020_01_19_add_permissions_to_systempartner_jobs_partner.php, release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9238)
=> PLAT-10320: changing permissions script name

batch/batches/Cleanup/KAsyncDirectoryCleanup.class.php, infra/chunkedEncode/KChunkedEncode.php, infra/storage/kFile.class.php
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9234)
=> PLAT-10736 directory cleanup fix

alpha/apps/kaltura/lib/myEntryUtils.class.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9240)
=> No-Plat: Fix notice

deployment/updates/scripts/xml/notifications/entryClipJobCompletedHttpNotificationTemplate.xml
[Jira task](https://kaltura.atlassian.net/browse/PSVAMB-11201)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9239)
=> Orion 15.19.0 psvamb 11201

configurations/base.ini
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9242)
=> Increase "copy_partner_limit_metadata_profiles" from 10 to 13

plugins/scheduled_task/lib/api/types/object_tasks/KalturaModifyEntryObjectTask.php, plugins/scheduled_task/lib/object_task_engine/KObjectTaskModifyEntryEngine.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9245)
=> Orion-15.20.0-PLAT-10739 adding deleting Media repurposing metadata option

alpha/apps/kaltura/lib/reports/kKavaReports.php, alpha/apps/kaltura/lib/reports/kKavaReportsMgr.class.php, alpha/lib/enums/ReportType.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9248)
=> add new report type for category analytics - highlights report

alpha/apps/kaltura/lib/model/objectfilters/filters.class.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9255)
=> Removing unnecessary  init

api_v3/services/LiveStreamService.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9256)
=> PLAT-10665: reduce the isLive cache when not live from 10 to 5

alpha/lib/model/LiveEntry.php, alpha/lib/model/LiveEntryServerNode.php, api_v3/lib/types/entry/KalturaLiveEntry.php, batch/batches/Archive/KAsyncLiveEntryArchive.class.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9243)
=> Orion 15.19.0 webc 1856

alpha/apps/kaltura/lib/myPlaylistUtils.class.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9262)
=> Orion-15.20.0-PLAT-10741 Playlist internal error on empty entry id list

deployment/permissions/service.jobs.ini, deployment/permissions/service.systempartner.systempartner.ini, deployment/updates/scripts/add_permissions/2020_03_17_update_permissions_systemPartner_jobs.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9261)
=> PLAT-10740: fix permissions on systemPartner and jobs services

alpha/apps/kaltura/lib/kEntitlementUtils.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9257)
=> No-Plat: Support entitlement check skip validation flag

alpha/apps/kaltura/lib/kParentChildEntryUtils.php, api_v3/lib/types/conversionProfile/filters/KalturaAssetFilter.php, plugins/content/caption/base/CaptionPlugin.php, plugins/content/caption/base/lib/api/filters/KalturaCaptionAssetFilter.php, plugins/content/caption/base/services/CaptionAssetService.php, plugins/reach/lib/kReachManager.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9267)
=> Orion-15.19.0 reach2 727 caption fix

plugins/vendor/zoom/lib/model/processors/kZoomRecordingProcessor.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9268)
=> Orion-15.20.0-PLAT-10746-zoom chat files

alpha/apps/kaltura/lib/webservices/kSessionUtils.class.php
after the code review change
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9264)
=> Orion-15.20.0-PLAT-10743 fixing handling privilege

alpha/apps/kaltura/lib/kUploadTokenMgr.php, alpha/lib/model/UploadToken.php, api_v3/lib/KalturaErrors.php, api_v3/services/UploadTokenService.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9269)
=> PLAT-10747: Block chunk uploads that have more than 1000 chunks waiting to be concatenated (debug mode)

alpha/apps/kaltura/lib/webservices/kSessionUtils.class.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9271)
=> Adding the playlist itself to the eligble entires

plugins/search/providers/elastic_search/lib/model/filters/ESearchEntryQueryFromFilter.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9277)
=> PLAT-10726

plugins/vendor/zoom/lib/model/kZoomClient.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9273)
=> Orion-15.19.0-PLAT-10128-HF zoom webinar

alpha/apps/kaltura/lib/reports/kKavaReportsMgr.class.php, alpha/apps/kaltura/lib/reports/myReportsMgr.class.php, api_v3/lib/types/report/KalturaReportInputFilter.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9279)
=>  AN-1273: add nodeIdsIn to report filter

plugins/tag_search/services/TagService.php, plugins/tag_search/sphinx/kTagFlowManager.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9281)
=> PLAT-10750:Avoid multiple handling of tags in case of entry delete

plugins/reach/lib/model/ReachProfile.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9278)
=> SUP-19377:prevent auto rule when categoryEntry is created

api_v3/lib/syndication/KalturaSyndicationFeedRenderer.php
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9276)
=> SUP-21111 handle syndication feed according to syndication confmap

alpha/apps/kaltura/lib/kEntitlementUtils.php, alpha/apps/kaltura/lib/myPlaylistUtils.class.php, alpha/apps/kaltura/lib/webservices/kSessionUtils.class.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9288)
=> Orion-15.20.0-PLAT-10751 DisableEntitlementForPlaylist in execute playlist

infra/chunkedEncode/KChunkedEncodeUtils.php
In order to save AWS egress, create the temp mp4 file in local /tmp folder
Delete the file right afterwards
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9289)
=> Write temp MP4 to local folder

alpha/apps/kaltura/lib/kParentChildEntryUtils.php, alpha/apps/kaltura/lib/myEntryUtils.class.php
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9290)
=> Orion 15.20.0 plat 10759

plugins/content/caption/search/lib/kCaptionSearchFlowManager.php, plugins/content_distribution/lib/kContentDistributionFlowManager.php, plugins/cue_points/base/lib/kCuePointManager.php
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9291)
=> PLAT-10758

batch/batches/ReportExport/engines/kReportExportEngine.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9287)
=> Update report title with categories/playbackContext ids

alpha/apps/kaltura/lib/monitor/KalturaMonitorClient.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9295)
=> No-Plat: add additional info to session counters print

plugins/cue_points/base/lib/kCuePointManager.php, plugins/cue_points/base/lib/model/CuePoint.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9296)
=> PLAT-10758 : avoid muliple queries in case of childres

plugins/reach/lib/model/ReachProfile.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9292)
=> SUP-19377: fix for php 5

plugins/conf_maps/admin/ConfigurationMapConfigureAction.php, plugins/conf_maps/admin/forms/ConfigurationMapConfigure.php
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9297)
=> NO-PLAT add date of map creation in admin console

alpha/lib/model/SchedulerWorker.php, alpha/lib/model/SchedulerWorkerPeer.php, deployment/base/scripts/createQueryCacheTriggers.php
schedulerWorker:schedulerConfiguredId
=> add query cache rule on schedulerWorker

plugins/conf_maps/admin/ConfigurationMapConfigureAction.php, plugins/conf_maps/admin/forms/ConfigurationMapConfigure.php
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9303)
=> PLAT-10771 confMaps fix for admin console - show created date of map

plugins/search/providers/elastic_search/lib/model/filters/ESearchEntryQueryFromFilter.php, plugins/search/providers/elastic_search/lib/model/filters/ESearchQueryFromAdvancedSearch.php
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9299)
=> PLAT-10766 PLAT-10768 adding qoutations search

alpha/apps/kaltura/lib/batch2/bcdl/kBusinessPreConvertDL.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9307)
=> SUP-21492 : Do not issue reconvert of source due to conversion finish

batch/batches/KScheduleHelper.class.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9309)
=> PLAT-10775: reduce access to scheduler_worker table

alpha/apps/kaltura/lib/batch2/bcdl/kBusinessPreConvertDL.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9308)
=> SUP-21492:Do not issue reconvert of source due to conversion finish

plugins/sip/services/PexipService.php
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9313)
=> PLAT-10776 - dont set explictlive to false on entry when creting sipUrl

alpha/lib/model/BatchJob.php
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9312)
=> PLAT-10761 decrease DB calls to batch tables

api_v3/services/BatchService.php, batch/batches/Convert/Engines/KJobConversionEngine.class.php, batch/batches/StorageUpdate/KAsyncStorageUpdate.php, deployment/permissions/service.batch.ini, deployment/updates/scripts/add_permissions/2020_03_25_add_action_extend_batch_job_lock_expiration.php, release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9321)
=> PLAT-10653:change function name to extendLockExpiration

batch/batches/StorageUpdate/KAsyncStorageUpdate.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9319)
=> PLAT-10320: release usage memory and call garbage cycle

alpha/apps/kaltura/lib/reports/kKavaBase.php, api_v3/web/analyticsSyncServe.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9323)
=> AN-1293: add kaltura meeting source type

alpha/apps/kaltura/lib/myInsertEntryHelper.class.php, alpha/apps/kaltura/modules/partnerservices2/actions/addentryAction.class.php, alpha/lib/model/entry.php, api_v3/lib/KalturaEntryService.php, api_v3/services/BaseEntryService.php, api_v3/services/EmailIngestionProfileService.php, api_v3/services/MediaService.php, api_v3/services/MixingService.php
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9316)
=> PLAT-10761 remove creation of kshow objects

deployment/permissions/service.reach.vendorCatalogItem.ini, deployment/updates/scripts/add_permissions/2020_06_04_add_permission_vendor_catalog_items.php, infra/general/KCsvWrapper.php, plugins/reach/ReachPlugin.php, plugins/reach/admin/CatalogItemExportAction.php, plugins/reach/admin/forms/CatalogItemFilter.php, plugins/reach/admin/scripts/plugin/catalog-item-export-action.phtml, plugins/reach/admin/scripts/plugin/catalog-item-list-action.phtml, plugins/reach/lib/api/data/vendorCatalogItem/KalturaVendorCatalogItem.php, plugins/reach/lib/kReachUtils.php, plugins/reach/services/VendorCatalogItemService.php
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9322)
=> REACH-836 - export vendor catalog items to csv

plugins/search/providers/elastic_search/lib/model/filters/ESearchEntryQueryFromFilter.php
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9329)
=> PLAT-10778 handle commas in kmcng free text search

plugins/content/attachment/lib/api/KalturaAttachmentAsset.php
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9331)
=> PLAT-10794 remove CRLF in attachment asset filename

alpha/lib/model/kuserPeer.php, plugins/vendor/zoom/lib/kZoomUser.php, plugins/vendor/zoom/lib/model/processors/kZoomMeetingProcessor.php, plugins/vendor/zoom/lib/model/processors/kZoomProcessor.php, plugins/vendor/zoom/lib/model/processors/kZoomRecordingProcessor.php, plugins/vendor/zoom/lib/model/processors/kZoomWebinarProcessor.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9332)
=> Propus-16.0.1-PLAT-10781-Zoom integration find user by zoom email

plugins/vendor/zoom/lib/model/processors/kZoomMeetingProcessor.php, plugins/vendor/zoom/lib/model/processors/kZoomRecordingProcessor.php, plugins/vendor/zoom/lib/model/processors/kZoomWebinarProcessor.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9336)
=> Propus-16.0.1-PLAT-10803 - zoom meeting owner is added as part of the  co publisher/co-editors

alpha/apps/kaltura/lib/kUploadTokenMgr.php
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9335)
=> PLAT-10794 - validate bat and eicar files

alpha/lib/model/entry.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9338)
=> Changing interactivity custom fields to be lower case as other fields

plugins/vendor/zoom/lib/model/processors/kZoomMeetingProcessor.php, plugins/vendor/zoom/lib/model/processors/kZoomWebinarProcessor.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9341)
=> Propus-16.0.1-PLAT-10803 fixing handling particpants

plugins/interactivity/lib/model/validators/kInteractivityNodeValidator.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9337)
=> Propus-16.0.1-PLAT-10797-changing interactivity interaction to be not mandatory

plugins/interactivity/lib/model/validators/kInteractivityDataValidatorFactory.php
Interactivity add fails on missing id wnen trying to add to playlist
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9340)
=> Propus-16.0.1-PLAT-10799 fixing interactivity fails missing id

plugins/interactivity/services/InteractivityService.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9342)
=> Propus-16.0.1-PLAT-10800-Interactivity edit entitlement

alpha/lib/model/entry.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9344)
=> Propus-16.0.1-PLAT-10801-Fix Adding interactivity return the object with empty version

plugins/interactivity/InteractivityPlugin.php, plugins/interactivity/lib/model/errors/kInteractivityErrorMessages.php, plugins/interactivity/lib/model/errors/kInteractivityException.php, plugins/interactivity/lib/model/kBaseInteractivity.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9345)
=> Propus-16.0.1-PLAT-10802-interactivity update before creating the interactivity

alpha/apps/kaltura/lib/KExternalErrors.class.php, alpha/apps/kaltura/lib/kContextDataHelper.php, alpha/apps/kaltura/modules/extwidget/actions/playManifestAction.class.php, alpha/apps/kaltura/modules/extwidget/actions/serveFlavorAction.class.php, alpha/lib/model/DeliveryProfileVod.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9304)
=> PLAT-10731: Add support for SimuLive

plugins/interactivity/InteractivityPlugin.php, plugins/interactivity/lib/api/errors/KalturaInteractivityErrors.php, plugins/interactivity/lib/model/errors/kInteractivityErrorMessages.php, plugins/interactivity/lib/model/errors/kInteractivityException.php, plugins/interactivity/lib/model/validators/kEntryInteractivityDataValidator.php, plugins/interactivity/lib/model/validators/kInteractivityBaseValidator.php, plugins/interactivity/lib/model/validators/kInteractivityDataValidator.php, plugins/interactivity/lib/model/validators/kInteractivityEntryNodeValidator.php, plugins/interactivity/lib/model/validators/kInteractivityInteractionValidator.php, plugins/interactivity/lib/model/validators/kInteractivityNodeValidator.php, plugins/interactivity/services/VolatileInteractivityService.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9351)
=> Propus-16.1.0-PLAT-10795 enhancing interactivity schema validation

alpha/apps/kaltura/modules/extwidget/actions/rawAction.class.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9352)
=> SUP-21816: Support returning decrypted file content when serving files through reAction

alpha/apps/kaltura/lib/batch2/kFlowHelper.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9354)
=> PLAT-10817: fix call to getEntryId on an entryId

alpha/apps/kaltura/lib/myEntryUtils.class.php, alpha/lib/model/entry.php, plugins/cue_points/quiz/QuizPlugin.php, plugins/interactivity/InteractivityPlugin.php, plugins/interactivity/lib/api/enums/InteractivityEntryCapability.php, plugins/interactivity/lib/model/kBaseInteractivity.php, plugins/interactivity/lib/model/kInteractivity.php, plugins/interactivity/lib/model/validators/kInteractivityInteractionValidator.php, plugins/interactivity/services/InteractivityService.php, release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9356)
=> Propus-16.1.0-PLAT-10793 interactivity capability

plugins/interactivity/lib/model/kBaseInteractivity.php, plugins/interactivity/lib/model/kInteractivity.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9357)
=> Propus-16.1.0-PLAT-10793-capability bug fix for volatile interactivity

alpha/apps/kaltura/lib/batch2/bcdl/kBusinessPreConvertDL.php, alpha/apps/kaltura/lib/batch2/kJobsManager.php, alpha/lib/model/StorageProfile.php
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9359)
=> PLAT-10818 - handle import files when periodic remote storage

alpha/apps/kaltura/lib/kUploadTokenMgr.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9343)
=> PLAT-10816: Concatenate upload chunk directly to target file if possible to reduce file moves inside the nfs

alpha/apps/kaltura/lib/storage/kStorageExporter.php, alpha/lib/model/StorageProfile.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9360)
=> PLAT-10818

batch/batches/ValidateLiveMediaServers/KAsyncValidateLiveMediaServers.class.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9363)
=> PLAT_10831: remove array_column as not supported by php 5.3

alpha/apps/kaltura/lib/myPlaylistUtils.class.php, alpha/apps/kaltura/lib/webservices/APIErrors.class.php, alpha/apps/kaltura/lib/webservices/kSessionUtils.class.php, alpha/lib/enums/PlaylistType.php, alpha/lib/model/entry.php, api_v3/lib/types/entry/KalturaPlaylist.php, api_v3/lib/types/entry/filters/KalturaPlaylistFilter.php, api_v3/lib/types/enums/KalturaPlaylistType.php, api_v3/services/PlaylistService.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9365)
=> Propus 16.1.0 plat 10666 adding PATH playlist type

alpha/lib/model/StorageProfile.php, api_v3/lib/types/storageProfile/KalturaStorageProfile.php, infra/general/kString.class.php
…ramsIds
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9364)
=> PLAT-10827:RemoteStorage profile add blacklist of flavorParamsIds

api_v3/services/MixingService.php
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9369)
=> PLAT-10761-kshow_removal

batch/batches/Storage/Periodic/KAsyncStoragePeriodicExport.class.php
@inbal-ben-david
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9372)
=> PLAT-10805 make remote storage profile batch load config from conf map

api_v3/services/StorageProfileService.php, deployment/base/scripts/createQueryCacheTriggers.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9373)
=> PLAT-10735: rename cache key to avoid overlap between services

alpha/apps/kaltura/modules/extwidget/actions/serveFlavorAction.class.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9375)
=> PLAT-10731: fix consts for old PHP's versions

plugins/bulk_upload/csv/batch/BulkUploadVendorCatalogItemEngineCsv.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9374)
=> REACH2-840: removing enableSpeakerId from searching in enums

plugins/interactivity/InteractivityPlugin.php, plugins/interactivity/lib/model/validators/kInteractivityDataValidatorFactory.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9379)
=> Propus-16.1.0-PLAT-10844 Wrong Interactivity Validator for PATH playlist

alpha/lib/model/LiveEntryServerNode.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9381)
=> In order to avoid race condition don't set the broadcast time

plugins/bulk_upload/csv/batch/BulkUploadVendorCatalogItemEngineCsv.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9383)
=> REACH2-840: make serviceFeature a mandatory param

plugins/interactivity/InteractivityPlugin.php, plugins/interactivity/lib/api/errors/KalturaInteractivityErrors.php, plugins/interactivity/lib/model/errors/kInteractivityException.php, plugins/interactivity/lib/model/validators/kInteractivityDataValidatorFactory.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9382)
=> Propus-16.1.0-PLAT-10849-block interactivity for non PATH playlist

plugins/reach/lib/kReachUtils.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9385)
=> REACH2-853:adding missing fields to export file

plugins/interactivity/lib/model/validators/kInteractivityNodeValidator.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9390)
=> Propus-16.2.0-PLAT-10855-Interactivity error on old PHP

alpha/lib/model/StorageProfilePeer.php
… profile id
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9391)
=> PLAT-10856 : Add remotestorage from global partner when searching by profile id 

configurations/elasticDynamicMap.template.ini
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9394)
=> Updated directives

batch/KGenericBatchMgr.class.php, batch/scheduler/KGenericScheduler.class.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9396)
=> Check if pcntl is enabled before using it

plugins/drm/DrmPlugin.php, plugins/drm/lib/DrmLicenseUtils.php, plugins/drm/providers/fairplay/FairplayPlugin.php, plugins/drm/providers/playready/PlayReadyPlugin.php, plugins/drm/providers/widevine/WidevinePlugin.php
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9393)
=> PLAT-10829 - Drm license url handling

admin_console/forms/Partner/StorageConfiguration.php, alpha/apps/kaltura/lib/myEntryUtils.class.php, alpha/apps/kaltura/lib/myPackagerUtils.class.php, alpha/apps/kaltura/lib/storage/kDataCenterMgr.class.php, alpha/lib/enums/kPackagerUrlType.php, alpha/lib/model/StorageProfile.php, api_v3/lib/types/storageProfile/KalturaStorageProfile.php, batch/batches/CaptureThumb/KAsyncCaptureThumb.class.php, configurations/local.template.ini
@inbal-ben-david 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9370)
=> PLAT-10835 - handle volume_map and thumbs with remote packager

alpha/apps/kaltura/modules/extwidget/actions/serveFlavorAction.class.php
return the encryption key to the packager
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9401)
=> serveFlavor - support encrypted captions

batch/batches/StorageUpdate/KAsyncStorageUpdate.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9406)
=> PLAT-10790: fixing print of range of hendled partners

alpha/apps/kaltura/lib/cache/kCacheManager.php, api_v3/services/StorageProfileService.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9407)
=> PLAT-10879: add new cache key layer name for storage keys

deployment/updates/sql/2020_05_17_audit_trail_config_reach_profile.sql, plugins/audit/lib/kAuditTrailManager.php, plugins/audit/lib/model/enums/AuditTrailObjectType.php, release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9404)
=> REACH2-845: adding Reach profile to audit trail

alpha/apps/kaltura/lib/cache/kCacheManager.php, api_v3/services/StorageProfileService.php
Reverts kaltura/server#9407
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9409)
=> Revert "PLAT-10879: add new cache key layer name for storage keys"

admin_console/configs/lang/en.php, admin_console/forms/Partner/LocalStorageConfiguration.php, admin_console/forms/Partner/StorageConfiguration.php, alpha/apps/kaltura/lib/myContentStorage.class.php, alpha/apps/kaltura/lib/storage/kS3PathManager.php, alpha/lib/interfaces/ISyncableFile.php, alpha/lib/model/BatchJob.php, alpha/lib/model/FileAsset.php, alpha/lib/model/LiveEntry.php, alpha/lib/model/StorageProfile.php, alpha/lib/model/asset.php, alpha/lib/model/conversionProfile2.php, alpha/lib/model/entry.php, alpha/lib/model/flavorAsset.php, alpha/lib/model/genericSyndicationFeed.php, alpha/lib/model/thumbAsset.php, alpha/lib/model/uiConf.php, plugins/content/caption/base/lib/model/CaptionAsset.php, plugins/content_distribution/lib/model/DistributionProfile.php, plugins/content_distribution/lib/model/EntryDistribution.php, plugins/content_distribution/lib/model/GenericDistributionProviderAction.php, plugins/event_notification/providers/email/lib/model/EmailNotificationTemplate.php, plugins/event_notification/providers/http/lib/model/HttpNotificationTemplate.php, plugins/metadata/lib/model/Metadata.php, plugins/metadata/lib/model/MetadataProfile.php
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9386)
=> PLAT-10683 - add dedicated S3 path manager.

alpha/apps/kaltura/lib/batch2/bcdl/kBusinessConvertDL.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9412)
=> PLAT-10889: pass assets and not ids to export when replacing entry

alpha/lib/model/asset.php
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9415)
=> PLAT_10683 - pathManager fix

alpha/apps/kaltura/lib/storage/kStorageExporter.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9411)
=> PLAT-10874: add ability to set partner package type in the cloud storage

batch/batches/Convert/Engines/KConversionEngineChunkedFfmpeg.class.php, batch/batches/Convert/Engines/KJobConversionEngine.class.php, batch/batches/Convert/KAsyncConvert.class.php, batch/batches/Convert/KChunkedEncodeJobScheduler.class.php, infra/chunkedEncode/KBaseChunkedEncodeSessionManager.php, infra/chunkedEncode/KChunkedEncodeMemcacheWrap.php, infra/chunkedEncode/KChunkedEncodeSessionManager.php, infra/chunkedEncode/KChunkedEncodeUtils.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9429)
=> Propus 16.3.0 plat 10920 chunked encoding updates

alpha/apps/kaltura/lib/storage/kStorageExporter.php, alpha/lib/enums/BatchJobType.php, alpha/lib/model/FileSync.php, api_v3/services/StorageProfileService.php, batch/batches/Storage/Periodic/KAsyncStoragePeriodicDeleteLocal.class.php, batch/batches/Storage/Periodic/KAsyncStoragePeriodicDeleteLocalExe.php, deployment/permissions/service.filesync.filesync.ini, deployment/updates/scripts/add_permissions/2020_05_17_fileSync_deleteLocalFileSyncs.php, plugins/file_sync/services/FileSyncService.php, release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9420)
=> PLAT-10894: periodic delete local file syncs that were exported

alpha/apps/kaltura/lib/clipconcat/kClipManager.php
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9431)
=> PLAT-10889 - lock addconcatjob during clip/trim flow

alpha/apps/kaltura/lib/clipconcat/kClipManager.php
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9434)
=> Propus 16.3.0 plat 10889

batch/batches/Storage/Periodic/KAsyncStoragePeriodicPurge.class.php, release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9433)
=> PLAT-10769: add range to the query

alpha/apps/kaltura/modules/extwidget/actions/playManifestAction.class.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9432)
=> PLAT-10927: return local and periodic flavors in playmanifest

api_v3/services/LiveStreamService.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9436)
=> LIV-114: get max stream limit from the liveEntry partner

alpha/apps/kaltura/lib/reports/kKavaQoeReports.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9286)
=> QOE-256: update QOE error tracking

alpha/apps/kaltura/lib/reports/kKavaQoeReports.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9285)
=> QOE-254: update qoe experience

alpha/apps/kaltura/lib/reports/kKavaBase.php, alpha/apps/kaltura/lib/reports/kKavaReportsMgr.class.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9416)
=> support external youtube as entry source type in analytics reports

alpha/scripts/kava/kava_plays_views_sync.sh, alpha/scripts/kava/updateEntryPlaysViews.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9438)
=> SUP-22038: add playsviews cache update to onprem script

alpha/lib/model/DeliveryProfile.php, alpha/lib/model/FileSync.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9442)
=> PLAT-10931: use serveFlavor when export from remote storage periodic

batch/batches/Convert/Engines/KJobConversionEngine.class.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9443)
=> fix - handle unset field

batch/batches/Convert/Engines/KConversionEngineChunkedFfmpeg.class.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9444)
=> fix - missing func arg

alpha/scripts/compatCheck.php
Reverts kaltura/server#9445
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9447)
=> Revert "Update compatCheck.php"

plugins/interactivity/lib/model/validators/kInteractivityDataValidatorFactory.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9449)
=> Propus-16.3.0-PLAT-10935 Enabling interactivity for rapt playlist

alpha/lib/model/Partner.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9448)
=> PLAT-10937: fix crash that was introduced in PLAT-10780

admin_console/configs/lang/en.php, plugins/audit/lib/kAuditTrailManager.php, plugins/audit/services/AuditTrailService.php, plugins/conf_maps/ConfMapsPlugin.php, plugins/conf_maps/admin/AuditTrailListAction.php, plugins/conf_maps/admin/forms/AuditTrailFilter.php, plugins/conf_maps/admin/scripts/plugin/audit-trail-list-action.phtml, plugins/reach/lib/model/data/kVendorCredit.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9435)
=> REACH2-863: adding audit trail to admin console

plugins/audit/services/AuditTrailService.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9450)
=> REACH2-863: fixing error in audit trail service

plugins/scheduled_task/lib/processors/KGenericProcessor.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9452)
=> Propus-16.3.0-PLAT-10938-MR-infinite loop

deployment/permissions/service.tagsearch.tag.ini, deployment/updates/scripts/add_permissions/2020_05_28_add_permission_analytics_base_to_tag_search.php, release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9453)
=> PLAT-10930: adding permission ANALYTICS_BASE to tag search

alpha/apps/kaltura/modules/extwidget/actions/embedPlaykitJsAction.class.php
Reverts kaltura/server#9115
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9460)
=> Revert "fix(FEC-9495): add canary version to embedPlaykit action"

alpha/apps/kaltura/modules/extwidget/actions/embedPlaykitJsAction.class.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9461)
=> fix(FEC-9495): add canary version to embedPlaykit action

api_v3/services/FlavorAssetService.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9463)
=> Fix PHP Fatal

api_v3/services/FlavorAssetService.php
Reverts kaltura/server#9463
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9464)
=> Revert "Fix PHP Fatal"

deployment/permissions/service.interactivity.interactivity.ini, deployment/updates/scripts/add_permissions/2020_06_02_update_interactivity_get_action_permissions.php, release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9466)
=> Propus-16.4.0-PATH-837 adding permissions

plugins/reach/ReachPlugin.php, plugins/reach/admin/CatalogItemImportAction.php, plugins/reach/admin/CatalogItemImportResult.php, plugins/reach/admin/forms/CatalogItemFilter.php, plugins/reach/admin/scripts/plugin/catalog-item-import-action.phtml, plugins/reach/admin/scripts/plugin/catalog-item-import-result-action.phtml, plugins/reach/admin/scripts/plugin/catalog-item-list-action.phtml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9467)
=> REACH2-871: changing the way bulk upload result is displayed in reach

api_v3/services/UserService.php, deployment/permissions/service.user.ini, deployment/updates/scripts/add_permissions/2020_05_31_user_validateHashKey.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9454)
=> PLAT-10916: add validateHashKayAction

deployment/uiconf/deploy_v2.php
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9455)
=> PLAT-10782 - uiconf deployment script fix

release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9469)
=> PLAT-10916: add release notes

admin_console/web/js/jquery.form.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9472)
=> PLAT-10950 fix admin console submit js due to chrome browser update

alpha/apps/kaltura/lib/batch2/model/kConvertJobData.php, api_v3/lib/types/batch/KalturaConvertJobData.php, batch/batches/Convert/Engines/KJobConversionEngine.class.php, infra/chunkedEncode/KBaseChunkedEncodeSessionManager.php, infra/chunkedEncode/KChunkedEncode.php, infra/chunkedEncode/KChunkedEncodeUtils.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9475)
=> Propus 16.4.0 no plat job cpu metrics

alpha/apps/kaltura/lib/kUploadTokenMgr.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9474)
=> SUP-22019: don't validate the file type for an empty file

api_v3/lib/types/storageProfile/KalturaAmazonS3StorageProfile.php, infra/storage/file_transfer_managers/s3Mgr.class.php, vendor/aws/Aws/Sts/Exception/ExpiredTokenException.php, vendor/aws/Aws/Sts/Exception/IDPCommunicationErrorException.php, vendor/aws/Aws/Sts/Exception/IDPRejectedClaimException.php, vendor/aws/Aws/Sts/Exception/IncompleteSignatureException.php, vendor/aws/Aws/Sts/Exception/InternalFailureException.php, vendor/aws/Aws/Sts/Exception/InvalidActionException.php, vendor/aws/Aws/Sts/Exception/InvalidAuthorizationMessageException.php, vendor/aws/Aws/Sts/Exception/InvalidClientTokenIdException.php, vendor/aws/Aws/Sts/Exception/InvalidIdentityTokenException.php, vendor/aws/Aws/Sts/Exception/InvalidParameterCombinationException.php, vendor/aws/Aws/Sts/Exception/InvalidParameterValueException.php, vendor/aws/Aws/Sts/Exception/InvalidQueryParameterException.php, vendor/aws/Aws/Sts/Exception/MalformedPolicyDocumentException.php, vendor/aws/Aws/Sts/Exception/MalformedQueryStringException.php, vendor/aws/Aws/Sts/Exception/MissingActionException.php, vendor/aws/Aws/Sts/Exception/MissingAuthenticationTokenException.php, vendor/aws/Aws/Sts/Exception/MissingParameterException.php, vendor/aws/Aws/Sts/Exception/OptInRequiredException.php, vendor/aws/Aws/Sts/Exception/PackedPolicyTooLargeException.php, vendor/aws/Aws/Sts/Exception/RequestExpiredException.php, vendor/aws/Aws/Sts/Exception/ServiceUnavailableException.php, vendor/aws/Aws/Sts/Exception/StsException.php, vendor/aws/Aws/Sts/Exception/ThrottlingException.php, vendor/aws/Aws/Sts/Resources/sts-2011-06-15.php, vendor/aws/Aws/Sts/StsClient.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9476)
=> Support s3 authentication using arn role name 

plugins/reach/admin/forms/CatalogItemFilter.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9478)
=> REACH2-871:removing display group

alpha/scripts/utils/getZoomToken.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9471)
=> Propus-16.4.0-Zoom-get-token-script

plugins/reach/lib/api/data/entryVendorTaks/KalturaAlignmentVendorTaskData.php, plugins/reach/lib/api/data/entryVendorTaks/KalturaTranslationVendorTaskData.php, plugins/reach/lib/api/data/entryVendorTaks/KalturaVendorTaskData.php, plugins/reach/lib/api/data/entryVendorTaks/KalturaVendorTaskDataCaptionAsset.php, plugins/reach/lib/model/data/kTranslationVendorTaskData.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9459)
=> REACH2-867:adding the option to add captionAssetId to translation EntryVendorTask

plugins/search/providers/elastic_search/lib/model/items/ESearchUnifiedItem.php
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9481)
=> Propus 16.4.0 plat 10914

configurations/local.template.ini
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9484)
=> add search help link

alpha/apps/kaltura/lib/batch2/bcdl/kBusinessPostConvertDL.php, alpha/apps/kaltura/lib/storage/kStorageExporter.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9480)
=> PLAT-10944: Export source when conversion is done

api_v3/lib/types/batch/KalturaBatchJob.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9487)
=> PLAT-10897: make job's urgency visible in batch

alpha/apps/kaltura/lib/kUploadTokenMgr.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9488)
=> Remove unused param

plugins/content/attachment/lib/api/KalturaAttachmentAsset.php
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9493)
=> PLAT-10785 - handle attachment filename CRLF html chars

alpha/apps/kaltura/lib/reports/kKavaReportsMgr.class.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9494)
=> support GB units for usage in custom reports

alpha/apps/kaltura/lib/monitor/KalturaMonitorClient.php, alpha/apps/kaltura/lib/request/infraRequestUtils.class.php, alpha/apps/kaltura/lib/request/kIpAddressUtils.php
Reverts kaltura/server#9496
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9497)
=> Revert "Fixes the below PHP errors"

alpha/apps/kaltura/lib/reports/kKavaRealtimeReports.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9504)
=> AN-1388: add avg bitrate to QOS overview report

deployment/permissions/service.partner.ini, deployment/updates/scripts/add_permissions/2020_06_20_add_permission_partner_get.php
Will add the release note in another PR
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9505)
=> LIV-145: Add permission of partner get to -5

release-notes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9507)
=> Add release note to partner get to -5

alpha/apps/kaltura/lib/reports/kKavaVpaasReports.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9418)
=> Add source type to VPAAS report

alpha/apps/kaltura/lib/storage/VodPackagerDeliveryUtils.php, alpha/apps/kaltura/lib/storage/urlTokenizers/kCloudFrontUrlTokenizer.php, alpha/lib/model/DeliveryProfileAkamaiAppleHttpDirect.php, alpha/lib/model/DeliveryProfileAkamaiHttp.php, alpha/lib/model/DeliveryProfileLevel3AppleHttp.php, alpha/lib/model/DeliveryProfileVod.php, alpha/lib/model/DeliveryProfileVodPackagerDash.php, alpha/lib/model/DeliveryProfileVodPackagerHds.php, alpha/lib/model/DeliveryProfileVodPackagerHls.php, alpha/lib/model/DeliveryProfileVodPackagerMss.php, plugins/delivery/edgecast/lib/DeliveryProfileEdgeCastHttp.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9501)
=> SUP-22619: make sure clipTo is part of the signature

alpha/apps/kaltura/lib/model/objectfilters/entryFilter.class.php, api_v3/lib/types/entry/filters/KalturaBaseEntryFilter.php, plugins/search/providers/elastic_search/client/elasticClient.php, plugins/search/providers/elastic_search/lib/model/enum/ESearchEntryFilterFields.php, plugins/search/providers/elastic_search/lib/model/filters/ESearchEntryQueryFromFilter.php, plugins/search/providers/elastic_search/lib/model/filters/ESearchQueryFromFilter.php
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9506)
=> PLAT-10957 - add partial search for description field

plugins/content/caption/base/lib/model/CaptionAsset.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9510)
=> SUP-22509:Caption assets logic

alpha/scripts/utils/moveFileSyncToDifferentStorage.php
=> PLAT-10998  handling export assets to remote storage script

alpha/scripts/utils/moveFileSyncToDifferentStorage.php
=> PLAT-10998

alpha/apps/kaltura/lib/reports/kKavaReportsMgr.class.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9508)
=> support time conversion for table reports

alpha/scripts/utils/moveFileSyncToDifferentStorage.php
=> PLAT-11002 - dont export sources to remote storage

admin_console/configs/lang/en.php, admin_console/controllers/PartnerController.php, admin_console/forms/PartnerCreate.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/server/9502)
=> PLAT-10875: Allow additional parameters in partner creation

deployment/permissions/object.KalturaCodeCuePoint.ini, deployment/updates/scripts/add_permissions/2020_06_25_add_capture_codeCuePoint_permission.php
=> KMS-20244: add codeCuePoint insert permission to capture

release-notes.md
add release note to -5 partner liveReports permissions
=> LIV-156: add release note to -5 partner liveReports permissions

deployment/permissions/service.livereports.ini, deployment/updates/scripts/add_permissions/2020_06_28_add_permission_livereports.php
=> LIV-156: add permission of livereports to partner -5

infra/chunkedEncode/KChunkedEncode.php
Manually set filter_units (via params_extra) override the original auto setting
=> PLAT-11025-Support-CAE-caps-passthrough-on-CE-mode

alpha/lib/model/LiveStreamEntry.php, api_v3/lib/KalturaEntryService.php, api_v3/lib/KalturaErrors.php, api_v3/services/LiveStreamService.php, plugins/sip/lib/api/KalturaSipResponse.php, plugins/sip/lib/api/enums/KalturaSipSourceType.php, plugins/sip/lib/model/providers/pexip/kPexipHandler.php, plugins/sip/lib/model/providers/pexip/kPexipUtils.php, plugins/sip/services/PexipService.php
@noam-arad 
@david-winder-kaltura
=> PLAT-10924 - handle Dual Stream (talking heads and screenshare) for VCI

alpha/scripts/compatCheck.php
=> PLAT-11027 - compatcheck new alerts on new server errors

plugins/search/providers/elastic_search/scripts/populateElasticFromLog.php
=> elastic population script fix

alpha/scripts/utils/ExportByEntryListToDifferentStorage.php
=> export to remote storage by entries list file

api_v3/lib/types/entry/KalturaLiveStreamEntry.php
=> PLAT-10914

plugins/cue_points/quiz/lib/model/kQuizPdf.php
A valid PDF is a one that begins with "%PDF-[version]".
=> PLAT-11013: create a valid PDF file upon quiz->serve

plugins/search/providers/elastic_search/scripts/populateElasticFromLog.php
=> elastic populate fix

plugins/content_distribution/providers/youtube/lib/YouTubeDistributionCsvEngine.php
When there isn't thumb asset id
=> PLAT-11085 Youtube CSV distribution failure

api_v3/lib/types/entry/KalturaLiveStreamEntry.php, plugins/sip/lib/api/enums/KalturaSipSourceType.php, plugins/sip/lib/model/enums/SipSourceType.php, plugins/sip/services/PexipService.php
=> PLAT-10924 -expose sip source type to client

plugins/search/providers/elastic_search/lib/model/filters/ESearchEntryQueryFromFilter.php, plugins/search/providers/elastic_search/lib/model/items/ESearchEntryItem.php, plugins/search/providers/elastic_search/lib/model/items/ESearchUnifiedItem.php
=> SUP-21926 ignore entries with display_in_search=-1 in elastic free text search

plugins/search/providers/elastic_search/scripts/populateElasticFromLog.php
=> Propus 16.8.0 elastic populate fix

alpha/apps/kaltura/modules/extwidget/actions/embedPlaykitJsAction.class.php
Do not save the updates bundle config to the uiconf. Will be handled in the studio instead.
Related to https://github.com/kaltura/server/pull/9592
=> feat(FEC-10291): remove saving to uiconf

api_v3/lib/types/report/KalturaReportInputBaseFilter.php
=> use fromDate/toDate without rounding to get the same results both from KMC and API

admin_console/forms/PartnerConfiguration.php
=> LIV-197: fix php 5 incompatibility

plugins/sip/lib/model/providers/pexip/kPexipUtils.php
=> PLAT-10924 support sip dual stream

plugins/sip/lib/model/providers/pexip/kPexipUtils.php
=> PLAT-10924

batch/scheduler/KSchedularTaskConfig.class.php, batch/scheduler/KSchedulerConfig.class.php, infra/storage/file_transfer_managers/s3Mgr.class.php
=> PLAT-11072 - load s3arn from task config

batch/scheduler/KSchedulerConfig.class.php
=> PLAT-11072

batch/scheduler/KSchedularTaskConfig.class.php, batch/scheduler/KSchedulerConfig.class.php, configurations/batch/batch.ini.template, infra/storage/file_transfer_managers/s3Mgr.class.php
=> PLAT-11072 use s3Arn from task config

alpha/apps/kaltura/lib/request/kNetworkUtils.php
remove the ltrim of leading slashes
=> align auth tokens between API & UDRM

batch/batches/Storage/Periodic/KAsyncStoragePeriodicExport.class.php
=> Revert "Propus 16.8.1 plat 11120"

alpha/apps/kaltura/lib/storage/kFileSyncUtils.class.php
=> Revert "PLAT-11140: check that path is not empty for preferred and fallback s…"

infra/storage/file_transfer_managers/s3Mgr.class.php
=> PLAT-11150 make all files upload to s3 using multipart

infra/storage/file_transfer_managers/s3Mgr.class.php
=> PLAT-11150 make all files s3 be uploaded as multipart

infra/storage/file_transfer_managers/s3Mgr.class.php
=> SUP-23552 fix s3Mgr to have s3Arn from kConf as well

infra/storage/file_transfer_managers/s3Mgr.class.php
=> Propus 16.9.0 sup 23552

api_v3/lib/KalturaErrors.php, api_v3/services/BatchService.php, batch/batches/Convert/KAsyncConvert.class.php, deployment/permissions/service.batch.ini, deployment/updates/scripts/add_permissions/2020_09_01_update_batch_service.php
=> CLOUDMGT-770:Support windows machine to put file via http POST

alpha/apps/kaltura/lib/batch2/bcdl/kReplacementHelper.php, alpha/apps/kaltura/lib/batch2/kFlowHelper.php, alpha/apps/kaltura/lib/kPlaybackContextDataHelper.php, alpha/apps/kaltura/lib/storage/kDataCenterMgr.class.php, alpha/apps/kaltura/lib/storage/kFileSyncUtils.class.php, alpha/apps/kaltura/lib/storage/kStorageExporter.php, alpha/apps/kaltura/modules/extwidget/actions/playManifestAction.class.php, alpha/lib/model/StorageProfile.php, plugins/file_sync/services/FileSyncService.php
=> Revert "PLAT-11153: always support cloud periodic file syncs for all partners"

alpha/apps/kaltura/lib/storage/kFileSyncUtils.class.php
instead of going through servefile action
=> support direct serving of remote files to packager

alpha/lib/model/DeliveryProfileLive.php
fixing issue of the case of streaming only backup and requesting playManifest of primary (streamType=0)
=> LIV-249: handle playManifest request serverType of 0 (primary)

api_v3/services/LiveStreamService.php
validate limits of the current entry streaming, regardless of the other limit exceedings
=> LIV-216: detach live limits validation

alpha/apps/kaltura/lib/myEntryUtils.class.php, plugins/thumbnail/lib/model/thumbnailFactory/kImageTransformationAdapter.php
Also changed clone to clone width and height
=> PLAT-11139 - Fix thumbnail adapter for entries without width and height

infra/chunkedEncode/KBaseChunkedEncodeSessionManager.php, infra/chunkedEncode/KChunkedEncode.php
write only the final file to shared to avoid loading the shared file
system.
change by @anatolkaltura
=> ChunkedEncode: create chunk on local temp file

alpha/apps/kaltura/lib/kUploadTokenMgr.php
- avoid calling glob per chunk - merge all possible chunks, then call glob again
- increase php stream chunk size to 100k
- print time took for open & chunk append
=> upload optimizations

alpha/scripts/kava/updateEntryPlaysViews.php
=> PSVAMB-15535 - Update DB regardless of cache

alpha/lib/model/kuser.php, api_v3/lib/types/KalturaUser.php
=> PLAT-11160

api_v3/services/StorageProfileService.php
=> Add path by worker id to lockPendingFileSync

alpha/apps/kaltura/lib/storage/kFileSyncUtils.class.php
the priority is chosen by dc & file path.
also - add support for forcing remote serve based on file path.
=> add support for prioritizing serve locations

infra/storage/file_transfer_managers/s3Mgr.class.php
=> control Concurrent Multipart Connections

alpha/apps/kaltura/modules/extwidget/actions/previewAction.class.php
Add access control validation for ContextType::METADATA on Preview Action
=> Preview action - add access control validation

alpha/lib/model/FileSync.php
=> SUP-24029 - build download url by http/https protocols

alpha/scripts/utils/ExportToDifferentStorage.php
handle links correctly + fix all sorts of bad syncs
=> export script improvements

api_v3/services/UploadTokenService.php
…st with fileName and statusEqual
=> PLAT-11189: Filter out old upload tokens when calling upload token list with fileName and statusEqual

alpha/apps/kaltura/modules/extwidget/actions/embedPlaykitJsAction.class.php
Add support for specifying playlist id for embed playkit action.
=> feat(FEC-10420): support auto/iframe embed with playlist id

api_v3/lib/types/syndicationFeed/xslt/opera_syndication.xslt, api_v3/lib/types/syndicationFeed/xslt/roku_syndication.xslt
=> SUP-23489 fix camelCase on Roku and Opera syndication files

alpha/apps/kaltura/lib/kSimuliveUtils.php, alpha/lib/model/LiveEntry.php
setting the conditional cache of isLive action according to the event scheduling
=> VIRTC-166: simulive - isLive conditional cache

alpha/scripts/utils/ExportToDifferentStorage.php
=> export script enhancements

alpha/apps/kaltura/lib/kSimuliveUtils.php
change duration calculation to be the min between the entry length the event length (in order to put EXT-X-ENDLIST on time)
=> VIRTC-166: simulive - change duration calculation

plugins/thumbnail/lib/model/sourceAction/kVidAction.php, plugins/thumbnail/lib/model/thumbnailFactory/kResizePlaylistAdapter.php
Also fixing error message when vid action fails
=> Cloudmgt 750 thumb adapter fix for playlist default vid sec

api_v3/services/MediaService.php
=> ignore validate local source on replaceResource

infra/chunkedEncode/KBaseChunkedEncodeSessionManager.php
=> FixChunks and Merge retries

alpha/bootstrap.php, api_v3/web/index.php, infra/cache/kInfraMemcacheCacheWrapper.php
may provide some visibility into slow bootstraps
=> output memcache stats to log after bootstrap

alpha/apps/kaltura/lib/myEntryUtils.class.php
=> PLAT-11076:HF Generate thumbnails from sources at S3 by ffmpeg using igned URL

plugins/content/document/scripts/killWindowsPopups.py, plugins/content/document/scripts/pdfCreatorCmd.py
instead of toolhelp api which no longer works on new windows servers
=> doc convert scripts: use wmi for listing processes

alpha/lib/model/entry.php, plugins/content/attachment/services/AttachmentAssetService.php
=> Revert "PLAT-11243:Validate user abilty to edit content"

infra/media/mediaInfoParser/KFFMpegMediaParser.php
Clear extra frame data that some MXF files have.
It messed the detection func
=> SUP-24553-Fix-ScanType-detection

alpha/apps/kaltura/lib/kCurrentContext.class.php, alpha/apps/kaltura/lib/kPermissionManager.php
=> Revert "PLAT-11259: init user id and kuser in each request"

infra/log/UniqueId.php
can help finding the original request in case the cdn returns a cached
response
=> add the server time to x-kaltura-session

alpha/lib/model/DeliveryProfilePeer.php
filter the configured ratios to those that can be used to serve the request, after applying access control restrictions
=> support multiple cdn ratios on a single account

infra/chunkedEncode/KChunkedEncodeMemcacheWrap.php
increase job fetch range to handle longer memcache connectivity times
=> adjust FetchNextJob fetchRangeRandMax param to 20

plugins/cue_points/base/batch/copyCuePoints/Engine/KCopyCuePointEngine.php
to avoid duplicate data from page 0
=> PSVAMB-17989 - Start pageIndex at 1

alpha/apps/kaltura/lib/kAssetUtils.class.php, alpha/apps/kaltura/lib/storage/kDataCenterMgr.class.php, alpha/apps/kaltura/lib/storage/kFileSyncUtils.class.php, alpha/apps/kaltura/modules/extwidget/actions/downloadAction.class.php, alpha/apps/kaltura/modules/extwidget/actions/serveFlavorAction.class.php, alpha/lib/model/DeliveryProfile.php, alpha/lib/model/flavorAsset.php
=> Revert "PLAT-11239: Add download from directory support to download action using serveFlavor url"

plugins/virus_scan/engines/clamav_scan_engine/lib/ClamAVScanEngine.php
which fixed CVE-2020-3350 by using realpath
=> PLAT-22485 - Support ClamAV 0.102.4

plugins/content/document/scripts/killWindowsPopups.py
=> support popup windows closer for office 2013

plugins/event_notification/providers/email/lib/batch/recipients/KEmailNotificationCategoryRecipientEngine.php
FYI @MosheMaorKaltura moved to workers config
=> SUP-24970: get maxPagesToScan value from worker params config, default is 7

api_v3/lib/KalturaResponseCacher.php
support passing the request params in json format (not only query params)
=> contextdata cache fix

plugins/vendor/zoom/lib/model/data/kZoomRecording.php, plugins/vendor/zoom/lib/model/data/kZoomRecordingFile.php, plugins/vendor/zoom/lib/model/processors/kZoomRecordingProcessor.php
Split handling the record file by their starting time
=> SUP-25292-Zoom-different records in same event

alpha/apps/kaltura/lib/monitor/KalturaMonitorClient.php
- change cache from dim to event type
- measure api start time from index.php
- use a separate metric for file size (avoid reusing exec time)
- make sure partner id, ks type, multirequest are strings
- output the execution time for cached apis
=> apimon touchups

alpha/scripts/compatCheck.php
=> Revert "PLAT-22492:adding ability to compat check complex arrays"

alpha/lib/model/FileSync.php, infra/storage/kEncryptFileUtils.php
=> Revert "SUP-25350: Support shared storage thumbnails when using encryption flow"

alpha/apps/kaltura/lib/batch2/kJobsSuspender.php
=> Revert "SUP-25084: unsuspend jobs with status suspend_almost_done"

alpha/apps/kaltura/lib/monitor/KalturaMonitorClient.php
in case of multirequest, need to measure the time from prev request end time
=> apimon: api exec time fix

alpha/apps/kaltura/lib/batch2/kJobsCacher.php, alpha/apps/kaltura/lib/cache/kApiCache.php, alpha/apps/kaltura/lib/monitor/KalturaMonitorClient.php, alpha/apps/kaltura/lib/storage/kFileUtils.php, infra/general/kLockBase.php, plugins/conference/services/ConferenceService.php
also, removed 'start' event for multirequest since 'end' is not sent for it
=> apimon: track sleep time

alpha/lib/model/LiveEntry.php
LiveEntry custom data fields now get copied when cloning an entry
Small consistency change for live entry dvr fields
=> PLAT-22519: add live entry custom data on clone

alpha/apps/kaltura/lib/monitor/KalturaMonitorClient.php
also, make sure uploaded file size is numeric
=> apimon fixes: make sure memcache wrapper is loaded

infra/storage/shared_file_system_managers/kS3SharedFileSystemMgr.php
=> Revert "FOUN-69: Support defining storage class when uploading files to s3"

alpha/apps/kaltura/lib/myCloudUtils.class.php, alpha/apps/kaltura/lib/myEntryUtils.class.php, alpha/apps/kaltura/lib/myPackagerUtils.class.php
Changing the code so getFileSyncServeFlavorFields will work as it used to on a non-cloud environment
=> Propus 16.14.0 plat 22548

alpha/apps/kaltura/lib/myCloudUtils.class.php, alpha/apps/kaltura/lib/myEntryUtils.class.php, alpha/apps/kaltura/lib/myPackagerUtils.class.php
Changing the code so getFileSyncServeFlavorFields will work as it used to on a non-cloud environment
=> PLAT-22548 volume and thumbnail fix Propus-16.13.0 merge

alpha/lib/model/accessControl.php
=> Revert "SUP-24898: allow reach vendors to access entries with access control"

alpha/apps/kaltura/lib/storage/kFileSyncUtils.class.php, alpha/lib/model/genericSyndicationFeed.php
=> Propus 16.14.0 foun 74

plugins/content_distribution/lib/model/DistributionProfile.php, plugins/content_distribution/lib/model/EntryDistribution.php, plugins/event_notification/providers/email/lib/model/EmailNotificationTemplate.php, plugins/event_notification/providers/http/lib/model/HttpNotificationTemplate.php
=> Propus 16.14.0 s3 content set entry distribution

alpha/apps/kaltura/lib/batch2/kFlowHelper.php, alpha/apps/kaltura/lib/batch2/kJobsManager.php, alpha/apps/kaltura/lib/storage/kPathManager.php, alpha/apps/kaltura/lib/storage/kS3PathManager.php, api_v3/services/ExportCsvService.php, batch/batches/ExportCsv/kAsyncExportCsv.class.php
=> FOUN-72 - export csv to s3

alpha/apps/kaltura/lib/storage/kFileSyncUtils.class.php, alpha/lib/model/BatchJob.php, plugins/bulk_upload/csv/batch/BulkUploadEngineCsv.php, plugins/bulk_upload/xml/batch/BulkUploadEngineXml.php, plugins/schedule/bulk_upload/batch/BulkUploadEngineICal.php
=> FOUN-52 - support s3 read and write batchFiles

alpha/lib/model/conversionProfile2.php
=> FOUN-50 conversion profile xslt to s3

alpha/apps/kaltura/lib/batch2/kFlowHelper.php
@MosheMaorKaltura created new pr for Propus-16.15.0
Old:
https://github.com/kaltura/server/pull/10316/files
=> SUP-25559: check if source asset is still in convert grace period

infra/monitor/KalturaMonitorClient.php
instead of propel/propel2 etc.
=> apimon: send the host name on db events

alpha/lib/model/entry.php, plugins/content/external_media/lib/model/ExternalMediaEntry.php, plugins/reach/lib/kReachManager.php
@MosheMaorKaltura  @ravitshalem 
Old PR https://github.com/kaltura/server/pull/9569/files
Only change is I switched this:
!empty($object->getLengthInMsecs())
with
$object->getLengthInMsecs()
Since default DB value for getLengthInMsecs is 0 so it's the same
=> SUP-20297: add REACH2 support for external_media of type YouTube

alpha/apps/kaltura/modules/extwidget/actions/thumbnailAction.class.php
calling ignore_user_abort has no effect - it only returns the current setting, need to send 'true'
=> thumbnailAction: ignore user abort

alpha/lib/model/BatchJob.php, plugins/bulk_upload/csv/batch/BulkUploadEngineCsv.php, plugins/bulk_upload/xml/batch/BulkUploadEngineXml.php, plugins/schedule/bulk_upload/batch/BulkUploadEngineICal.php
=> Propus 16.14.0 foun 52

alpha/apps/kaltura/modules/extwidget/actions/serveFlavorAction.class.php
add 'id' (the assetId) to each sequence of the json returning from serveFlavor in simulive flows
=> PLAT-22579: Simulive - add id to sequence (serveFlavor)

batch/batches/Convert/KAsyncConvert.class.php
=> Delete not allowed temp file

alpha/lib/model/kuser.php, configurations/elastic/mapping/kuser_mapping.json
=> FOUN-83 - add user picture to elastic kuser index

infra/chunkedEncode/KChunkedEncodeMemcacheWrap.php
in order to improve chunk pods utilization
=> HF: increase fetchRangeRandMax

infra/chunkedEncode/KChunkedEncodeMemcacheWrap.php
in order to improve chunk pods utilization
=> increase fetchRangeRandMax

infra/chunkedEncode/KChunkedEncode.php, infra/chunkedEncode/KChunkedEncodeMemcacheWrap.php, infra/media/mediaInfoParser/KFFMpegMediaParser.php
add logic to verify that there are no empty frames (very small pkt size) in the chunk beginnig
if there are - regenerate with larger back-offset value
=> Propus 16.16.0 sup 25701 gop on chunk boundaries

alpha/scripts/compatCheckElasticSearch.php, configurations/elastic/mapping/entry_mapping_sub.json, configurations/elastic/mapping/kuser_mapping.json
=> FOUN-54 - automate elastic indexing

infra/chunkedEncode/KChunkedEncodeMemcacheWrap.php
the current KChunkedEncodeMemcacheScheduler::FetchNextJob causes low AWS pods utilzation 
when number of pods exceeds 200.
new func uses memcache another approach, taking advantage of memcache add func 'atomic' operation
=> PLAT-22600-new-FetchNextJob

alpha/apps/kaltura/lib/batch2/kJobsManager.php, alpha/apps/kaltura/lib/batch2/model/kConvertJobData.php, batch/batches/Convert/KAsyncConvert.class.php, batch/batches/KBatchBase.class.php, batch/batches/KDistributedFileManager.php, infra/storage/kFileBase.php, infra/storage/shared_file_system_managers/kS3SharedFileSystemMgr.php, infra/storage/shared_file_system_managers/kSharedFileSystemMgr.php
=> FOUN-101 make windows batches work with shared Storage

batch/batches/KBatchBase.class.php, configurations/base.ini, infra/general/batch/kBatchUtils.php, infra/storage/file_transfer_managers/s3Mgr.class.php
=> FOUN-108 - fix cloud_storage conf loading in batches

batch/batches/Convert/KAsyncConvert.class.php
=> FOUN-101 handle windows conversion for s3

infra/storage/kFileBase.php
=> FOUN-113 fix mime type for windows machines

plugins/search/providers/elastic_search/scripts/populateElasticFromLog.php
=> FOUN-54 reset populate elastic client on ping fail

batch/batches/Convert/KAsyncConvert.class.php
=> FOUN-101 move through api only if file is not sharedLocationFile

api_v3/lib/types/filters/KalturaUserEntryFilter.php
=> PLAT-11136: show list of all user_entry if user is a entitled for entry

alpha/apps/kaltura/lib/myEntryUtils.class.php, alpha/apps/kaltura/lib/myPackagerUtils.class.php
when getting width = 0 (original width) and vid_slices
=> thumbnailAction: avoid hitting the jpeg 64k limit

infra/chunkedEncode/KChunkedEncodeMemcacheWrap.php
=> HF:Prevent-Chk0-Reconverts

batch/batches/Convert/KAsyncConvert.class.php
=> FOUN-85 set conversion log ext to conv.log

plugins/content/document/lib/operation_engines/KOperationEnginePdfCreator.php
=> Revert "Update KOperationEnginePdfCreator.php"

alpha/scripts/utils/ExportToDifferentStorage.php
=> export script: handle null file type

.github/workflows/linter.yml
=> Revert "disable PHP lint for now"

api_v3/lib/KalturaRequestDeserializer.php, api_v3/lib/reflection/KalturaDocCommentParser.php, api_v3/lib/types/KalturaBaseUser.php, api_v3/lib/types/KalturaUser.php
…ed parameter to a specified size
=> Added a new annotation that safely truncates the value of the annotated parameter

alpha/apps/kaltura/modules/kmcng/actions/kmcngAction.class.php
add latest uiconf confvars to KMC php to be forwarded to v7 studio
=> feat(FEC-10607): add a current version indication in the studio

alpha/lib/model/DeliveryProfileLive.php
=> Liv-472: Changed live manifest url param order

batch/batches/Import/KAsyncImport.class.php
=> Revert "FOUN-98 save importedFile to shared path if size exceeds the size thr…"

plugins/content/caption/base/lib/kCaptionsContentManager.php
=> Revert "SUP-18687: fix SRT line index when clipping the beginning of the entry"

alpha/scripts/utils/ExportToDifferentStorage.php
can be used to work around all sorts of weird issues like multiple file sync keys/cross dc link
=> export script: support original only mode

alpha/apps/kaltura/lib/batch2/kJobsManager.php
Moved to Quasar-17.1.0
Already approved by @yossipapi and @MosheMaorKaltura in
https://github.com/kaltura/server/pull/10635
Will require compat check
=> SUP-26711: postConvert prefer file sync from periodic_storage_ids if exists

alpha/apps/kaltura/lib/storage/kFileSyncUtils.class.php, alpha/lib/model/FileSync.php
Moved to Quasar-17.1.0
Already approved by @yossipapi and @MosheMaorKaltura  in
https://github.com/kaltura/server/pull/10640
Will require compat check
=> SUP-26711: YouTubeApi prefer file sync from periodic_storage_ids if exists

api_v3/lib/KalturaLiveEntryService.php
add to the recording creation time check the session reconnect time (180)
=> LIV-511 : change the recording creation check

plugins/vendor/zoom/lib/api/webPage/KalturaZoomRegistrationPage.html, plugins/vendor/zoom/lib/model/ZoomHelper.php, plugins/vendor/zoom/services/ZoomVendorService.php
Zoom On Prem - Allow creating of Zoom Integration without oAuth2 call from Zoom
=> Quasar 17.1.0 plat 22647

deployment/permissions/service.vendor.zoomVendor.ini, plugins/vendor/zoom/lib/api/webPage/kalturaRegionalRedirectPage.html, plugins/vendor/zoom/services/ZoomVendorService.php
Added action to zoomVendor.ini
=> action name was not the same in all places. fixed

api_v3/services/BatchControlService.php
=> fix dynamic confiugred_id allocation

configurations/vendor.template.ini, plugins/content/caption/base/lib/api/KalturaCaptionAsset.php, plugins/vendor/zoom/ZoomDropFolderPlugin/batch/processors/zoomTranscriptProcessor.php, plugins/vendor/zoom/lib/model/processors/kZoomTranscriptProcessor.php, release-notes.md
Encapsulated Accuracy inside Zoom
=> Quasar 17.1.0 reach2 1061

alpha/apps/kaltura/lib/kSimuliveUtils.php, alpha/apps/kaltura/lib/myPlaylistUtils.class.php
change the Simulive's serveFlavor json to not include unready caption assets
=> SUP-27732: Simulive - exclude unready caption assets

plugins/search/providers/elastic_search/scripts/populateElasticFromLog.php
=> FOUN-138 - elasticFix for bofa

plugins/search/providers/elastic_search/scripts/populateElasticFromLog.php
=> FOUN-103  - update elastic populate

alpha/apps/kaltura/lib/myPartnerRegistration.class.php, api_v3/services/PartnerService.php, deployment/permissions/service.partner.ini, deployment/updates/scripts/add_permissions/2021_05_04_Partner_RegistrationValidationPermission.php, release-notes.md
=> Revert "Refactored Partner Registration to registration and validation"

infra/chunkedEncode/KChunkedEncodeSessionManager.php, infra/chunkedEncode/KChunkedEncodeUtils.php
Fix CE UserCPU metrics for Kava
=> Quasar 17.3.0 plat 22902 fix user cpu metrics

release-notes.md
=> Revert "REACH2-1062:adding release notes"

deployment/updates/scripts/xml/responseProfiles/2021_06_06_update_reach_vendor_response_profiles.template.xml
=> Revert "REACH2-1062:adding type,name,system_name to the xml"

plugins/sip/lib/model/providers/pexip/kPexipUtils.php
This to support Pexip server with version greater than v21.
@gotlieb , @MosheMaorKaltura , please review.
=> PSVAMB-25378, PSVAMB-24119: match path only as a fallback

api_v3/lib/types/conversionProfile/KalturaAsset.php
=> Revert "SUP-27743-Java-Long-Integers-FlavorAsset-SizeInBytes:Change type of sizeInBytes from int to long"

alpha/apps/kaltura/lib/batch2/kJobsManager.php, batch/batches/DeleteFile/KAsyncDeleteFile.class.php
=> Revert "Quasar 17.4.0 foun 150"

plugins/schedule/base/lib/api/KalturaLinkedScheduleEvent.php, plugins/schedule/base/lib/api/KalturaScheduleEvent.php, plugins/schedule/base/lib/api/errors/KalturaScheduleErrors.php, plugins/schedule/base/lib/kScheduleEventsConsumer.php, plugins/schedule/base/lib/model/LiveStreamScheduleEvent.php, plugins/schedule/base/lib/model/ScheduleEvent.php, plugins/schedule/base/lib/model/data/kLinkedScheduleEvent.php, plugins/schedule/base/services/ScheduleEventService.php
=> Quasar 17.4.0 plat 22775

api_v3/services/LiveStreamService.php
change the getDetails broadcastStatus result to be aligned with the isLiveAction
=> PLAT-22966: fix getDetailsAction for Simulive

alpha/apps/kaltura/modules/extwidget/actions/embedPlaykitJsAction.class.php
Beta and latest are changing and for that cases we won't have beta/latest map, need to check existance
=> fix: warnings for Undefined index

alpha/scripts/utils/ExportToDifferentStorage.php
- improve original dc selection (cases of no-original/more than one)
- print to log the paths in all dcs
=> export script touchups

alpha/scripts/utils/ExportToDifferentStorage.php
prioritize the file syncs by -
1. ready
2. original
3. direct (non-link)
=> export script: improve original dc logic

plugins/search/providers/elastic_search/lib/kElasticSearchManager.php, plugins/search/providers/elastic_search/lib/model/search/kBaseESearch.php, plugins/search/providers/elastic_search/scripts/populateElasticFromLog.php
=> REG-202 - support elastic split indexes

alpha/apps/kaltura/lib/storage/kFileSyncUtils.class.php
=> Order file syncs by preffered dc

plugins/drop_folder/lib/kDropFolderEventsConsumer.php
Drop Folder File been created for replaced entryId. 
CodeFix for checking if the entry is temporary if so taking the replaced entryID for the query.
=> SUP-27588-replaced-entry-drop-folder-file: Change query for replacing entry drop folder file

alpha/scripts/webcast/setupWebcast.php
This automates manual steps listed in ee44980ae55cd12cad1796e86b4cd7ccab5e9cb9
=> PSVAMB-16509: Add setup script for Webcast event notifications

plugins/vendor/microsoft/teams/batch/KMicrosoftTeamsDropFolderEngine.php
Prevent creation of duplicate entries.
Add logging.
=> PLAT-23052

api_v3/lib/KalturaEntryService.php
=> FOUN-175 handle trimming for static content

deployment/base/scripts/init_data/08.flavorParamsConversionProfile.ini, deployment/updates/scripts/ini_files/2021_07_26_capture_tools_content.flavorParamsConversionProfile.ini, deployment/updates/scripts/ini_files/2021_07_26_kaltura_meeting_recordings.flavorParamsConversionProfile.ini, deployment/updates/scripts/ini_files/2021_07_26_msft_teams_recordings.flavorParamsConversionProfile.ini, deployment/updates/scripts/ini_files/2021_07_26_zoom_recordings.flavorParamsConversionProfile.ini
=> FOUN-174 static content

alpha/apps/kaltura/lib/batch2/bcdl/kBusinessPreConvertDL.php
=> FOUN-204 handle static content reconvert

alpha/apps/kaltura/lib/batch2/bcdl/kBusinessPreConvertDL.php
=> Revert "FOUN-204 handle static content reconvert"

api_v3/lib/KalturaErrors.php, configurations/sip.template.ini, plugins/sip/lib/model/providers/pexip/kPexipUtils.php, plugins/sip/services/PexipService.php
=> SUP-28126 sipUrl encryption enhancement

api_v3/lib/KalturaErrors.php, configurations/sip.template.ini, plugins/sip/lib/model/providers/pexip/kPexipUtils.php, plugins/sip/services/PexipService.php
=> Revert "SUP-28126 sipUrl encryption enhancement"

api_v3/lib/KalturaErrors.php, configurations/sip.template.ini, plugins/sip/lib/model/providers/pexip/kPexipUtils.php, plugins/sip/services/PexipService.php
=> Quasar 17.7.0 sup 28126

plugins/sip/lib/model/providers/pexip/kPexipUtils.php
=> SUP-28126 - sup url encryption

plugins/content/caption/search/CaptionSearchPlugin.php
=> FOUN-172 - index appropriate captions to elastic and sphinx

infra/general/timeOffset/TimeConst.php, infra/general/timeOffset/kTimeConversion.php, plugins/webexDropFolderPlugin/batch/KWebexDropFolderEngine.php
=> PLAT-22929: Webex drop folder be able to scan unlimited history

alpha/lib/model/DeliveryProfile.php
"flavor" could be of type "flavorParams" which not have "getLanguage" method (the assumption that "flavor" is of "asset" type was wrong)
revert of https://github.com/kaltura/server/pull/10302/commits/d1bb9ca5785c155606e586aa2b72ecb7f2b6156f
=> PLAT-23050: check that the flavor has "getLanguage" callable function

infra/media/mediaInfoParser/KFFMpegMediaParser.php
Fix abnormally hi fps vals caused by varying/irregular frame rates
mostly in recorded/LC sources
=> FIX: Abnormal frame rate vals

alpha/apps/kaltura/lib/kSimuliveUtils.php
fix php5.3 incompatibility (accessing array as reference inside foreach loop)
=> LIV-756: kSimuliveUtils - fix php5.3 incompatibility

alpha/apps/kaltura/lib/myPartnerUtils.class.php, api_v3/services/PartnerService.php, batch/batches/CopyPartner/KAsyncCopyPartner.class.php, release-notes.md
=> Revert "Fix for uiconf crash in batch, 'unknown error' exception and a added log line"

plugins/reach/plugins/ReachInternal/batch/engines/kReachVendorTaskProcessorEngine.php
Exception will be caught by KAsyncReachInternalQueueHandler.class.php where the job will terminate correctly.
=> Prevent catching the exception at this level

configurations/base.ini
=> bump Analytics version to v2.6.3

alpha/lib/model/UserLoginData.php
=> Revert "PLAT-23102: updateLoginData action in user service allow saving a new…"

plugins/reach/plugins/ReachInternal/batch/KAsyncReachQueueHandler.class.php
Skip processing a task in an incorrect status
=> Skip processing task

infra/chunkedEncode/KBaseChunkedEncodeSessionManager.php, infra/chunkedEncode/KChunkedEncode.php, infra/chunkedEncode/KChunkedEncodeMemcacheWrap.php, infra/chunkedEncode/KChunkedEncodeUtils.php
Add support for VP9 and AV1 vid codecs to Chunk Encoding
=> Quasar 17.7.0 plat 23017 chunk enc vp9 av1

batch/scheduler/KSchedulerConfig.class.php
=> FOUN-215 modify batch host wildcard regex

plugins/content/document/scripts/convert.php
https://imagemagick.org/script/command-line-options.php#density
=> SUP-28549: Set target quality to sharpen image

plugins/reach/plugins/OpenCalais/batch/kReachVendorTaskOpenCalaisProcessorEngine.php
Copy from pull request https://github.com/kaltura/server/pull/11155
=> REFINITIV-2515 -> Merge Tags header code

deployment/permissions/service.fileasset.ini, deployment/permissions/service.quiz.quiz.ini, deployment/updates/scripts/add_permissions/2021_11_15_update_file_asset_permission.php, deployment/updates/scripts/add_permissions/2021_11_15_update_quiz_permissions.php
Same as #11227 for Quasar-17.12.0 for 21Q4 QS
=> PSVAMB-26104: CrossKalturaDistribution permissions

plugins/vendor/zoom/ZoomDropFolderPlugin/lib/kZoomDropFolderFlowManager.php
reverted the original from the wrong branch. this revert will revert from the correct branch
=> reverting from 17.15.0 

plugins/beacon/lib/api/errors/KalturaESearchBeaconErrors.php, plugins/beacon/lib/api/filters/KalturaBeaconEnhanceFilter.php, plugins/beacon/lib/api/filters/KalturaBeaconFilter.php
=> FOUN-182 - fix beacon search exceptions on missing parameters

alpha/apps/kaltura/lib/storage/kFileUtils.php, alpha/lib/model/DeliveryProfileLive.php, infra/general/KCurlWrapper.class.php, infra/monitor/KalturaMonitorClient.php
if curl fails, use the curl error code, otherwise, use the http status
=> apimon: add curl errors

admin_console/forms/Delivery/DeliveryProfileLivePackager.php, alpha/lib/model/DeliveryProfileLive.php, alpha/lib/model/DeliveryProfileLiveAppleHttp.php, api_v3/lib/types/delivery/KalturaDeliveryProfileLivePackager.php
add "shouldRedirect" flag to KalturaDeliveryProfileLivePackager (configurable from admin console form)
=> PLAT-23259: add "shouldRedirect" flag to live delivery profile

batch/batches/Convert/Engines/KJobConversionEngine.class.php, batch/batches/Convert/KAsyncConvert.class.php
@yossipapi this is not the final pr
will clarify in teams
=> FOUN-301: count userCpu usage for convert process

plugins/vendor/zoom/ZoomDropFolderPlugin/batch/KZoomDropFolderEngine.php, plugins/vendor/zoom/ZoomDropFolderPlugin/batch/processors/zoomProcessor.php, plugins/vendor/zoom/ZoomDropFolderPlugin/lib/api/KalturaZoomDropFolder.php, plugins/vendor/zoom/infra/kZoomClient.php, plugins/vendor/zoom/infra/kZoomTokens.php, plugins/vendor/zoom/lib/model/kZoomEventHanlder.php, plugins/vendor/zoom/lib/model/processors/kZoomProcessor.php, plugins/vendor/zoom/lib/model/processors/kZoomRecordingProcessor.php, plugins/vendor/zoom/services/ZoomVendorService.php
=> Revert "Quasar 17.17.0 sup 30033"

infra/cdl/kdl/KDLAudioMultiStreaming.php, infra/cdl/kdl/KDLFlavor.php
supports generating of lingual audio-only flavors w/single audio sources
=> Quasar 17.19.0 plat 23330 single audio stream

infra/cache/kInfraMemcacheCacheWrapper.php
$errno is always '8' (E_NOTICE), extracting the code from the message
instead.
=> apimon: report memcache error codes

plugins/drop_folder/batch/Engine/KDropFolderEngine.php, plugins/vendor/zoom/ZoomDropFolderPlugin/batch/KZoomDropFolderEngine.php, plugins/vendor/zoom/infra/kZoomClient.php, plugins/vendor/zoom/lib/model/ZoomHelper.php
1. At the beginning, load all drop folder files. later, load only the latest, the ones that were added since the last one drop folder file.
2. Scan one day each time.
3. Added 3 optional parameters to the 'ini' file under 'zoom' section: meetingGracePeriod, fileProcessingGracePeriod, maxMeetings.
=> PLAT-23504: Improvements to Zoom drop folder

api_v3/services/LiveStreamService.php
print the LiveStream:isLive response before returning the result
=> PLAT-23257: add log print of isLive response

configurations/base.ini
Backport #11410 and #11404 to Quasar-17.20.0
for SUP-31011 and PLAT-23570
=> Backport #11410 #11404 to Quasar-17.20.0

alpha/lib/model/uiConf.php
Original https://github.com/kaltura/server/pull/11285/files
=> FOUN-293: generate uiConf file directly on s3 path

api_v3/lib/types/entry/KalturaLiveStreamEntry.php
done to comply with the official srt docs
https://github.com/Haivision/srt/blob/master/docs/apps/srt-live-transmit.md
=> changed srtPass requirements

infra/chunkedEncode/KChunkedEncode.php, infra/chunkedEncode/KChunkedEncodeMemcacheWrap.php, infra/chunkedEncode/KChunkedEncodeSessionManager.php, infra/media/mediaInfoParser/KFFMpegMediaParser.php
Handle - 
- chunk time outs caused by in chunk job retries
- increase audio chunk timeout on very high bitrate source (aka APCN codecs)
- AV1 ffprobe chunk extract media misbehaved due to bad ‘picture-type’ and missing ‘pict-num’. That caused false ‘empty frame’ detections, causing not needed in-chunk-job reconverts and chunk timeouts
=> Rigel 18.2.0 plat 23648 chunk timeouts av1

release-notes.md
One need to add "srt_domain" to the broadcast.ini files
=> LIV-884: Add release note for SRT conf

alpha/apps/kaltura/lib/KDLWrap.php
in call for KChunkedEncode::verifySupport
=> No-Plat: Fix minor CE rounding issue

infra/media/mediaInfoParser/KAMFMediaInfoParser.php, infra/media/mediaInfoParser/KSyncPointsMediaInfoParser.php
https://ffmpeg.org/ffprobe.html#Stream-specifiers-1
Change in FFmpeg 4.2
https://github.com/FFmpeg/FFmpeg/commit/24e0e149ada6bd6287c4454fe5fd7ef3480b5d83
base.ini changes in this PR are not real and are already in the target branch.
=> PSVAMB-32896: use correct stream specifier format

alpha/apps/kaltura/lib/kSimuliveUtils.php, alpha/apps/kaltura/modules/extwidget/actions/serveFlavorAction.class.php
add 'isOffsetPlaybackAllowed' to kSimuliveUtils - return true if got admin ks
=> LIV-943: simulive - allow offset playback with admin ks

plugins/schedule/base/lib/api/KalturaLiveStreamScheduleEvent.php
remove sourceEntryId existence check from out of 'validateEntryField' function (missed by mistake from https://github.com/kaltura/server/pull/11538)
=> LIV-944-B: remove forgotten condition (source entry existence)

plugins/vendor/zoom/ZoomDropFolderPlugin/batch/KZoomDropFolderEngine.php, plugins/vendor/zoom/ZoomDropFolderPlugin/batch/ZoomBatchUtils.php
=> Revert "PLAT-23726: Zoom opt-out no recording get uploaded to any user, opt-i…"

plugins/vendor/zoom/lib/api/types/KalturaZoomIntegrationSetting.php, plugins/vendor/zoom/lib/model/ZoomVendorIntegration.php
=> Revert "PLAT-23708: Setting Fields in Wrong Order"

plugins/vendor/microsoft/teams/batch/KMicrosoftGraphClient.php, plugins/vendor/microsoft/teams/batch/KMicrosoftTeamsDropFolderEngine.php
Add curl timeout to Graph requests
=> PSVAMB-29073

plugins/schedule/base/lib/model/LiveFeature.php
Was supposed to be included in:
https://github.com/kaltura/server/pull/11622
=> fixed naming of live feature params

plugins/reach/plugins/OpenCalais/batch/RuleEngine.php
Taken from Rigel-18.8.0-PSVAMB-35059
=> Rigel 18.10.0 psvamb 35059

plugins/reach/errors/KalturaReachErrors.php, plugins/reach/lib/api/data/entryVendorTaks/KalturaEntryVendorTask.php, plugins/reach/lib/api/data/entryVendorTaks/KalturaScheduledVendorTaskData.php
validation for the scheduled event entry id
validation for scheduled event type
=> added additional validations for shceduled vendor tasks

plugins/reach/plugins/OpenCalais/batch/RuleEngine.php
Code(2 commits) was already approved here: https://github.com/kaltura/server/pull/11639
=> Rigel 18.12.0 psvamb 35059

plugins/reach/lib/kReachManager.php, plugins/reach/lib/kReachUtils.php, plugins/reach/lib/model/VendorCatalogItem.php, plugins/reach/lib/model/data/VendorCaptionsCatalogItem.php, plugins/reach/services/EntryVendorTaskService.php
=> LIV-1004: use alternate duration value for live entry vendor tasks

plugins/reach/lib/api/data/entryVendorTaks/KalturaEntryVendorTask.php, plugins/reach/services/EntryVendorTaskService.php
moved check if catalog item exists to avoid edge case exception in validateForInsert when catalog item does not exist
=> PLAT-23850: move catalog validation into validateForInsert

plugins/vendor/microsoft/teams/batch/KMicrosoftTeamsDropFolderEngine.php
=> Revert "PSVAMB-35945 User ID Format of Teams Recording Ingestion"

api_v3/services/UserService.php
=> Revert "SUP-33280 change loginDataResetPasswordAction to return the user with…"

plugins/reach/lib/api/data/entryVendorTaks/KalturaEntryVendorTask.php
=> FOUN-596: Move entryVendorTask->add / update to use general "kString::checkIsValidJson()

alpha/apps/kaltura/modules/extwidget/actions/embedPlaykitJsAction.class.php
=> Revert "FEV-1373: Add linked player plugins based on conf map "

api_v3/lib/types/partner/KalturaPartner.php
=> PLAT-23950 - Expose flag skip password restriction of first/last name on response

plugins/vendor/zoom/ZoomDropFolderPlugin/batch/processors/zoomRecordingProcessor.php, plugins/vendor/zoom/lib/model/processors/kZoomRecordingProcessor.php
=> Revert "SUP-33912: Add Time Zone (GMT) to Zoom recording description"

api_v3/lib/types/report/KalturaReportInputBaseFilter.php
Reverts kaltura/server#11529
merged to wrong version
=> Revert "SUP-31492 change the fromDate and toDate params to bigint instead of …"

alpha/lib/model/kuser.php, api_v3/lib/types/KalturaUser.php
add 'isGuest' flag (insertable only) to KalturaUser to mark guest users
=> NR2-7294: add 'isGuest' to KalturaUser

infra/chunkedEncode/KChunkedEncode.php
adjust chunk timings to match the correct fps
=> SUP-34498-Fix-chunk-timings

plugins/reach/lib/kReachManager.php
=> Revert "SUP-28497 add support to not add entry vendor tasks through rules for…"

alpha/lib/enums/resetPassLinkType.php, alpha/lib/model/UserLoginDataPeer.php, configurations/local.template.ini, release-notes.md
add new type of password reset for KME, so when user reset his password from CMS he'll get a reset link of CMS
=> NR2-7461: New KME reset password link

alpha/apps/kaltura/lib/myContentStorage.class.php, alpha/apps/kaltura/lib/myEntryUtils.class.php, alpha/apps/kaltura/lib/myPackagerUtils.class.php, alpha/apps/kaltura/modules/extwidget/actions/thumbnailAction.class.php
=> Revert "SUP-27694: Storage path for capture thumbnail requests"

plugins/metadata/MetadataPlugin.php
=> Revert "SUP-34825: prevent race conditions in metadata updates"

plugins/vendor/webex/batch/processors/KWebexAPIDropFolderEngine.php, plugins/vendor/webex/lib/model/oAuth/kWebexAPIOauth.php
=> Revert "PLAT-24058: Pagination of Webex recordings created at the same time f…"

alpha/apps/kaltura/lib/storage/kFileSyncUtils.class.php
=> FOUN-958: Copy aditional src file sync attrs when creating file sync in replace flow

infra/general/kString.class.php
=> Revert "SUP-34618: ignore non-utf8 characters in xmlEncode"

alpha/apps/kaltura/lib/storage/kFileSyncUtils.class.php
=> Revert "FOUN-958: Copy aditional src file sync attrs when creating file sync in replace flow"

infra/chunkedEncode/KChunkedEncode.php
use only -1.4 itsoffset during chunk fixing procedure
=> SUP-36041-Fix-wrong-FPS-on-HLS-manifest

plugins/content_distribution/providers/cortex/lib/CortexApiDistributionEngine.php
Already been approved here https://github.com/kaltura/server/pull/12079#pullrequestreview-1336904149
=> Scorpius 19.5.0 psvamb 42565

infra/cdl/kdl/KDLOperatorFfmpeg2_1_3.php, infra/cdl/kdl/KDLOperatorFfmpeg2_2.php
new 'arProcessingMode=6', to support portrait-to-landscape conversion
=> Scorpius 19.7.0 sup 31372 9x16 for hbb tv

alpha/lib/model/LiveEntry.php
Reimplementing this change following approval from david ben shoshan
https://github.com/kaltura/server/pull/12064
https://github.com/kaltura/server/pull/12044
=> LIV-1090: removing entry id from live stream name

alpha/apps/kaltura/lib/reports/kKavaEventPlatformReports.php
join reports doesn't work for more than one dimension
=> use union query for geo reports 

api_v3/services/BaseEntryService.php, plugins/schedule/base/lib/api/KalturaLiveRestreamFeature.php, plugins/schedule/base/lib/model/LiveRestreamFeature.php
added playBack url field to RestreamFeature
=> LIV-1130: add playback url field

plugins/vendor/zoom/services/ZoomVendorService.php
When using localRegistrationPage
=> PLAT-24397 - Make sure zoom auth type is S2S

alpha/apps/kaltura/lib/db/KalturaStatement.php, alpha/apps/kaltura/lib/request/infraRequestUtils.class.php, api_v3/lib/KalturaBaseUserService.php, api_v3/lib/KalturaDispatcher.php, api_v3/lib/KalturaFrontController.php, api_v3/lib/KalturaRequestDeserializer.php, api_v3/lib/reflection/KalturaActionReflector.php, api_v3/lib/reflection/KalturaDocCommentParser.php, api_v3/lib/reflection/KalturaPropertyInfo.php, api_v3/lib/reflection/KalturaTypeReflector.php, api_v3/lib/types/KalturaBaseUser.php, api_v3/lib/types/KalturaObject.php, api_v3/lib/types/KalturaUser.php, api_v3/services/AdminUserService.php, api_v3/services/SearchService.php, api_v3/services/SessionService.php, api_v3/services/UserService.php, infra/general/kString.class.php, infra/log/KalturaLog.php, vendor/propel/Propel.php
=> VCP-14151 Backport FOUN-1380 19.16.0 to 18.18.1

plugins/vendor/zoom/ZoomDropFolderPlugin/batch/processors/zoomRecordingProcessor.php, plugins/vendor/zoom/lib/model/processors/kZoomRecordingProcessor.php
retrieve only active users for zoom participants
=> SUP-38401-retrieve only active users for zoom participants

infra/media/mediaInfoParser/KFFMpegMediaParser.php, infra/media/mediaInfoParser/KMediaFileComplexity.php
Speed up some of the ExtractMedia lengthy processing 
and fix some minor issues
=> Scorpius 19.17.0 plat 24429 slow extract media

deployment/updates/scripts/ini_files/2023_09_24_live_languages_aze_urd.liveParams.ini
in order to enable deployment on RC
=> Removed Ids from live flavors

alpha/apps/kaltura/lib/batch2/model/kImportJobData.php, alpha/lib/data/resource/kUrlResource.php, api_v3/lib/types/batch/KalturaImportJobData.php, api_v3/lib/types/resource/KalturaUrlResource.php, batch/batches/Import/KAsyncImport.class.php, infra/general/KCurlWrapper.class.php, plugins/vendor/zoom/ZoomDropFolderPlugin/batch/processors/zoomChatFilesProcessor.php, plugins/vendor/zoom/ZoomDropFolderPlugin/batch/processors/zoomProcessor.php, plugins/vendor/zoom/ZoomDropFolderPlugin/batch/processors/zoomRecordingProcessor.php, plugins/vendor/zoom/ZoomDropFolderPlugin/batch/processors/zoomTranscriptProcessor.php, plugins/vendor/zoom/lib/model/ZoomHelper.php, plugins/vendor/zoom/lib/model/processors/kZoomChatFilesProcessor.php, plugins/vendor/zoom/lib/model/processors/kZoomRecordingProcessor.php, plugins/vendor/zoom/lib/model/processors/kZoomTranscriptProcessor.php
moved function getRedirectUrl and correct all indentation issues
=> Scorpius 19.19.0 sup 38185 new

api_v3/lib/KalturaLiveEntryService.php
=> Revert "SUP-40499: Protect against duplicate recording VOD"

deployment/base/sql/01.kaltura_ce_tables.sql, deployment/base/sql/01.kaltura_sphinx_ce_tables.sql
Changing mysql engine from MyISAM to InnoDB on kaltura_sphinx_log
=> Move from MyISAM to InnoDB on kaltura_sphinx_log.* and kaltura.flickr_token

infra/chunkedEncode/KChunkedEncodeSessionManager.php
The last chunk validation logic was too aggressive, causing false failures
=> Fix last chunk validation logic

plugins/content_distribution/providers/cortex/lib/model/CortexApiDistributionProfile.php
@hilak This is a small change, if you can please review it. It will only be pushed to the next deployment(20.8.0).
=> PSVAMB-48370 -> Remove entry name limitation

alpha/lib/model/kuser.php, configurations/elastic/mapping/elasticsearch-7/kuser_mapping.json, configurations/elastic/mapping/kuser_mapping.json, plugins/search/providers/elastic_search/lib/api/enum/KalturaESearchBaseUserFieldName.php, plugins/search/providers/elastic_search/lib/api/enum/KalturaESearchUserOrderByFieldName.php, plugins/search/providers/elastic_search/lib/api/types/items/user/KalturaESearchUserItem.php, plugins/search/providers/elastic_search/lib/api/types/order/items/KalturaESearchUserOrderByItem.php, plugins/search/providers/elastic_search/lib/model/enum/ESearchUserFieldName.php, plugins/search/providers/elastic_search/lib/model/enum/ESearchUserOrderByFieldName.php, plugins/search/providers/elastic_search/lib/model/items/ESearchUserItem.php, release-notes.md
add option to search and order users by fullname using elastic
=> PSVAMB-48998

alpha/lib/model/kuserPeer.php
=> PLAT-24713: Adding new user with admin role fails due to old reset password link

deployment/permissions/service.room.room.ini, deployment/updates/scripts/add_permissions/2024_03_18_update_room_permissions.php, plugins/room/services/RoomService.php, release-notes.md
add createRecordedEntry action to RoomService, create the recorded entry with "rootEntryId" set as the room entry (readonly field)
=> NR2-8156: add attachRecordedEntry action to RoomService

plugins/room/lib/api/KalturaRoomEntry.php, plugins/room/lib/model/RoomEntry.php
add brodcastEntryId to roomEntry customData
=> KME-1559: add brodcastEntryId to roomEntry

infra/chunkedEncode/KChunkedEncodeSessionManager.php
the chunk maxExecution time is increased on retry attempt, while letting the already running chunk job to complete.
instead of creating a new job with the same maxExecution time.
this improves the chances of successful completion, and saves execution time and CPU load of multiple full retries
=> Improved Chunk Timeout retry handling

plugins/schedule/base/lib/iCal/kSchedulingICalComponent.php, plugins/schedule/base/lib/iCal/kSchedulingICalEvent.php
=> Revert "SUP-42310 fix TZID to be in the same line"

alpha/apps/kaltura/lib/batch2/kBatchManager.php
=> Revert "SUP-42110 add a check if the tag force_tags exist in the tags array"

alpha/lib/model/LiveEntryServerNode.php
nvp1 is working in EDT and live is GMT
=> SUP-42293: SetViewModeUpdatedAt with timezone

infra/chunkedEncode/KChunkedEncodeSessionManager.php
Update chunk timeout logic to handle crashing pods cases
=> Update chunk timeout logic

plugins/room/lib/api/KalturaRoomEntry.php, plugins/room/lib/model/RoomEntry.php
add templateRoomEntryId to RoomEntry, KME will use this room to calculate the room settings
=> KME-2084: add templateRoomEntryId to RoomEntry

batch/batches/Import/KAsyncImport.class.php
=> VCP-18577: when importing files, if no 'filesize' from headers default to shared path

plugins/event_notification/providers/email/lib/batch/recipients/KEMailNotificationUserRecipientEngine.php
support dynamic content parameters in the user recipient provider, so user list can be determined based on the event/scope
=> support dynamic content parameters in the user recipient provider

alpha/lib/model/entryPeer.php, plugins/room/lib/api/KalturaRoomEntry.php
move room entry retrieval to entryPeer as "retrieveByIdAndPartnerIds"
=> KME-2117: move room entry retrieval to entryPeer

plugins/vendor/webex/batch/processors/KWebexAPIDropFolderEngine.php
…ds due to time gap of Webex two DB
=> SUP-42910: Let our watcher look back for $secondsToWatchBack time to cover missing records due to time gap of Webex two DB

alpha/apps/kaltura/lib/myPlaylistUtils.class.php, api_v3/services/PlaylistService.php
=> Revert "SUP-39240 FIXED  Redirected queries to Elasticsearch instead of Sphin…"

alpha/apps/kaltura/lib/myPlaylistUtils.class.php, api_v3/services/PlaylistService.php
=> Revert "SUP-39240 Redirected queries to Elasticsearch instead of Sphinx for d…"

plugins/reach/lib/kReachManager.php, plugins/reach/lib/kReachUtils.php, plugins/reach/lib/model/VendorCatalogItem.php, plugins/reach/lib/model/data/VendorQuizCatalogItem.php, plugins/reach/services/EntryVendorTaskService.php
for example when trying to do add_quiz from reach failing
https://github.com/kaltura/server/blob/74d0fe31d9dc8663c8f18bebaded67a07fd19109/plugins/cue_points/quiz/services/QuizService.php#L76
=> KAI-96: Add the user to the KS in order to perform some actions

alpha/apps/kaltura/lib/batch2/kFlowHelper.php, plugins/search/providers/elastic_search/lib/kElasticSearchManager.php, plugins/search/providers/sphinx_search/lib/kSphinxSearchManager.php
…llow builders to skip objects per plugin
=> VCP-18066: add skipObjects array for sphinx and elastic managers to allow builders to skip objects per plugin

plugins/cue_points/annotation/lib/api/KalturaAnnotation.php
=> Revert "PLAT-24975: Stricter entitlement"

plugins/reach/admin/CatalogItemConfigureAction.php, plugins/reach/admin/CatalogItemListAction.php, plugins/reach/admin/PartnerCatalogItemListAction.php, plugins/reach/batch/EntryVendorTasksCsv/KExportEntryVendorTaskEngine.php, plugins/reach/config/lang/en.php, plugins/reach/lib/api/data/vendorCatalogItem/KalturaVendorCatalogItem.php, plugins/reach/lib/api/data/vendorCatalogItem/KalturaVendorOcrCatalogItem.php, plugins/reach/lib/api/data/vendorCatalogItem/filters/KalturaVendorOcrCatalogItemFilter.php, plugins/reach/lib/model/VendorCatalogItem.php, plugins/reach/lib/model/VendorCatalogItemPeer.php, plugins/reach/lib/model/data/VendorOcrCatalogItem.php, plugins/reach/lib/model/enums/VendorServiceFeature.php
add new type of vendor task - OCR
=> KAI-111: OCR vendor task

plugins/content/caption/base/CaptionPlugin.php
get the stream language from entryServerNode instead of entry stream.
=> PLAT-25012: fix live webvtt captions

plugins/reach/admin/forms/CatalogItemConfigure.php, plugins/reach/lib/api/data/vendorCatalogItem/KalturaVendorVideoAnalysisCatalogItem.php, plugins/reach/lib/api/enums/KalturaVendorVideoAnalysisType.php, plugins/reach/lib/kReachManager.php, plugins/reach/lib/model/VendorCatalogItem.php, plugins/reach/lib/model/data/VendorVideoAnalysisCatalogItem.php, plugins/reach/lib/model/enums/VendorVideoAnalysisType.php, plugins/reach/services/EntryVendorTaskService.php
KAI-121: duration limit - the limit (in sec) of a video to be analyzed 
KAI-117: type - the analysis type (currently only OCR supported)
=> KAI-121: add duration limit and analysis type to videoAnalysis catalogItem

alpha/apps/kaltura/modules/extwidget/actions/embedPlaykitJsAction.class.php
=> Revert "FEC-14264: As a Rapt client I would like to use iframe embed"

alpha/apps/kaltura/modules/extwidget/actions/embedPlaykitJsAction.class.php
=> FEC-14264: As a Rapt client I would like to use iframe embed

infra/media/mediaInfoParser/KFFMpegMediaParser.php, infra/media/thumbnailMaker/KFFMpegThumbnailMaker.php
- frame stretching of the portrait/vertical contents - https://kaltura.atlassian.net/browse/SUP-46289
- thumbs failures of the interlaced contents - https://kaltura.atlassian.net/browse/SUP-46375
=> Ursa 21.7.0 mult tkt hf ffmpeg6 issues

plugins/bulk_upload/csv/batch/BulkUploadVendorCatalogItemEngineCsv.php, plugins/reach/lib/api/data/vendorCatalogItem/KalturaVendorCatalogItem.php
=> Revert "PLAT-25098: Add Intelligent Tagging To CSV Bulk Upload"

infra/media/mediaInfoParser/KFFMpegMediaParser.php
transforming the new FFM6 rotation mode style
into the existing Kaltura style (FFM4 based)
=> SUP-46289-Rotation-Fix

plugins/reach/lib/api/data/vendorCatalogItem/KalturaVendorTranslationCatalogItem.php
Same as done in KalturaVendorLiveTranslationCatalogItem
=> KAI-59: Transcription traget lang validation

alpha/apps/kaltura/lib/model/objectfilters/UserEntryFilter.php, plugins/content/entry_permission_level/lib/api/filters/KalturaPermissionLevelUserEntryFilter.php, plugins/content/entry_permission_level/lib/model/PermissionLevelUserEntry.php
=> Revert "PLAT-25073: Added bit mask for UserEntry PermissionLevel"

alpha/apps/kaltura/lib/reports/kKavaReportsMgr.class.php
=> PSVAMB-80720 - support getting report enrichment data from single layer cache 

alpha/apps/kaltura/lib/reports/kKavaVpaasReports.php
headers should be the same as the base report (USER_USAGE)
=> add full_name header to vpaas user usage report

plugins/search/providers/elastic_search/lib/model/search/ESearchEntryQueryFilterAttributes.php
=> Revert "SUP-42743: Update the display in search filter, remove the redundant …"

api_v3/lib/types/filters/KalturaGroupUserFilter.php
=> Revert "PLAT-25146: Search all group types by default"

api_v3/lib/types/KalturaGroupUser.php, api_v3/lib/types/filters/KalturaGroupUserFilter.php, api_v3/services/GroupUserService.php, plugins/group/lib/api/KalturaGroup.php
=> Revert "PLAT-25146: Improvements and fixes to filtering"

api_v3/lib/types/filters/KalturaGroupUserFilter.php
=> Revert "defaulting to type group"

alpha/lib/model/om/BaseconversionProfile2Peer.php, api_v3/lib/types/entry/KalturaBaseEntry.php
if conversion profile wasn't found, check if it associated with PID 0.
=> SUP-45919:Allow replacement of entries with a static conversion profile

alpha/apps/kaltura/lib/storage/kFileSyncUtils.class.php
Test cases:
Small file set (< 1KB) to small files cache
Small file get from small files cache
Large file set - same as before
Large file get - same as before
=> Added logs

plugins/search/providers/elastic_search/lib/model/search/ESearchBaseQueryFilterAttributes.php, plugins/search/providers/elastic_search/lib/model/search/ESearchEntryQueryFilterAttributes.php, plugins/search/providers/elastic_search/lib/model/search/kBaseESearch.php, plugins/search/providers/elastic_search/lib/model/search/kBaseSearch.php, plugins/search/providers/elastic_search/lib/model/search/kEntrySearch.php, plugins/search/providers/elastic_search/lib/model/search/queries/kESearchBoolQuery.php
=> Revert "SUP-42743: Fixing the NOT operator when filtering with display in search"

api_v3/lib/types/report/KalturaReportResponseOptions.php
to avoid issues with client libs generation
=> remove default value

plugins/search/providers/elastic_search/lib/api/errors/KalturaESearchErrors.php, plugins/search/providers/elastic_search/lib/api/types/KalturaESearchParams.php, plugins/search/providers/elastic_search/lib/model/ESearchParams.php, plugins/search/providers/elastic_search/lib/model/search/kBaseSearch.php, plugins/search/providers/elastic_search/lib/model/search/queries/kESearchTermQuery.php, plugins/search/providers/elastic_search/services/ESearchService.php
=> Revert "Ursa 21.15.0 plat 25229"

plugins/scheduled_task/admin/MediaRepurposingUtils.php
Additional changes were needed. Even though in the original fix the text area did appear. I didn't took care of the form processing when applying changes and also when loading up the form. QA found this issue so I reviewed this whole flow again.
=> SUP-48097 additional missing changes

alpha/apps/kaltura/modules/extwidget/actions/embedPlaykitJsAction.class.php
When using V2 redirection to V7, creating a div with id as player targetId if not existing already
=> PLAT-25296: Auto-embed: BE should create div for the player

plugins/reach/admin/scripts/plugin/partner-catalog-item-configure-action.phtml
(cherry picked from commit a6e43fd3d21ef1395b1cd611d9ed0a7b4a30f90d)
=> PSVAMB-85314 -> Support SignLanguage ratio display

plugins/content/caption/base/services/CaptionAssetService.php
=> SUP-48483 add a check if the caption has not already been set to default

infra/cdl/kdl/KDLOperatorFfmpeg6_0.php
=> SUP-48535-Fade-InOut-issue

plugins/reach/lib/model/VendorCatalogItem.php, plugins/reach/lib/model/data/VendorQuizCatalogItem.php
=> SUP-48864: no need to override the user anymore.

api_v3/lib/KalturaErrors.php, plugins/schedule/base/services/ScheduleEventService.php
=> SUP-48831: add lock for scheduleEvent feature update action

deployment/base/scripts/init_data/01.Partner.template.ini, deployment/permissions/partner.-25.ini, deployment/permissions/partner.0.ini, deployment/updates/scripts/add_permissions/2025_06_30_agents_manager_add_partner.php, release-notes.md
=> KAM-61: Add Agents Manager partner and permissions configuration

alpha/scripts/utils/updateEntriesCountForCategory.php
=> SUP-48883 update entriesCount for category

alpha/lib/model/flavorAsset.php
=> Check isset to avoid php notice

plugins/event_notification/providers/kafka/lib/model/KafkaNotificationTemplate.php
=> No-Plat: getRequiresPermissions should return default empty string

plugins/content/caption/base/services/CaptionAssetService.php
=> SUP-48483 add a check if the user is entitledKuserEdit on the entry

infra/storage/shared_file_system_managers/kS3SharedFileSystemMgr.php
=> SUP-48979: Select pre signed url method based on request method

alpha/apps/kaltura/lib/reports/kKavaEventPlatformReports.php
=> force total count to support count when using endUser filter

plugins/admin_console/system_partner/lib/api/KalturaSystemPartnerConfiguration.php
=> SUP-48911: Refuse setting DisableCategoryLimit if category has more than one privacy context, instead of one or more as before

plugins/admin_console/services/EntryAdminService.php
=> SUP-48436 adding additional condition if file exists

plugins/admin_console/system_partner/lib/api/KalturaSystemPartnerConfiguration.php
=> Revert "SUP-48911: Refuse setting DisableCategoryLimit if category has more than one privacy context, instead of one or more as before"

plugins/reach/lib/api/data/entryVendorTaks/KalturaQuizVendorTaskData.php, plugins/reach/lib/model/data/kQuizVendorTaskData.php
=> PLAT-25419: add intructions to QuizEntryVendorTask

plugins/reach/lib/kReachManager.php
=> SUP-48440: Add more checks to avoid automatic captions when block auto transcript enabled

plugins/content/markdown/MarkdownPlugin.php, plugins/content/markdown/lib/kMarkdownFlowManager.php
Added to support the kMarkdownFlowManager kObjectAddedEventConsumer implementtation
=> PLAT-25431: Enable update entry date when adding markdown

plugins/reach/lib/api/data/entryVendorTaks/KalturaSummaryVendorTaskData.php, plugins/reach/lib/model/data/kSummaryVendorTaskData.php
=> Venus 22.1.0 plat 25440

alpha/lib/model/DeliveryProfileLive.php, alpha/lib/model/DeliveryProfileLiveAppleHttp.php, alpha/lib/model/flavorParams.php
=> LIV-1342: Add codec to play manifest.

plugins/reach/lib/kReachManager.php, plugins/reach/lib/model/HandlerFcatory.php
- [N/A ] I have created new clients
- [N/A] I have notified related apps - KMCNG / KMS / EP .... about new clients
- [N/A] I have added a deployment script
- HF for - [https://kaltura.atlassian.net/browse/SUP-49289](https://kaltura.atlassian.net/browse/SUP-49289)
=> SUP-49289: Handle case of attachment asset that add entryVendorTask

api_v3/services/CategoryService.php
=> SUP 47061 added parent id to the lock key

plugins/content_distribution/providers/tvinci/lib/TvinciDistributionFeedEngine.php
=> SUP-49071: If distribution doesn't succeed on the first try, don't throw an exception and exit instead retry

alpha/scripts/utils/updatePartnerUserSecret.php
=> PLAT 25449 adding a script to update user secret

api_v3/services/BaseEntryService.php
=> PLAT-25443: if entry has live_schedule_capability has schedule info

infra/monitor/KalturaMonitorClient.php
=> No-Plat: Add safe log for service status stats

plugins/event_notification/providers/http/admin/HttpNotificationTemplateConfiguration.php
=> Fix error - set contentType on null object

plugins/event_notification/providers/http/admin/scripts/js/kObjects.js, plugins/event_notification/providers/kafka/admin/KafkaNotificationTemplateConfiguration.php, plugins/event_notification/providers/push/admin/PushNotificationTemplateConfiguration.php
- [ V] I have tested the changes locally.
- [ v] This PR follows the coding style guidelines.
- fixing a typo in the admin console event notifications GUI
- [ v] Yes
- reverting the fix
=> Fix typo in notification GUI - Syndication Feed

plugins/event_notification/providers/http/lib/KDispatchHttpNotificationEngine.class.php
=> SUP-49839 - avoid duplicate entries for content-type header

plugins/search/providers/sphinx_search/lib/kSphinxSearchManager.php
=> No-Plat: Cache sphinx connection ID based on resolved host name

configurations/plugins.template.ini, deployment/base/scripts/init_data/01.Partner.template.ini, deployment/permissions/partner.-26.ini, deployment/permissions/service.permission.ini, deployment/updates/scripts/add_permissions/2025_09_28_add_in_app_messaging_partner.php, release-notes.md
=> PLAT-25503: Add new partner for in-app messaging

plugins/content_distribution/providers/tvinci/lib/api/KalturaTvinciDistributionProfile.php, plugins/content_distribution/providers/tvinci/lib/model/TvinciDistributionProfile.php
https://kaltura.atlassian.net/browse/SUP-49925
- Handle cases that the customer saves content bigger then the max field size on DB in TVICHI dist profile.
=> SUP-49925: if custom data field is above 32kb then field is zipped

plugins/content_distribution/lib/model/ConfigurableDistributionProfile.php
=> Revert "SUP-49925: compressed config array if the payload size exceeds 65KB"
